### ISSUE TITLE
Getting a NoMethodError for using image_changed?

### ISSUE THREAD

**Issue by spletta** [carrierwaveuploader/carrierwave#1058]
I'm following along the Railscasts episode http://railscasts.com/episodes/253-carrierwave-file-uploads and am getting a NoMethodError at /businesses/1
undefined method `image_changed?'. 
![Screen Shot 2013-04-09 at 10 34 01 PM](https://f.cloud.github.com/assets/135679/359091/e17d96ee-a154-11e2-988b-72df53f3cce4.png)

I'm a little lost at why this pops up.. here is a snippet from the dev log

  User Load (0.6ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 2 LIMIT 1
  Business Load (0.4ms)  SELECT "businesses".\* FROM "businesses" WHERE "businesses"."id" = $1 LIMIT 1  [["id", "2"]](0.2ms)  BEGIN
   (0.3ms)  ROLLBACK
Completed 500 Internal Server Error in 10ms

NoMethodError - undefined method `image_changed?' for #<Business:0x007fd12f9d7c88>:
  (gem) activemodel-3.2.11/lib/active_model/attribute_methods.rb:407:in`method_missing'
  (gem) activerecord-3.2.11/lib/active_record/attribute_methods.rb:149:in `method_missing'
  (gem) carrierwave-0.8.0/lib/carrierwave/mount.rb:249:in`store_previous_model_for_image'

**Comment by sg552** [comment]
if you are mounting 'avatar' as the uploader, make sure you have 'avatar' column in your database table.

**Comment by ilan-senexx** [comment]
hi. didn't manage to fix it, so i comment out the mount_uploader lines from model, and run migration , 
then removed comments
