### ISSUE TITLE
Versions on a subclassed uploader save to the location of the parent class

### ISSUE THREAD

**Issue by Gazler** [carrierwaveuploader/carrierwave#1064]
I have made a repository that displays this issue at https://github.com/Gazler/carrierwave-upload-versions

I am not sure if this behaviour is intended.  I have the following Uploader that sets the versions to be used by other Uploaders:

```ruby
class BaseUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :file

  version :square do
    process :resize_to_fill => [380, 380]
    end

  version :thumb, :from_version => :square do
    process :resize_to_fill => [119, 119]
  end
end
```

I then want to override the store location when an uploader subclasses this, so I do the following:

```ruby
class AvatarUploader < BaseUploader

  def store_dir
    "uploads/people/pictures/#{model.id}"
  end
end
```

When I upload an image, I get the following urls:

```ruby
User.first.avatar.url # "/uploads/people/pictures/4/avatar.png"
User.first.avatar.thumb.url #"/uploads/thumb_avatar.png"
```

I would expect the url of the thumbnail to be:

```ruby
User.first.avatar.thumb.url #"/uploads/people/pictures/thumb_avatar.png"
```

Apologies if this is intentional or has been raised before.

**Comment by eavgerinos** [comment]
This is a general design issue that can be seen [here](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L69). 

Any patch that changes this logic without breaking something will be appreciated.

**Comment by Christian-Hansen** [comment]
I'm also seeing this issue when I'm subclassing a `base_uploader`. If files are defaulted to `fog_public = false` in my `base_uploader`-class. Even when I set 

```ruby
def self.fog_public
  true
end
```

In a subclass, this is only respected for the original file, but not in `version`-calls. So for now, I've done this

```ruby
version :thumb do
  def fog_public
    self.class.fog_public
  end
  process resize_to_fill: [200, 200]
end
```

Based on suggestion here: https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L96 but it hurts my eyes.

**Comment by thomasfedb** [comment]
@chrhansen if you believe that you have found a genuine bug, rather than a design choice, please report a new issue.

**Comment by tbrammar** [comment]
We've just run into this same issue. As this is by design perhaps it might be helpful to highlight this in the Readme text?
