### ISSUE TITLE
remote_image_url not work properly in before_save callback

### ISSUE THREAD

**Issue by HappySoft** [carrierwaveuploader/carrierwave#1078]
Consider sample Uploader and Model:

``` ruby
class ImageUploader < CarrierWave::Uploader::Base
  storage :file
end

class User < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  before_save do
    self.remote_image_url = 'http://www.eso.org/public/archives/images/screen/eso1119b.jpg'
  end
end
```

When model User saving, Carrierwave actually download remote image, save it on the disk, but not save in DB field `image` with file name. I expected, Carrierwave will properly set `image` column with file name of remote image.
Test it in rails console:

```
> u = User.create!
=> #<User id: 3, image: nil, created_at: "2013-04-24 21:23:55", updated_at: "2013-04-24 21:23:55">
> u.image
=> /uploads/eso1119b.jpg
> u = User.last
=> #<User id: 3, image: nil, created_at: "2013-04-24 21:23:55", updated_at: "2013-04-24 21:23:55">
> u.image
=>
> u.image.present?
=> false
```

So, image file was persisted and left orphaned -  there is no info about it in DB.

**Comment by codener** [comment]
Thanks! I had the same problem as you, but didn't figure THIS.
