### ISSUE TITLE
Carrierwave with Rails 3.2.13, TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by smoothdvd** [carrierwaveuploader/carrierwave#1079]
TypeError - no implicit conversion of nil into String:
  (gem) carrierwave-0.8.0/lib/carrierwave/uploader/cache.rb:159:in `cache_path'
  (gem) carrierwave-0.8.0/lib/carrierwave/uploader/cache.rb:131:in`block in cache!'
  (gem) carrierwave-0.8.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  (gem) carrierwave-0.8.0/lib/carrierwave/uploader/cache.rb:122:in`cache!'
  (gem) carrierwave-0.8.0/lib/carrierwave/mount.rb:327:in `cache'
  (gem) carrierwave-0.8.0/lib/carrierwave/mount.rb:179:in`file='
  (gem) carrierwave-0.8.0/lib/carrierwave/orm/activerecord.rb:38:in `file='
  app/controllers/admin/images_controller.rb:14:in`create'
  (gem) actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/base.rb:167:in`process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:436:in `_run__952615287020680754__process_action__1782160296596935145__callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`__run_callback'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:81:in`run_callbacks'
  (gem) actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in`process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`block in instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  (gem) activesupport-3.2.13/lib/active_support/notifications.rb:123:in`instrument'
  (gem) actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  (gem) actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  (gem) activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  (gem) actionpack-3.2.13/lib/abstract_controller/base.rb:121:in`process'
  (gem) actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
  (gem) actionpack-3.2.13/lib/action_controller/metal.rb:203:in`dispatch'
  (gem) actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  (gem) actionpack-3.2.13/lib/action_controller/metal.rb:246:in`block in action'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in`call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in`block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  (gem) rack-1.4.5/lib/rack/etag.rb:23:in `call'
  (gem) rack-1.4.5/lib/rack/conditionalget.rb:35:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in `call'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:210:in`context'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in`call'
  (gem) activerecord-3.2.13/lib/active_record/query_cache.rb:64:in `call'
  (gem) activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in`_run__2649398181073966691__call__4445070734432223285__callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:79:in`better_errors_call'
  (gem) better_errors-0.8.0/lib/better_errors/middleware.rb:56:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:32:in`call_app'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:16:in `block in call'
  (gem) activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in`tagged'
  (gem) railties-3.2.13/lib/rails/rack/logger.rb:16:in `call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in`call'
  (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  (gem) rack-1.4.5/lib/rack/runtime.rb:17:in`call'
  (gem) activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  (gem) rack-1.4.5/lib/rack/lock.rb:15:in`call'
  (gem) actionpack-3.2.13/lib/action_dispatch/middleware/static.rb:63:in `call'
  (gem) railties-3.2.13/lib/rails/engine.rb:479:in`call'
  (gem) railties-3.2.13/lib/rails/application.rb:223:in `call'
  (gem) railties-3.2.13/lib/rails/railtie/configurable.rb:30:in`method_missing'

**Comment by izumeroot** [comment]
Sorry. But can I fix it, if I need  multiple=true? I use rails 3.2.13

**Comment by GSMgo** [comment]
just use` f.file_field`
