### ISSUE TITLE
uninitialized constant CarrierWave::Mount (NameError)

### ISSUE THREAD

**Issue by leebrooks0** [carrierwaveuploader/carrierwave#1103]
When I follow the instructions on the docs about after loading my ORM to require 'carrierwave/orm/activerecord' (I did this in application.rb), I get the message below. 
SO informed me that I just need to require 'carrierwave'. I did that and everything works.
I am using Rails 4 and Ruby 2.

``` shell
lee@lee-pc:~/Code/keep_it_local/test/controllers$ rails c
/home/lee/.rvm/gems/ruby-2.0.0-p0/gems/carrierwave-0.8.0/lib/carrierwave/orm/activerecord.rb:9:in `<module:ActiveRecord>': uninitialized constant CarrierWave::Mount (NameError)
    from /home/lee/.rvm/gems/ruby-2.0.0-p0/gems/carrierwave-0.8.0/lib/carrierwave/orm/activerecord.rb:7:in `<module:CarrierWave>'
    from /home/lee/.rvm/gems/ruby-2.0.0-p0/gems/carrierwave-0.8.0/lib/carrierwave/orm/activerecord.rb:6:in `<top (required)>'
    from /home/lee/Code/keep_it_local/config/application.rb:4:in `require'
    from /home/lee/Code/keep_it_local/config/application.rb:4:in `<top (required)>'
    from /home/lee/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:64:in `require'
    from /home/lee/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:64:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by unmultimedio** [comment]
Sorry to still misunderstood this. @bensie says that the only need in rails is just include the gem in `Gemfile`, but @0bserver07 says you need to put the `require 'carrierwave/orm/activerecord'` in `environment.rb`.

Which one is it? (Rails 5.0.1)

**Comment by Joemarc** [comment]
For me the problem was indeed to have  `require 'carrierwave/orm/activerecord' `in  `environment.rb`, it worked only with the call in the gemfile
