### ISSUE TITLE
Carrierwave with amazon s3 not work with counter_culture gem

### ISSUE THREAD

**Issue by shir** [carrierwaveuploader/carrierwave#1127]
If you create model like this

``` ruby
class UploadTest < ActiveRecord::Base

  belongs_to :category

  attr_accessible :category_id, :something

  mount_uploader :something, PhotoUploader

  counter_culture :category
end
```

with uploader connected to s3 (fog and carrierwave-aws backends have same behavior) after updating file only file name in database is updated, but new file on s3 is not uploaded (old file stays on s3). This issue only on updating file, creating new object works ok.

Not sure if I should create same issue in [counter_culture](https://github.com/magnusvk/counter_culture/issues/new) project.

**Comment by danielevans** [comment]
This issue appears to be caused by the fact that counter_culture is doing a `#dup` and would be fixed by https://github.com/carrierwaveuploader/carrierwave/pull/1544
