### ISSUE TITLE
Using CloudFront CDN for private files

### ISSUE THREAD

**Issue by tkbeili** [carrierwaveuploader/carrierwave#1158]
It seems like if I have fog_public set to false:

``` ruby
config.fog_public       = false
```

It seems to ignore the asset host parameter:

``` ruby
config.asset_host       = 'https://xxxxxx.cloudfront.net'
```

It seems like the asset host is used only in public URL: https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L281 

So it seems like authenticated URL doesn't use that:
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L139

CloudFront allows serving private CDN content: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html

I wonder if there is a way to serve private CDN content using CarrierWave?

**Comment by casiodk** [comment]
might this work?
http://stackoverflow.com/questions/9956712/use-cdn-with-carrierwave-fog-in-s3-cloudfront-with-rails-3-1#answer-22751020
