### ISSUE TITLE
`recreate_versions!(...)` ignores `:from_version => ...`

### ISSUE THREAD

**Issue by igreg** [carrierwaveuploader/carrierwave#1164]
Having the following code:

``` ruby
class MyUploader < CarrierWave::Uploader::Base
  version :medium do
    ...
  end

  version :small, :from_version => :medium do
    ...
  end
end
```

CarrierWave works as expected when I assign the file for the first time.
It also works when I call `recreate_versions!` without any parameters.
But when I call `recreate_versions!(:small)`, it ignores `:from_version` and use the original file that was uploaded.

I suspect the bug to be in the method `recreate_versions!`:

``` ruby
def recreate_versions!(*versions)
  # Some files could possibly not be stored on the local disk. This
  # doesn't play nicely with processing. Make sure that we're only
  # processing a cached file
  #
  # The call to store! will trigger the necessary callbacks to both
  # process this version and all sub-versions
  if versions.any?
    file = sanitized_file if !cached?
    store_versions!(file, versions)
  else
    cache! if !cached?
    store!
  end
end
```

https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L223

It passes `sanitized_file` to `store_versions!` which I suspect is the original file that was uploaded instead of being the cache version corresponding to `:medium`

**Comment by mchlfhr** [comment]
Just stumbled over this. Sad, it is not fixed yet (confirming issue still exists using CarrierWave 0.10.0). It would make my code much cleaner.

I saw this when I wanted to do some of my picture work over a background job - where several jobs do different manipulations (e.g. one does a resize another does some cropping stuff). With a working `recreate_versions!(...)`, this would have been much easier. 

I am currently using CarrierWaves conditional-versions for achieving my goal:

    version :thumb, if: :size_job? do
      process resize_to_fill: [165, 165]
    end

and then:

    protected
    
    def size_job?(file)
      model.job_processing.present? && model.job_type == "size"
    end

Whereby `.job_processing` and `.job_type` are virtual attributes of the model set by the job at execution.

**Comment by thomasfedb** [comment]
May be related to #1602.

**Comment by fwuensche** [comment]
Meanwhile, what's a possible way to work around this problem?

**Comment by fwuensche** [comment]
I followed more or less @andrewcohen solution. I didn't overwrite recreate_versions though. That's because I don't want other people to be surprise if their method does not work as usual. 

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::ImageOptimizer
  include CarrierWave::RMagick

  storage :fog

  def recreate_versions_for!(*versions)
    if versions.any?
      removable_versions(versions).each { |name, v| v.remove! }
      from_versions = versions.group_by { |v| self.class.versions[v][:options][:from_version] }
      from_versions.each do |from, versions|
        next if from.nil?
        file = CarrierWave::SanitizedFile.new(self.versions[from.to_sym].file)
        store_versions!(file, versions)
      end
    end
  end

  def removable_versions(requested_versions)
    versions.select { |k, v| requested_versions.include?(k) }
  end

  # ...
end
```

Be careful if you have multiple images chained one after the other. For example, the code below won't work if you try to recreate :thumb. 

```ruby
version :xlarge do
  ...
end

version :large, from_version: :xlarge do
  ...
end

version :thumb, from_version: :large do
  ...
end
```

So please make sure all of them have at most one dependency, for instance:

```ruby
version :xlarge do
  ...
end

version :large, from_version: :xlarge do
  ...
end

#                             vvvvvvv
version :thumb, from_version: :xlarge do
  ...
end
```

Than you can call:

```ruby
a = Art.find(123)

# since xlarge only depends on the original file
art.image.recreate_versions!(:xlarge)

art.image.recreate_versions_regarding_from_version!(:large)
art.image.recreate_versions_regarding_from_version!(:thumb)
```

**Comment by molefrog** [comment]
For those who stumbled upon this issue, the hacks proposed by @fwuensche and @andrewcohen don't work starting from version 1.0.0 (didn't have chance to test it on earlier versions, sorry).
Using monkey patching is probably not the best idea for production apps, so I decided to change the code to `recreate_versions!` without any parameters. Also, we use fog, so the patch won't help anyway.

However, I do feel like the fix should be quite easy to implement. I started my own research by reading the source code, but seems like I don't exactly understand some core concepts like caching etc. Does anyone here have some time to guide me over the source code and maybe help me doing a PR?

Hope, I can get some attention from the team members 🙏

**Comment by graudeejs** [comment]
I've stumbled upon this as well.
While recreate_versions! for particular versions don't work well (ignores ```:from_version``` options), It works fine without arguments (in which case it recreates all versions correctly).

For me, at this moment it's good enough given that my files are on servers disk. I haven't checked if this works as expected if files are in S3 though.
