### ISSUE TITLE
Cannot remove cached Files

### ISSUE THREAD

**Issue by vardhan-nyros** [carrierwaveuploader/carrierwave#1234]
Hi,

I am running a cron job to remove carrierwave cached files using Carrierwave.clean_cached_files! method. But this does not seem to work.

Here is my Carrierwave initializer file.
CarrierWave.configure do |config|
  config.root = Rails.root.join('tmp')
  config.cache_dir = 'carrierwave'
  config.fog_credentials = {
      :provider => 'AWS',
      :aws_access_key_id => s3.access_key_id,
      :aws_secret_access_key => s3.secret_access_key,
      :region => s3.bucket_region when creating the bucket
  }
  config.fog_directory = s3.bucket
  config.fog_attributes = {'x-amz-storage-class' => 'REDUCED_REDUNDANCY'}

and here is my scheduler code to run cron job
every :day, at: ["10:00 pm"] do
  runner "CarrierWave.clean_cached_files!"
end

My problem is whenever tmp/carrierwave/ folder becomes more than 1.5GB images are not uploading.

Thanks in advance

**Comment by eavgerinos** [comment]
This issue if fixed.
