### ISSUE TITLE
resize_to_fill adds white borders with GraphicsMagick

### ISSUE THREAD

**Issue by scarfacedeb** [carrierwaveuploader/carrierwave#1242]
I'm using carrierwave to upload images and minimagick to resize them.

I'm trying to resize and crop images using `resize_to_fill` method. (so, I'll always get images with the same fixed size)

When I **don't** use GraphicsMagick, it all works well and I get images like that:
![imageMagick](https://f.cloud.github.com/assets/706648/1320131/adf224ce-333b-11e3-8aa7-028f7ba29a67.jpg)

But when I **use** graphicsMagick, it adds strange left and right white paddings to the images:
![graphicsMagick](https://f.cloud.github.com/assets/706648/1320134/f0651ea6-333b-11e3-9a2d-1f522024fca8.jpg)

Original image: https://dl.dropboxusercontent.com/u/9877279/ava_cropped.jpg

Related code section (in my ImageUploader class):

``` ruby
# using graphicsMagick instead of imageMagick
MiniMagick.processor = :gm

version :thumb do
    process resize_to_fill: [165, 135]
end
```
### Software versions

OS: Debian sid
imageMagick: 8:6.7.7.10-6
graphicsMagick: 1.3.16-1.1+b2

**gems:**
mini_magick (3.6.0)
carrierwave (0.9.0)
rails (4.0.0)

_I'm not sure where should I report this issue: here or minimagick tracker?
But given that `resize_to_fill` method is defined inside `lib/carrierwave/processing/mini_magick.rb`, I thought that this would be more appropriate place for this issue._

**Comment by kesha-antonov** [comment]
Same. Did anyone fix it?

**Comment by kesha-antonov** [comment]
This works https://github.com/carrierwaveuploader/carrierwave/issues/694
