### ISSUE TITLE
Images with missing/wrong extensions

### ISSUE THREAD

**Issue by NielsKSchjoedt** [carrierwaveuploader/carrierwave#1247]
I have been struggling a lot with issues concerning remote image paths that does not have a regular image extension, and hence cannot be processed by carrierwave. This is often the case with remote images on image servers etc. E. g. "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbK2NSUILnFozlX-oCWQ0r2PS2gHPPF7c8XaxGuJFGe83KGJkhFtlLXU_u" The file does not have a .jpeg extension, but the content_type is always correct in those examples. In this case `Kernel.open` would return `"content-type"=>"image/jpeg"`.

The other day I stumbled upon this solution  http://stackoverflow.com/a/19384117/1002814 and I'm wondering why this is not the default actually?

**Comment by yllihv27** [comment]
Not working on this image url https://api.tbotechnology.in/imageresource.aspx?img=FbrGPTrju5e5v0qrAGTD8pPBsj8/wYA5fyPRj8rAX+R5MnG/qe2Xb8ueHLbdyMeDVVxboAU+ZCXgWhBgn65dhqCeVbV9c4elBy/wk3I3G2RgiVB6XTRYPQ==
