### ISSUE TITLE
CarrierWave::SanitizedFile#content_type is nil when move_to_cache is true

### ISSUE THREAD

**Issue by KieranP** [carrierwaveuploader/carrierwave#1259]
When Consider this setup that I have:

``` ruby
class AttachmentUploader < CarrierWave::Uploader::Base
  # Prevent expensive and unneeded copies of large files
  def move_to_cache
    !Rails.env.test?
  end
end

class Attachment < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  before_save :store_file_attributes

  private

  def store_file_attributes
    self.file_name = self.attachment.file.filename
    self.file_size = self.attachment.file.size
    self.file_type = self.attachment.file.content_type
    true
  end
end
```

Then upload a file and inspect the resulting Attachment instance. The file name is set, the file size is set, but the file type is nil.

The result of self.attachment.file (which returns a CarrierWave::SanitizedFile instance) doesn't have a content_type set.

If I comment out the move_to_cache method it works (the content type is set as expected). However, we need the move_to_cache method because we accept large multi-gigabyte files and don't want a bottleneck with IO).

The ActionDispatch::Http::UploadedFile instance that Rails gets after the upload has the correct content type, just not the carrierwave instance.

Any reason why this shouldn't be working correctly?

**Comment by thomasfedb** [comment]
@KieranP if this is still an issue that needs to be fixed please request this issue be reopened.
