### ISSUE TITLE
remote url with white list error

### ISSUE THREAD

**Issue by KazuhiroIwata** [carrierwaveuploader/carrierwave#1287]
hi guys,

i have installed rails 4 and carrierwave (0.9.0) and it has the following problems.

1: Successful conditions 

 def extension_white_list
       %w(jpg jpeg gif png)
 end
 
 remote_avator_url: http://graph.facebook.com/100000042265252/picture?type=large

2 : Failure conditions
 def extension_white_list
      %w(jpg jpeg gif png)
 end

remote_avatar_url: https://lh4.googleusercontent.com/-LlQdk-l6mOE/AAAAAAAAAAI/AAAAAAAAAIw/ySB3XhJhplw/photo.jpg

Errors : avatar=>["You are not allowed to upload \"\" files, allowed types: jpg, jpeg, gif, png"]

2.5 :Failure conditions

comment out 

def extension_white_list
     # %w(jpg jpeg gif png)
end

remote_avatar_url: https://lh4.googleusercontent.com/-LlQdk-l6mOE/AAAAAAAAAAI/AAAAAAAAAIw/ySB3XhJhplw/photo.jpg

Although the picture has been acquired, the avatar filed shows '__' strings.

**Comment by thomasfedb** [comment]
@KazuhiroIwata this appears to be an issue with the header received from Google, rather than an issue in Carrierwave. I feel that obeying the `content-disposition` is reasonable. As noted by @VladimirMikhailov, there are workarounds for when the headers should be ignored.
