### ISSUE TITLE
Stack level too deep when file does not exist but db record does.

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [carrierwaveuploader/carrierwave#1308]
This problem is caused by the fact that using remove_[attribute] in my form removes the file on disk but leaves the db entry intact. Simply loading the edit page of my model instance when there's a filename in the db's column but no actual file raises this error.

webrat (0.7.3) lib/webrat/core_extensions/blank.rb

Better_errors highlights the contents of def blank? as the error.
class String #:nodoc:
  def blank?
    self !~ /\S/
  end
end

**Comment by stanhu** [comment]
FYI, CarrierWave v0.7.0+ does indeed delete the filename from the database (see https://github.com/carrierwaveuploader/carrierwave/pull/712). If the filename is not being updated, it's possible a validation in your model has failed, causing the save to fail. I found that after removing the image, a blank or nil filename would then cause `ActiveRecord::RecordInvalid` to be thrown. For thsoe of you having issues, you may want to change your `model.save` to `model.save!` to see if you can catch the problem.

**Comment by kntmrkm** [comment]
In my case

```
upload_file = ActionDispatch::Http::UploadedFile.new(
          filename: "#{file_name}.csv", type: 'text/csv', tempfile: f)
        @project.remove_csv!
        @project.update_column(:csv, nil)
        @project = Project.find(@project.id) # reload not works well
        @project.csv = upload_file
        @project.save!
```

it works
