### ISSUE TITLE
Skip Copy on Version

### ISSUE THREAD

**Issue by narfanator** [carrierwaveuploader/carrierwave#1310]
So, we're using Carrierwave to catch incoming video files, and then using Zencoder to do the conversion from whatever is uploaded to m4v. 

However, CW, when making a version of a file, makes a copy of that file, runs the process, and then uploads the resulting file - since we're not actually processing the file into it's final form in the `process` directive for that version, we don't actually want that to happen. Is there a way to tell CW to skip that step?

If there isn't, can you give a few pointers about where to stick in some code to add that feature, so we have an easier time making a pull request?

Thanks!
(BTW, CarrierWave is one of my all-time favorite gems, so thank you guys for an excellent job!)

**Comment by thomasfedb** [comment]
If this feature is still required please request this issue be reopened.

**Comment by asselstine** [comment]
I've come across a need for this feature now in several projects, as uploading direct to S3 is a must for Heroku.

I would be open to helping out on this feature, but I would need to know where to start in the code base.  I've poked through but the code is very meta, so some high level advice would be useful.
