### ISSUE TITLE
"remove_" attribute does not respect validates_presence_of in model

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [carrierwaveuploader/carrierwave#1316]
Using `validates_presence_of :photo` works just fine for saves of a new model instance, but  it fails when I remove a photo on an existing instance.

1) Create new instance with a photo
2) Update the instance by clicking a check box named appropriately (remove_photo in my case)
3) Model is saved and photo is deleted. This shouldn't happen if `validates_presence_of :photo` exists.

**Comment by tboyko** [comment]
I solved this issue in my implementation by adding a custom validation. If I have an activerecord model `Person` and attribute/attachment `headshot`, I add `validate :headshot` to the `Person` model:

    def headshot_is_present
        unless headshot.present? && !remove_headshot
            errors.add :base, "A headshot image must be provided"
        end
    end

This seems to take care of situations where removing the image from an existing object should cause it to fail validation.

**Comment by rlue** [comment]
@bensie, is there any reason that CarrierWave couldn't set a `before_save` callback on models that simply sets the `model.photo = nil` if the `remove_photo` var is set? That'd be sufficient to trip the presence validation on the attribute, wouldn't it?
