### ISSUE TITLE
Update after removing file re-saves the file path pointing to the removed file

### ISSUE THREAD

**Issue by lsimoneau** [carrierwaveuploader/carrierwave#1333]
I'm using CarrierWave with the fog storage engine. If I load a record, then do the following steps:

```ruby
post.remove_image!
post.save
```

This executes:

```sql
UPDATE `posts` SET `image` = NULL, `updated_at` = '2014-03-06 22:59:19' WHERE `posts`.`id` = 3787
```

But if later on in the same request I need to update the post's other attributes: 

```ruby
post.update(title: "new title")
```

This executes:

```sql
UPDATE `posts` SET `title` = 'new title', `image` = '1394146746-17935-1645/my_image.jpg', `updated_at` = '2014-03-06 23:01:10' WHERE `posts`.`id` = 3787
```

It seems as though something's leftover in the model attributes after calling the `remove_image!` so it's re-persisted incorrectly in subsequent saves. Any ideas?

**Comment by amartell-smx** [comment]
I'm having this issue, any fix or workaround?

**Comment by markets** [comment]
Hi @amartell-smx, I think this is still an issue. Related: https://github.com/carrierwaveuploader/carrierwave/issues/1594.

In my case, the workaround was to reload the instance (same as @lsimoneau):

```
reconstruction.reset_images!
reconstruction = Reconstruction.find(reconstruction.id)
```

**Comment by thomasfedb** [comment]
If this issue persists please request this issue be reopened.
