### ISSUE TITLE
Don't require all of Fog

### ISSUE THREAD

**Issue by bquorning** [carrierwaveuploader/carrierwave#1337]
In lib/carrierwave/storage.rb, we currently require all of Fog

``` rb
begin
  require "fog"
rescue LoadError
end
```

And following that, we require lib/carrierwave/storage/fog.rb

Recently (for ~~v1.12.0~~ v1.20.0), Fog was changed so that each storage backend can be required separately: fog/fog#1712.

It would be nice if we could change this to only require `"fog/core"` and let Carrierwave users be responsible for requiring the storage backends they need. In my case, I would just `require 'fog/aws/storage'` somewhere in my application.

**Comment by blarralde** [comment]
This is very useful! Saving almost 10mb of memory with that.

Will a new gem version including that update be released soon? 

PS this is my f4v0r1t3 155u3.
