### ISSUE TITLE
Validation failing for uploaded image containing a space on 0.10.0

### ISSUE THREAD

**Issue by greggomalley** [carrierwaveuploader/carrierwave#1342]
On updating to 0.10.0 I can no longer upload images with paths that contain a space. Things seem to still work fine on 0.9.0.

I'm developing on Windows 7 using Carrierwave with MiniMagick.

The error being returned is:

> ActiveRecord::RecordInvalid - Validation failed: Image Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: identify.exe: unable to open image `D:/My': No such file or directory @ error/blob.c/OpenBlob/2643.

As you can see the file being sent to the minimagick is being truncated at the space (path should be something like "D:/My Files/uploads/img.png"). I tried to trace it though and compare it to the code for 0.9.0 and it appears the exception is first being raised in mini_magick.rb at line 266 on version 0.10.0. This line contains the following code

```
image.run_command("identify", current_path)
```

This seems to be new for 0.10.0. I'd guess that the current_path needs to be escaped at some point before executing the minimagick command? I'm no expert though so I could be wrong here, but I just wanted to give any context I could.

**Comment by thomasfedb** [comment]
@G0dwin would you consider submitting a pull request with your changes?

**Comment by mshibuya** [comment]
Fixed in MiniMagick side by https://github.com/minimagick/minimagick/commit/a86f48224b36cb422d5ea1bfa44e3e954ccf3040.
