### ISSUE TITLE
ApplicationUploader.enable_processing takes priority over SubclassedUploader.enable_processing

### ISSUE THREAD

**Issue by shekibobo** [carrierwaveuploader/carrierwave#1349]
I have an `ApplicationUploader` and a `DocumentUploader`. In my specs:

```ruby
require 'carrierwave/test/matchers'

describe ApplicationUploader do
  include CarrierWave::Test::Matchers

  context "with a pdf" do
    before(:all) do
      puts "\n-- Testing Uploader: ApplicationUploader\n"
      ApplicationUploader.enable_processing = true
      @uploader = ApplicationUploader.new(Fabricate.build(:media_item), :attachment)
      @uploader.store!(File.open(Rails.root.join("spec", "support_files", "sample.pdf")))
    end

    after(:all) do
      ApplicationUploader.enable_processing = false
      @uploader.remove!
    end
    
    # ...
  end
end
```

```ruby
require 'spec_helper'
require 'carrierwave/test/matchers'

describe DocumentUploader do
  include CarrierWave::Test::Matchers

  context "with a pdf" do
    before(:all) do
      puts "\n-- Testing Uploader: DocumentUploader\n"
      # ApplicationUploader.enable_processing = true
      DocumentUploader.enable_processing = true
      @uploader = DocumentUploader.new(Fabricate.build(:media_document), :attachment)
      @uploader.store!(File.open(Rails.root.join("spec", "support_files", "sample.pdf")))
    end

    after(:all) do
      # ApplicationUploader.enable_processing = false
      DocumentUploader.enable_processing = false
      @uploader.remove!
    end
  end
end
```

If `application_uploader_spec` runs before `document_uploader_spec`, `document_uploader_spec` will not run processing, despite the processing being enabled for the subclassed uploader. If the `document_uploader_spec` runs first, all is well. In order to get specs to pass, the commented line needs to run to enable processing on both `ApplicationUploader` and `DocumentUploader`.

I believe this is also the case when using `config.enable_processing` - processing will use the highest-level value to determine whether processing should occur, and cannot be overridden by the subclasses.

I don't know if this is actually an issue - which is a better way to go - but I've spent a few hours racking my brain over this and thought that it should at least be documented somewhere. It seems like if I can toggle processing at the instance level, I should be able to toggle processing at the class level as well, rather than the parent class or configuration rule all.

**Comment by thomasfedb** [comment]
@shekibobo If you believe this is a bug, please submit a new issue. New features are welcome if you are able to provide an implementation.
