### ISSUE TITLE
FloatDomainError: Infinity

### ISSUE THREAD

**Issue by alexch** [carrierwaveuploader/carrierwave#1378]
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/mini_magick.rb#L177 doesn't check for "0" in dimensions returned by minimagick. This is possible when a slightly-corrupt image is uploaded -- not corrupt enough to fail completely, but enough to make minimagick/imagemagick think its dimensions are 0x0. This causes the Carrierwave code to divide by zero, which makes Infinity, and rounding Infinity will raise a `FloatDomainError`.

My suggestion would be to check for 0 in either dimension and raise a proper exception with a good explanation, and then to catch it and add it to the ActiveRecord "errors" list for that field and fail validation.

**Comment by kroky** [comment]
Just to note that we are experiencing the same issue in production and will follow your advice of writing our own resize methods. However, if this happens often, it might be worth to include such methods in the core...
