### ISSUE TITLE
content-type wrong when converting specific format

### ISSUE THREAD

**Issue by johnvoloski** [carrierwaveuploader/carrierwave#1388]
`CarrierWave 0.8.0`
`Ruby 1.9.3-p545`

``` ruby
# Uploader
process convert: 'png'
process set_content_type: true
```

``` ruby
uploader = Uploader.new
uploader.image = 'image.jpeg'
uploader.store!
```

https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/mime_types.rb#L60

Content-type should be based on the new format, but is based on the original image

**Comment by thomasfedb** [comment]
@timherby @FabianOudhaarlem could you please provide a minimal reproduction of this issue with carrierwave 0.10.0.

**Comment by timherby** [comment]
Thanks for the follow-up.  We actually switched to a different solution using carrierwave only for upload and [ImgIx](https://www.imgix.com/) for resizing/formatting.  So we no longer need this.

**Comment by lostapathy** [comment]
I  am seeing this using carrierwave 1.2.2 and mini_magick 4.8.0 and then uploading the image to S3 with fog-aws 2.0.0.  The image format conversion is successful, but the original (now wrong) mime-type is stored in S3, which causes S3 to serve the file back out with the wrong mime-type.

In our case, we're converting pdf to png, and getting those mime-types mixed up is not handled gracefully by the browser.  We're working around it with a solution inspired by #617 for now.

**Comment by mshibuya** [comment]
Fixed by https://github.com/carrierwaveuploader/carrierwave/pull/2237.
