### ISSUE TITLE
Rename files after upload

### ISSUE THREAD

**Issue by firedev** [carrierwaveuploader/carrierwave#1401]
Is there a way to rename files after upload? I want filenames to match model ID after it was saved:

```
# image.rb

after_create :rename_file

def rename_file
  file.rename!(id)
end
```

But I can't find a simple way to do this.

**Comment by ginolon** [comment]
Hi, I don't know how to rename my uploaded files. Can you help me?

Here is my question: https://github.com/carrierwaveuploader/carrierwave/issues/1639

**Comment by TiSer** [comment]
@chrisalley Did you create that gem for Paperclip and Carrerwave? :)

**Comment by chrisalley** [comment]
@TiSer No I didn’t. There’s probably no point supporting Paperclip now (since it has been deprecated), but it might be worth investigating a solution for CarrierWave, Active Storage, and others.

**Comment by JesusGautamah** [comment]
1. **create file hash column on db**
`rails g migration AddFileHashToObject file_hash:string`

2. **define your method to rename file in controllers/object_controller.rb**
`def file_hash_creator`
`  new = rand(0..100000000).to_s(16)`
`  enc = encstr.hex`
 `  return enc`
 `end`
  
3. **controllers/object_controller.rb in  create add line**
`@object.file_hash = Digest::SHA2.hexdigest   file_hash_creator().to_s`

4. **uploaders/file_uploader.rb**
`def filename`
 `  #{model.file_hash}.#{file.extension}" if original_filename`
 `end`

worked for me
