### ISSUE TITLE
asset_host is ignored in production

### ISSUE THREAD

**Issue by firedev** [carrierwaveuploader/carrierwave#1403]
Here is my `config/initializers/carrierwave.rb`:

```
if Rails.env.production?
  CarrierWave.configure do |config|
    config.asset_host = "//images.whatever.com"
  end
end
```

It works on local when I run `rails s -e production` but once deployed the directive is being ignored. At the same time `config.action_controller.asset_host` works. I have tried to initialise CarrierWave both in a separate initialiser and in `production.rb` - nothing. Works on localhost either way though.

Is there something I am missing? Thanks.

**Comment by RathanakSreang** [comment]
@firedev 
I also face same kind of problem.
Can you tell me how you fix it?

**Comment by firedev** [comment]
Sorry, this was it, it works. Does it work on localhost? Maybe the server is not restarted when you deploy?

**Comment by RathanakSreang** [comment]
I did restart server many time.
