### ISSUE TITLE
Doesn't seem to work: "Making uploads work across form redisplays"

### ISSUE THREAD

**Issue by jmuheim** [carrierwaveuploader/carrierwave#1414]
When uploading a new file and triggering a validation error, then saving again without validation error, the newly selected file is not uploaded, but still the old file is there (or none, if there wasn't one).

It seems to be a common problem, as I found already these posts on StackOverflow:
http://stackoverflow.com/questions/16431089/carrierwave-cache-not-resubmitting
http://stackoverflow.com/questions/9783904/carrierwave-not-saving-upload-after-form-redisplay

Still, I couldn't find a fix. I have the `avatar` and `avatar_cache` fields whitelisted in StrongParameters, and the hidden `avatar_cache` field is there in the form, too.

You can check the problem out here: http://base.sirius.uberspace.de/

Just do the following:

- Click on "Sign up"
- Select an avatar image
- Click "Sign up"
- You should see some validation errors and the previously selected avatar image
- Fill out the inputs correctly, so the next submit won't have any validation errors anymore
- Click "Sign up" again
- You should now be registered. But the image isn't there (otherwise it would be displayed next to "Welcome, Username")
- You can click on "Edit account" and trigger the same behaviour again - or you can upload an image successfully when avoiding any validation errors.

You can check out the source of the Rails app here: https://github.com/jmuheim/base/tree/features/avatar_upload

All specs should pass. You can then go to `spec/features/file_upload_spec.rb` and uncomment lines 50-52, then run the specs again. Now the spec testing the behavior above fails.

It would be really nice to have a fix for this problem. Thank you. :+1:

**Comment by jmuheim** [comment]
The issue was fixed, I forgot to add `:avatar_cache` to the permitted params.

**Comment by fatuhoku** [comment]
Hmmm the URL of your project is broken! Did you use `redirect_to` or `render`

**Comment by fatuhoku** [comment]
Hmm. This seems to be broken for Rails 4.2.5.   I even tried adding:

```
# my_model.rb
attr_accessor :avatar_cache
```

What's going on?
