### ISSUE TITLE
Adding a text watermark?

### ISSUE THREAD

**Issue by kapso** [carrierwaveuploader/carrierwave#1427]
I am trying to add a text watermark to my image, but it does not work - as in when I run this code with `watermark` processing, the image fails to upload?

I took the MiniMagick watermarking code from here - http://snippets.aktagon.com/snippets/197-how-to-add-a-text-caption-to-an-image-with-minimagick-and-ruby

``` ruby
class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  process :set_content_type
  process :watermark

  def store_dir
    "#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def filename
    "#{Digest::MD5.hexdigest(model.id.to_s)}.png"
  end

  def set_content_type
    file.content_type = 'image/png'
  end

  def watermark
    manipulate! do |img|
      img.combine_options do |cmd|
        cmd.gravity 'south'
        cmd.draw 'text 10,10 "whatever"'
        cmd.font '-*-helvetica-*-r-*-*-18-*-*-*-*-*-*-2'
        cmd.fill 'black'
      end

      img
    end
  end
end
```

**Comment by Reedlee** [comment]
@kapso hi.
I also search answer on this question. Thanks @bensie for signing that it is minimagick issue, as result i found this:

https://github.com/minimagick/minimagick/issues/150

I hope it would be hepfull another people.
