### ISSUE TITLE
after :cache callbacks are called with invalid file object when using :fog as a cache_storage

### ISSUE THREAD

**Issue by pachkovsky** [carrierwaveuploader/carrierwave#1430]
The `cache!` method on `CarrierWave::Uploader::Cache` passes a file object to `with_callbacks` as an argument. 

``` ruby
def cache!(new_file = sanitized_file)
  ...
  with_callbacks(:cache, @file) do
    @file = cache_storage.cache!(@file)
  end
  ...
end
```

While `File` storage modifies the same object

``` ruby
def cache!(new_file)
  new_file.move_to(::File.expand_path(uploader.cache_path, uploader.root), uploader.permissions, uploader.directory_permissions, true)
end
```

`Fog` storage returns new object in `cache!` method and this means that all after callbacks (create_versions! in particular) are called with workfile while they had to be called with cached file instead which in that case is stored at S3 or any other remote storage service.

``` ruby
def cache!(new_file)
  f = CarrierWave::Storage::Fog::File.new(uploader, self, uploader.cache_path)
  f.store(new_file)
  f
end
```

Beside the fact that `:from_version` is completely ignored in that case you can't even have more than one version as workfile is removed after first version was created in `ensure` block.

``` ruby
ensure
  FileUtils.rm_rf(workfile_path(''))
end
```

**Comment by mshibuya** [comment]
I don't consider this to be a bug, it's by design. You should expect that the file is stored remotely after caching, if you're using a remote cache store.
If you need a local file, you can use the `after :process` callback.
