### ISSUE TITLE
Version arg not being passed to `default_url`

### ISSUE THREAD

**Issue by shekibobo** [carrierwaveuploader/carrierwave#1434]
I think [Revert "Only return version url if version exists"](https://github.com/carrierwaveuploader/carrierwave/commit/23767467e6dc152b8c1c309fa07bc12c43f957a1)  is affecting the expected input of [Pass #url args to #default_url](https://github.com/carrierwaveuploader/carrierwave/commit/8ea59c7c685eded5d09cf7c5c163cb84db78ce1a). The updated `url` and `default_url` methods now accept all the arguments, and allow passing a non-existent version and handle it explicitly in an overridden `default_url` method of an uploader.

My use-case depends on a version name being passed, since I'm using conditional versioning, and a version may not exist for a particular subclass of my `ApplicationUploader`. Since `arg.first` is no longer being passed, the requested version cannot be determined and handled.

**Comment by eavgerinos** [comment]
Closing this in favor of #1665 which references extensively non-existent versions and handling them will be discussed there. Thanks for reporting.
