### ISSUE TITLE
Getting a deprecation warnings  for BeNoLargerThan

### ISSUE THREAD

**Issue by torstenb** [carrierwaveuploader/carrierwave#1437]
Getting the following deprecation warning:

```
CarrierWave::Test::Matchers::BeNoLargerThan implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
```

**Comment by jrmyward** [comment]
Did this not make it into the `0.11.0` release? I'm still getting the deprecation warnings after updating the gem.

**Comment by tom-lord** [comment]
I'm still getting deprecation warnings, too. Using `0.11.2`.

**Comment by prrrnd** [comment]
Also getting deprecation warnings for `CarrierWave::Test::Matchers::HaveDimensions`, using `0.11.2`

**Comment by Bastes** [comment]
Also getting the deprecation warnings for ```0.11.2```

**Comment by Bastes** [comment]
Hey guys, I've sent a little pull request to allow all of us who aren't really ready to get to a 1.0.0-beta working on their production projects: https://github.com/carrierwaveuploader/carrierwave/pull/2054
