### ISSUE TITLE
upload multiple files with carrierwave error

### ISSUE THREAD

**Issue by cuihq** [carrierwaveuploader/carrierwave#1464]
I upload 2 jpg flies in a field,so carrierwave talk 'extension_white_list_error'.
```html
<input type="file" name="xxx" multiple/>
```
here is ruby code:
```ruby
def extension_white_list
   %w(jpg jpeg gif png)
end
```
what's up? Please fix it,Thanks!

**Comment by eavgerinos** [comment]
I don't understand exactly your problem. Can you provide more information such as:

- Your uploader
- How did you mount it
- What did you do to get the error

Thanks

**Comment by cuihq** [comment]
On 17 Oct 2014, @jnicklas have added the features., and @bensie merged it.
Not at all.(#1481)
