### ISSUE TITLE
Passing custom headers to Fog

### ISSUE THREAD

**Issue by tacticiankerala** [carrierwaveuploader/carrierwave#1496]
I was trying to use Customer Key encryption for S3. But, I was not able to pass in the right headers to carrierwave so that those headers will be sent to S3(after some pre-processing) using fog. 

For example, 

``` ruby
def file
    @file ||= directory.files.head(path)
end
```

When we call `directory.files.head(path)`, Fog supports passing in headers as options hash but we are ignoring it.

Can we take in an optional hash here and pass it on to `head` method? 

Also, we will have to identify similar places where we can pass on the options hash.

**Comment by stanhu** [comment]
fog-aws does support passing a options hash, but it's not actually used in the headers. We would need to add support for that: https://github.com/fog/fog-aws/issues/571
