### ISSUE TITLE
Suggestion: allow versions redefine

### ISSUE THREAD

**Issue by kuraga** [carrierwaveuploader/carrierwave#1505]
According to [now](https://github.com/carrierwaveuploader/carrierwave/blob/ce4af694905d3b1af631a8c0d0902c19ed726f5b/lib/carrierwave/uploader/versions.rb#L53) we can't redefine versions. So I can't redefine a version in a subclass uploader. I think it breaks inheritance idea.

What about to change this convention?
P.S. Also this is a workaround for #1495 .

Thanks.

**Comment by kuraga** [comment]
Comment, please?

**Comment by bensie** [comment]
Sorry @kuraga! Didn't mean to close without comment.

I'm not opposed to changing that to remove the `unless versions[name]`. Just need to make sure it doesn't break anything else. Care to work up a pull request?

/cc @taavo

**Comment by kuraga** [comment]
ping

**Comment by plribeiro3000** [comment]
@kuraga Since you already did some code research, could you take a stab and open a PR for this?

**Comment by kuraga** [comment]
See also #1671

**Comment by kuraga** [comment]
@plribeiro3000 no, seems like I checked this test only :cry: (#1671)

**Comment by kuraga** [comment]
After research: sorry, it's not an issue. Test like [this](https://github.com/carrierwaveuploader/carrierwave/pull/1671/files#diff-06e25fc69f8838fd8c17cbae5208c59cR167) has been green already. I'm sorry.

**Comment by mhluska** [comment]
But what if instead of overriding you want to extend?
