### ISSUE TITLE
Using rails generator/rspec/smth else when internet is down

### ISSUE THREAD

**Issue by AvaelKross** [carrierwaveuploader/carrierwave#1509]
Hello there! 
I've got a problem with carrierwave using generators/rspec/maybe smth else when internet connection is not possible.
Any of this tasks ends up with error 
```
/Users/Avael/.rvm/gems/ruby-2.1.1@rails411/gems/excon-0.41.0/lib/excon/socket.rb:166:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError) (Excon::Errors::SocketError)
```
So, can I fix it somehow? I've tried to mock fog in test helper:
```ruby
Fog.mock!
Fog.credentials_path = Rails.root.join('config/fog_credentials.yml')
connection = Fog::Storage.new(:provider => 'Rackspace')
connection.directories.create(:key => 'qweqwe')
```
but it's not working for me :(
And ofc it will not resolve problem with generating migrations for example..

**Comment by bensie** [comment]
CarrierWave does not require an Internet connection when running its generators. It's possible that you have something in your Fog config though that is requiring a connection.
