### ISSUE TITLE
SanitizedFile#move_to Issue on OS X

### ISSUE THREAD

**Issue by raja** [carrierwaveuploader/carrierwave#1510]
Since OS X's defaults to using the Extended journal file system with case insensitive, there are some issues with SanitizedFile's move_to. 

I was running into an issue where uploading a file with a capitalized extension ("image.JPG") and processing a format conversion (with minimagick) would cause an exception from move_to. 

same file: /Users/raja/Code/XX/tmp/1417383051-57731-0619/large/IMG_2090.JPG and /Users/raja/Code/XXX/tmp/1417383051-57731-0619/large/IMG_2090.jpg

/Users/raja/.gem/ruby/2.1.3/bundler/gems/carrierwave-888940323195/lib/carrierwave/sanitized_file.rb:184:in `move_to'
/Users/raja/.gem/ruby/2.1.3/bundler/gems/carrierwave-888940323195/lib/carrierwave/processing/mini_magick.rb:307:in`manipulate!'

One fix is to use File.rename instead of FileUtils.mv.

**Comment by Cervenka** [comment]
Did you find temporary workaround for this?

**Comment by jankeesvw** [comment]
I'm seeing the same issue on OSX.

**Comment by thomasfedb** [comment]
Looks to me that there are three ways to solve this issue:

1. Implement `SantizedFile#rename_to` for use when we are renaming files.
2. When generating new files with ImageMagick, we should save them to `/tmp` and then move them to their destination.
3. Remove the file renaming step and save files with the correct name initially.

**Comment by anduong** [comment]
@thomasfedb Do we have any PR for this bug yet?

Where can we apply this `Remove the file renaming step and save files with the correct name initially.`? In the `Uploader`? Can you advise more in details? Thanks.

**Comment by anduong** [comment]
While waiting for the fix in the gem, I have done the workaround like this.
`Download the image with capital extension and name it with normalized name (lower extension) then use upload from local file`
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file

**Comment by bengalamx** [comment]
+1 !!
