### ISSUE TITLE
model.id is empty?

### ISSUE THREAD

**Issue by laerciocrestani** [carrierwaveuploader/carrierwave#1515]
Hey ... I'm using carrierwave with 4 Rails and Ruby 2.x, with multiple upload with jQuery File Upload Plugin 5.42.1  * Https://github.com/blueimp/jQuery-File-Upload

def store_dir
    "imgs/#{Apartment::Tenant.current_tenant}/noticias/#}/#{model.id}"
  end

It's all right, but the directory and the URL that this saving is that?
public/imgs/ligaccbg/noticias/lg_image.jpg

Wish he'd get the ID and separated into folders like this:
public/imgs/ligaccbg/noticias/3/lg_image.jpg

Someone can help me? it's weird not be picking up the ID.

**Comment by eavgerinos** [comment]
I'm sorry. Can't reproduce. I'm using the same technique in most of my uploaders.
