### ISSUE TITLE
Version filename convention change?

### ISSUE THREAD

**Issue by astjohn** [carrierwaveuploader/carrierwave#1519]
At gem version 0.8.0, versioned uploaders produced filenames such as:

`basename_version.filetype`
`balloons_thumb.png`

Indeed, this convention is specified in a wiki article too, so I'm not losing my mind. ;-)
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Customize-your-version-file-names

After upgrading to 0.10.0, it seems this has changed to:

`version_basename.fileype`
`thumb_ballooons.png`

Any reason for this change? What exactly can I do to remedy the situation. I have tried `recreate_versions!` however, I am running into a `CarrierWave::ProcessingError: Failed to manipulate with MiniMagick` problem, which is probably unrelated. I'm using rails4, mongoid4, and the latest carrierwave-mongoid, and carrierwave.

**Comment by thomasfedb** [comment]
The fix is likely to run `recreate_versions!`, once you've ensured that the processing can run successfully.
