### ISSUE TITLE
file validators gem integration

### ISSUE THREAD

**Issue by musaffa** [carrierwaveuploader/carrierwave#1525]
File size and content type validations are perhaps two of the most sought after features of Carrierwave. My gem [File Validators](https://github.com/musaffa/file_validators) is an ActiveModel file validator that can be used in any project, for example CarrierWave, that has a dependency on ActiveModel. It supports validations before and after upload. Give this gem a shoot and let me know if you are interested in integrating FileValidators with CarrierWave.

**Comment by xpepermint** [comment]
+1

**Comment by bensie** [comment]
@musaffa What kind of integration do you have in mind? What issues exist on the CarrierWave side of things that prevent its use as a plugin?

**Comment by eavgerinos** [comment]
@musaffa There is a (feature)[https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/magic_mime_whitelist.rb] for validating the actual content type in the master branch.

As for the FileSize you can always write a module in your application that emits an IntegrityError (just like the one above) and include it in your Uploader.

**Comment by eavgerinos** [comment]
@musaffa Yeap

**Comment by musaffa** [comment]
Unix `file` command also uses magic number to detect the content type. Is there any extra benefit of using `filemagic`?

**Comment by eavgerinos** [comment]
Kind of out of the scope of this issue, but, yes, you skip the fork/exec overhead from executing shell commands in your Ruby VM.

**Comment by musaffa** [comment]
It still creates an extra dependency on a gem while the file command can be called directly with ruby. In `file validators` it also has an dependency on `cocaine` gem for such shell command. I'm planning to remove it and save some memory for server instances.
