### ISSUE TITLE
Default URL for the unprocessed images

### ISSUE THREAD

**Issue by venkatasubbaiah** [carrierwaveuploader/carrierwave#1527]
Hi all,

   I am using carrierwave and rmagick gem  in project, to upload the image for my profile and I am resizing my uploaded images as per my requirement like 50x50 and 100x100. And I have added default profile image also. My questions is that, How can I show in the place of 50x50 and 100x100 images, if the  uploaded successfully and the image resize  process is failed rather that default image.
Is the any way to solve this?

Thanks in advance.
Venky Kandagaddala

**Comment by thomasfedb** [comment]
@venkatasubbaiah this is a feature request, are you able to provide an implementation?
