### ISSUE TITLE
Cache file on redisplay in Rails engine

### ISSUE THREAD

**Issue by sfandrew** [carrierwaveuploader/carrierwave#1539]
Currently cannot get the cache method to work on form re-display on a rails engine through a host app.

    <%= fields_for "dynamic_form_entry[attachments_attributes][#{field.id}]", 
        @dynamic_form_entry.attachments.build, :multipart => true  do |attachment| %>

      <%= attachment.hidden_field :content_name, value: field.name %>
      
      <%= attachment.file_field :filename, :class => "form-control uploader" %>
      <%= attachment.hidden_field :filename_cache %>
    <% end %>

**Comment by DemitryT** [comment]
Are you including `filename_cache` in strong params?
