### ISSUE TITLE
Don't rescue Exception

### ISSUE THREAD

**Issue by guigs** [carrierwaveuploader/carrierwave#1540]
I was running a script do upload some files and notice that I could't interrupt the script with Ctrl+C. I investigated and found out that it is because it is rescuing from Exception in [CarrierWave::Uploader::Download#file](https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/lib/carrierwave/uploader/download.rb#L38-L47).
In rescue block it raises `CarrierWave::DownloadError`, but then, it is rescued in [CarrierWave::Mount#remote_url=](https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/lib/carrierwave/mount.rb#L349-L367) because `:ignore_download_errors` is true by default.
Note: this code seems to be moved to mounter.rb in master.

I do want to ignore ordinary download errors, but not Interrupt or other runtime execeptions. [You would never want to](http://daniel.fone.net.nz/blog/2013/05/28/why-you-should-never-rescue-exception-in-ruby/).

Is there any reason not to rescue from StandardError in CarrierWave::Uploader::Download#file?
Before fcbbfb33614209e274c26afb75a59406d9ef5a6f it was.

**Comment by bensie** [comment]
@guigs This is a bug. Care to work up a pull request that rescues from `StandardError` instead?

**Comment by bensie** [comment]
Closed by ac0fab7551607cda8f8e69895f6c11406806769d
