### ISSUE TITLE
Compress uploaded file into zip. Is there a simple solution?

### ISSUE THREAD

**Issue by mcmegavolt** [carrierwaveuploader/carrierwave#1541]
For example, user select file ``document.doc`` and after uploading his file is accessible as a compressed zip file instead of ``.doc``

**Comment by swaathi** [comment]
In your create action of the controller (that you are using for file uploads), you can write a small `system()` command that executes after file upload is done, typically after the record is saved to the database. 

Based on the OS you are running on (this works on Mac and Linux), you can do this to zip files:  `system(zip -r NEWNAME.zip PATH-TO-UPLOADED-FILE)`.

Of course this would change the extension of your file, and the remaining logic of your Rails app would need to always remember this, before say downloading the said file.

**Comment by mcmegavolt** [comment]
Cool! Thanks for advice!
