### ISSUE TITLE
Checking MIME type by extension is a potential security risk

### ISSUE THREAD

**Issue by d4rky-pl** [carrierwaveuploader/carrierwave#1543]
Nothing stops the user from spoofing the file extension and [uploading potentially dangerous file](https://www.owasp.org/index.php/Unrestricted_File_Upload#Using_White-List_for_Files.E2.80.99_Extensions).

[Paperclip solves this using UNIX `file` command](https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/lib/paperclip/content_type_detector.rb). If you believe this is a viable solution, I can prepare a pull request.

**Comment by JangoSteve** [comment]
@d4rky-pl FYI, you can use the built-in mime_types processor to do more extensive MIME type testing:

```
class MyUploader < CarrierWave::Uploader::Base
  include CarrierWave::MimeTypes
  process :set_content_type
end
```

Then you could validate based on the content_type.

**Comment by JangoSteve** [comment]
Also, [here's the original discussion on why Carrierwave uses the extension to determine the mime type by default](https://github.com/carrierwaveuploader/carrierwave/pull/356).

**Comment by d4rky-pl** [comment]
The problem with mime_types gem is that it doesn't do any actual checking.

```ruby
# sanitized_file.rb:246

    def content_type
      return @content_type if @content_type
      if @file.respond_to?(:content_type) and @file.content_type
        @content_type = @file.content_type.to_s.chomp
      elsif path
        @content_type = ::MIME::Types.type_for(path).first.to_s
      end
    end
```

```ruby
# mime/types.rb:151

  # Return the list of MIME::Types which belongs to the file based on its
  # filename extension. If there is no extension, the filename will be used
  # as the matching criteria on its own.
```

The link you've provided to the discussion does not explain why Carrierwave uses the extension to determine the mime type, I think you've got the wrong link :)

**Comment by JangoSteve** [comment]
@d4rky-pl That's a good point. I could have sworn that the mime_types gem actually introspected the file content to make sure it matched the content type, but looking through the source code, I'm not seeing it. Now that I think about it, I think the problem the mime_types processor solved was simply having a more complete dictionary of mime-types.

It seems that the [ruby-filemagic](https://github.com/ricardochimal/ruby-filemagic) gem has the bindings to libmagic to do what you're talking about (or, like you said, you could just farm it out to the unix command).

Might consider making it a processor though in the same vein as my link.

I thought we had discussed why it wasn't there by default, and why I added the mime_types as a processor in that pull request, but I'm now thinking maybe we had that discussion offline. The main reason was to minimize gem dependencies. A processor allows you to add extra functionality that may depend additional gems, without then requiring that gem as a hard dependency for people who don't need the functionality.

**Comment by d4rky-pl** [comment]
I feel a bit unease about using `ruby-filemagic`, considering it haven't been updated for the past 4.5 years :) Farming it from file command is probably the best idea right now, with fallback to extension-based MIME checking on Windows (or any other solution that is possible on this system). If we do it this way, there won't be any additional gems dependencies. 

The choice on how to proceed is yours though, I can devote some time to this problem on some weekend.

**Comment by bensie** [comment]
File introspection to determine mime types is outside the scope of what we'll include in core. Like @JangoSteve mentioned though, adding a new processor capable of this would be great.

**Comment by seb-sykio** [comment]
any update about  checking mime type with file and not extension ?

**Comment by kevinjom** [comment]
both `ruby-filemagics` and `mimetypes` gems work poorly, they are not working well with MS offices files. and as mentioned above, they are not updated frequently and PRs are not processed. 

The problem with content-type check is its not reliable, you can rename a shell script with an image file extention, and the browser (from what I saw) will set the content type to `image/..`
