### ISSUE TITLE
Multiple file upload is not working - filename is `nil`

### ISSUE THREAD

**Issue by arashm** [carrierwaveuploader/carrierwave#1548]
Based on the documentation, I should be able to do this from rails console:

```ruby
user = User.last
user.images = [File.open('path.png'), File.open('path2.png'), File.open('path3.png')]
user.save!
```
But it raise an error:

```ruby
TypeError: no implicit conversion of nil into String
from /home/arashm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:160:in `join'
```
From the codes I can see `CarrierWave::SanitizedFile` is not capable to extracting `filename` from the array and `@file` points to the array of files not he files themselves, so expressions like `@file.respond_to?(:path)` is not working.

**Comment by sigra** [comment]
I have same issue. These steps helped me:

-- Switch to github in Gemfile.

```ruby
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```
-- Use `mount_uploaders` instead of `mount_uploader` in your User class

```ruby
mount_uploaders :images, ImageUploader
```

**Comment by arashm** [comment]
Thank you. I give it a try :)

**Comment by netqyq** [comment]
3
