### ISSUE TITLE
Photos not resizing to fit dimensions

### ISSUE THREAD

**Issue by pwz2k** [carrierwaveuploader/carrierwave#1550]
I am trying to get my photos to fit a specific size.

I have done this

```
   version :similar do
     process :resize_to_fill => [194, 139]
   end
```

and also tried adding `process :auto_orient` to it. The photo resizes, however the top of everyones head is cut off. Does someone know how I can fix this?

![screen shot 2015-01-21 at 9 38 43 pm](https://cloud.githubusercontent.com/assets/3035945/5849635/20c075ac-a1b6-11e4-9441-0e4c61191b5b.png)

**Comment by eavgerinos** [comment]
@pwz2k Yeap, `:resize_to_fill` crops the image if the algorithm finds it necessary [see doc](http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/MiniMagick:resize_to_fill).

Perhaps, what you would like to perform on the image is `:resize_to_fit` [see doc](http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/MiniMagick:resize_to_fit) which does not crop anything.

**Comment by pwz2k** [comment]
@eavgerinos I did that originally, however it left a blurry image which is why I switch to resize_to_fill. Take a look at the below screenshot.

![screen shot 2015-04-10 at 11 28 41 pm](https://cloud.githubusercontent.com/assets/3035945/7100072/6795c62e-dfd9-11e4-8c67-637a546a47bd.png)

Is there a way I can do resize_to_fit, and still keep the image quality?

**Comment by eavgerinos** [comment]
@pwz2k Please for usage questions post in StackOverflow instead of Github issues.

IMHO, `process resize_to_fit: [194, "139>"]` with do what you need. (maintain the aspect ratio)

**Comment by pwz2k** [comment]
Thanks for the reply. Future reference I will post these sort of questions on Stack.

I think I will just go back to resize_to_fill as that presents the best quality. Using your solution still presents a blurry image. Some photos will have their heads cut off, but it's better than losing quality of image.

![screen shot 2015-04-11 at 11 23 29 am](https://cloud.githubusercontent.com/assets/3035945/7101928/36096124-e03d-11e4-928f-c1325d395d71.png)

**Comment by eavgerinos** [comment]
It's hard to reproduce it without the original image :) 

You can try [resize_to_limit](http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/MiniMagick:resize_to_limit) too.

**Comment by pwz2k** [comment]
Yes I did resize_to_limit prior to originally posting on Git. Produces the same blurry quality. Only resize_to_fill keeps the original quality intact.

**Comment by HatemMahmoud** [comment]
You can use the gravity option like this:
`process :resize_to_fill => [194, 139, :North]`

Check the docs for other options: http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/MiniMagick#resize_to_fill-instance_method
