### ISSUE TITLE
cannot set or access extension after/during file rename

### ISSUE THREAD

**Issue by limratana** [carrierwaveuploader/carrierwave#1552]
When using filename or full_filename it seems one cannot set the extension if the original filename is missing a file extension. The error is "NoMethodError Exception: undefined method `extension=' for #<CarrierWave::SanitizedFile"

**Comment by eavgerinos** [comment]
@limratana As you can see in [SanitizedFile class](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L81) this is just a getter that splits the original filename.

You have to rename the whole file, including the extension.
