### ISSUE TITLE
remove 'require "fog"' from 'lib/carrierwave/storage/fog.rb'

### ISSUE THREAD

**Issue by tompesman** [carrierwaveuploader/carrierwave#1557]
Carrierwave requires the complete fog gem, but it looks like fog is moving all supported cloud providers to separate gems. I've removed the `require "fog"` line from the `lib/carrierwave/storage/fog.rb` file and added `gem 'fog-aws'` to my `Gemfile` which is sufficient for carrierwave's S3 support. I've not made a PR because I cannot test all the cloud providers. I think this is easily tested by someone with the correct setup.

See:
https://github.com/tompesman/carrierwave/commit/08a1232fe2371d25a0ef879bb8a3fb67c6808ef5

**Comment by bquorning** [comment]
The ability to require only selected parts of Fog was implemented in #1364 – check the README https://github.com/carrierwaveuploader/carrierwave#optimized-loading-of-fog. The feature is unfortunately not yet available in a released version of Carrierwave, only on master.

**Comment by bronislav** [comment]
@bquorning It doesn't works with latest version of `fog` gem, because they separated fog gem to the several provider specific gems. And `fog/aws/storage` doesn't exist in the `fog` gem anymore. It is moved to the `fog-aws` gem.

**Comment by tompesman** [comment]
Yes, this is even more optimised :wink: if you include `gem 'fog'` you'll get additional gems of different cloud providers. It looks like the fog gem requires all the extracted gems. There is a new fog-core gem which includes the generic parts which where previously in the fog gem.

gem 'fog'
```
    fog (1.24.0)
      fog-brightbox
      fog-core (~> 1.23)
      fog-json
      fog-radosgw (>= 0.0.2)
      fog-sakuracloud (>= 0.0.4)
      fog-softlayer
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.27.3)
      builder
      excon (~> 0.38)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.0)
      multi_json (~> 1.0)
    fog-radosgw (0.0.3)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-sakuracloud (0.1.2)
      fog-core
      fog-json
    fog-softlayer (0.3.30)
      fog-core
      fog-json
    fog-xml (0.1.1)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
```
vs
gem 'fog-aws'
```
    fog-aws (0.0.8)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.28.0)
      builder
      excon (~> 0.38)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.0)
      multi_json (~> 1.0)
    fog-xml (0.1.1)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
```

**Comment by darrenboyd** [comment]
:+1 for this change, it'd be nice to keep the bundle as slight as it can be.

If anyone finds this page looking for a solution (like I did), I managed to get this working in my Rails application, without forking any gem.  The workaround is detailed in this gist...

  https://gist.github.com/darrenboyd/feb2bc38f46a88e44b8d

**Comment by bquorning** [comment]
I think this could be fixed by changing the two instances of `require "fog"` to `require "fog-core"`. Probably adding a `rescue LoadError` to handle the case of someone using an earlier version of Fog that doesn’t define `Fog::Core`.

**Comment by bquorning** [comment]
PR in #1570.

**Comment by bensie** [comment]
Closing in favor of #1570
