### ISSUE TITLE
How to GZIP files and send both version to AWS S3?

### ISSUE THREAD

**Issue by Rendez** [carrierwaveuploader/carrierwave#1563]
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

What would be the best way to accomplish this in an automated way?

**Comment by bensie** [comment]
You would need to implement this outside the context of CarrierWave with fog or aws-sdk. We don't have built-in support for it.

**Comment by Rendez** [comment]
@bensie thanks for your answer.
