### ISSUE TITLE
Single quotes are not escaped in the url

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [carrierwaveuploader/carrierwave#1564]
Other characters such as the comma are converted to their ASCII percent-encoded equivalents, but not the single quote. This is causing problems in my sitemap.xml.

According to [this page](http://www.sitemaps.org/protocol.html) (regarding entity escaping), I need to convert `'` to `&apos;` in my sitemap document. If Carrierwave would percent-encode the single quote as expected, it would not be converted to `&apos;` in the resulting XML source. I have encountered many issues with crawlers trying to visit URLs with single quotes in them and failing due to the URL being truncated before the `'` or `&apos`. The actual raw XML URL should show `%27`, not `&apos;` as the apostrophe in this circumstance is NOT to be considered as a reserved character in the URL.

What the URL should be: `http://example.com/product/someone%27s-lucky-day`  
Typing into a browser address bar: `http://example.com/product/someone's-lucky-day`

What Carrierwave produces: `http://example.com/product/someone's-lucky-day`  
The resulting sitemap.xml produces: `http://example.com/product/someone&apos;s-lucky-day`

**Comment by thomasfedb** [comment]
@JakeTheSnake3p0 please include some code as to how you're using carrierwave to create these problematic results.

**Comment by JakeTheSnake3p0** [comment]
Simply calling `object_instance.photo.url(:show)` yields `/for/someone's-lucky-day`, should yield `/for/someone%27s-lucky-day`.

```ruby
# encoding: utf-8
module Manager
  # Handle Wine image
  class WinePhotoUploader < CarrierWave::Uploader::Base
    include CarrierWave::MiniMagick
    include CarrierWave::ImageOptimizer

    CarrierWave::SanitizedFile.sanitize_regexp = /[^[:word:]\.\-\+]/

    process :strip_all_but_profile!
    process resize_to_limit: [2000, 2000]

    version :show do
      process :resize_to_show
      process convert: :jpg
      process :optimize
      def full_filename(for_file = model.photo.file)
        the_filename
      end
    end

    def common(q = 100, s = '1.2x1+0.75+0.05')
      manipulate! do |img|
        img.combine_options do |i|
          i.quality q
          i.antialias
          i.background :white
          i.flatten
          i.density 72
          i.profile "#{ profiles_path }/sRGB_v4_ICC_preference_displayclass.icc".freeze
          i.strip
        end
        img = yield(img) if block_given?
        img.combine_options do |i|
          i.unsharp s
        end
        img
      end
    end

    def resize_to_show
      common do |img|
        img.combine_options do |i|
          i.trim
          i.thumbnail 110
          i.background :white
          i.gravity :center
          i.extent 170
        end
        img
      end
    end

    # Add a white list of extensions which are allowed to be uploaded.
    # For images you might use something like this:
    def extension_white_list
      %w(jpg jpeg gif png tif tiff)
    end

    # Override the filename of the uploaded files:
    # Avoid using model.id or version_name here, see uploader/store.rb for details.
    def filename
      "#{ model.normalized_permalink }#{ File.extname original_filename }" if original_filename
    end

    def the_filename
      "#{ version_name }_#{ model.normalized_permalink }.jpg"
    end

    def strip_all_but_profile!
      # Retrieve embedded ICC/ICM profile name if present
      source_profile = begin
        /Profile-ic(?:c|m):.*\n?(.*)?/.match(`identify -quiet -verbose #{ @file.file }`)[1].strip
      rescue
        # No profile present, assume sRGB
        destination_profile
      end

      source_profile = "#{ profiles_path }/" << case source_profile
                                                when /1998/
                                                  'AdobeRGB1998.icc'.freeze
                                                when /pro photo/
                                                  'ProPhoto.icm'.freeze
                                                else
                                                  destination_profile
                                                end

      # Strip quietly and convert profiles
      manipulate! do |img|
        img.combine_options do |i|
          i.strip
          i.quiet
          i.profile source_profile
          i.profile destination_profile(include_path: true)
        end
        img
      end
    end

    def destination_profile(include_path: false)
      # profile = 'sRGB_v4_ICC_preference_displayclass.icc'
      profile = 'sRGB_v2.icm'.freeze
      include_path ? "#{ profiles_path }/#{ profile }" : profile
    end

    def profiles_path
      "#{ Manager::Engine.root }/lib/manager/color_profiles".freeze
    end
  end
end
```

**Comment by thomasfedb** [comment]
@JakeTheSnake3p0 definitely looks like a bug, could you provide a minimal case please?

**Comment by mehlah** [comment]
@JakeTheSnake3p0 Why do you consider that CarrierWave should encode `'` in URLs?
Based on the RFC, as this reserved character doesn't have a delimiting role, there is no reason to encode.

>    URI producing applications should percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.  If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.

https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by mshibuya** [comment]
Stale, please reopen on update.
