### ISSUE TITLE
Question: why are filenames saved as an array?

### ISSUE THREAD

**Issue by olimart** [carrierwaveuploader/carrierwave#1565]
Here is how attachments are currently saved:

```
[#<AttachmentUploader:0x007fc557199e60 @model=#<Order id: 59, 
attachments: "[\"image1.png\", \"image2.png">, @mounted_as=:attachments, @storage=#
<CarrierWave::Storage::File:0x007fc557199de8 @uploader=#<AttachmentUploader:0x007fc557199e60 ...>>
, @file=#<CarrierWave::SanitizedFile:0x007fc5571995c8 
@file="/myapp/public/uploads/order/attachments/59/[\"image1.png\", \"image2.png\"]", 
@original_filename=nil, @content_type=nil>, @versions={}>]
```
Looping through `order.attachments` returns 1 single file `__image1.png____image2.png__`

I'm following the multiple upload section of the readme.

**Order model**
```
mount_uploaders :attachments, AttachmentUploader
```
attachment is JSON type column in PG.

**views**
```ruby
<%= f.file_field :attachments, multiple: true %>
<% @order.attachments.each do |file| %>
  <li><%= link_to file.file.filename, file.url %></li>
<% end %>
```

**Comment by dmastylo** [comment]
I didn't have this issue with a JSON column on PostgreSQL, but when I tried at first with a string column I had this issue. Additionally, JSON columns aren't supported on MySQL.

**Comment by bensie** [comment]
Native JSON columns are supported in MySQL [as of 5.7.8](http://dev.mysql.com/doc/refman/5.7/en/json.html).
