### ISSUE TITLE
Should the fog-aws gem still be used?

### ISSUE THREAD

**Issue by vassyz** [carrierwaveuploader/carrierwave#1572]
Using the 'fog-aws' gem returns the following error when starting the server:
```uninitialized constant CarrierWave::Storage::Fog```

Replacing it with the 'fog' gem works fine.

I'm using an initializer for CarrierWave, but even moving that into lib/carrierwave/storage/fog.rb didn't solve the issue. The docs are a little bit ambiguous about where to put your configuration values.
https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3

What's the difference between these two gems? Should the README get updated?

**Comment by edlebert** [comment]
There are lot of changes going on in fog right now.  It'd be nice if carrierwave could cut a release.

**Comment by bensie** [comment]
There is some Rails 3.2.x test coverage that is currently holding us back from cutting a release. PRs to fix that are welcome and would definitely speed up an official release!
