### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by stgeneral** [carrierwaveuploader/carrierwave#1574]
Today anniversary of last release (0.10.0) this excellent gem :)

Is there any plans to release next version?
Or may be `master` branch is rather stable to be used on the production?
Or may be https://github.com/refile/refile killed carrierwave?

**Comment by bensie** [comment]
There is some Rails 3.2.x test coverage that is currently holding us back from cutting a release. PRs to fix that are welcome and would definitely speed up an official release!
