### ISSUE TITLE
Check if conditional version exists

### ISSUE THREAD

**Issue by 7h3kk1d** [carrierwaveuploader/carrierwave#1575]
I'm using a conditional version if a file is an image. I expected that the version would be null if the condition wasn't met but it's truthy and still generates a version url even though it wasn't created.

**Comment by eavgerinos** [comment]
@7h3kk1d Can you provide a snippet with the version definition including the condition please?

**Comment by jasper502** [comment]
I have the same issue but can't seem to find any posts on this.  If you follow the docs: https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-do-conditional-processing the files do not get processed but you end up with phantom versions.  For example you would upload a PDF and still end up with `Attachment.file.thumb.url` == `/path/to/file/thumb_somefile.jpg` etc.  This is what I see too.  I have am trying to generate thumbnails etc. for uploaded images.  I resize them, convert them to jpg and rename them a generic `thumb.jpg`, 'small.jpg` etc.  The files are not processed but the CW versions get saved.  You would expect `Attachment.file.thumb` to be `nil` for a non-image uploaded.
