### ISSUE TITLE
Identifier nil when using multi file upload

### ISSUE THREAD

**Issue by philipgiuliani** [carrierwaveuploader/carrierwave#1581]
I implemented the multi-file upload functionality in my new project, and when i call now `image.identifier` it returns `nil`.

Example in console:

``` ruby
shoe = Shoe.first
shoe.images[0].url
# => "/uploads/shoe/images/1/2_4.jpg" 
shoe.images[0].path
# => "/full-path/public/uploads/shoe/images/1/2_4.jpg"
shoe.images[0].identifier
# => nil
```

In the meantime i am using

``` ruby
shoe.images_identifiers[0]
```

Branch: master
Ruby: 2.2.0
Rails. 4.2.0

**Comment by eavgerinos** [comment]
Yeap, this happens if you are using the same attribute as a mounter and a serialization column. 

In order to get the identifier, you can use the `image_identifiers` method that you already to or 

```ruby
shoe.images[0].file.identifier
```
