### ISSUE TITLE
Missing translations: min_size_error, max_size_error

### ISSUE THREAD

**Issue by frobichaud** [carrierwaveuploader/carrierwave#1585]
These two tokens are only provided in locale/en.yml:
min_size_error: "File size should be greater than %{min_size}"
max_size_error: "File size should be less than %{max_size}"

They're used in file_size.rb, so I assumed they need to be translated, and not removed.

**Comment by bensie** [comment]
All translations are provided by the community. Pull requests to add missing ones are always welcome!
