### ISSUE TITLE
serializable_hash method not called if same method defined in ActiveRecord model

### ISSUE THREAD

**Issue by fuyi** [carrierwaveuploader/carrierwave#1589]
This problem happens to latest release 0.10.0

If ActiveRecord model has serializable_hash defined and has a attribute mounted to Carrierwave, like this:

```
class User < ActiveRecord::Base
    # mount image uploader to profile_img
    mount_uploader :profile_img, ProfileUploader

    # customize hash here
    def serializable_hash(options = {})
        super options
    end
end
```

This serializable_hash method defined in file lib/carrierwave/orm/activerecord.rb:65 never get called, which leads to the problem that Carrierwave mounted attribute does not get serialized properly.

I notice that ActiveRecord::Base extend CarrierWave::ActiveRecord module

```
ActiveRecord::Base.extend CarrierWave::ActiveRecord
```

But serializable_hash is defined with class_eval block, maybe this explains why it does NOT get called with super.

**Comment by jnimety** [comment]
This affects the uploader setter as well:

```
mount_uploader :file, ControlFileUploader

# overwrites `file=` defined by Carrierwave via class_eval
def file=(new_file)
  super(new_file)
  self.file_updated_at = DateTime.current
end
```

**Comment by thomasfedb** [comment]
I'm changing this from a bug to an enhancement, as I feel that it's not unreasonable to define these methods via `class_eval` and that it's fairly common practice to do so. Other methods of achieving the same results generally require dynamic module generation and injection and can be fairly complex.

**Comment by jnimety** [comment]
you might want to update any wiki entries that suggest redefining the setter, I know of at least one: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Detect-a-new-file-in-a-mounted-uploader

**Comment by mshibuya** [comment]
`#serializable_hash` was removed by 62eee426ff0b012082fdb433b7cf07af0414e56e.
