### ISSUE TITLE
Readme out of sync with released gem

### ISSUE THREAD

**Issue by LukasSkywalker** [carrierwaveuploader/carrierwave#1590]
Commit https://github.com/carrierwaveuploader/carrierwave/commit/4160daa32d9e2306905b458b1d73fdc6536026bc changed the gem code and the README to mention that users can install the `fog-aws` gem instead of `fog`. I installed carrierwave today and read the documentation. Problem is, if I install `fog-aws` and do everything as the documentation says, Rails throws an exception (`uninitialized constant CarrerWave::Storage::Fog`). It works with the normal `fog` gem. I suspect some kind of incompatibility.

**Comment by bensie** [comment]
Refer to the README from v0.10.0. The README you're looking at is based on the latest master branch, which has a number of changes coming in the next release:

https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/README.md

**Comment by imshenitsky** [comment]
ok, to clarify - the only way to get it working is (according to v 0.10.0):
gem 'fog', '~> 1.3.1'
