### ISSUE TITLE
[Request For Comments] Magic Mime Validator

### ISSUE THREAD

**Issue by eavgerinos** [carrierwaveuploader/carrierwave#1593]
This is request for comments for a feature I'm willing to implement for CarrierWave.

There are situations where the _actual_ content-type of a file is important to know and validate, e.g. when processing a file as an image with `minimagick` or when storing a file with metadata in a storage like Openstack's Swift.

Therefore, I was thinking of an optional validator which works similarly to `Extension(Whitelist|Blacklist)`.

A rough skeleton looks like

```Ruby
module CarrierWave::Uploader::MagicMimeWhitelist
  extend ActiveSupport::Concern

  included do
    before :cache, :check_whitelist_pattern!
  end

  # Override in this with a regex
  # example: /image\// for checking images
  def mime_type_whitelist_pattern; end

  private

  def check_whitelist_pattern!
    # do serious stuff here and raise an integrity error if it does not match with the whitelist pattern
  end
end
```

This module is going to use `ruby-filemagic` which is not supported on JRuby, therefore, it must be optional and manually included by the user of the library. Also, a mirror module named `MagicMimeBlacklist` must be provided with the exact opposite logic.

**Comment by harmoney-danc** [comment]
Hello,
this is a very nice feature that I badly need in my current project :) Do you know when will this be released?

Best regards,
Dan.
