### ISSUE TITLE
avatar? returns false after I remove avatar and then add back gain

### ISSUE THREAD

**Issue by pmatsinopoulos** [carrierwaveuploader/carrierwave#1594]
Project that demonstrates the problem can be found here: https://github.com/pmatsinopoulos/test_carrierwave

I have a test case in which the `#avatar?` returns `false` where it should be returning `true`.
Here is the test case:

```
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  test "avatar" do
    @user = User.new
    @user.name = "George"
    @user.save!

    assert_equal false, @user.avatar?

    # set avatar
    @user.avatar = File.open("#{Rails.root}/test/files/lion-30-x-30.jpg")
    @user.save!

    assert_equal true, @user.avatar?

    # remove avatar
    @user.remove_avatar!
    @user.save!

    assert_equal false, @user.avatar?

    # add another one
    @user.avatar = File.open("#{Rails.root}/test/files/lion-2-30-x-30.jpg")
    @user.save!

    assert_equal true, @user.avatar?
  end
end
```
Last test fails.

Any clue why?

**Comment by eavgerinos** [comment]
Weird, all seems to pass here

```
Run options: --seed 44483

# Running:

DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. (called from block in <class:UserTest> at /Users/avgerinos/code/Rails/test_carrierwave/test/models/user_test.rb:29)
........

Finished in 0.660630s, 12.1097 runs/s, 25.7330 assertions/s.

8 runs, 17 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by pmatsinopoulos** [comment]
Yes. It works now because I have added the line:
https://github.com/pmatsinopoulos/test_carrierwave/blob/master/test/models/user_test.rb#L29
which essentially reload / reset the variable "@user". If you remove this
line....the test fails.
So, that line, works as a workaround. There is definitely a bug on
carrierwave.

P.

On Sun, Mar 15, 2015 at 11:49 AM, Aggelos Avgerinos <
notifications@github.com> wrote:

> Weird, all seems to pass here
>
> Run options: --seed 44483
>
> # Running:
>
> DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. (called from block in <class:UserTest> at /Users/avgerinos/code/Rails/test_carrierwave/test/models/user_test.rb:29)
> ........
>
> Finished in 0.660630s, 12.1097 runs/s, 25.7330 assertions/s.
>
> 8 runs, 17 assertions, 0 failures, 0 errors, 0 skips
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carrierwaveuploader/carrierwave/issues/1594#issuecomment-80938062>
> .
>



-- 
Panayotis Matsinopoulos
*You can book me here*: https://panayotis.youcanbook.me/
===========================================
I am sending SMS over the WEB using Rayo SMS <http://sms.rayo.gr/>
*E-mail*: panayotis@matsinopoulos.gr
*My Video Course*: Introduction To Computer Programming
<https://www.udemy.com/introduction-to-computer-programming/?couponCode=EMAIL-SIGNATURE>
*Blog:* http://pmatsinopoulos.github.com/
*Site:* http://pmatsinopoulos.github.io/
*Mobile:* +30 697 26 69 766
*Skype Id: *panayotis.matsinopoulos
*Facebook: *http://www.facebook.com/PanayotisMatsinopoulos
*Twitter:* http://www.twitter.com/pmatsino
*LinkedIN:* http://www.linkedin.com/in/panayotismatsinopoulos
*Github*: https://github.com/pmatsinopoulos
*Rubygems:* https://rubygems.org/profiles/55099
*Google+:* https://www.google.com/+PanayotisMatsinopoulos
*YouTube: *http://www.youtube.com/user/pmatsinopoulos

**Comment by eavgerinos** [comment]
@pmatsinopoulos Hm, true, it seems weird.

I added this spec in `spec/orm/activerecord_spec.rb` inside CarrierWave and it passes.

```ruby
describe "image?" do
      context "when a file is removed and stored again" do
        it "returns true" do
          @event.image = stub_file('test.jpeg')
          @event.save!
          @event.remove_image!
          @event.save!
          @event.image = stub_file('test.jpeg')
          @event.save!

          expect(@event.image?).to be_true
        end
    end
```

**Comment by pmatsinopoulos** [comment]
I will have a look at your code. Meanwhile, please read this:
https://github.com/carrierwaveuploader/carrierwave/issues/401#issuecomment-30495755
and below. It seems to be an issue that others have encountered in the past.



On Sun, Mar 15, 2015 at 3:54 PM, Aggelos Avgerinos <notifications@github.com
> wrote:

> @pmatsinopoulos <https://github.com/pmatsinopoulos> Hm, true, it seems
> weird.
>
> I added this spec in spec/orm/activerecord_spec.rb inside CarrierWave and
> it passes.
>
> describe "image?" do
>       context "when a file is removed and stored again" do
>         it "returns true" do
>           @event.image = stub_file('test.jpeg')
>           @event.save!
>           @event.remove_image!
>           @event.save!
>           @event.image = stub_file('test.jpeg')
>           @event.save!
>
>           expect(@event.image?).to be_true
>         end
>     end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carrierwaveuploader/carrierwave/issues/1594#issuecomment-81015471>
> .
>



-- 
Panayotis Matsinopoulos
*You can book me here*: https://panayotis.youcanbook.me/
===========================================
I am sending SMS over the WEB using Rayo SMS <http://sms.rayo.gr/>
*E-mail*: panayotis@matsinopoulos.gr
*My Video Course*: Introduction To Computer Programming
<https://www.udemy.com/introduction-to-computer-programming/?couponCode=EMAIL-SIGNATURE>
*Blog:* http://pmatsinopoulos.github.com/
*Site:* http://pmatsinopoulos.github.io/
*Mobile:* +30 697 26 69 766
*Skype Id: *panayotis.matsinopoulos
*Facebook: *http://www.facebook.com/PanayotisMatsinopoulos
*Twitter:* http://www.twitter.com/pmatsino
*LinkedIN:* http://www.linkedin.com/in/panayotismatsinopoulos
*Github*: https://github.com/pmatsinopoulos
*Rubygems:* https://rubygems.org/profiles/55099
*Google+:* https://www.google.com/+PanayotisMatsinopoulos
*YouTube: *http://www.youtube.com/user/pmatsinopoulos

**Comment by eavgerinos** [comment]
@pmatsinopoulos Is this still an issue?

**Comment by pmatsinopoulos** [comment]
Yes. The test still fails as I have already published here:
https://github.com/pmatsinopoulos/test_carrierwave


On Mon, Apr 6, 2015 at 7:27 PM, Aggelos Avgerinos <notifications@github.com>
wrote:

> @pmatsinopoulos <https://github.com/pmatsinopoulos> Is this still an
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carrierwaveuploader/carrierwave/issues/1594#issuecomment-90132848>
> .
>



-- 
Panayotis Matsinopoulos
*You can book me here*: https://panayotis.youcanbook.me/
===========================================
I am sending SMS over the WEB using Rayo SMS <http://sms.rayo.gr/>
*E-mail*: panayotis@matsinopoulos.gr
*My Video Course*: Introduction To Computer Programming
<https://www.udemy.com/introduction-to-computer-programming/?couponCode=EMAIL-SIGNATURE>
*Blog:* http://pmatsinopoulos.github.com/
*Site:* http://pmatsinopoulos.github.io/
*Mobile:* +30 697 26 69 766
*Skype Id: *panayotis.matsinopoulos
*Twitter:* http://www.twitter.com/pmatsino
*LinkedIN:* http://www.linkedin.com/in/panayotismatsinopoulos
*Github*: https://github.com/pmatsinopoulos
*Rubygems:* https://rubygems.org/profiles/55099
*Google+:* https://www.google.com/+PanayotisMatsinopoulos
*YouTube: *http://www.youtube.com/user/pmatsinopoulos

**Comment by pmatsinopoulos** [comment]
Book&Table Logo ( https://www.bookandtable.com )

You’ve been invited!

Inviting Person Image

Book&Table connects you with tutors for in-person or online
lessons. Whether it's reading development, GMAT prep, or web
development,
Book&Table has the educator you need.

Sign Up ( https://www.bookandtable.com/?email=reply%2B000db4eee63ecf5951993bf2b110faec3ff709f5313915c892cf00000001111d510f92a169ce039d7871%40reply.github.com&invited_by_email=panayotis%40matsinopoulos.gr )

( http://www.facebook.com/bookandtable )

( https://twitter.com/bookandtable )

( https://www.linkedin.com/company/book&table )

Sent with
&amp;#9829;
from Book&Table

54 W 40TH ST, NEW YORK, NY, 10018, U.S.A.If you would like to unsubscribe and stop receiving these emails click here: http://notifications.bookandtable.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcbRKyR6bFmTvAqfCRB8hWC4hnUhnKPkRH1KZpaVyT4Dz-2BI06u-2FqfUoyGLpGD24ShLBnmfr95jWGn-2FeUCBdMwwaA9o0nxNgVHFRXYLllNupN3QB8tfKoo3ERSJycdPEtYlluM2CABOeJN0KsvSlgjdBhPwFJ3H4H-2FO6C74JJQ66LjchW-2Fmkzv56EdUQq7kx0Ii1tN0lf2WlTLKG5febxizNRTJaIXN28vGX7dfJSq-2BaYhoLesFg67Hkhla3EpA3uMnayDe8kHShOFIJFkNHs6DDD8pIfByvhhw30CHh6VO7onEIAOKExK8zH2jzs4sdwXfg-3D-3D.

**Comment by pmatsinopoulos** [comment]
Book&Table Logo ( https://www.bookandtable.com )

You’ve been invited!

Inviting Person Image

Book&Table connects you with tutors for in-person or online
lessons. Whether it's reading development, GMAT prep, or web
development,
Book&Table has the educator you need.

Sign Up ( https://www.bookandtable.com/?email=reply%2B000db4ee649c1388cfa0ba3c1d55521c60f2fcb8fa5a258192cf00000001113a75f292a169ce039d7871%40reply.github.com&invited_by_email=panayotis%40matsinopoulos.gr )

( http://www.facebook.com/bookandtable )

( https://twitter.com/bookandtable )

( https://www.linkedin.com/company/book&table )

Sent with
&amp;#9829;
from Book&Table

54 W 40TH ST, NEW YORK, NY, 10018, U.S.A.If you would like to unsubscribe and stop receiving these emails click here: http://notifications.bookandtable.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcWaEHbyAPUHimiRF-2Fhg9Nbg0BNqkwq6t6KRBGl8c2yNpFHK8SPjXRl5P6i6wL2WvybwIsq7hX2sZFf7Iknhstdmfe6YTDyfsbiGnLfxoG7rfX2Ab-2BwEyz94Cs06JI5K1SNfcEGe3WSSrkdJ1FHOId5KeB3hDVb3XBVUw3hu7Za1tCUEZPKWVTi1vD8P6e41BGU3BnJhbCjL4zJDficXqcIugot3CMQjNko0gl8riAh3jC1q5v5OOKFYC1GuPF68um1-2FPS4WYrHs3IRi7JVrpW2g1uDgspO3o1GGhxtORbzYZx-2FicgobMxMU3VV-2B2BKclmg-3D-3D.

**Comment by pmatsinopoulos** [comment]
Book&Table Logo ( https://www.bookandtable.com )

You’ve been invited!

Inviting Person Image

Book&Table connects you with tutors for in-person or online
lessons. Whether it's reading development, GMAT prep, or web
development,
Book&Table has the educator you need.

Sign Up ( https://www.bookandtable.com/?email=reply%2B000db4ee5e45e2d1bc82ba2cb8cb498c9fc421dbe32ef7fc92cf00000001111d17ab92a169ce039d7871%40reply.github.com&invited_by_email=panayotis%40matsinopoulos.gr )

( http://www.facebook.com/bookandtable )

( https://twitter.com/bookandtable )

( https://www.linkedin.com/company/book&table )

Sent with
&amp;#9829;
from Book&Table

54 W 40TH ST, NEW YORK, NY, 10018, U.S.A.If you would like to unsubscribe and stop receiving these emails click here: http://notifications.bookandtable.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcU89xuwswyxErXBfqRiD9XDGNp30Q5KuSbrNPfr0mlxyxY-2B5s3Kcmyit6Fh8fKu9veBEh3wp3EoD8HpkjevWTzZSqPx4rpdP6Hi7F6fGCAAIhSly9-2F80o9YaC0bh4i9DnnUsxLgfd4pQGnWQeh3jjKGgiFO7AfVVlCbtqkxd2bTOm8vrJPwLmho91Q2-2FluOhFXorh9F5UBFa-2BsaVp1H-2FdaHZZDUiigorLvJnCwsDLMzgZP9efQFu-2FllhesWSzJkwarx2-2BhaaRkzGkl5piYcuwWf6x-2FsegH-2FpE96Fxc6bayfe.

**Comment by eavgerinos** [comment]
@pmatsinopoulos [out-of-context] I believe your email account has been compromised.

**Comment by AlexLarra** [comment]
@eavgerinos I tried recently with v0.10.0 and the problem still exists. I had to re-initialize it.

**Comment by eavgerinos** [comment]
UPDATE: This bug was introduced in version 0.7.0
