### ISSUE TITLE
Unable to upload multiple images

### ISSUE THREAD

**Issue by DaniG2k** [carrierwaveuploader/carrierwave#1599]
Hello all, I'm having a problem uploading multiple images via Carrierwave and am not sure if it's a bug or user error (probably the latter). I'm doing everything in a rather standard way though (as per documentation) so it's weird that this doesn't work.

I have the following in my **Gemfile**:
`gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'`

my **image_uploader.rb**:
```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :thumb do
    process :resize_to_limit => [590, 590]
  end
  version :featured do
    process :resize_to_fill => [390, 390]
  end
  def extension_white_list
    %w(jpg jpeg gif png)
  end
end
```

My **article.rb** file:
```ruby
class Article < ActiveRecord::Base
  mount_uploaders :images, ImageUploader
end
```

I am letting the params pass from my controller with:

```ruby
def article_params
  params.require(:article).permit(:title, :images, :body)
end
```

And the **_form.html.erb** partial uses:

```erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <%= f.label :images %><br>
  <%= f.file_field :images, multiple: true %><br>
  <%= f.submit 'Update Article' %>
<% end %>
```

Oddly, when I upload two images, I am not seeing them passed into the article_params from the update method.

If I pry it, I can see that:
```ruby
params.require(:article).permit(:images)
Unpermitted parameters: title, images, body
=> {}
```
Images seems to be unpermitted, even though I explicitly permit it...

Any clue as to what may be incorrect here?

**Comment by philipgiuliani** [comment]
Hi! Haven't read the whole post, but try:
```ruby
params.require(:article).permit(images: [])
```
since images is an array now.

**Comment by DaniG2k** [comment]
Hi Philip,

Thanks for this. Yes I eventually found that the fix was to do:

```ruby
params.require(:article).permit(:title, { images: [] }, :body)
```

I really think this ought to be documented in the Readme so that n00bs such as myself don't end up getting confused :smile:

**Comment by eavgerinos** [comment]
@DaniG2k I believe this belongs to Rails documentation, as you can see [here](http://edgeguides.rubyonrails.org/action_controller_overview.html#nested-parameters)

**Comment by DaniG2k** [comment]
What would be the correct way to remove multiple uploads?
With a single upload, one can do
```ruby
<%= f.check_box :remove_avatar %>
```
But when I try this for the multi upload, it removes all images. Is there a way to remove individual ones?
