### ISSUE TITLE
Can't install the latest version of Carrierwave. Get's an year old version

### ISSUE THREAD

**Issue by THPubs** [carrierwaveuploader/carrierwave#1601]
I tried to install the version 1.0 as mentioned in the readme file :

`As of version 1.0.0, CarrierWave requires Rails 4.0 or higher and Ruby 2.0 or higher. If you're on Rails 3, you should use v0.10.0.`

Then it gives me an error saying `Could not find gem 'carrierwave (= 1.0.0) ruby' in the gems available on this machine`

In the ruby gems site also we get the version 0.10.0 built an year ago!

**Comment by bensie** [comment]
1.0.0 is not yet released. We're prepping for it though. You'll need to point your Gemfile at master to get the latest.

**Comment by darryn02** [comment]
Is 1.0 getting close?

**Comment by thomasfedb** [comment]
Version 1.0.0 will be release once the designed features have been implemented, and we have a stable codebase worthy of the 1.0.0 designator. We have no set timeframe for the release. All are very welcome to contribute.
