### ISSUE TITLE
undefined method `mount_uploaders' when using carrierwave multiple uploads

### ISSUE THREAD

**Issue by rajkiran** [carrierwaveuploader/carrierwave#1606]
I am using carrierwave for multiple uploads. 
In this process I added 
**gem 'carrierwave'** in Gemfile

    rails g migration add_avatars_to_users avatars:json
    rake db:migrate

In my model:

   
    class InvoiceDetail < ActiveRecord::Base
      mount_uploaders :avatars, AvatarUploaderz
    end

form:

    <%= form_for(@invoice_detail , html: {class: 'form-horizontal', role: 'form' }) do |f| %>
    <div class="field">
        <%= f.label :invoice_date, :class => 'control-label' %>
                    <div class="controls1">
    
        <%= f.date_select :invoice_date, :class => 'text_area' %>
        </div>
      </div>
      <%= form.file_field :files, multiple: true %>
    
         <div class="control-group">
          <%= f.label :avatar, :class => 'control-label' %>
          <div class="controls">
            <%= f.file_field :avatar, :class => 'file_field', :required => true %>
          </div>
        </div>
        <%end%>
    <%end%>

when I run the server, I am getting error as 

*undefined method `mount_uploaders' for #<Class:0x000000037dcc80>*

With some googling I added require `'carrierwave/orm/activerecord'`
in my model, but it didn't helped me. 
SOme suggested me to make mount_uploaders as mount_uploader. When I did this, the I am able to select multiple files for upload but they are stored in the database as "nil".
Please help me out.

**Comment by ardecvz** [comment]
Hello,
Multiple upload by `mount_uploaders` method hasn't been released in a stable version yet.

If you're brave and ready to test, just use master version of the gem:
Change `gem 'carrierwave'` to `gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'` in your `Gemfile`.

Please consider using search before opening an issue as your question has already been solved several times, thanks!

**Comment by eavgerinos** [comment]
Thanks @ardecvz
