### ISSUE TITLE
Error in Readme.md - mount_uploaders

### ISSUE THREAD

**Issue by mdamaceno** [carrierwaveuploader/carrierwave#1609]
The method `mount_uploaders` mentioned in Readme.md file in Multiple Uploaders section doesn't exist. I think `mount_uploader` method is the correct.

**Comment by bensie** [comment]
The README reflects the current master branch, which is not yet released on RubyGems. You probably want to look at the README from v0.10.0: https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0
