### ISSUE TITLE
callbacks not supported in rails 4?

### ISSUE THREAD

**Issue by jshow** [carrierwaveuploader/carrierwave#1611]
rails 4.2, ruby 2

ref: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-use-callbacks

after :store, :post_to_wistia

NoMethodError: undefined method `after' for #<Class:0x00000006523cc0>

as Rails has moved away from the generic after(before) callback syntax, this appears to break carrierwave callbacks

at the least this is a doc change - is there an undocumented approach to hooking into after :store ?

thanks

**Comment by eavgerinos** [comment]
@jshow Can you please provide the chunk of code you used to get this error? Thanks in advance

**Comment by jshow** [comment]
@eavgerinos it has just occurred to me that I was 

after :store

inside my model (that was mounting the uploader), not the uploader itself

doh

**Comment by eavgerinos** [comment]
@jshow I guessed it was something like that. :smile: CarrierWave has its own callbacks mechanism.
