### ISSUE TITLE
ArgumentError - same file

### ISSUE THREAD

**Issue by Cervenka** [carrierwaveuploader/carrierwave#1623]
Hi, I'm seeing following issue when trying to convert a jpg file. This only happens when the original file's file extension is an upper case JPG.

Thanks

Version I'm using: carrierwave (0.10.0 186e890)

ArgumentError (same file: /Users/Flo/Projekte/igowild/tmp/1429028869-70628-5758/full/IMG_1465.JPG and /Users/Flo/Projekte/igowild/tmp/1429028869-70628-5758/full/IMG_1465.jpg):
  app/controllers/api/v1/items_controller.rb:41:in `create'

version :full do
    def full_filename (for_file = model.filemount.file)
      "#{model.slug}.jpg"
    end
    process :print_size
    process :auto_orient
    process :print_size
    process :convert => 'jpg' # <-- this is causing issues
    process :resize_to_limit => [936, nil]
    process :print_size
    process :save_display_size
  end

**Comment by eavgerinos** [comment]
@Cervenka Thanks for reporting. Closing this in favor of #1510 (duplicate).
