### ISSUE TITLE
Please consider supporting QuickMagick

### ISSUE THREAD

**Issue by Bodacious** [carrierwaveuploader/carrierwave#1624]
Hi guys, any thoughts on adding support for QuickMagick.

It seems to perform better than both RMagick and MiniMagick

https://github.com/aseldawy/quick_magick

**Comment by bensie** [comment]
Additional processors belong as plugins, so this isn't something that would be supported in core. It also doesn't help that the project hasn't been touched in 5 years. MiniMagick has come a long way since that README was written.

**Comment by Bodacious** [comment]
Thanks for getting back to me
