### ISSUE TITLE
setting a file_size limit vs resize_to_fit

### ISSUE THREAD

**Issue by m2omou** [carrierwaveuploader/carrierwave#1627]
I want to set the upload limit to 5MB, but I am still able to upload a 20MB file.

I'm using the following validator from https://gist.github.com/chrisbloom7/1009861:

```ruby
validates :file, :file_size => { :maximum => 5.megabytes.to_i }
```

But my `resize_to_fill` is dropping my file to 5MB, so the validation is never hit.

Is it possible to check the upload limit first and then resize the file ?

**Comment by bensie** [comment]
This is available in master, have a look at #1026 to see how it's used.
