### ISSUE TITLE
TypeError: Cannot visit KeyUploader

### ISSUE THREAD

**Issue by dtom90** [carrierwaveuploader/carrierwave#1632]
I have an ActiveRecord Key that is using an Uploader:

    class Key < ActiveRecord::Base
      mount_uploader :file, KeyUploader
      after_initialize :defaults
    
      private
      def defaults
    
        if self.name.nil?
          target_name = self.file
          same_name_matches = Key.find_by name: target_name
          
          self.name = target_name + self.id
        end
    
      end
    end

The line `same_name_matches = Key.find_by name: target_name` fails with:

**TypeError in KeysController#new**
**Cannot visit KeyUploader**

The only two attributes in Key are :name and :file

**Comment by eavgerinos** [comment]
__Please post usage questions in StackOverflow__

Maybe you want something like `target_name = self.file.path`.
