### ISSUE TITLE
filename should not return empty string or nil

### ISSUE THREAD

**Issue by teeceepee** [carrierwaveuploader/carrierwave#1634]
Accidently I overwrite the `filename` method to return an empty string, then I update a model object. After these two steps, I cannot upload any file to this model object. In `update` action, Rails raises an `Permission Denied` Error. I find that `store_dir`'s permission has been set to 644. CarrierWave want to set the uploaded file' permission to 644, but when `filename` return empty string, it set `store_dir`'s permission to 644, which causes the error. I think when `filename` return empty string or nil, CarrierWave will raise an error or fallback to use `@filename` as the file name.

**Comment by eavgerinos** [comment]
@teeceepee Can you please provide a script that reproduces your case?
