### ISSUE TITLE
Carrierwave Fails for Capital Lettered Column Names

### ISSUE THREAD

**Issue by greggawatt** [carrierwaveuploader/carrierwave#1638]
Hello

I'm working with a quickbooks table and attempting to store an image. Calling `.save!` on my object fails the first time and succeeds the second time, it will fail every other time after that. The error on failure that I get is `NameError: uninitialized constant CustomField15
from /Users/gregg/.rvm/gems/ruby-2.1.4/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:233:in 'store_previous_model_for_CustomField15'`

Any Idea what's up? I look at line 233 and didn't see any hint of what I could be doing wrong, i'd be willing to fix this if I knew where to start. I can confirm that the file saves on the second call to `.save!`

Below is a screen shot of me in the console. 
![screen shot 2015-04-29 at 2 41 12 pm](https://cloud.githubusercontent.com/assets/682680/7402097/147acf4e-ee7e-11e4-9e7f-18a41155d8f6.png)

**Comment by greggawatt** [comment]
I was able to solve this by doing ` alias_attribute :file, :CustomField15 ` before my `mount_base64_uploader :file, InvoicePdfUploader` 

This is still an issue though with carrierwave not liking capitalized column names

**Comment by eavgerinos** [comment]
I believe this is not a CarrierWave bug. If you see [here](https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/lib/carrierwave/mount.rb#L233), you are actually calling this method on an initialized constant, and as we all know everything that stats with a capital letter, in Ruby, is a constant.
