### ISSUE TITLE
Rename the file from edit _form.html.erb once uploaded

### ISSUE THREAD

**Issue by ginolon** [carrierwaveuploader/carrierwave#1639]
I have MyfileUploader class normally.

I have index.html.erb where I list all the files.

I have edit.html.erb and new.html.erb file that render _form.html.erb file for modify my file's attribute.

Something that I want is to rename the file.

I can delete the file and everything works, but for rename I don't know how to do!

index.html.erb

<%= download.url_identifier %>
<%= link_to 'Delete', myfile, method: :delete %>
_form.html.erb

<%= form_for(@myfile) do |f| %>
<%= f.label :url %>
<%= f.file_field :url %>
I want here something like this:

<%= f.label :rename, "Rename" %>
<%= f.text_field :rename %>
And the file would be renamed in the folder.

def filename
#...something...    
end
How to pass params from the _form.html.erb?

Or maybe I have to use the move_to method?

**Comment by chrisalley** [comment]
You could try [the technique I posted in the other issue](https://github.com/carrierwaveuploader/carrierwave/issues/1401#issuecomment-63603160) (note, you'll need to convert it to use Carrierwave's methods - the example I gave was for Paperclip). Once you've implemented that, you could use a virtual attribute for the new file name form field and pass it into the "sync_file_name_of" method.

**Comment by ginolon** [comment]
Thanks, @chrisalley. I will try!
