### ISSUE TITLE
Errno::ENOENT: No such file or directory

### ISSUE THREAD

**Issue by uwdevendra** [carrierwaveuploader/carrierwave#1645]
we are using 'carrierwave', '~> 0.7.1' ,'rmagick', '2.13.2', "fog", '~> 1.8.0' , "carrierwave_backgrounder", '~> 0.1.3' , 'delayed_job_active_record', '~> 0.3.3', 'daemons', '~> 1.1.9'  gems for application 

shows following error on heroku cedar but working fine on local 

UPDATE "delayed_jobs" SET locked_at = '2015-05-08 11:22:40.251551', locked_by = 'host:7a0248ab-5637-42c8-8e06-6598654b7ad3 pid:3' WHERE (id = 74 and (locked_at is null or locked_at < '2015-05-08 07:22:40.251551') and (run_at <= '2015-05-08 11:22:40.251551'))

AnswerPhotoWorker failed with Errno::ENOENT: No such file or directory - /app/tmp/uploads/20150508-1122-12-3796/logo.png - 0 failed attempts
-----------------------------------------------------------------------
uploader 
 def cache_dir
    "#{Rails.root}/tmp/uploads"
  end
----------------------------------------------------------------------
initializer

CarrierWave.configure do |config|
  config.root = Rails.root.join('tmp')
  config.cache_dir = "uploads"
  config.delete_tmp_file_after_storage = false                        
  config.fog_credentials = {
    :provider               => 'AWS',                     
    :aws_access_key_id      => ENV['S3_ACCESS_KEY'],                     
    :aws_secret_access_key  => ENV['S3_SECRET'],                       
  }
  config.storage = :fog
  config.fog_directory  = ENV['S3_BUCKET']                      
  config.fog_attributes = {'Cache-Control'=>'max-age=315576000'}  
end
---------------------------------------------------------------

model 

mount_uploader :photo, ImageUploader
store_in_background :photo, AnswerPhotoWorker
-------------------------------------------------------------------

**Comment by eavgerinos** [comment]
@uwdevendra Please reformat your answer, it's unreadable.

**Comment by fervisa** [comment]
(Assuming you're trying to process a file from a background job) I think the problem here is that each dyno (web/job) runs under its own filesystem, so the file `/app/tmp/uploads/20150508-1122-12-3796/logo.png` created by the web dyno is not accessible by the job dyno.

**Comment by plribeiro3000** [comment]
@uwdevendra Try to update your `fog` version as well. You are using a pretty old one. It can be related to your issue after all.

**Comment by bensie** [comment]
@fervisa is correct, you cannot use a worker process to connect to the filesystem of another dyno. If you're uploading files via Heroku, you have to send them straight to S3 and if they are processed by a worker, the worker needs to pull them down from S3 before processing.
