### ISSUE TITLE
Carrierwave with ActiveAdmin and multiple files

### ISSUE THREAD

**Issue by alestuber** [carrierwaveuploader/carrierwave#1653]
Hi guys,

Just want to inform you about something that I found a solution (after almost kill myself trying to find some answer with no success at all for two days).

I'm using here carrierwave (master branch) with multiple uploads and everything is sweet and awesome, until I try to use it inside ActiveAdmin.

If you use it inside ActiveAdmin with just one file everything works perfectly.

If you're using it with multiple files and an array column in postgresql, in your form you need to change the name of the file_input to name = "user[avatars][]", otherwise it will fail validation and not update the field.

This is a must have information in the readme of the master branch, with the one regarding AA permit_params (that if you're using an array column you need to declare it like "permit_params avatars: []"

Best
Alex

**Comment by eavgerinos** [comment]
@alestuber Can you please provide some snippets and a test that reproduces your case? 

Thanks

**Comment by alestuber** [comment]
Using Postgresql 9.4.1, Rails 4.2.1, ActiveAdmin 1.0.0.pre1.

This isn't a carrierwave bug per se, but it should be good to have this in the readme instructions. This is how you get the problem:

You follow the instructions to have carrierwave with multiple uploads:

gem 'carrierwave', github:'carrierwaveuploader/carrierwave'

Run bundle install and generate the uploader.

Then you create a migration to add a text array for your postgresql database:

class AddImagesToVariants < ActiveRecord::Migration
  def change
    add_column :variants, :images, :text, array: true
  end
end

add to your model the link between the array column and carrierwave uploader:

mount_uploaders :images, ImageUploader

And of course, you add the proper params for strong params: "images: []"

If you use this in any regular part of your rails application, everything will be fine, the problem is when you  try to use it inside activeadmin, it won't save your uploads/changes. The error is simple but tricky:

First thing you need to add the new column strong params on AA:

permit_params images: []

It's important that the hash { images: [] } is the last thing of your method, as always.

Then you need to create your AA form for creating/editing the AA resource like this:

form html: { multipart: true } do |f|
      # all your other fields here
+    f.input :images, as: :file, input_html: { multiple: true } # This multiple: true option is the thing that solves the problem as it changes the name of the form field from "model[column]" to "model[column][]"
+    f.actions # this line is just for the regular form buttons
+  end

If you follow this your carrierwave multiple uploads will work perfectly with AA, otherwise people may loose a lot of time like I did trying to find the problem.

Sorry for not putting code in snippets and formatting it all as it should, I'm kind of on a short deadline on my startup right now. I hope this can help more people.

Best
Alex

**Comment by eavgerinos** [comment]
I'm sorry, it's really hard to read. Can you please create a demo app with a test that reproduces your case? I've never worked with ActiveAdmin.

Though, your case seems like `strong_params` misconfiguration.

**Comment by glaubersantana** [comment]
Hi,

I followed the alestuber's instructions exactly, the multipart trick helped me to get working with upload of multiple images successfully. But I still get error on exhibition of the images.

My code:

```ruby
# Gemfile
# (...)
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem "mini_magick"
# (...)

# migration
class CreateProducts < ActiveRecord::Migration
  def up
    create_table :products do |t|
      t.string :name
      t.string :slug, null: false
      t.decimal :price, precision: 8, scale: 2
      t.text :description
      t.text :images, array: true
      t.references :category

      t.timestamps null: false
    end
    add_index :products, :slug, unique: true
    
    Product.create_translation_table! :name => :string, :description => :text
  end
  
  def down
    drop_table :products
    Product.drop_translation_table!
  end
end

#app/uploaders/image_uploader.rb
class ImageUploader < CarrierWave::Uploader::Base

  include CarrierWave::MiniMagick
  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :thumb do
    process :resize_to_fit => [200, 200]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end
end

#app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  
  translates :name, :description
  active_admin_translates :name, :description
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  mount_uploaders :images, ImageUploader
  
  def to_s
    name
  end
end

#app/admin/product.rb
ActiveAdmin.register Product do
  permit_params :category_id, :price, translations_attributes: [:id, :locale, :name, :description, :_destroy], images: []
  
  index do
    selectable_column
    column :name
    column :category
    column :price do |product|
      number_to_currency product.price
    end
    translation_status_flags
    actions
  end
  
  show do
    attributes_table do
      row :slug
      translated_row :name
      translated_row :description
      row :category
      row :price do |product|
        number_to_currency product.price
      end
      row :images do
        ul do
          product.images.each do |image|
            li do
              image_tag(image.url(:thumb))
            end
          end
        end
      end
    end
        
    active_admin_comments
  end
  
  form html: { multipart: true } do |f|
    f.semantic_errors
    
    f.inputs do
      f.translated_inputs auto_sort: false do |t|
        t.input :name
        t.input :description
      end
    end
    
    f.inputs do
      f.input :category
      f.input :price
      f.input :images, as: :file, input_html: { multiple: true }
    end
    
    actions
  end
end
```

The error:

```
Started GET "/uploads/product/images/1/thumb_%5B%22image_1.jpg%22%2C%20%22image_2.png%22%5D" for 10.0.2.2 at 2015-07-14 13:01:43 +0000

ActionController::RoutingError (No route matches [GET] "/uploads/product/images/1/thumb_%5B%22image_1.jpg%22%2C%20%22image_2.png%22%5D")
```

It seems the object saved into the database is a one item array, independent of the amount of files I have pick in the upload form.
The images get saved as expected on the filesystem.

Any idea where is the problem??

Thanks in advance!

**Comment by johnmcl** [comment]
@glaubersantana - try adding ```serialize :photos``` to your product model

**Comment by glaubersantana** [comment]
@johnmcl great, thanks!

**Comment by thomasfedb** [comment]
Appears that this is not an issues that requires and changes in Carrierwave.
