### ISSUE TITLE
Uploaded multiple files not stored after failing one of validation

### ISSUE THREAD

**Issue by diegorv** [carrierwaveuploader/carrierwave#1654]
My model

```ruby
class Image < ActiveRecord::Base
  mount_uploader :logo_image   , LogoImageUploader
  mount_uploader :layout_image , LayoutImageUploader

  validates_presence_of  :layout_image, :logo_image
end
```

If i upload the "layout_image" file but not the "logo_image" file, this show a validation error as expected.

But Carrierwave fail in save the image of "layout_image"

**Comment by eavgerinos** [comment]
@diegorv 
Well, this is true and expected. Since your model is invalid no changes will apply to it.

**Comment by diegorv** [comment]
Hm...

I understand.

i'll change my feature behaviour.

Thanks :)
