### ISSUE TITLE
HEAD request to S3

### ISSUE THREAD

**Issue by carrascoacd** [carrierwaveuploader/carrierwave#1655]
I noticed each time I get a version of a picture NewRelic is reporting this:
```
Excon[bucker.amazonaws.com]: HEAD
```
It takes 100ms to get a the response, so when I manage a collection of pictures its a lot of time.
Is that normal?

My code look like this: 
```
@picture.photo_url(:thumb)
```

**Comment by eavgerinos** [comment]
The HTTP response time isn't something that is handled by CarrierWave. Maybe you should contact S3 support.

**Comment by josepjaume** [comment]
I'm observing the same behavior using `fog`. Did you ever manage to sort out what it was?
