### ISSUE TITLE
Remaining items to release 1.0.0

### ISSUE THREAD

**Issue by nickhammond** [carrierwaveuploader/carrierwave#1661]
I'd like to help out and get 1.0.0 ready for release but I'm not sure what features/fixes are essential to launch. Would it be possible to create issues and start tagging them or associating them with a 1.0.0 milestone?

**Comment by eavgerinos** [comment]
We are already trying to do this. The milestone will be provided when we decide 100% what's going to be on 1.0.0 and what not. :) 

Also, all contributions to any of the open issues are more than appreciated :)

Closing this since it's not a technical/blocker for the release issue.

**Comment by nickhammond** [comment]
@eavgerinos Thanks for the update and all of your awesome work on Carrierwave :) I'll browse through the issues and see what I can help with.

**Comment by eavgerinos** [comment]
@nickhammond Thank you for your kind words :)
