### ISSUE TITLE
Multiple buckets support and fetch assets from related bucket based on user location

### ISSUE THREAD

**Issue by naveed-ahmad** [carrierwaveuploader/carrierwave#1663]
Maybe rare case here. 

I've been using Google storage to host assets of my application. Now storage charges are fine( $0.026/GB ) but Egress( download ) charge are killer for websites in early stages, especially if they have to host lot of data.  

But what if there is a way to duplicate data in all three regions on google storage and serve images from nearest bucket to user? 

Carrierwave doesn't have support for storing data in multiple bucket for now, is there is any plan to add this feature in coming months? 

thanks for awesome gem :)

**Comment by naveed-ahmad** [comment]
One possible solution I could think of is to have two Uploader classes, which will do the exactly same things but upload image in different buckets( which are based on different location)

Then based on user location choose the uploader and server the image. Doesn't looks like a DRY approach and lot of processing(we are having couple of copies of images in different sizes).

**Comment by thomasfedb** [comment]
@naveed-ahmad This is not something we're planning to support in carrierwave. Sounds like you need a CDN.
