### ISSUE TITLE
Removing orphaned version files

### ISSUE THREAD

**Issue by djohnson** [carrierwaveuploader/carrierwave#1665]
I can't find a way to delete the file of a specific version from an uploader.  Given an uploader "photo" with versions "way_too_big" and "just_right", I would like to be able to delete the way_too_big version and have the corresponding way_too_big version files deleted in storage, in my case S3 via fog.  

This issue hits me in two real world scenarios.  On one project I have some 500k Carrierwave assets on s3 and quite a few of them are orphaned with no clear path to clean up.  Secondly, I need to have version fingerprinting such that each reversioning creates a new fingerprint.  This is so that if a version's size is updated and recreate_versions! is called it which will break the cache.  

I'm not sure if there is any way to do this currently, but here are a couple possible suggestions:
* An uploader could have a method "delete_version_files(:way_too_big)" method so you could run through all the instances of your uploader and call this before removing the version from your uploader definition.

* Alternatively, It would be amazing if recreate_versions! could take a "remove_orphaned_files" flag and just remove all currently unreferenced files in the current uploader's directory automatically.  

My fingerprinting implementation for reference:  I have the following module included in my uploader which prepends a timestamp to the versioned files, but leaves the original as is.  Calling recreate_versions! creates a new timestamp fingerprint and corresponding files, but the old version files remain effectively orphaned.  

```ruby
# This provides for unique fingerprinting for versions
# original file is NOT fingerprinted
#
module UploaderFingerprinting
  extend ActiveSupport::Concern

  included do
    process :reset_fingerprint
  end

  def filename
    # only fingerprint the versioned uploads NOT originals
    version_fp = version_name.present? ? fingerprint : nil
    [version_fp, super].compact.join('_')
  end

  def fingerprint
    model["#{mounted_as}_fingerprint"]
  end

  private

  def reset_fingerprint
    if version_name.nil?
      model["#{mounted_as}_fingerprint"] = Time.now.to_i
    end
  end

end
```

**Comment by bousquet** [comment]
+1

**Comment by eavgerinos** [comment]
@djohnson Thanks for your detailed description.

What you describe here seems valid.

Though, 

### For the orphaned files case 

Currently CarrierWave's implementation holds reference (to your favourite database) only for the *original* file. All versions paths/urls are generated dynamically according to the versions defined in your Uploader's class.

Therefore, it's not "cheap" to tell what versions have been orphaned.

Of course, you can perform 

- a filesystem operation (`File.exists?`) - `storage :file`
- a HEAD/GET HTTP request - `storage :fog`

for each and every file stored in your backend, to tell what has been orphaned.

Though, this looks way too aggressive to me and won't scale (or even work) on an application that hosts millions of files.

My suggestion to this as a workaround is to perform an one-off script to clear the orphaned files. See it as a "data migration" on the filesystem / cloud storage.

### For the timestamp case

I believe this belongs to the business logic of each application. Adding something like that right to the core of CarrierWave could mess up things for users like caching. Also, simple timestamping doesn't work for everyone.

There are tones of ways to implement such logic in a module and I believe it's pretty simple.

I'm using something similar (with sha1 digests) at my job and works perfectly.

Thanks for your time :)

**Comment by djohnson** [comment]
@eavgerinos Thanks for taking the time to reply.

I think if there was a disclaimer under versions: "You are on your own to figure out how to remove existing versions that are no longer needed on whichever storage backend you use"  it would put a lot of people off.  People are paying for that storage so it'd be nice to help them clean it up!  Other uploader solutions do this such as Paperclip's `rake paperclip:clean`

I don't think this has to be too difficult or negatively impact performance at all. It could function very similarly to the `recreate_versions!` method.  Even for millions of uploader instances it could just be added to a job queue and run through it as priority/resources allow.   Here is a rough implementation of this for fog storage https://github.com/djohnson/carrierwave/commit/f6a86df7fd8b9743726ae2cbc37c2b5ff078a038

The timestamp case can be ignored, it was just one real world example i've encountered in addition to removing a version definition.  Fixing one fixes the other.

**Comment by thomasfedb** [comment]
@djohnson Feel welcome to submit a pull request with your `destroy_orphaned_files` implementation. Otherwise I'm going to close this issue for now.
