### ISSUE TITLE
minimagick error when converting image to png

### ISSUE THREAD

**Issue by robinsingh-bw** [carrierwaveuploader/carrierwave#1669]
Hi,

I have added: process :convert => 'png', to my carrierwave uploader but it keeps failing with this error:

{"errors":{"file":["Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: 
`convert /tmp/mini_magick20150607-3227-1vae7ti.png[0] /tmp/mini_magick20150607-3227-3qr2i8.png` failed
 with error:\nconvert.im6: Expected 8192 bytes; found 4986 bytes `/tmp/mini_magick20150607-3227-1vae7ti
.png' @ warning/png.c/MagickPNGWarningHandler/1754.\nconvert.im6: Read Exception `/tmp/mini_magick20150607-3227-1vae7ti
.png' @ error/png.c/MagickPNGErrorHandler/1728.\nconvert.im6: corrupt image `/tmp/mini_magick20150607-3227-1vae7ti
.png' @ error/png.c/ReadPNGImage/3723.\nconvert.im6: no images defined `/tmp/mini_magick20150607-3227-3qr2i8
.png' @ error/convert.c/ConvertImageCommand/3044.\n"]}}

This error only appears when I upload a png file, if I upload a jpg file I no longer get the error but the resulting image is completely gray.

I am working on a vagrant ubuntu 14.04 installation, I have verified that imagemagick is working for png and jpg files by running the convert command on some images.

Any help would be appreciated!

Regards.

**Comment by mattolson** [comment]
Same this is happening to me. I am using Debian Wheezy with ImageMagick 6.7.7-10. Whenever I try to do an operation that requires writing with png transparency, I get something like this:

```       Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `mogrify -thumbnail 220x279> -background rgba(255, 255, 255, 0.0) -gravity Center -extent 220x279 /tmp/mini_magick20150814-1102-1pbub2y.png` failed with error:
       mogrify.im6: Expected 3341 bytes; found 1941 bytes `/tmp/mini_magick20150814-1102-1pbub2y.png' @ warning/png.c/MagickPNGWarningHandler/1754.
       mogrify.im6: Read Exception `/tmp/mini_magick20150814-1102-1pbub2y.png' @ error/png.c/MagickPNGErrorHandler/1728.
       mogrify.im6: corrupt image `/tmp/mini_magick20150814-1102-1pbub2y.png' @ error/png.c/ReadPNGImage/3723.```

**Comment by mattolson** [comment]
This happens when I add `process :convert => 'png'` and also happens when I use `resize_and_pad` with a transparent background.

**Comment by mattolson** [comment]
Here is my configuration, if that helps:

```
app@a702c50ed58f:~$ convert -list configure

Path: /usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/config/configure.xml

Name          Value
-------------------------------------------------------------------------------
CC            gcc -std=gnu99 -std=gnu99
CFLAGS        -I/usr/include/lqr-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fopenmp -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -pthread
CODER_PATH    /usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/modules-Q16/coders
CONFIGURE     ./configure  '--prefix=/usr' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--sysconfdir=/etc' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'FFLAGS=-g -O2' 'LDFLAGS=-Wl,-z,relro' '--with-modules' '--with-gs-font-dir=/usr/share/fonts/type1/gsfonts' '--with-magick-plus-plus' '--with-djvu' '--with-wmf' '--without-gvc' '--enable-shared' '--without-dps' '--without-fpx' '--with-perl-options=INSTALLDIRS=vendor' '--x-includes=/usr/include/X11' '--x-libraries=/usr/lib/X11'
CONFIGURE_PATH /etc/ImageMagick/
COPYRIGHT     Copyright (C) 1999-2012 ImageMagick Studio LLC
CPPFLAGS      -I/usr/include/ImageMagick
CXX           g++
CXXFLAGS      -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread
DEFS          -DHAVE_CONFIG_H
DELEGATES     bzlib djvu fontconfig freetype jbig jpeg jng jp2 lcms2 lqr lzma openexr pango png rsvg tiff x11 xml wmf zlib
DISTCHECK_CONFIG_FLAGS 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-z,relro' --disable-deprecated --with-quantum-depth=16 --with-umem=no --with-autotrace=no --with-dps=no --with-fpx=no --with-gslib=no --with-fontpath= --with-gs-font-dir=/usr/share/fonts/type1/gsfonts --with-gvc=no --with-perl=no
DOCUMENTATION_PATH /usr/share/doc/ImageMagick-6.7.7
EXEC-PREFIX   /usr
EXECUTABLE_PATH /usr/bin
FEATURES      OpenMP
FILTER_PATH   /usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/modules-Q16/filters
HOST          x86_64-unknown-linux-gnu
INCLUDE_PATH  /usr/include/ImageMagick
LDFLAGS       -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -L/usr/lib/X11 -L/usr/lib
LIB_VERSION   0x677
LIB_VERSION_NUMBER 6,7,7,10
LIBRARY_PATH  /usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7
LIBS          -lMagickCore -llcms2 -ltiff -lfreetype -ljpeg -llqr-1 -lglib-2.0 -lfontconfig -lXext -lSM -lICE -lX11 -lXt -llzma -lbz2 -lz -lm -lgomp -lpthread -lltdl
NAME          ImageMagick
PCFLAGS       -fopenmp
PREFIX        /usr
QuantumDepth  16
RELEASE_DATE  2014-03-08
SHARE_PATH    /usr/share/ImageMagick-6.7.7
SVN_REVISION  8535
TARGET_CPU    x86_64
TARGET_OS     linux-gnu
TARGET_VENDOR unknown
VERSION       6.7.7
WEBSITE       http://www.imagemagick.org

Path: [built-in]

Name          Value
-------------------------------------------------------------------------------
NAME          ImageMagick
```

**Comment by thomasfedb** [comment]
Hi @robinsingh-bw. Can you please provide a minimal replication case so we can look into this further.

**Comment by adrianov** [comment]
It seems to be Vagrant+VirtualBox bug with Ubuntu 14.04 running on top of Windows 10. I got the same problem.

**Comment by thomasfedb** [comment]
If it's not a carrierwave issue please take this up with the MiniMagick team.
