### ISSUE TITLE
Remove checkbox is not working in nested form

### ISSUE THREAD

**Issue by oney** [carrierwaveuploader/carrierwave#1673]
I use [cocoon](https://github.com/nathanvda/cocoon) to do nested forms, and forms have a carrierwave file input

edit.html.erb
```
<%= simple_form_for @product, url: product_path do |f| %>
  <%= f.input :name %>
  <div id="features">
    <%= f.simple_fields_for :features do |feature| %>
      <%= render 'feature_fields', :f => feature %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add feature', f, :features %>
    </div>
  </div>
<% end %>
```
_feature_fields.html.erb
```
<div class="nested-fields">
  <%= f.input :title %>

  <%= image_tag(f.object.photo_url) if f.object.photo? %>
  <%= f.input :photo, as: :file %>
  <%= f.hidden_field :photo_cache %>
  <%= f.check_box :remove_photo %>
  <%= link_to_remove_association 'remove feature', f %>
</div>
```

Uploading photo of feature is working, the problem is that when I check remove_photo, and it doesn't remove the photo of features.

product.rb
```
class Product < ActiveRecord::Base
  has_many :features
  accepts_nested_attributes_for :features, reject_if: :all_blank, allow_destroy: true
end
```
feature.rb
```
class Feature < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :product
end
```
products_controller.rb
```
class ProductsController < Admin::BaseController
  before_action :set_product

  def update
    @product.update(product_params)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params[:product].permit(:name,
        features_attributes: [:id, :title, :photo, :photo_cache, :remove_photo, :_destroy])
    end
end
```
Model and strong parameter is set correctly.
if I puts product_params in controller, I get
```
{"name"=>"T shirt",
 "features_attributes"=>
  {"0"=>{"id"=>"1", "title"=>"Soft", "photo_cache"=>"", "remove_photo"=>"1", "_destroy"=>"false"},
   "1"=>{"id"=>"4", "title"=>"Beautiful", "photo_cache"=>"", "remove_photo"=>"0", "_destroy"=>"false"}}}
```
remove_photo is "1", but it doesn't remove photo.

**Comment by jmuheim** [comment]
I have a similar problem. In my situation, the image is only removed, when also another attribute is changed, so I guess it has something to do with the attrs_changed? mechanism...

**Comment by edatrix** [comment]
Just ran into this issue and spent some time debugging before realizing that it's been fixed on master.  Rails' dirty tracking doesn't seem to jive well with nested forms here, but if you update your gemfile to track master it solves the problem. :+1:

**Comment by jmuheim** [comment]
Thanks, @edatrix. In my case, it suddenly worked without setting branch to master. Don't know why.

**Comment by thomasfedb** [comment]
If this is still a problem please open a new issue with a minimal reproduction.

**Comment by jmuheim** [comment]
Doesn't seem to be a problem anymore. Thanks.

**Comment by edatrix** [comment]
Back again, this same issue is occurring.  When I check the box to remove the item in the nested form, it will not do so without also adjusting another attribute in the nested form.  Identical setup and behavior as out above.

**Comment by thomasfedb** [comment]
@edarix please submit a new issue, including the gem version and a minimal reproduction.
