### ISSUE TITLE
S3 Signed URL on a file per file basis

### ISSUE THREAD

**Issue by PabloVallejo** [carrierwaveuploader/carrierwave#1675]
I have my project files stored in a S3 bucket, however, there is one root public folder and one private one. I'd like to know if there's a way to generate signed URLs for the files in the private folder and regular URLs for the files in the public folder.

Currently I've seen there's only a global configuration:

```ruby
config.fog_public = false
config.fog_authenticated_url_expiration = expiration_time
```

But I've couldn't find a way to configure this on each uploader or by passing params in the file URL.
Is there a way to achieve this?

**Comment by bensie** [comment]
No sorry, this is not supported. Pull requests are always welcome though if it's something you'd like to tackle!
