### ISSUE TITLE
Setting either the cache or remove attributes does not dirty records

### ISSUE THREAD

**Issue by mrj** [carrierwaveuploader/carrierwave#1676]
If a value is assigned to either the cache or remove Ruby attributes for an upload, calling `changed?` on the model instance returns false, even though the record *will* change on save (unless nothing is removed). Is this as it should be, meaning one should implement a model method like
```ruby
  def changed?
    !!upload_cache || !!remove_upload && upload? || super
  end
```
or should CarrierWave be doing this?

**Comment by thomasfedb** [comment]
It looks like #1656 will address this issue.

@mjr I'm going to close this issue, but if the PR I've mentioned above doesn't fix your issue feel free to comment for me to reopen.
