### ISSUE TITLE
u.avatar_identifier on README.md is wrong

### ISSUE THREAD

**Issue by Alejandro9R** [carrierwaveuploader/carrierwave#1677]
Just change the:

```
u.avatar_identifier # => 'file.png'
```

to this: 

```
 u.avatar.identifier # => 'file.png' 
```

Little thing! Haha

**Comment by bensie** [comment]
`avatar_identifier` works as well.

**Comment by cesc1989** [comment]
Neither `_identifier` or `.identifier` worked for me but `_url` does work. Version 0.11.2
