### ISSUE TITLE
To_json not behaving like a "normal" model

### ISSUE THREAD

**Issue by pywebdesign** [carrierwaveuploader/carrierwave#1689]
Hi,

let say we have a user model, this line:
````ruby
User.first.to_json
````
will output:
````json
{ "name": "John", "email": "skj@gmail.com"...}
````
on the other side, if I have a avatar field with carrierwave and I do:

````ruby
User.first.avatar.to_json
````
It output wrongly:
````json
{ "avatar": {"url": "...", "large_avatar": {...}, ...}}
````
instead of:
````json
{"url": "...", "large_avatar": {...}, ...}
````

It make it very incompatible with ActiveModelSerializer

As a dirty tricks:
````ruby
User.first.avatar.as_json[:avatar]
````

is this intended? why? what do you think?
Thanks

**Comment by thomasfedb** [comment]
Hi @pywebdesign I'd be very interested in a pull request to change this behaviour. In the meantime, I'm going to close this issue as there isn't a bug here.
