### ISSUE TITLE
Help: Failed to manipulate with MiniMagick, maybe it is not an image.

### ISSUE THREAD

**Issue by samuraraujo** [carrierwaveuploader/carrierwave#1696]
Hi there,
I am getting this error when uploading a image with carrierwave. 

"Avatar Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: ImageMagick/GraphicsMagick is not installed"

The problem happen after I installed ImageMagick from source on Centos. The intriguing part is that MiniMagick works standalone,  as well as, Rmagick. 

Any clue is causing the problem? 

Here is the version I have installed
mini_magick (4.2.7)
carrierwave (0.10.0)

Version: ImageMagick 6.7.7-10 2015-07-03 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

**Comment by samuraraujo** [comment]
# encoding: utf-8
class AvatarUploader < CarrierWave::Uploader::Base

  # Include RMagick or MiniMagick support:
  #include CarrierWave::RMagick
  include CarrierWave::MiniMagick

  # Choose what kind of storage to use for this uploader:
  storage :file
  # storage :fog
  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def filename
    if original_filename
      @name ||= Digest::MD5.hexdigest(File.dirname(current_path))
      "#{@name}.jpg"
    end
  end

  # Provide a default URL as a default if there hasn't been a file uploaded:
  def default_url
    if model.class == User
      "/images/avatar.png"
      else
      "/images/#{model.class.to_s.downcase}.png"
    end
  end

  # Process files as they are uploaded:
  # process :scale => [200, 300]
  #
  # def scale(width, height)
  #   # do something
  # end

  process :mogrify => [{  }]
  process :resize_to_fit => [300, nil]

  version :small do

    process :mogrify => [{  }]
    process :resize_to_fill => [50, 50]
  end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
    %w(jpg jpeg gif png)
  end
  private

  def mogrify(options = {})
    manipulate! do |img|
      img.format("jpg") do |c|
        c.quality("80")
        c.trim
        c.rotate      "#{options[:rotate]}" if options.has_key?(:rotate)
        c.resize      "#{options[:resolution]}>" if options.has_key?(:resolution)
        c.resize      "#{options[:resolution]}<" if options.has_key?(:resolution)
        #c.push        '+profile'
        # c.+           "!xmp,*"
        # c.profile     "#{Rails.root}/lib/color_profiles/sRGB_v4_ICC_preference_displayclass.icc"
        c.colorspace  "sRGB"
      end
      img
    end
  end
end

**Comment by esilvamg** [comment]
I'm also with this same problem, but my version of ImageMagik is `6.5. *`

Someone would know what happens?

**Comment by samuraraujo** [comment]
I could not find a solution yet. Maybe we solve it together. What is you linux version?

**Comment by esilvamg** [comment]
We are about to change our infrastructure and use CentOS7 from now on in order to fix this issue.

An other possible solution is to update ImageMagick to version 6.9.* but we can't get this done with our current version of CentOS, which is CentOS5.

**Comment by bensie** [comment]
This is not a CarrierWave issue. You need to ensure that ImageMagick is in your `PATH` for the user running the app server.

**Comment by lakehouseru** [comment]
Have the same issue  - and  PATH variable is ok. Mogrify tool works from command-line and MiniMagick works from rails console. - Any clues?

**Comment by caraya10** [comment]
Did you all find a resolution to this?  I'm having the same issue.  Things work in the rails console but not with passenger...

**Comment by Novsochetra** [comment]
I am also got the same issue. My rails version is 5.2 and carrierwave is version 1.3

**Comment by george-norris-salesforce** [comment]
Same error
https://stackoverflow.com/questions/56031037/carrierwave-maybe-it-is-not-an-image-original-error-mogrify-strip
