### ISSUE TITLE
Remote URL with authentication

### ISSUE THREAD

**Issue by jbschrades** [carrierwaveuploader/carrierwave#1697]
Is it possible to save a remote file from a URL that requires http authentication using the remote_column_url method?

**Comment by trestrantham** [comment]
I could also use this option if possible.

**Comment by bensie** [comment]
I haven't tried it, but using http://username:password@host.com/path _might_ work for HTTP basic auth.

**Comment by eavgerinos** [comment]
@bensie It won't work. This returns ```ArgumentError: userinfo not supported.  [RFC3986]```.

@jbschrades Carrierwave [downloader](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/download.rb#L40) uses Open-Uri's `#open` method.

As it is implemented now, unfortunately, you cannot pass any params to it.

IMHO, this issue enforces the need of [this feature request](https://github.com/carrierwaveuploader/carrierwave/issues/1636).

I think we can close this issue if favour of the above one. What do you think?

**Comment by jpatel** [comment]
This feature will be wonderful and I can use it.

**Comment by jbschrades** [comment]
@eavgerinos sounds good to me
