### ISSUE TITLE
Stable version broken for Fog

### ISSUE THREAD

**Issue by joallard** [carrierwaveuploader/carrierwave#1698]
Following #1608. Seems 0.10.0 is broken when using Fog-AWS. The only alternatives are to require all of them Fog gems, which, goodbye memory, or switch to master.

For your pleasure, the error message:

    carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:73:in `eval': 
      uninitialized constant CarrierWave::Storage::Fog (NameError)

I'm looking for either a backport or a workaround. I tried requiring a bunch of things, spending an hour on this issue, to no avail.

**Comment by trantorLiu** [comment]
I also encountered this issue. I fixed it by specify an older Carrierwave revision in *Gemfile.lock*.

Here's my Gemfile.lock. Revision 37cf31d34fa411db20e99cc654195020b06202c3 doesn't work for me, so I rollbacked to cb1a5bfc6601a4e5d0abb6bad17911d73dcb57e3. And then everything worked as it used to be.
```
GIT
  remote: git://github.com/carrierwaveuploader/carrierwave.git
  revision: cb1a5bfc6601a4e5d0abb6bad17911d73dcb57e3
  specs:
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
```

Here's my Gemfile. FYI.
```
gem 'fog', require: 'fog/aws'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```

**Comment by bensie** [comment]
@joallard Both alternatives you listed are reasonable: require all of fog, or switch to master :)

**Comment by defsprite** [comment]
If you refer to carrierwave in a `gemspec` switching to master is not really an option. We worked around this in our shared gem creating a `lib/fog.rb` containing the following:

```ruby
require 'fog/core'
require 'fog/xml'
require 'fog/json'
require 'fog/aws'
``` 

Which allowed us to happily depend only on `fog-aws` with `carrierwave = 0.10.0`. So far it seems to work, but we haven't looked too deeply into it. YMMV.
