### ISSUE TITLE
public / private assets generate dynamically

### ISSUE THREAD

**Issue by casiodk** [carrierwaveuploader/carrierwave#1699]
Hi, this is my initializer file

```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider: 'AWS',
    aws_access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  }
  config.fog_directory  = "#{ ENV['FOG_DIRECTORY'] }#{ Rails.env }"
  config.fog_public     = false
  config.fog_authenticated_url_expiration = 600
end
```

If I need to dynamically generate urls to an asset without the expiration (= config.public = true), how would I do that?

Im sending an URL in an email, so the URL should not expire in that case

Best

**Comment by bensie** [comment]
You are storing files on S3 privately, so there is no public URL available. If you want to store files privately and need to send URLs in emails, consider using a crazy long expiration time.
