### ISSUE TITLE
Using ActiveRecord::Store with Carrierwave

### ISSUE THREAD

**Issue by robyedlin** [carrierwaveuploader/carrierwave#1703]
I'm having trouble with an implementation of Carrierwave, and I'm wondering if the following is possible.

~~~
class Section < ActiveRecord::Base
    store :info, accessors: [:description, :image]
    mount_uploader  :image, ImageUploader
end
~~~

Ordinarily I would use a separate column for :image, but I need the info column to be JSON because some sections will have completely different info.

I want the column data to look like this:

~~~
info: {"description"=>"Some description", "image"=>"image.jpg"}
~~~

When I try this, it returns this error, because it seems to be looking for a column named "image" rather than an accessor:

> undefined method `image_will_change!'

**Comment by bensie** [comment]
This won't work because CarrierWave expects an ActiveRecord attribute, which generates other methods it relies on.

**Comment by robyedlin** [comment]
Got it. Thanks.

**Comment by mingca** [comment]
https://github.com/simonoff/carrierwave_accessors
