### ISSUE TITLE
Protect against compression bombs by default?

### ISSUE THREAD

**Issue by ryana** [carrierwaveuploader/carrierwave#1710]
Hey guys,

A "security researcher" just jpeg compression bombed me. I found a great fix on StackOverflow: http://stackoverflow.com/questions/7527887/validate-image-size-in-carrierwave-uploader

Think it would make sense to include something like this as a default option? I would argue that it could be turned on by default with a limit of something like 10000x10000, but if not turned on by default, I would at least give it a very prominent spot in the README.

If the powers that be agree this is a worthwhile option, let me know and I'll get a PR together.

**Comment by bensie** [comment]
@ryana I think this would be great! If you can find some time we'd welcome a PR!
