### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by jasonrhalpern** [carrierwaveuploader/carrierwave#1714]
I received the deprecation warning below for this snippet of rspec code. I saw an old issue that referenced this, but that seemed to do with the upgrade to Rspec 3. All the gems I am using are recent versions (last two months or so). Just wanted to see what the current recommended fix is for the warnings:

context "avatar dimensions" do
    it "should have three versions" do
      expect(@user.avatar).to be_no_larger_than(400, 400)
      expect(@user.avatar.medium).to have_dimensions(200, 200)
      expect(@user.avatar.thumb).to have_dimensions(50, 50)
    end
  end

CarrierWave::Test::Matchers::HaveDimensions implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.

**Comment by thiaguerd** [comment]
psot full message warning

**Comment by jasonrhalpern** [comment]
Deprecation Warnings:

--------------------------------------------------------------------------------
CarrierWave::Test::Matchers::HaveDimensions implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
--------------------------------------------------------------------------------

If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

--------------------------------------------------------------------------------

**Comment by thiaguerd** [comment]
try add on /config/application.rb
config.active_record.raise_in_transactional_callbacks = true

**Comment by jasonrhalpern** [comment]
Thanks for the quick response but that didn't help. I should've mentioned I am using Rails 4.1.7. From my understanding it seems that fix might work in Rails 4.2?

**Comment by cburgmer** [comment]
See #1418, #1421 and #1424. Looks like it is fixed in trunk but awaiting a proper release.

**Comment by jasonrhalpern** [comment]
Thanks for the update on that.
