### ISSUE TITLE
File storage: url and path (unexpected) behaviour

### ISSUE THREAD

**Issue by mariusbutuc** [carrierwaveuploader/carrierwave#1717]
Running v0.10.0, and using `file` storage provides a surprising (to me) behaviour. The `url` and `path` methods on the uploaded image work the opposite compared to the expectation created when using `fog` for storage, or the Rails helper patterns:
  - `url` returns the relative path, while
  - `path` returns the absolute path.

Is there a reason behind this, or is this a bug?

**Comment by eavgerinos** [comment]
@mariusbutuc I can't see something wrong with those methods. It work quite well on me (`fog` storage`).

Can you please provide more info?

**Comment by mariusbutuc** [comment]
@eavgerinos using `fog` storage they behave as expected, but using `file` storage their behaviour is flipped. In an attempt to explain it better, here's the "hack" I'm relying on at the moment:
```ruby
def artwork_url(image:)
  image._storage.to_s.match('File') ? image.path : image.url
end
```
Does this help?

**Comment by lulalala** [comment]
@mariusbutuc I tried on my end:

```
irb(main):002:0> i.image.url
=> "/uploads/28/1445068540_29_-_2.jpeg"
irb(main):003:0> i.image.path
=> "/Users/foo/bar/public/uploads/28/1445068540_29_-_2.jpeg"
```

This is when asset_host is not set.

Are you sure your image.path is outputting the url not the file path on your system?

**Comment by thomasfedb** [comment]
@mariusbutuc to clarify:

- `path` returns the path of the file on your system.
- `url` returns a relative URL which you should use in your views, etc.

If you can provide a concrete example to the contrary, please let us know.
