### ISSUE TITLE
Cannot switch to stable branches on github

### ISSUE THREAD

**Issue by travisjtodd** [carrierwaveuploader/carrierwave#1719]
In the Readme documentation for carrierwave on the master branch there is this warning:

![screen shot 2015-08-13 at 11 01 33](https://cloud.githubusercontent.com/assets/47908/9246263/c416873e-41aa-11e5-8d3c-d468a69f88f4.png)

But when I click on the branches tab I do not see the latest stable branch that is in the Releases section (0.10.0 as of writing). 

![screen shot 2015-08-13 at 11 01 41](https://cloud.githubusercontent.com/assets/47908/9246303/fc4fca7a-41aa-11e5-9eda-4c03bc8e8694.png)

Maybe I'm just a github newb and can't find the way to get to the right branch, but perhaps you should making access to the current stable documentation easier from the Readme...

**Comment by eavgerinos** [comment]
@travisjtodd Check the tags :) 
![github-tags](https://cloud.githubusercontent.com/assets/1211471/9246341/a137ce0e-41b3-11e5-8f8e-70c0874db30f.png)
