### ISSUE TITLE
Rails, Carrierwave & PrawnLabel Gem

### ISSUE THREAD

**Issue by annieogrady** [carrierwaveuploader/carrierwave#1724]
I am using rails 4.0 (somewhat of a newbie) and I am trying to create a PDF with Prawn Labels Gem and then save the result using Carrierwave.   Any guidance is appreciated.  I am trying to figure out if this is a bug with Carrierwave or something I am doing wrong.    I want to create the Labels and then save them to Carrierwave.  

I have successfully create the PDF but when i try to save the @email_campaign.file, it seems to have some contention with the Mount.... PdfUploader. (If I comment out the Mount (in the model),it saves the file name) but then i don't get benefit of Carrierwave.

I am trying to save the file name (from the Prawn Gem) to the @email_campaign.file If I run the code (as it is below), and the field is nil.

Using the following Gems

```
gem "carrierwave" # for handling file uploads
gem "mini_magick" # processing images
gem 'prawn-labels', '~> 1.2.3'
```

Here is my db.schema:

```
create_table "print_campaigns", force: :cascade do |t|
t.string   "title"
t.datetime "printed_at"
t.integer  "user_id"
t.integer  "contact_id"
t.text     "contacts"
t.datetime "created_at",                  null: false
t.datetime "updated_at",                  null: false
t.string   "label_size"
t.string   "grades",         default: [],              array: true
t.string   "groups",         default: [],              array: true
t.datetime "pdf_created_at"
t.string   "name"
t.string   "file"
```

Here is my Model:

```Ruby
class PrintCampaign < ActiveRecord::Base

belongs_to :user
has_many :print_campaign_messages
mount_uploader :file, PdfUploader
Here my Controller:

def create
@print_campaign = current_user.print_campaigns.new(print_campaign_params)
set_select_contacts
set_label_type(@print_campaign.label_size)
create_campaign_labels
@print_campaign.pdf_created_at = Time.zone.now
if @print_campaign.save!

....
def create_campaign_labels
  quantity = 0
  @labels = Prawn::Labels.render(@contacts,
          :type => @type) do |pdf, contact|
  name = contact.name
  quantity = quantity + 1
  address_string_line1 = create_contact_address1_string(contact)
  address_string_line2 = create_contact_address2_string(contact)
  name = contact.name + "\n" + address_string_line1 +
         "\n" + address_string_line2
  pdf.text name
  end

   @print_campaign.pdf_created_at = Time.zone.now
  if @print_campaign.name?
    @name = "Labels " + @print_campaign.name + "-" +
            Time.zone.now.to_formatted_s(:short) + ".pdf"
  else
    @name = "AB Labels " + "-" + Time.zone.now.to_formatted_s(:short) + ".pdf"
  end
file = @name
send_data @labels, :filename => @name, :type => "application/pdf"
@print_campaign.file = @name
Util.log "FILE NAME #{file}"
Util.log "FILE NAME #{@print_campaign.file}"
@print_campaign.quantity = quantity

end
```

Params are: (From looking at other SO, its seems sometimes the param (:file is missing - but i have that - see below)

```Ruby
def print_campaign_params
  params.require(:print_campaign).permit(
    :id,
    :title,
    :printed_at,
    :user_id,
    :lead_id,
    :contact_id,
    :contacts,
    :label_size,
    :printed,
    :pdf_created_at,
    :recipient_type,
    :name,
    :file,
    :quantity,
    grades: [],
    groups: [],
  )
end
```

NB: the first UTIL log prints the file (e.g. Labels Hallie 080816...') but it seems that it will not save to @print_campaign.file

here is my Uploader:

```Ruby
# encoding: utf-8

class PdfUploader < CarrierWave::Uploader::Base
#include ::CarrierWave::Backgrounder::Delay
#include CarrierWaveDirect::Uploader
# Include RMagick or MiniMagick support:
# include CarrierWave::RMagick
# include CarrierWave::MiniMagick

# Choose what kind of storage to use for this uploader:
# storage :file
# storage :fog

# Override the directory where uploaded files will be stored.
# This is a sensible default for uploaders that are meant to be mounted:
def store_dir
  "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
end

# Provide a default URL as a default if there hasn't been a file uploaded:
# def default_url
#   # For Rails 3.1+ asset pipeline compatibility:
#   # ActionController::Base.helpers.asset_path("fallback/" + [version_name,        "default.png"].compact.join('_'))
#
#   "/images/fallback/" + [version_name, "default.png"].compact.join('_')
# end

# Process files as they are uploaded:
# process :scale => [200, 300]
#
# def scale(width, height)
#   # do something
# end

# Create different versions of your uploaded files:
# version :thumb do
#   process :scale => [50, 50]
# end

# Add a white list of extensions which are allowed to be uploaded.
# For images you might use something like this:
# def extension_white_list
#   %w(jpg jpeg gif png)
# end

def extension_white_list
  %w(pdf)
end

# Override the filename of the uploaded files:
# Avoid using model.id or version_name here, see uploader/store.rb for details.
# def filename
#   "something.jpg" if original_filename
# end

end
```

If I comment out the mount_uploader :file, PdfUploader - then the file saves the string (but I think i need the mount in my model so that to be able to use Carrierwave?).

Any thoughts? many thanks.

**Comment by eavgerinos** [comment]
@annieogrady I edited your comment to provide some styling in order to be readable. I hope you are ok with this. :smile:

**Comment by eavgerinos** [comment]
@annieogrady Please for usage questions post to StackOverflow under the `carrierwave` tag.
You can use the `#file_identifier` method

```
print_campaign.file_identifier
```

You can always use the `:mount_on` option to write the filename in a different field of your model.

eg. If you name the column `filename`

```Ruby
mount_uploader :file, PdfUploader, mount_on: :filename
```

**Comment by annieogrady** [comment]
@eavgerinos - many thanks - i have posted on SO with carrier wave.   if it is okay, i'd like to add your comment to my question.    

i did add another column naume (e.g. filename and it saves successfully to that).  I sitll don't understand why it does not save to just '@print_campaign.file' - that shows as nil.

@print_campaign.file_identifier  --- gives a undefined method.  

again, many thanks - apologies for posting here.

**Comment by eavgerinos** [comment]
@annieogrady Feel free to copy anything you want.

I believe you should change this line

```Ruby
@print_campaign.file = @name
```

With this one

```Ruby
@print_campaign.file = File.open(@name)
```

**Comment by annieogrady** [comment]
thanks so much for your help.  very new to coding. many thanks.

Annie O'Grady
Co-founder
AgentBright, Inc
3544 Crown Point Road
Louisville, TN 37777
860-575-6950


On Mon, Aug 24, 2015 at 4:18 PM, Aggelos Avgerinos <notifications@github.com
