### ISSUE TITLE
Carrierwave always tries to populate a mounted field with its identifier

### ISSUE THREAD

**Issue by phuongnd08** [carrierwaveuploader/carrierwave#1727]
I'm recently running into issue a field mounted with an uploader being populated with its name (so if the field name: assets, it will be populated with 'assets') every time the record being saved, even though no file assigned to it yet.

Upon closer inspection, I found 2 things:
1. When an uploader is mounted to a record, it install these `before_save :"write_#{column}_identifier"`
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L58

2. When the callback being invoked, it then write its identifier to column value:
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/mount.rb#L171

When the model is updated (like a person name being updated), then  `person.picture.present?` returns `true` (cause it now has the value of `"picture"`) which doesn't seem to be correct because the field is actually not uploaded yet.

I am a bit surprised to find that I haven't experienced the effect of this issue so far, but to day it really bit me hard. Any thoughts?

**Comment by phuongnd08** [comment]
My bad. Although the field is populated with its name, `field.present?` still return false. Perhaps it's another bug that confuses me.

**Comment by phuongnd08** [comment]
After retry a few times, I can confirm that this is real. When the Rails model get saved (like an attribute get changed), the uploader field is populated with its name and then start thinking that it has been uploaded, which is incorrect.

**Comment by phuongnd08** [comment]
And just to add helpful details, I'm using carrierwave-aws to upload files to S3. Maybe the combination result in the mess?

**Comment by thomasfedb** [comment]
@phuongnd08 can you please submit this as an issue to [sorentwo/carrierwave-aws](https://github.com/sorentwo/carrierwave-aws).

**Comment by thomasfedb** [comment]
Note that AWS is also supported via Fog.
