### ISSUE TITLE
Add configuration variable to not delete files on model destruction

### ISSUE THREAD

**Issue by gustavoschmidt** [carrierwaveuploader/carrierwave#1730]
I'm preventing CarrierWave from deleting any files from the storage. To do that, I'm skipping callback methods for all models with mounted uploaders.

I just found out the config variable `remove_previously_stored_files_after_update` that prevents the deletion after a update. Do you guys thinks a new configuration variable `remove_stored_files_after_destroy` is a common use case? If so, I'd love to work on this.

Cheers!

**Comment by eavgerinos** [comment]
@gautampunhani Hello there.

I can't  see what kind of usage this feature would have. 

What I mean, once you have destroyed your record, you have no reference to the uploaded file, thus, it's unusable for the application.

IMHO, a case like the one you describe must be solve in the application level.

**Comment by gustavoschmidt** [comment]
My idea is to never delete any files, so we can revert changes in case of a bug. I'm also using papertrail to have an audit-trail, so if I want to use a previous version of my model, that file will be already delete from storage.

But if it's not a common use case, I don't think it makes sense to add this config variable to carrierwave. Thanks @eavgerinos, I'm closing this issue.
