### ISSUE TITLE
Cannot load "fog-google"

### ISSUE THREAD

**Issue by micahalcorn** [carrierwaveuploader/carrierwave#1732]
If I follow the Readme and attempt to `config.fog_provider = 'fog-google'`, then `activesupport-4.2.0` throws "cannot load such file -- fog-google". This is resolved by changing my `config.fog_provider` to `fog/google` (slash instead of hyphen, which then matches the Readme for AWS & Rackspace).

When I originally posted this issue I had missed the instruction to also provide a `:provider` on the config object. I'll assume that the revision mentioned above is necessary. Let me know if there is any way that I can help.

**Comment by eavgerinos** [comment]
@micahalcorn Which version of CarrierWave are you using? 

The README refers to the master branch. In case you are using `v0.10.0` please switch to its branch and configure your application according to it.

**Comment by micahalcorn** [comment]
This is what I don't understand. The master branch identifies version 0.10.0 in `carrierwave/lib/carrierwave/version.rb`. The only numbered branches that I see in the repo are 0.3-stable, 0.4-stable, and 0.5-stable. What am I missing?

**Comment by eavgerinos** [comment]
@micahalcorn https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0

**Comment by micahalcorn** [comment]
@eavgerinos thanks. Sorry, I wasn't familiar with tags.
