### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by gfx** [carrierwaveuploader/carrierwave#1733]
I'd like to use CarrierWave::Uploader::MagicMimeWhitelist, which is not bundled in v0.10.0.

I know the v1.0.0 milestones are working in progress but it should be possible that a new non-v1.0.0 version, or v0.11.0 is released before v1.0.0.

**Comment by fran-worley** [comment]
+1 for this. I would love for the ability to just use fog-aws and not have every single fog gem a dependancy.

**Comment by matthewrudy** [comment]
+1

**Comment by fran-worley** [comment]
Forgot to mention, if you need any help in doing this I have some time at the moment.

**Comment by inket** [comment]
+1

**Comment by stephankaag** [comment]
+1

**Comment by fabn** [comment]
+1000 for this. Who can do that?

Saw #1574 and #1661 and both seems solved.

@bensie Do you think current master it's ready to be released?

If not tell us how can we help to get this in rubygems.

**Comment by jpmcgrath** [comment]
+1 here. Wanting to use the multiple file uploader. Thanks!

**Comment by bensie** [comment]
Milestone is here: https://github.com/carrierwaveuploader/carrierwave/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+v1.0.0%22

**Comment by jpmcgrath** [comment]
Ok, so if I understand correctly. once those 3 milestone issues are resolved, the v1.0.0 can be released. Thanks for the update.

**Comment by inket** [comment]
Right from OP:

> I know the v1.0.0 milestones are working in progress but it should be possible that a new non-v1.0.0 version, or v0.11.0 is released before v1.0.0.

Those issues are going to take ages, by the way.

**Comment by bensie** [comment]
We'd love all your help! +1 comments are the opposite of helpful.

There will not be a 0.11.0 release. Stick with `master` if you need the latest in the meantime.
