### ISSUE TITLE
Question: How to check if alternative versions were created successfully

### ISSUE THREAD

**Issue by Z-von-Bub** [carrierwaveuploader/carrierwave#1734]
The uploader can handle various file types. When uploading images it is easy to create the alternative versions of file (e.g. thumbs). If txt (or doc, xml, xsl, .... ) file is uploaded, the thumb cannot be created. Or creation of thumb can fail by any reason. How can I check it the alternative versions were created and uploaded successfully?

**Comment by thomasfedb** [comment]
Hey @Z-von-Bub, I'd suggest checking the filetype and only asking carrierwave to create thumbnails for images. Perhaps even use a separate uploader.
