### ISSUE TITLE
Image cache not being used with S3 prior to upload

### ISSUE THREAD

**Issue by dylansm** [carrierwaveuploader/carrierwave#1735]
I've been struggling to get image cache to show up. The cache dir is being set and the images are sized and saved locally to the cache dir, but the view prepends the asset_host URL to the front of the path, which is on S3, but the images, at this point, are only local. So, e.g. if I save the model with failing validations, the screen refresh always has the remote URL instead of the local cache path. Right now I'm removing that portion of the URL but that feels like a hack. I've tried both 0.10.0 and latest code on master and can't get it to NOT prepend the S3 URL.

**Comment by thomasfedb** [comment]
What are you trying to acheive @dylansm?

**Comment by dylansm** [comment]
I was having an issue where, if a form validation on another field failed, I wanted to show the cached image instead of the uploaded image. However, the path to the image was always for the intended upload location instead of the local cached image (but it never was uploaded—so it was a broken image). I never could get it to work so just wrapped it in my own condition.

**Comment by allaire** [comment]
@dylansm @thomasfedb Just faced a similar issue, here is my solution:

```
  config.asset_host = proc do |file|
    "https://blkstr.ca/#{ENV["OPENSTACK_TENANT"]}/#{ENV["OPENSTACK_CONTAINER"]}" if !file.cached?
  end

  config.cache_dir = "#{Rails.root}/public/uploads/tmp"
```
