### ISSUE TITLE
 carrierwave-sequel maintaining

### ISSUE THREAD

**Issue by kuraga** [carrierwaveuploader/carrierwave#1737]
@bensie , sorry about a little off-topic but can you please see my e-mail in CarrierWave mailing list?
https://groups.google.com/forum/#!topic/carrierwave/Q7-Xtgk9SFM
Nobody wants to do this or reply...
Thanks very much!

**Comment by kuraga** [comment]
@bensie , ping

**Comment by mrbrdo** [comment]
:+1: could we get this guy access to that repo?

**Comment by bensie** [comment]
@kuraga I've added you as a collaborator on carrierwave-sequel.

**Comment by kuraga** [comment]
Wow, thanks! Wait me tomorrow! :smile:

I'll close this after publishing new version of `carrierwave-sequel`.

**Comment by mrbrdo** [comment]
I think you won't be able to publish to Rubygems yourself, that's a separate credential I think :)

**Comment by bensie** [comment]
I don't have Rubygems access for carrierwave-sequel either...

/cc @jnicklas @trevorturk

**Comment by trevorturk** [comment]
I have access -- let me know what you'd like me to do, @bensie -- add you? to multiple gems?

**Comment by bensie** [comment]
@trevorturk That'll work for now, just need carrierwave-sequel. Thanks!

**Comment by trevorturk** [comment]
@bensie ok I think you're all set!

**Comment by bensie** [comment]
thanks!

**Comment by kuraga** [comment]
@bensie @mrbrdo Good day!

I tagged [0.1.1 version](https://github.com/carrierwaveuploader/carrierwave-sequel/releases/tag/v0.1.1). Can you push it to RubyGems, please?

Thanks!

**Comment by bensie** [comment]
@kuraga done!

**Comment by kuraga** [comment]
Thanks!
