### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer in /.rvm/gems/ruby-2.2.3/gems/carrierwave-0.9.0/lib/carrierwave/mount.rb:155:in `[]='

### ISSUE THREAD

**Issue by mrblackmountain** [carrierwaveuploader/carrierwave#1741]
I'm using Carrierwave 0.9.0 with rmagick (not the first project) and ran into a strange issue:

I do have an Upload Model with a :file and an :image attribute. I mounted two Uploaders and everything worked as expected. This is what the Model looked like. Nothing special there, except some attr_accessor for cropping:
```
class Upload < ActiveRecord::Base
	has_many :upload_associations
	belongs_to :project

	attr_accessor :crop_x, :crop_y,:crop_w, :crop_h

	mount_uploader :image, ImageUploader
	mount_uploader :file, FileUploader
end
```
 At some point I decided to refactor the code since I either use the :file or the :image attribute, but never both. So Single Table Inheritance was my go-to path. I removed the mount_uploader from the Upload Model and created two Models that inherited from Upload which are ImageUpload and FileUpload with both mounting the respective uploader on the :file attribute. This is the source of the three files:

```
#app/models/upload.rb
class Upload < ActiveRecord::Base
	has_many :upload_associations
	belongs_to :project
	scope :image_uploads, -> { where(file: 'image_upload') }
	self.inheritance_column = :file

	attr_accessor :crop_x, :crop_y,:crop_w, :crop_h

	def self.uploaders
		%w(ImageUploader FileUploader)
	end
end

#app/models/image_upload.rb
class ImageUpload < Upload
	mount_uploader :image, ImageUploader
end

#app/models/file_upload.rb
class FileUpload < Upload
	mount_uploader :image, FileUploader
end
```
This code is not super clean yet, since I decided to firstly just use the :file attribute as inheritance column because I just wanted to give it a quick try without migrations. I can confirm, that the STI is working correctly since when I just remove the uploader I can instantiate ImageUpload and FileUpload in console, with the :file attribute correctly set to "image_uplad". :image attribute is accessible.

However, as soon as I mount the uploader Carrierwave won't initialize but throw above error. Please see the stack trace here: 
```
2.2.3 :001 > FileUpload.new
TypeError: no implicit conversion of Symbol into Integer
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/carrierwave-0.9.0/lib/carrierwave/mount.rb:155:in `[]='
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/carrierwave-0.9.0/lib/carrierwave/mount.rb:155:in `mount_uploader'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/carrierwave-0.9.0/lib/carrierwave/orm/activerecord.rb:15:in `mount_uploader'
	from /Users/klaus/code/smaply-refactor/app/models/file_upload.rb:2:in `<class:FileUpload>'
	from /Users/klaus/code/smaply-refactor/app/models/file_upload.rb:1:in `<top (required)>'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:443:in `load'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:443:in `block in load_file'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:633:in `new_constants_in'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:442:in `load_file'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:342:in `require_or_load'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:180:in `const_missing'
	from (irb):1
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/klaus/.rvm/gems/ruby-2.2.3/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'2.2.3 :002 >
```

If I mount the exact same Uploader on the Upload Model instead the inherited one, everything works fine again. I searched StackOverflow and Google for 3 days now but I don't find a solution. I also checked the affected code in CarrierWave directly but don't find anything that would prevent me from mounting the Uploader on a Child object. Furthermore, everything I read online suggested that it should just work fine.

I usually fight my way through to solutions but after 3 days of searching I have no Idea what could be left to do. Of course, I could just skip my refactoring path but I just can't believe why it shouldn't work. 

Halp please.

**Comment by thomasfedb** [comment]
Hi @mrblackmountain could you please update to the latest version of carrierwave and see if this is still an issue.
