### ISSUE TITLE
CarrierWave.root not updating

### ISSUE THREAD

**Issue by randoum** [carrierwaveuploader/carrierwave#1743]
Found this bug while trying to use `CarrierWave.clean_cached_files!` from a rake task with a custom `CarrierWave.root` path. Trimmed it down to the following step by step that can be reproduced on a new project:

Create a new project, and create a *config/initializers/carrier_wave.rb* with content:
```
CarrierWave.configure do |config|
  config.root = Rails.root.to_s
end
pp CarrierWave.root

CarrierWave.root  = Rails.root.to_s
pp CarrierWave.root
```

The output is:
```
"/path/my_project/public"
"/path/my_project"
```

Unlike what would be expected, `config.root =` does not update the value of `CarrierWave.root`
Thanks in advance for your feedback

**Comment by randoum** [comment]
@bensie any insights? Thanks

**Comment by thomasfedb** [comment]
@randoum please try `pp CarrierWave::Uploader::Base` instead of `pp CarrierWave.root`.

**Comment by randoum** [comment]
@thomasfedb 

`CarrierWave::Uploader::Base = Rails.root.to_s`
gives
`warning: already initialized constant CarrierWave::Uploader::Base`

**Comment by thomasfedb** [comment]
@randoum I never suggested attempting to assign to `CarrierWave::Uploader::Base` - clearly it's a constant, and quite an important one.

Rather, give this a go:

```ruby
CarrierWave.configure do |config|
  config.root = Rails.root.to_s
end

pp CarrierWave::Uploader::Base.root
```

**Comment by randoum** [comment]
Ok. This is strange.

Quick explanation : few months ago I realized that `CarrierWave.configure { |c| c.root = Rails.root.to_s }` did not suffice and my *tmp* and *upload* directories was still present in *public* (restarted server, stopped spring, deleted those directories, did several tests without success). And the only solution was to add after the `configure` block the instruction `CarrierWave.root = Rails.root.to_s`
And that's what motivated me to write this issue. 
Anyhow, now removing the additional instruction `CarrierWave.root = Rails.root.to_s` works as expected (i.e no more tmp or upload in public). I certainly made a mistake at some point.

Well anyhow thanks for your answers.
