### ISSUE TITLE
Check for column existence before raising seemingly unrelated errors?

### ISSUE THREAD

**Issue by olivierlacan** [carrierwaveuploader/carrierwave#1747]
Would you accept a PR that adds AR column checking to `CarrierWave::ActiveRecord#mount_uploader` or is that a bad idea?

This is a very obtuse error and I doubt I would have figured out I forgot to run `rake db:migrate` a few years back:
```ruby
NoMethodError: undefined method `portrait_will_change!' for #<Member:0x007f92dc652f18>
```

PS: after a cursory Google check there seems to be a bunch of people wondering why AR dynamic methods are causing exceptions, so I think this might help out more than few people

**Comment by olivierlacan** [comment]
This is a really dumb/naive implementation of what I mean: https://github.com/olivierlacan/carrierwave/commit/6c62250a46e7857d78ee449f05ab560e143563fa

That might help gauging how insane this is. Obviously calling `connection` this early might be an issue but I found that this only raises when an AR object is instantiated anyway.

**Comment by eavgerinos** [comment]
@olivierlacan Hello. Thanks for pointing this out.

I'm not quite sure about the check for column.

I have 2 considerations about this change:

- Maybe some people use a virtual attribute for this by hacking the `ActiveModel::Dirty`. 
- If we are about to check it, I believe that `ArgumentError` is the proper error to raise.

What do you think?

**Comment by thomasfedb** [comment]
@olivierlacan Please feel free to request this issue be reopened if you require.
