### ISSUE TITLE
@user.avatar is not updated when it's changed by a feature spec

### ISSUE THREAD

**Issue by jmuheim** [carrierwaveuploader/carrierwave#1752]
I have the following spec:

      visit edit_user_registration_path
      check 'user_remove_avatar'
      fill_in 'user_current_password', with: 's3cur3p@ssw0rd'

      expect {
        click_button 'Save'
        @user.reload
      }.to change { File.basename @user.avatar.to_s }.from('image.jpg').to eq ''

This doesn't work, I have to explicitly use `User.last` (`@user` is the only user that exists in the DB, no danger of confusion here), then it works:

      visit edit_user_registration_path
      check 'user_remove_avatar'
      fill_in 'user_current_password', with: 's3cur3p@ssw0rd'

      expect {
        click_button 'Save'
      }.to change { File.basename User.last.avatar.to_s }.from('image.jpg').to eq ''

It seems that somehow the `@user` instance variable doesn't notice that the image was removed in the spec. I think this is unexpected behaviour.

**Comment by thomasfedb** [comment]
@jmuheim Are you able to reproduce this outside of RSpec?
