### ISSUE TITLE
Add "official" documentation for using multiple file uploads with SQLite / MySQL

### ISSUE THREAD

**Issue by bensie** [carrierwaveuploader/carrierwave#1755]
Serialized column + string column...

**Comment by rbonick** [comment]
Definitely agree documentation on this needs added... spent over an hour trying to figure this out thanks to a sqlite3 database.

**Comment by ardianys** [comment]
+1 for this

**Comment by chibui** [comment]
+1

**Comment by bananaappletw** [comment]
+1
