### ISSUE TITLE
build same filename (md5) for all versions and original on S3

### ISSUE THREAD

**Issue by 3zone** [carrierwaveuploader/carrierwave#1757]
In a Rails4 app I have a model with an uploader which use legacy fields from Paperclip:

    class Location < ActiveRecord::Base

      mount_uploader :logo, LocationLogoUploader, mount_on: :logo_file_name

    end

in the uploader I use MiniMagick to generate some versions

    class LocationLogoUploader < CarrierWave::Uploader::Base
      include CarrierWave::Compatibility::Paperclip
      include SharedUploader
      include CarrierWave::MiniMagick

      after :remove, :delete_empty_upstream_dirs

      def filename
        shared_filename if super
      end

      def extension_white_list
        %w(jpg jpeg gif png)
      end

      version :thumb do
        process resize_to_fit: [200, -1]
      end

    end

in an external module I set the filename: I want to set same filename for all versions (included original filename):

    module SharedUploader

      def self.included(klass)
        
        # ... other stuff

        def shared_filename
          "#{md5}-#{SanitizeFilename.new(original_filename).run}" if original_filename.present?
        end

        def md5
          chunk = model.send(mounted_as)
          @md5 ||= Digest::MD5.hexdigest(chunk.read.to_s)
        end

        # ... other stuff

      end

    end

this code works well in localhost with file storage, instead I have a problem with Fog S3:
 when I upload an image the original file is saved in S3 with a different md5 compared to md5 of generated versions:
  this is a problem because in DB field logo_file_name is written the original filename with different md5 then I can't retrieve the other versions path.

**Comment by thomasfedb** [comment]
@3zone have you attempted to debug the issue at all? Presumably `Digest::MD5.hexdigest` is receiving different values to produce different digests.

Feel free to request this issue be reopened if you can show us how you this carrierwave is misbehaving.
