### ISSUE TITLE
How to change location of newly uploaded files, without changing location of existing files?

### ISSUE THREAD

**Issue by Chaseph** [carrierwaveuploader/carrierwave#1760]
I'd like to change the directory and add a cache-busting token to newly uploaded images. I tried the following:

```ruby
def filename
  "#{original_filename}-#{cache_busting_name}.#{file.extension}" if original_filename.present?
end

def store_dir
  "actions/#{model.id}/#{mounted_as}"
end
```
but this results in the url of existing images getting changed as well.

Is there any way to only change the path of new images, without breaking old images?

**Comment by desmondhume** [comment]
Same problem here. Any solution so far?

**Comment by thomasfedb** [comment]
@Chaseph I would recommend moving the existing uploads, rather than splitting the locations. Otherwise, you could try a technique involving `model.created_at` to determine the correct filename for a particular upload.
