### ISSUE TITLE
Directory problem

### ISSUE THREAD

**Issue by juanpastas** [carrierwaveuploader/carrierwave#1761]
I am getting:

```
Excon::Errors::SocketError (hostname "myapp-staging1.myapp-staging1.s3-us-west-2.amazonaws.com" does not match the server certificate (OpenSSL::SSL::SSLError)):
```

with this config:

```
CarrierWave.configure do |config|
    config.fog_credentials = {
      :provider               => 'AWS',                        # required
      :aws_access_key_id      => ENV["aws_access_key_id"],                        # required
      :aws_secret_access_key  => ENV["aws_secret_access_key"],                        # required
      :region                 => 'us-west-1',                  # optional, defaults to 'us-east-1'
    }
    config.fog_directory  = ENV["fog_directory"]                          # required
  end
```

`ENV["fog_directory"]` is `myapp-staging1` on server console.

Why I could be getting a repeated part in `myapp-staging1.myapp-staging1.s3-us-west-2.amazonaws.com`?

I also created an issue on [fog](https://github.com/fog/fog/issues/3734). And a [gist](https://gist.github.com/juanpastas/eea1b7b236b35835ebc2) with the entire trace.

**Comment by plribeiro3000** [comment]
See fog/fog#3734 to find the resolution. Closing due feedback that seems to be a misconfiguration.

Thank your for your feedback!
