### ISSUE TITLE
Files are not copied to destination folder, remains in tmp folder when using multiple uploading and mongoid

### ISSUE THREAD

**Issue by ajoseerazo** [carrierwaveuploader/carrierwave#1767]
I'm trying to upload multiple files. My model is written in MongoID. I've tested using not multiple option for uploading and works, but when in try to use multiple files, the files are uploaded but remains in tmp folder, are not copied to destination folder.

I'm doing exactly the same example of the wiki for multiple files but using mongoID insteand of ActiveRecord. What could be the issue?

**Comment by thomasfedb** [comment]
@ajoseerazo can you please provide your model and uploader code, or a minimum reproduction.
