### ISSUE TITLE
validate remote url response, not the url itself

### ISSUE THREAD

**Issue by raphaelcm** [carrierwaveuploader/carrierwave#1768]
I'm trying to upload remote images that are retrieved with urls of the form:

https://foobar.com/friends/photos/?id=405534

This retrieves a perfectly valid JPEG:

![download](https://cloud.githubusercontent.com/assets/929080/11015732/adccd4f8-8537-11e5-814a-e1d82f5730a2.jpeg)

However, Carrierwave throws an error because it validates the URL string, rather than the response from retrieving the url:

`The following errors were found: Avatar You are not allowed to upload "" files, allowed types: jpg, jpeg, gif, png`

Is there a way around this? This is a common way of retrieving files, so validating on the presence of "jpg" in the URL string seems overly simplistic.

**Comment by raphaelcm** [comment]
The response specifies `Content-Type: image/jpg` which seems like a much more sensible thing to validate on.

**Comment by awinabi** [comment]
@raphaelcm 
I'm trying to replicate the issue, but this seems to work fine for me.

The remote url, I'm using is https://chart.googleapis.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World

```ruby
irb(main):004:0> u = _
=> #<User id: 6, name: "User123", email: "user123@gmail.com", created_at: "2015-12-17 05:52:10", updated_at: "2015-12-17 05:52:10", avatar: "chart.png">
irb(main):005:0> u.remote_avatar_url = 'https://chart.googleapis.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World'
=> "https://chart.googleapis.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World"
irb(main):006:0> u.save
   (0.2ms)  begin transaction
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 6]]
  SQL (1.7ms)  UPDATE "users" SET "avatar" = ?, "updated_at" = ? WHERE "users"."id" = 6  [["avatar", "chart.png"], ["updated_at", Thu, 17 Dec 2015 06:49:04 UTC +00:00]]
Digest::Digest is deprecated; use Digest
   (210.0ms)  commit transaction
=> true
irb(main):007:0> 



irb(main):008:0* user = User.create(name: 'User44', email: 'user44@gmail.com', remote_avatar_url: 'https://chart.googleapis.com/chart?cht=p3&chd=t:60,40&chs=250x100&chl=Hello|World')
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "users" ("avatar", "created_at", "email", "name", "updated_at") VALUES (?, ?, ?, ?, ?)  [["avatar", "chart.png"], ["created_at", Thu, 17 Dec 2015 06:59:04 UTC +00:00], ["email", "user44@gmail.com"], ["name", "User44"], ["updated_at", Thu, 17 Dec 2015 06:59:04 UTC +00:00]]
   (178.2ms)  commit transaction
=> #<User id: 7, name: "User44", email: "user44@gmail.com", created_at: "2015-12-17 06:59:04", updated_at: "2015-12-17 06:59:04", avatar: "chart.png">
irb(main):009:0> User
=> User(id: integer, name: string, email: string, created_at: datetime, updated_at: datetime, avatar: string)
irb(main):010:0> 
```

The config files and uploader I'm using is @ https://gist.github.com/anonymous/3304f6a1fdde0bff5343

Can you provide more details on the error and also the versions (rails and carrierwave) that you are using?
