### ISSUE TITLE
Process XML files

### ISSUE THREAD

**Issue by Aetherus** [carrierwaveuploader/carrierwave#1774]
Recently I want to handle TMX (Translation Memory eXchange) file uploads. TMX is just XML. Since it the uploaded files can be huge, I want to provide a tiny preview version of the original. I'm struggling with it. Here is my code:

**app/models/tmx.rb**

```ruby
class Tmx < ActiveRecord::Base
  has_one :upload
  has_many :downloads

  mount_uploader :file, TmxUploader

  def digest
    Digest::SHA1.hexdigest(file.file.read)
  end
end
```

**app/uploaders/tmx_uploader.rb**

```ruby
class TmxUploader < CarrierWave::Uploader::Base
  
  storage :sftp
  
  version :preview do
    process :retain => 10
  end

  def retain(translation_units)
    doc = Nokogiri::XML(TMX_ROOT)
    body = doc.at_css('body')

    tus = 0
    Nokogiri::XML::Reader(model.file.file.to_file).each do |node|
      break if tus >= translation_units
      next unless node.name == 'tu' && node.node_type == Nokogiri::XML::Reader::TYPE_ELEMENT
      body.add_child(node.outer_xml)
      tus += 1
    end

    Tempfile.new('tmx').tap{|f| f.write doc.to_xml; f.rewind}
  end
  
  def extension_white_list
    %w(tmx)
  end
  
  def filename
    "#{model.digest}.tmx"
  end

  TMX_ROOT = <<-XML.strip
  <?xml version="1.0" encoding="utf-8"?>
  <tmx version="1.4">
    <body></body>
  </tmx>
  XML
end
```

Every time I upload a TMX file, there is a preview version, but it's identical to the original file. I'm pretty sure that the original TMX has more than 10 `tu`'s. What is supposed to be returned by the process method (`retain`)?

**Comment by thomasfedb** [comment]
As far as I can tell @Aetherus, the return value of the processing methods is not used.

See here: [lib/carrierwave/uploader/processing.rb#L73](https://github.com/carrierwaveuploader/carrierwave/blob/1e4e7b0bf20fee70d8ac3815d0921144f39e14cf/lib/carrierwave/uploader/processing.rb#L73)

**Comment by thomasfedb** [comment]
I'm going to close this issue, as due to no reply from @Aetherus, particularly given that this is a fairly corner-case usage.
