### ISSUE TITLE
Moving from single file to multiple files, how to migrate?

### ISSUE THREAD

**Issue by ch3m1c** [carrierwaveuploader/carrierwave#1782]
Hello guys,

I've got multiple files upload working, created another field in database for it, renamed/refactored uploader etc. But now there's a question, how to properly migrate old data, what's stored under attachment to newly created attachments (files and also database)

Thanks alot!

**Comment by thomasfedb** [comment]
Hi @ch3m1c. I'd suggest that you follow the following migration pathway:

1. Add `attachments` to your database and add `mount_uploaders :attachments`
2. Write a migration to move existing files from `attachment` to `attachments`
3. Remove the old `attachment` column and uploader mount.

Hope this helps!

**Comment by ch3m1c** [comment]
2. Write a migration to move existing files from attachment to attachments
everything else works already, this is a question.. how to write proper migration to move existing files from attachment to attachments + make changes in database at the same time

**Comment by thomasfedb** [comment]
```ruby
# in db/migrations/...

change_table :foos do |t|
  t.column :attachments, :string, array: true
end

class Foo < ActiveRecord::Base
  mount_uploader :attachment
  mount_uploaders :attachments
end

Foo.all.each do |foo|
  foo.attachments = [foo.attachment]
  foo.save!
end

change_table :foos do |t|
  t.remove :attachment
end
```

**Comment by ch3m1c** [comment]
First, column type can't be array, it has to be :json to work with Carrierwave.
Second, this migration doesn't move files from old location to new location, right? 

I would love to run the migration so old files will go threw the same "pipe" that new files will go (get's renamed, moved to right place etc)

**Comment by thomasfedb** [comment]
@ch3m1c The above code will do all that, as long as you mount the right uploader at `:attachments`.
