### ISSUE TITLE
Will Carrierwave work with postgresql 9.4's jsonb data type?

### ISSUE THREAD

**Issue by popup-user** [carrierwaveuploader/carrierwave#1783]
I'm interested in using carrierwave with Rails 4.2.4 with Postgresql 9.4 for "multiple file uploads" - and I see in the example, you use a json field. Would it work with a jsonb field, instead - I'd like to use one.

Thanks!

**Comment by thomasfedb** [comment]
From the PostgreSQL docs:

> There are two JSON data types: json and jsonb. They accept almost identical sets of values as input. The major practical difference is one of efficiency. The json data type stores an exact copy of the input text, which processing functions must reparse on each execution; while jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage.

Sounds that, as far as DB users are concerned, that `jsonb` should work about the same as `json`.

I'd suggest you give it a go @popup-user, let us know how you go.

**Comment by popup-user** [comment]
Thanks for the quick reply -- I'll give it a try!

**Comment by popup-user** [comment]
@thomasfedb I did as you said and gave it a go:  iThe answer is YES jsonb worked for me. I used carrierwave with my gemfile set to:
```gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'```
with Postgresql 9.4.1.0.
my migration simply was:
```add_column :my_model, :photos, :jsonb```
Thanks!

**Comment by thomasfedb** [comment]
Great to know. Thanks @popup-user.

**Comment by CaioBianchi** [comment]
Shouldn't `jsonb` be _(tongue-twister here..)_  the default?
Perhaps a little note should be added to the README file?

**Comment by oshanz** [comment]
@CaioBianchi I thought array is the most suitable data structure and it perform better.
