### ISSUE TITLE
[Feature] Carrierwave Remote URL basic auth & proxy

### ISSUE THREAD

**Issue by wraithseeker** [carrierwaveuploader/carrierwave#1786]
Is it possible for us to customize the params open-uri takes in such a way that a proxy / basic auth can be used for Carrierwave Remote URL? I can't find any methods to do this in the wiki.

**Comment by thomasfedb** [comment]
Hi @wraithseeker, I'd be very happy to look at a pull request that provides this functionality, although I can't promise that we'd decide to include this in Carrierwave. Carrierwave isn't really a downloading tool.

Perhaps it would be easier to download the file with `Net::HTTP` and then let Carrierwave handle the storage.
