### ISSUE TITLE
Multiple files: Array of filenames instead of single filename in path string

### ISSUE THREAD

**Issue by maikokuppe** [carrierwaveuploader/carrierwave#1789]
I have a setup like this:
```
class User < ActiveRecord::Base
  mount_uploaders :pictures, PictureUploader

  def add_picture_by_url(url)
    urls = self.remote_pictures_urls || []
    self.remote_pictures_urls = urls.push url
  end
end
```
Adding pictures and saving works fine. But calling `user.pictures.first.path` e.g. returns something like
```
/path_to_app/public/images/user/pictures/1/[\"first_pic.png\", \"second_pic.png\"]
```
I see no way to access the file itself (to get an md5 checksum) without too much hacking.
`user.pictures.first.file` has the same problem since it uses the same path.

**Comment by thomasfedb** [comment]
@maikokuppe please explain the whole series of events that leads to the result from `user.pictures.first.path` that you've described.

**Comment by maikokuppe** [comment]
```
u = User.new
u.remote_pictures_urls = ['http://lorempixel.com/400/300', 'http://lorempixel.com/400/200']
u.save!
u.pictures.first.path
  # => path_to_app/public/images/development/user/pictures/105/first.jpeg

u.reload
u.pictures.first.path
  # => path_to_app/public/images/development/user/pictures/105/[\"first.jpeg\", \"second.jpeg\"]

```

**Comment by thomasfedb** [comment]
Where do `"first"` and `"second"` come from @maikokuppe?

**Comment by maikokuppe** [comment]
`u.pictures` is an array. If you use `u.pictures[0].path`, the result will be the same.

**Comment by maikokuppe** [comment]
I updated the filenames in the first post.
In fact I generate random filenames, when a file is fetched; I just wanted to simplify the example a bit.
I tested the updated code and it yields the same result.

**Comment by thomasfedb** [comment]
Okay, thanks @maikokuppe.

**Comment by maikokuppe** [comment]
I forgot to mention that I was using MySQL, which does not support array or json columns, but this is required as mentioned in the readme: https://github.com/carrierwaveuploader/carrierwave#activerecord-1

This is the reason for these serialized arrays within the paths. I switched to PostgreSQL and everything works fine now.

I'm going to close this issue, since the prerequisites (database which supports json or array) are already mentioned in the readme.
