### ISSUE TITLE
Problem issue for multiple upload

### ISSUE THREAD

**Issue by KinSai1975** [carrierwaveuploader/carrierwave#1790]
<b>In my form:</b>
<%= form_for@service, :html => {:multipart => true} do |f| %>
<%= f.file_field :photo, :mutiple => true, name: "service[photo][]" %>
<% end %>

<b>in my model:</b>
mount_uploaders :photos, PhotoUploader

<b>answer from server:</b>

ActionDispatch::Http::UploadedFile:0x007fd2584c2278 @tempfile=#
Tempfile:/tmp/RackMultipart20151203-5746-18g2zwr.jpg, @original_filename="brico.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"service[photo][]\"; filename=\"brico.jpg\"\r\nContent-Type: image/jpeg\r\n">]
</code>

**Comment by thomasfedb** [comment]
@KinSai1975 this is not sufficient information to determine what issue you are experiencing. We need you to explain (in words) what is the behaviour you're expecting, how the actual behaviour different, and what you've tried to investigate the issue.
