### ISSUE TITLE
custom filename with fog storage uploads the file with its original name

### ISSUE THREAD

**Issue by ariera** [carrierwaveuploader/carrierwave#1792]
I am having a problem when overriding the default `filename` method and using fog as a storage.

Whenever I add a file it is being uploaded to S3 with its original name, but in the database the new name is stored.

This is how my uploaded looks like:

```ruby
class ActivityImageUploader < FogUploader
  before :cache, :reset_secure_token

  def filename
    "#{secure_token}.#{file.extension}" if original_filename.present?
  end

  protected
  def secure_token
    column = :"#{mounted_as}_secure_token"
    model.send(column) || model.send("#{column}=", SecureRandom.uuid)
  end

  def reset_secure_token(file)
    column = :"#{mounted_as}_secure_token"
    model.send("#{column}=", nil)
  end
end
```

and FogUploader looks like this:

```ruby
# encoding: utf-8

class FogUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  include CarrierWave::Meta
  process :store_meta => [{md5sum: true}]

  # on tests get those fogging images into our file system.
  if Rails.env.test?
    storage :file
  else
    storage :fog
  end

  def self.fog_public
    true # or false
  end

  def store_dir
    "#{model.class.to_s.underscore}/#{model.id}"
  end

  # Check process options at http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/RMagick#resize_and_pad-instance_method
  version :medium do
    process resize_to_fit: [400, 400]
    process quality: 80
  end

  version :limit_50 do
    process resize_to_limit: [50, 50]
    process quality: 80
  end
 
  # and 14 more versions defined that i'll omit 

  def extension_white_list
    %w(jpg jpeg gif png)
  end
end

```

This is what can be found in my Gemfile.lock regarding carrierwave:

```
GIT
  remote: https://github.com/carrierwaveuploader/carrierwave.git
  revision: e3acabb512cb55b683b6d74a63db0723f06df091
  specs:
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
```

Am i doing something wrong?

Thank you very much :)

**Comment by ariera** [comment]
hey @thomasfedb, sorry to bother you, do you have an idea on what's going on?
is there something obviously wrong here? it looks to me that it should work, i'm a bit lost :-o

thanks a lot :)

**Comment by thomasfedb** [comment]
Hi @ariera, it does look like something has going wrong.

Could you try to work this into a minimal reproduction, then perhaps somebody will be able to investigate.

**Comment by ariera** [comment]
That was a good idea, thanks @thomasfedb.
After playing a bit and reducing it to the minimal I was able to pin point the culprit to this line:

`process :store_meta => [{md5sum: true}]`

But interestingly the problem is calculating the md5, not the rest of the metadata.
If i call the processor this way:

`process :store_meta`

everything will work as expected

**Comment by thomasfedb** [comment]
@ariera I have noticed that people tend to have problems when attempting this sort of thing. Perhaps use an `ActiveSupport::Concern` instead. For example:

```ruby
module FogUploader
  extend ActiveSupport::Concern

  included do
    if Rails.env.test?
      storage :file
    else
      storage :fog
    end
  end
```

```ruby
class WidgetUploader
  include FogUploader

  # ...
end
```
