### ISSUE TITLE
Difference between .url and _url?

### ISSUE THREAD

**Issue by maximski** [carrierwaveuploader/carrierwave#1793]
What is the difference between the following two codes:

```
image_tag avatar_url
image_tag avatar.url
```

**Comment by thomasfedb** [comment]
Hi @maximski 

As we can see [in mount.rb](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/mount.rb#L151), the `_url` variant is simply a convenience method which should produce an identical result.

```ruby
def #{column}_url(*args)
  #{column}.url(*args)
end
```

**Comment by maximski** [comment]
Alright, thanks!
