### ISSUE TITLE
Question: limits to the number of uploaded files with multiple file upload

### ISSUE THREAD

**Issue by nathanpop** [carrierwaveuploader/carrierwave#1798]
I see that there is a way on the backend to validate the _dimensions_ of files uploaded, but I wonder if  
using the multiple file uploader, is there a straightforward way to limit the _number_ of allowed uploaded files to e.g: 3?

Thank you!

**Comment by thomasfedb** [comment]
I'd do this in your model rather than in your uploader.

```ruby
def check_max_files
  if files.size > 3
    errors.add(:files, "must not contain more than 3 files")
  end
end
```

**Comment by nathanpop** [comment]
Cool. thx!
