### ISSUE TITLE
Having two mount_uploader micro methods in a model

### ISSUE THREAD

**Issue by megablend** [carrierwaveuploader/carrierwave#1799]
Hi Guys,
is there a way this can be achieved with a single model attribute?

mount_uploader :file_name, TemporaryEpubFileUploader, if: :is_epub_file 
mount_uploader :file_name, ProductsImagesUploader, if: :is_cover_image

**Comment by thomasfedb** [comment]
@megablend if it can be achieved it is certainly not supported. Perhaps try StackOverflow.
