### ISSUE TITLE
Calculating MD5 of large uploaded files

### ISSUE THREAD

**Issue by sintro** [carrierwaveuploader/carrierwave#1800]
How can I calculate the MD5 hash of large (may be, 1 GB and more) files, when I uploading it using CarrierWave? I think, one should use some optimized algorithm (may be, calculate the hash of only the small part of original file), or move the calculation to background process (using Sidekiq or another gem). And what if I uploading the file to cloud service (S3, for example), and does not keep local copy? It seems to be a problem. Did anybody already solve similar problems, or I should not worry about the performance of MD5 hash calculating?

**Comment by thomasfedb** [comment]
This question would be better off on StackOverflow, it's not an issue. In any case, sounds like premature optimisation.
