### ISSUE TITLE
remove checkbox in nested form does not work without also editing additional attribute

### ISSUE THREAD

**Issue by edatrix** [carrierwaveuploader/carrierwave#1801]
related to #1673, attachments in nested forms aren't removed unless another attribute is also edited.

bug reproduced [here](https://github.com/edatrix/carrierwave-nested-form-issue) using version 0.10.0

**Comment by thomasfedb** [comment]
Hi @edatrix, can you please let me know:

1. Does setting the remove attribute affect the model's `changed?` value?
2. Does it affect the `attr_changed?` value, where `attr` is the uploader mount point.

**Comment by edatrix** [comment]
hi @thomasfedb,

checking the box does not affect either the `changed?` value of the parent (Elf) or `image_changed?` of the child (Toy).  i checked by going through the console and inspecting after i'd committed my changes to the form.

**Comment by thomasfedb** [comment]
Right, that confirms my suspicions. @edatrix Could you include your controller and model code in the issue please.

**Comment by edatrix** [comment]
```class ElvesController < ApplicationController
  before_action :find_elf, :only => [:show, :edit, :update, :destroy]

  def index
    @elves = Elf.all
  end

  def new
    @elf = Elf.new
    @elf.toys.build
  end

  def create
    @elf = Elf.new(elf_params)

    respond_to do |format|
      if @elf.save
        format.html { redirect_to elves_path, :notice => "#{@elf.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @elf.update(elf_params)
        format.html { redirect_to elves_path, :notice => "#{@elf.name} was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @elf.destroy
  end

  private

  def find_elf
    @elf = Elf.find(params[:id])
  end

  def elf_params
    params.require(:elf).permit([:name, :toys_attributes => [:id, :name, :image, :remove_image, :_destroy]])
  end

end```

```class Elf < ActiveRecord::Base
  has_many :toys
  accepts_nested_attributes_for :toys, :reject_if => :all_blank, :allow_destroy => true
end```

```class Toy < ActiveRecord::Base
  belongs_to :elf

  mount_uploader :image, ImageUploader
end```

**Comment by thomasfedb** [comment]
@edatrix Is all that controller code required to reproduce the issue? Seems like a lot.

**Comment by edatrix** [comment]
@thomasfedb i'm not sure what you're asking.  yes, new/create and edit/update are required to reproduce the issue since the issue occurs when editing (trying to remove an attachment).

you can see the entire reproduction [here](https://github.com/edatrix/carrierwave-nested-form-issue).

**Comment by thomasfedb** [comment]
Hi @edatrix,

Would this not be a simpler `update` method that still reproduces the issue?

```ruby
def update
  if @elf.update(elf_params)
    redirect_to elves_path
  else
    render :edit
  end
end
```

Also, if you're going to provide an application as a replication, please provide a very clear list of exact steps required to induce the issues and the expected and actual result of those steps in the `README`.

**Comment by edatrix** [comment]
ah, right on both counts @thomasfedb.  i've updated the README with clearer instructions.  hope that this helps!

**Comment by thomasfedb** [comment]
Thanks @edatrix, that's much more helpful now.

**Comment by RomanKapitonov** [comment]
This one is still reproduced. Just got into the same situation. Any thought or workarounds?

**Comment by RomanKapitonov** [comment]
All right, i've looked through the commit history in master. This one is already fixed by https://github.com/carrierwaveuploader/carrierwave/commit/76e00a08e0eff059b13182ac478c0c4cc0d8fac9

The issue may be closed. 
@edatrix, you may use the master branch with the corresponding ref.
