### ISSUE TITLE
Fog generates wrong url with AWS-S3

### ISSUE THREAD

**Issue by mrudult** [carrierwaveuploader/carrierwave#1802]
Gemfile:

``` ruby
gem 'carrierwave'
gem 'fog', require: 'fog/aws'
```

Carrierwave Initializer:

``` ruby
config.fog_credentials = {
 :region                => 'ap-southeast-1'
}
config.fog_public       = true
config.fog_directory    = 'my-bucket'
```

I'm able to upload the files to s3 properly but when I call `model.asset.url` I get

```
https://my-bucket.s3.amazonaws.com/file.png
```

But my s3 console shows the public link as:

```
https://s3-ap-southeast-1.amazonaws.com/my-bucket/file.png
```

What am i doing wrong? How to fix this?
##### Update:

Manually putting the url in the browser gives:

``` xml
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>somestring</RequestId><HostId>somerandomstring=</HostId></Error>
```
##### Update:

On further investigation it looks like the url should be:

```
https://my-bucket.s3-endpoint-here.amazonaws.com/file.png
```

**Comment by srozen** [comment]
I was experiencing the same problem but I noticed that, when you open the file directly in your AWS bucket, the url looks like this : `https://s3-eu-west-1.amazonaws.com/mybucket/dir/image.png`   

So my solution was to edit my endpoint in credentials configuration which was `:endpoint => 'http://s3.amazonaws.com'` to `:endpoint => 'http://s3-eu-west-1.amazonaws.com'`.

Works fine now!
