### ISSUE TITLE
Fix 0.10-stable build

### ISSUE THREAD

**Issue by thomasfedb** [carrierwaveuploader/carrierwave#1822]
As the master branch is now targetting 1.0.0, and a large number of applications use CarrierWave 0.10.0, we should ensure that the `0.10-stable` branch builds successfully so that we have a basis for any future fixes required in the 0.10.x series.

**Comment by thomasfedb** [comment]
For some context, CarrierWave 0.10.0 has had 2,205,941 downloads from RubyGems.org.

**Comment by mehlah** [comment]
This could be closed ;-)

**Comment by thomasfedb** [comment]
Very true!
