### ISSUE TITLE
Remove locales from the main repository

### ISSUE THREAD

**Issue by mehlah** [carrierwaveuploader/carrierwave#1823]
I'm suggesting to extract locales to another repo (`carrierwave-i18n` I guess) and make it an optional dependency.
The current locales are hard to maintain and some are outdated as soon as a new feature that might needs locales is introduced.
This is a first step in splitting some parts of the codebase into other projects for easier contributions and releases.
I'd be happy to tackle it if it sounds good to you.

**Comment by thomasfedb** [comment]
I'm a little wary of this, for a few reasons:

1. Localisations feel, to me, to be fairly strongly tied to the code that makes use of them. How exactly do you intend to separate them?
2. What will be the result when `carrierwave` is installed without `carrierwave-i18n`?

**Comment by mehlah** [comment]
We'd maintain only `en` locales in the main repo, and all the translations moved to a separate project with separate (and faster specs), easier contributions and an independent release cycle.
We could also add tests for consistency across translations (currently broken).

Users of `carrierwave` who might need additional locales could either add `carrierwave-i18n` gem or simply copy/paste the needed locales to their applications.

**Comment by thomasfedb** [comment]
> We'd maintain only en locales in the main repo

Right, that makes more sense now.

> We could also add tests for consistency across translations (currently broken).

Does this include consistency with the `en` locale in the `carrierwave` repo?

**Comment by mehlah** [comment]
A work in progress https://github.com/craftsmen/carrierwave-i18n and https://github.com/carrierwaveuploader/carrierwave/commit/4d89e8a5bb412995385816a584bc5b36e6a6acaa

**Comment by thomasfedb** [comment]
How're you going with this @mehlah? Also, @bensie, what do you think of this idea, and would you have access to bring the new repo over the the @carrierwaveuploader GitHub org?

**Comment by mehlah** [comment]
@thomasfedb I have to update a couple of specs in the main repo that were relying on some locales, then it should be ready for a review.
I'll build a demo app running it and update docs later if it's all good for you.
I'd be happy ofc to transfer the repo to @carrierwaveuploader org.

**Comment by mshibuya** [comment]
Closed by #1848.
