### ISSUE TITLE
Code style inconsistencies

### ISSUE THREAD

**Issue by mehlah** [carrierwaveuploader/carrierwave#1826]
CarrierWave code got a lot of style inconsistencies (quotes styles, line breaks, line max lengths, indentations, use of `and` and `or` without a valid reason...)
I think the project quality will benefit from linting the code based on a documented code style guide for contributors.
The ideal scenario is to automate this thanks to Rubocop and even better, to [Hound](https://houndci.com/) (based on Rubocop).
PRs would be automatically reviewed against the shared style guide.
I can take care of documenting this and setting up the rubocop.yml (or hound.yml with our set of rules).
We shouldn't commit a huge cleanup to the code base in one pass to avoid breaking up blames, but from now, pushing (and fixing in passing) a consistent code (I tended to do this in my recent PRs).

Thoughts?

**Comment by thomasfedb** [comment]
I'd be happy to give Hound a shot. My only concern is to avoid putting people off contributing to the project.

**Comment by thomasfedb** [comment]
@bensie what do you think?

**Comment by mehlah** [comment]
> My only concern is to avoid putting people off contributing to the project.

Precisely, I think getting an automated and quick code style review would make contributions easier to accept/decline. The improved code quality and consistency will make it easier for someone unfamiliar with CW code to dig it in the future.
If we find Hound is too invasive, we could disable it and only let core contributors to use Rubocop in their machines with shared rules in rubocop.yml configuration file.

**Comment by bensie** [comment]
:-1: to Hound, but I'm open to a rubocop.yml file to encourage consistency. PRs should not be rejected based on these style issues though.

**Comment by thomasfedb** [comment]
It does look like hound is fairly invasive. Let's go with putting together a rubocop.yml.

**Comment by plribeiro3000** [comment]
:+1: to try hound

Em sex, 8 de jan de 2016 21:58, Thomas Drake-Brockman <
notifications@github.com> escreveu:
