### ISSUE TITLE
Set fog_authenticated_url_expiration

### ISSUE THREAD

**Issue by mbajur** [carrierwaveuploader/carrierwave#1836]
Hello everyone.

I was curious - is that possible to temporay overwrite default `fog_authenticated_url_expiration` on `model.uploader_column.url()` level? I want to use a default expiration time everywhere in my app but also be able to set longer expiration times for images displayed in mails (cause sometimes mail arrives or is opened a way longer than after 10 minutes and that causes the images being broken). 

I would imagine it more or less like that: `model.photo.url(:medium, fog_authenticated_url_expiration: 6000)`

Thanks in advance!

**Comment by thomasfedb** [comment]
Hi @mbajur, that functionality is not currently supported, although it could be implemented in `CarrierWave::Storage::Fog#authenticated_url`. If you'd like to provide a pull request with such an implementation, I'd be happy to look over it.

**Comment by FantasticJimmy** [comment]
Have this been implemented since 2016?

**Comment by blombard** [comment]
For the internet people, yes it has been implemented here: https://github.com/carrierwaveuploader/carrierwave/pull/2397

https://github.com/carrierwaveuploader/carrierwave/blob/0a6ffe1311bf3ed82967168370760e16ac93cce1/lib/carrierwave/storage/fog.rb#L205
