### ISSUE TITLE
Raising ProcessingError on version processing adds error message twice to record

### ISSUE THREAD

**Issue by sarithats** [carrierwaveuploader/carrierwave#1839]
Reference:  #1306
Version 0.10
https://github.com/carrierwaveuploader/carrierwave/blob/0.10-stable/lib/carrierwave/processing/mini_magick.rb#L273

Raises error messages twice on the record.

To reproduce, rename a non-image to jpg extension and try process.

**Comment by thomasfedb** [comment]
Can you please include a full reproducible example in your issue report.

**Comment by sarithats** [comment]
sorry for the false positive. Was mounting uploader in my super class as well.
Closing issue.
