### ISSUE TITLE
Carrierwave with Rmagick not cropping large size image

### ISSUE THREAD

**Issue by Ashviniv** [carrierwaveuploader/carrierwave#1840]
I am trying to upload profile picture for user. For that I used ```process : cropper``` which is 
```
def cropper
    if model.crop_x.present?
      resize_to_fill(400, 400)
      manipulate! do |img|
        img = img.crop(model.crop_x.to_i, model.crop_y.to_i,model.crop_w.to_i, model.crop_h.to_i)
        img = yield(img) if block_given?
        img
      end
    end 
  end
```
If I upload large size image e.g: 86kb image it is cropping wrong portion of image.It cuts some upper part of image.

**Comment by thomasfedb** [comment]
Hi @Ashviniv, this is not a suitable minimal reproduction, as it depends on details contained on your model. Unless you can provide a minimal reproduction, with example input, the resulting output, and the expected output then we will not be able to look at your issue.

I'm closing this issue until you have provided the above.
