### ISSUE TITLE
Content Type is lost when using model instance

### ISSUE THREAD

**Issue by rsiddle** [carrierwaveuploader/carrierwave#1841]
I'm uploading a video MP4 file and by default it's returning the content_type as "application/mp4" instead of "video/mp4".

At the point below within the uploader, the pry statement is showing the correct content_type

```
process :set_content_type

  def set_content_type(*args)
    content_type = file.content_type == 'application/octet-stream' || file.content_type.blank? ? MIME::Types.type_for(original_filename).first : file.content_type

    self.file.instance_variable_set(:@content_type, content_type)
    binding.pry
  end
```

Here is the output at this point
`
pry(#<AttachmentUploader>)> self.file.content_type
=> "video/mp4"
`

in my upload.rb file, I use

```
attachment.content_type
```

The result is 

```
pry(#<Upload>)> attachment.content_type
=> "application/mp4"
```

I can't figure out why CarrierWave is changing the content_type

**Comment by mehlah** [comment]
Thanks @rsiddle for the report.
Which version of CW are you using?

**Comment by dsandstrom** [comment]
This happens with 1.0.0.beta

**Comment by olegantonyan** [comment]
This bug appeared to me after update to 1.0.0

**Comment by ngoral** [comment]
1.2.2 is also affected

**Comment by mshibuya** [comment]
#2117 should work, please provide detail if you're still having this issue.
