### ISSUE TITLE
How to access carrierwave object (or convert to one) when using SQL SELECT statement?

### ISSUE THREAD

**Issue by mrudult** [carrierwaveuploader/carrierwave#1843]
User Model:
```
class User < ActiveRecord::Base
  has_many :avatars
end

class Avatar < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, AvatarUploader
end
```
The image is being uploaded properly to the specified storage. I'm also able to access the urls by calling something like - `Avatar.first.image_url`

The example above is just simple case. But you know, when you have complex query, we need to join many tables. In that case, we need way to get url(s)/versions(s) from raw sql, i.e we need to select the `image` column manually. But by doing so, the `image` column only has the image file name. Is there a way to convert the raw data (like id, file_name, etc) into carrierwave object?

A simple example of the query looks something like this:
```
User.joins(:avatars).select("users.name, users.email, avatars.image")
```

**Comment by thomasfedb** [comment]
Hi @mrudult , you haven't provided enough information in order for us to be ale to work out a) what you're trying to do, b) how you're trying to do it, or c) why it isn't working.

You should provide the relevant code from your model and uploader, as well as an interactice console session demonstrating what you're attempted.

I'm closing this issue until you can update with sufficient details.

**Comment by mrudult** [comment]
@thomasfedb Please check now. Have updated the issue details.

**Comment by thomasfedb** [comment]
Have you tried anything yet @mrudult?

Perhaps something like:

```ruby
User.joins(:avatars).select("users.name, users.email, avatars.image").avatars.map(&:image)
```

**Comment by mrudult** [comment]
@thomasfedb Yup. The above query return the `image` name and not the image (carrierwave) object.
Bet'n the above query should be:
```
User.joins(:avatars).select("users.name, users.email, avatars.image").each { |u| u.avatars.map(&:image) }
```
This has been asked on [SO](http://stackoverflow.com/a/19659911/1552570) as well.

**Comment by thomasfedb** [comment]
@mrudult the only supported method to access a CarrierWave file object is through a model with a mounted uploader.

**Comment by evanjmg** [comment]
If I have an image object that belongs to my place and I have a list of places that I want there images for. Is there a way to join  and load :images with my request? Or does the mounted uploader restrict that? 
Right now I have to load each set of image urls separately, adding 3 seconds to my request.

**Comment by mrudult** [comment]
@evanjmg I had (have) the same issue. That's why I created this issue at first place. Not able to call the `image` object directly when we do `joins` or `includes`. So I make two calls. For example, in your case it would be something like:

In controller:
```
 @places = Place.all
 @place_images = PlaceImages.group_by(&:place_id) # Assuming place_id is foreign_key to places table
```
In view (this assumes jbuilder):
```
json.place @places.each do |place|
  json.name place.name
  json.set! :images do
    @place_images[place.id].each do |place_image|
      place_image.image.versions.each do |k,v|
        json.set! k,v.url
      end
    end
  end
end
```
This way you make two database calls. Basically what I'm doing is, `grouping` the `place_images` by the foreign_key `place_id` and the accessing this resulting `Hash` by key, which is `place.id` in the view.

This is just a workaround. I'd still like to see this issue being resolved.

**Comment by anle1337** [comment]
hi, i couldn't find any answer to this. Is acccess to carrier wave image urls of different sizes not possible via raw sql?
