### ISSUE TITLE
SanitizedFile#rewind error when calling recreate_versions!

### ISSUE THREAD

**Issue by quidquid** [carrierwaveuploader/carrierwave#1845]
Hey there, I ran into a glitch using recent versions of both the master branch and 0.10-stable under a Rails 3.2 app. This had been stable for over a year, but updating the gem seems to have caused issues. Rewinding to commit a1b96d05d021f0ab53c8a2ef460bc96664e52b79 from last summer fixed it, so I'm fine staying on that version.

```
Error message
----------------
undefined method `rewind' for #<CarrierWave::SanitizedFile:0x0000000aa62598>

Trace
----------------
/usr/local/rvm/gems/ruby-2.0.0-p247@wdwot32/gems/activesupport-3.2.21/lib/active_support/core_ext/object/try.rb:36:in `try'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/sanitized_file.rb:165:in `read'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/sanitized_file.rb:221:in `block in copy_to'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/sanitized_file.rb:221:in `open'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/sanitized_file.rb:221:in `copy_to'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/uploader/cache.rb:134:in `cache!'
/var/web/loveland_prod/vendor/gems/carrierwave/lib/carrierwave/uploader/versions.rb:227:in `recreate_versions!'
/var/web/loveland_prod/lib/photos/edit.rb:15:in `rotate'
```

The uploader's simple enough, using Fog on AWS. Below are the essentials including my rotate processing function and a filename function, which has the effect, when you rotate, of assigning a new filename. When it started breaking, I'd get a new filename saved on AWS (as desired) but not rotated and the smaller versions never created.

``` ruby
class BlextCloudUploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick
  storage :fog

  def rotate(cw)
    manipulate! do |img|
      img.rotate!(cw)
      img
    end
  end

  def filename
    if original_filename.present?
      "#{secure_token}.#{file.extension}"
    end
  end
end
```

Immediate steps preceding the error (`ph` is the uploader above):

``` ruby
ph.rotate(angle)
ph.store!
ph.recreate_versions!  # exception happens here
```

**Comment by mshibuya** [comment]
#1812 + Rails 3 causes this issue. We've dropped support even for Rails 4, this can be closed.
