### ISSUE TITLE
Setting filename (without overriding)

### ISSUE THREAD

**Issue by chadwtaylor** [carrierwaveuploader/carrierwave#1846]
```ruby
tempfile = filedata.tempfile # ActionDispatch::Http::UploadedFile
uploader = AttachmentUploader.new
uploader.store!(tempfile)
```

The problem with the above is that it will store the temp's filename instead of the original filename. When using Tempfile, how can I preserve the original filename (eg: `filedata.original_filename`). 

Disclaimer: I'm not using ActiveRecord.

Any tips greatly appreciated.

**Comment by chadwtaylor** [comment]
I think I got it covered but would appreciate feedback:

```ruby
class AttachmentUploader < CarrierWave::Uploader::Base

  storage :fog

  def initialize(options={})
    @custom_filename = options[:filename] if options[:filename].present?
  end

  def filename
    @custom_filename
  end

end
```

```ruby
class AttachmentsController < ApplicationController

  def create
    uploader = AttachmentUploader.new(filename:"your-custom-filename.jpg")
    filedata = params[:files].first # {files:[ActionDispatch::Http::UploadedFile]}
    uploader.store!(filedata.tempfile)
  end

end
```

**Comment by mehlah** [comment]
@chadwtaylor what would happen if you don't provide a `filename` when initializing an uploader?

I guess you could either do some kind of fallback to the `original_filename` if `options[:filename]` is blank, or make the `filename` argument a required one with
```ruby
def initialize(filename:)
  @custom_filename = filename
end
```
Otherwise it looks good to me.

**Comment by mshibuya** [comment]
Seems to be resolved.
