### ISSUE TITLE
Using SimpleForm and `use :maxlength`, a textarea for an image uploader has maxlength of 255

### ISSUE THREAD

**Issue by jmuheim** [carrierwaveuploader/carrierwave#1851]
I'm using SimpleForm, and I just activated `use :maxlength` so it calculates the maxlength for input elements according to their length validations:

```ruby
# Use this setup block to configure all options available in SimpleForm.
SimpleForm.setup do |config|
    # Calculates maxlength from length validations for string inputs
    b.use :maxlength
    ...
```

I also use [carrierwave-base64](https://github.com/lebedev-yury/carrierwave-base64) to send an image as base64 string to the server using a textarea:

```slim
= f.input :screenshot, as: :text
```

Interestingly, this textarea now has a maxlength of 255:

![image](https://cloud.githubusercontent.com/assets/1814983/12618817/db6d327c-c515-11e5-8744-7db81521ee03.png)

I didn't find any way around this except setting it manually to -1 (even setting it to `nil` didn't remove the `maxlength` attribute), which definitely isn't valid HTML:

```slim
= f.input :screenshot, as: :text, maxlength: -1
```

I'm wondering now, where the problem lies: is it carrierwave? Is it SimpleForm? By the way, it doesn't seem to be a carrierwave-base64 problem, as the maxlength is always set to 255, whether I use a default carrierwave uploader or a carrierwave-base64 uploader.

**Comment by thomasfedb** [comment]
Looks to be a SimpleForm issue @jmuheim. May be that SimpleForm is using the width of the underlying string column to calculate the `maxlength`.
