### ISSUE TITLE
"param is missing or the value is empty: ticket" Rails 5.0

### ISSUE THREAD

**Issue by adavia** [carrierwaveuploader/carrierwave#1854]
I am getting this error every time i submit an empty form with a file field. It wont happen if i remove the file field. A workaround should probably be doing something like  params.fetch(:ticket, {}).permit(:name, :photo)

Is this an issue with rails 5.0?

**Comment by thomasfedb** [comment]
@adavia please provide the complete log entry for the request, and the view code.

**Comment by hail2skins** [comment]
I also have the same issue.   In my case I have an Article model where I have validations on name and content.   This works fine when I leave both as blank.   But, when I add the file_field and Carrierwave, if I leave name and content blank AND leave the file blank, I get the error described here for create and update.

I'll actually try fetch, but I had to write a nil check to get it to work.   My controller is now:

```ruby
    if params[:article].nil?
      params[:article][:name] = nil
      @article = @business.articles.build(params[:name])
    else
      @article = @business.articles.build(article_params)
    end
```

**Comment by hail2skins** [comment]
I changed to fetch and it works too, but it doesn't with require.

**Comment by mshibuya** [comment]
This issue is about use of StrongParameters, not related to CarrierWave.
