### ISSUE TITLE
Store different versions with the exact same filename but in different directories

### ISSUE THREAD

**Issue by Silex** [carrierwaveuploader/carrierwave#1861]
Hello

I'm using carrierwave from master.

It looks like we cannot have the exact same filename for different versions.

If I upload a file, say "hello.jpg" and the associated model has id 123, I want it to be saved that way on the disk (the model.id is irrelevant here, it can be anything as long as it results in the exact same filename):

```
/data/original/123.jpg
/data/version1/123.jpg
/data/version2/123.jpg
```

Here is what I tried:

``` ruby
class MyUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :file

  def store_dir
    "/data/#{version_name || 'original'}"
  end

  def filename
    "#{model.id}.jpeg" if original_filename.present?
  end

  version :version1 do
    def full_filename(for_file)
      for_file
    end
  end

  version :version2 do
    def full_filename(for_file)
      for_file
    end
  end
end
```

It fails when creating the versions because I guess it deletes the same cache file twice (it works if I let the filename be different, with the version1_ or version2_ being prefixed). 

Also, someone at http://stackoverflow.com/questions/31729932/how-to-customize-version-filename-in-carrierwave seems to have the same problem.

**Comment by Silex** [comment]
I just had an idea, maybe I could have `store_dir` return "/data" and `full_filename` return "version1/123.jpg". The idea is that the changing directory would be part of the filename instead of the store dir.

**Comment by thomasfedb** [comment]
@Silex what's your usecase?

**Comment by Silex** [comment]
@thomasfedb: I store images, I need to store a "medium" version that is 800x600 and a "small" version that is 200x150. I want them to have this layout on the disk:

`"/data/#{version_name || 'original'}/#{model.created_at.to_i}.jpeg"`

That is, have the following files:

```
/data/medium/1454397604.jpeg
/data/medium/1454411423.jpeg
/data/medium/1454412602.jpeg
/data/medium/1454414406.jpeg
/data/medium/1454415600.jpeg
/data/original/1454397604.jpeg
/data/original/1454411423.jpeg
/data/original/1454412602.jpeg
/data/original/1454414406.jpeg
/data/original/1454415600.jpeg
/data/small/1454397604.jpeg
/data/small/1454411423.jpeg
/data/small/1454412602.jpeg
/data/small/1454414406.jpeg
/data/small/1454415600.jpeg
```

**Comment by Silex** [comment]
I just found the hack needed for it to work:

```
class AlbumImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :file

  def store_dir
    "/images/%s" % (version_name || 'original')
  end

  def filename
    "%s.jpeg" % model.created_at.to_i if original_filename.present?
  end

  def full_filename(for_file)
    if model.new_record?
      super(for_file)
    else
      for_file
    end
  end

  version :medium do
    process resize_to_fill: [800, 600]
  end

  version :small, from_version: :medium do
    process resize_to_fill: [200, 150]
  end
end
```

Should I create a new wiki entry with this?

**Comment by thomasfedb** [comment]
We're always interested in new contributions @Silex. Glad you found a solution!

**Comment by Silex** [comment]
@thomasfedb: before I do, can you confirm that in `full_filename`, checking with `cached?` is the appropriate way to know wether you want a filename for the cache or for the store?

**Comment by thomasfedb** [comment]
Hi @Silex, you're going to have to investigate and read through the codebase.

I'm not a long-standing CarrierWave developer, just somebody who volunteered to come on to look after the issues and PRs.
