### ISSUE TITLE
set_content_type broken, need docs/wiki update

### ISSUE THREAD

**Issue by naaano** [carrierwaveuploader/carrierwave#1864]
There have been some improvements and cleanup with mime-types, which is great, but breaks old code, and wiki is still with the old way. 
#1584 for reference.

I know there's mime-types gem and ruby-filemagic but don't know how to replicate set_content_type with them, and update this pages accordingly:
https://github.com/carrierwaveuploader/carrierwave/wiki/Saving-Content-Type
and here: 
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Store-the-uploaded-file-size-and-content-type

thanks

**Comment by thomasfedb** [comment]
@mehlah might know best about this.

**Comment by mehlah** [comment]
Hi @naaano, 
Some Wiki pages might be outdated as those targets 0.10 and the code recently cleaned up is not yet released (probably the upcoming 1.0).

Content type is automatically fetched and available for you.
Here is a small script proving this https://gist.github.com/mehlah/fdea4487cd2cde3caf23

I don't know what exactly you want to achieve, but if you need to store the content type explicitly in the database for whatever reasons, you can do it different ways.
For example, in your uploader class https://gist.github.com/mehlah/9b852d24d44a0af934ad

**Comment by codebycliff** [comment]
@mehlah Is there a way to explicitly set the content type in the case where carrierwave doesn't correctly determine it? The `mime-types` gem can't determine the content type in my situation.

I tried things like:

```
process :force_content_type

def force_content_type
  file.content_type = 'text/css'
  # Also tried...
  file.instance_variable_set(:@content_type, 'text/css')
end
```

**Comment by mshibuya** [comment]
Wiki was already updated.
