### ISSUE TITLE
`CarrierWave::MiniMagick#height` throws Errno::ENOENT error if the application or file path contains a space

### ISSUE THREAD

**Issue by danielevans** [carrierwaveuploader/carrierwave#1872]
The problem appears to be that `#mini_magick_image` prefers `url` over `current_path` and `url` is url encoded, so the path that should be opened is `/Users/gate/work/bug test/tmp/1455065589-53775-0001-1488/_3x/three.jpg` is instead sent to mini_magick as `/Users/gate/work/bug%20test/tmp/1455065589-53775-0001-1488/_3x/three.jpg` causing the exception.

I've created a [branch with a failing spec](https://github.com/danielevans/carrierwave/pull/1)

**Comment by thomasfedb** [comment]
Definitely looks like a bug. Thanks! Would you consider contributing a fix?

**Comment by danielevans** [comment]
I most definitely will, when I have the time and assuming nobody else beats me to it.

**Comment by artemas** [comment]
Tests passed because url is subbed https://github.com/carrierwaveuploader/carrierwave/blob/master/spec/processing/mini_magick_spec.rb#L12

**Comment by danielevans** [comment]
@artemas I haven't had time to do more in-depth testing but I suspect simply using `current_path` will result in errors when the file isn't cached or isn't stored locally. 

I have a spec where I have removed that stub and demonstrate the issue. https://github.com/danielevans/carrierwave/pull/1/files

**Comment by artemas** [comment]
@danielevans i meant just particular case, when `url` was not empty but did not work, it needs some different condition to choose which value to use

**Comment by danielevans** [comment]
I can no longer recreate this issue myself, it seems to be fixed.
