### ISSUE TITLE
Time for new RubyGems publish?

### ISSUE THREAD

**Issue by kreintjes** [carrierwaveuploader/carrierwave#1874]
Could you publish a new release of this gem on RubyGems? There hasn't been a new release in two years. The 0.10.0-stable branch fixes an RMagick deprecation warning, but unfortunately is not officially released yet.

**Comment by thomasfedb** [comment]
Please see #1875.

**Comment by thomasfedb** [comment]
Also, please note @kreintjes that we're always happy to look over PRs if you'd like to contribute.

**Comment by kreintjes** [comment]
@thomasfedb I didn't know you were waiting for the changelog to be updated. I just created a PR (https://github.com/carrierwaveuploader/carrierwave/pull/1883) which should bring the changelog up to date! Please let me know what you think.
