### ISSUE TITLE
image saved to root but not to DB

### ISSUE THREAD

**Issue by bodaonline** [carrierwaveuploader/carrierwave#1877]
Hi All,

**EDIT 15th FEBR 16:53 GMT+1** : Reinstalled the gem and I used only Picture for the name now, not EventPicture. Still no luck.

this is my 2nd CW install. First went smoothly. But this... have been trying to get it working for 4 hrs now :(
The form saves without error and the file gets saved in my app's root (not in public/uploads as per defined). In the server log I see this POST / PATCH:
`"picture"=>""` And that makes me very sad :)

If I put validates presence true in the event model I get error displayed which says "picture not provided" despite the fact that I selected image.

Hope someone can nail this. Thanks in advance!

ruby '2.1.4' 

Rails 4.2.5 

Development web server PUMA, 

CarrierWave (0.10.0) 

sqlite3 (1.3.9)

development environment: C9 IDE

gems:
```
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
```

schema.rb
    `t.string   "picture"`

event.rb
```
mount_uploader :picture, PictureUploader
....
  def picture_size
    if picture.size > 2.megabytes
      errors.add(:picture, "#{t 'event.maxpicsize'}")
    end
  end  
....
```
uploaders/picture_uploader.rb

```
class PictureUploader < CarrierWave::Uploader::Base
  
  process resize_to_limit: [1024, 576]
  include CarrierWave::MiniMagick
  
  if Rails.env.production?
    storage :fog
  else
    storage :file
  end

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :thumb do
    process :resize_to_fit => [150, 150]
  end
  
  version :web do
    process :resize_to_fit => [370, 250]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

end
```

events_controller.rb

```
private
    def event_params
      params.require(:event).permit(:title, ......... :picture, .....)
    end
```

_form.html.erb

```
<%= form_for(@event, html: { multipart: true }) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> <%= t 'event.form.errors' %>:</h2>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

    <div class="field" id="uploadpic">
      <%= f.label "#{t 'event.form.picture'}" %> <%= t 'event.form.picmax' %><br>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>

    </div>
....
<% end %>
```

**Comment by thomasfedb** [comment]
Hi @bodaonline, you'll need to provide a minimal reproduction of the issue if we're going to be able to help you. We need the simplest possible mode/uploader/controller/view that is able to demonstrate the problem.

**Comment by bodaonline** [comment]
Hi @thomasfedb 

I hope this is what you asked for: https://bitbucket.org/bodaonline/cw_upload_issue/src
Removed all the sensitive parts/files.

Meanwhile I checked my other app with nearly identical setup (model names differ) in develeopment mode and I see this in the log when uploading:
`"picture"=>#<ActionDispatch::Http::UploadedFile:0x007f0ddfb5c4f0 @tempfile=#<Tempfile:/home/ubuntu/workspace/stuff/RackMultipart20160215-47502-1c1mwtp.png>, @original_filename="ambi2.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"item[picture]\"; filename=\"ambi2.png\"\r\nContent-Type: image/png\r\n">`
Strange enough here again the file landed in the root whereas couple month ago the uploaded pictures were saved in public/uploads/item/picture/1 .. /n

Updated Rails from 4.2.0 to 4.2.5 did not help.
Adding this require 'carrierwave/orm/activerecord' to my environment.rb did not help.

TIA!

**Comment by bodaonline** [comment]
if in my modell 
I use this
`mount_uploader :picture, EventPictureUploader`
instead of this:
`mount_uploader :picture, ::EventPictureUploader`

still the same

**Comment by bodaonline** [comment]
uninstall, reinstall of gem didn't help neither

update of rails from 4.2.0 to 4.2.5 didn't help neither

**Comment by bodaonline** [comment]
one more info: the file that gets saved to the root looks like this: RackMultipart20160215-1427-180hfas.png
which is not similar to files that got saved in my other app in the public folder

**Comment by bodaonline** [comment]
if in my modell 
I use this
`mount_uploader :picture, PictureUploader`
pic gets uploaded

If like this (like in my other app)
`mount_uploader :picture, ::PictureUploader`
pic gets not uploaded
although my other app uses the same 0.10.0 version of CW

**Comment by bodaonline** [comment]
Just created a new app from scratch and there it works... This is driving me nuts.

**Comment by thomasfedb** [comment]
Hi @bodaoline, glad you've got it working in your new app. Doesn't seem to be specifically an issue with CarrierWave. I hope you manage to debug you other app. You'll be best off trying to simplify things in general, rather than making little tweaks here and there.
