### ISSUE TITLE
Google Group is overrun by spam

### ISSUE THREAD

**Issue by walterdavis** [carrierwaveuploader/carrierwave#1880]
Could you switch it to moderated, please? I volunteer to moderate, since it's low (genuine) volume, and I just wasted a half hour this weekend marking 79 messages from the same recruiter as spam. 

Thanks

**Comment by bensie** [comment]
Best I can tell I have no power there, sorry @thomasfedb!

**Comment by thomasfedb** [comment]
Neither do I! @walterdavis you might need to find a group admin.
