### ISSUE TITLE
Providing a default URL for User avatar field

### ISSUE THREAD

**Issue by bobur554396** [carrierwaveuploader/carrierwave#1884]
Hi, I'm using Rails 4 and I cannot set default image to my Users avatar field, which uploads using carrierwave gem. 
I change my default_url method in Uploader class like this.
`ActionController::Base.helpers.asset_path("/" + [1, "default.jpg"].compact.join('_'))`

Can anyone explain where I should save my default.jpg file, in public/ or in assets/images ?

**Comment by thomasfedb** [comment]
Given that you're using the `asset_path` helper it would seem that you should place your imagine in your assets directory.
