### ISSUE TITLE
Overriding filename causes empty Uploader to think file exists

### ISSUE THREAD

**Issue by gabrielrotbart** [carrierwaveuploader/carrierwave#1885]
1. Override filename in uploader (e.g. ImageUploader)

    ```
    def filename
      "call_file_this.png"
    end
    ```

2. POST without selecting an image, which will result in a nil for the ["image"] param.
e.g. Rails:
`params["image"].nil?` #=> true
  
An ImageUploader image with all the correct attributes for a file will be created.

`image.url` will contain "call_this_file.png"
`image.current_path` will contain "call_this_file.png"
etc

However, `image.exists?` will be false and `default_url` will not be called. This will result is rendering broken images.

**Comment by thomasfedb** [comment]
See the following example from the README:

```
def filename
  super.chomp(File.extname(super)) + '.png' if original_filename.present?
end
```
