### ISSUE TITLE
Error 'uninitialized constant CarrierWave::MimeTypes' after gem update

### ISSUE THREAD

**Issue by NadiyaKa** [carrierwaveuploader/carrierwave#1887]
Hi!

I'm using a carrierwave gem 0.10.0 to upload 1 picture to the model. Now I want to be able to attach several pictures so I followed the steps from documentation one of which was to change `gem 'carrierwave', '~> 0.10.0'` to `gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'`.
After that I'm getting such error **uninitialized constant CarrierWave::MimeTypes**. Any ideas on what's going on?

P.S. If I delete `include CarrierWave::MimeTypes` in file_uploader.rb several pictures uploading works just fine

**Comment by jfuentesdelgado** [comment]
I have the same error.

**Comment by NadiyaKa** [comment]
Was solved by removing

`include CarrierWave::MimeTypes
  process :set_content_type`

It is included automatically after update
