### ISSUE TITLE
extension_white_list being ignored

### ISSUE THREAD

**Issue by feroiso** [carrierwaveuploader/carrierwave#1896]
Using `extension_white_list` doesn't seem to filter uploaded file extensions.
Nothing happens when invalid format is uploaded.

**Comment by aried3r** [comment]
I'm facing the same issue. My image uploader accepts `test.mp3` with MIME-type `audio/mpeg` in a controller test, but not when doing the same in the Rails console, starting with carrierwave 0.11.0.

```Ruby
file = Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec', 'fixtures', 'test.mp3'), 'audio/mpeg')
image = message.message_images.build(image: file)
image.save # Fails!
image.errors.full_messages
=> [
  [0] "Image Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `identify /var/folders/_d/g814lpwx12q5ltjkzc_r9m740000gn/T/mini_magick20160412-96095-98tzco.mp3` failed with error:\nidentify: no decode delegate for this image format `MP3' @ error/constitute.c/ReadImage/501.\n"
]
```

Same in RSpec:
```Ruby
let(:message) { FactoryGirl.create :message }
let(:not_an_image) { fixture_file_upload('test.mp3', 'audio/mpeg') }
let(:invalid_params) { message_id: message, message_image: { image: not_an_image } }

it 'returns an error' do
  post :create, invalid_params # This works! But didn't with carrierwave 0.10.0
  # … assertions …
end
```

**Comment by thiagofm** [comment]
Hello,

We have changed the method name. It's in the changelog for the 0.11 version:

https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md
[BREAKING CHANGE] Rename extension_white_list ~> extension_whitelist (@mehlah #1819)

Cheers

**Comment by aried3r** [comment]
I am using the correct method names. :)

After reading [this comment](https://github.com/carrierwaveuploader/carrierwave/issues/1914#issuecomment-205924307) I tried using the master version using `gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'` which makes all tests pass again.

I could not locate the exact change that makes it work again in `master` (0.10.0, [see this](https://github.com/carrierwaveuploader/carrierwave/pull/1917)) and not in the `0.11-stable` branch.

So it seems it has been fixed, but not in the 0.11-stable branch.

**Comment by thiagofm** [comment]
I've seen reports of that change missing, that is right. I need time to roll up a new release to fix that. If you feel up to the adventure, feel free to open a PR in the 0.11 branch.

Cheers.

**Comment by aried3r** [comment]
What exactly is the roadmap here? I just saw the 0.11.0 branch has about 380 fewer commits than the master branch, but was released only a few weeks ago.

I could try to find the necessary commit, but what exactly is going on here? :)

**Comment by thiagofm** [comment]
@aried3r we're working on a 1.0.0 version

**Comment by lebart** [comment]
Hello, 

Any update on this issue? 

I actually use the 0.11.2 version and the whitelist is totally ignored.

**Comment by magnocosta** [comment]
Hello,

I am using Carrierwave 0.11.2 and as @lebart sayed the method "extension_whitelist" is total ignored.
I saw the Carrierewave code and I didn't find error but when I use the old name method ("extension_white_list") is working. 

I think that you have problem on publish new code on RubyGems because when I saw the code downloaded on version 0.11.2 we have this version file:

`def extension_white_list; end`


If you are using version 0.11.2 from Ruby Gem you need use old name "extension_white_list"
Or You can set on Gemfile:

`gem 'carrierwave', :github => 'carrierwaveuploader/carrierwave'`

I think that it

**Comment by lebart** [comment]
@magnocosta Thanks for the tip!

**Comment by magnocosta** [comment]
Now,

I am using version from Master branch and the new name method is working ("extension_whitelist").

`gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'`

On my uploader I did:

`
  def extension_whitelist
    %w(jpg png)
  end
`

It is working for me

**Comment by rodrigohenriques** [comment]
Thanks for the tip @magnocosta! It's now working for me too.

**Comment by daniel-g** [comment]
Shouldn't we close this issue?

**Comment by shuaibzahda** [comment]
extention_white_list did not work for me on production server (centos 6.8) but was working on my local machine.
However, when I changed it to extension_whitelist it worked on my production server.
