### ISSUE TITLE
multiple file upload shows nothing after validation

### ISSUE THREAD

**Issue by nathanpop** [carrierwaveuploader/carrierwave#1897]
I see that it's possible to preserve a file upload when making validations with a single file upload with Carrierwave, but I've tried this with multiple file uploads, and it doesn't seem to work:
https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays

my form:

```
<%= f.file_field :space_photos, multiple: true %>
<%= f.text_field :space_photos_cache %>

```

my model:

```
mount_uploaders :space_photos, LandlordApplicationPhotoUploader
validates_integrity_of :space_photos
```

`attr_accessor :space_photos_cache`

my controller:

```
def form_params
   params.require(:my_form).permit({space_photos: []}, space_photos_cache: [])
end
```

Thank you!

**Comment by linzhewei** [comment]
change 
```
def form_params
   params.require(:my_form).permit({space_photos: [], space_photos_cache: []})
end
```
