### ISSUE TITLE
original_filename is always present and it makes the filename change on every update

### ISSUE THREAD

**Issue by acaron** [carrierwaveuploader/carrierwave#1898]
This piece of code doesn't work anymore:

```
def filename
    "#{secure_token}.#{file.extension}" if original_filename.present?
end
```

`original_filename` is always present so `update_attributes` or `save` makes the file change its name every single time.

It was the solution to this issue: http://stackoverflow.com/questions/22748385/carrierwave-filename-keeps-changing-on-update-attributes

**Comment by abMatGit** [comment]
I'm also getting an issue with this. Also when loading a model via `Model.find ...`, the uploader will recompute the `secure_token` because it picks up the `original_filename`.

**Comment by abMatGit** [comment]
It seems as though the solution is the memoize the full filename instead of just the secure token.

So instead of:
```ruby
class PhotoUploader < CarrierWave::Uploader::Base
  def filename
    "#{secure_token}.#{file.extension}" if original_filename.present?
  end

  protected
  def secure_token
    var = :"@#{mounted_as}_secure_token"
    model.instance_variable_get(var) or model.instance_variable_set(var, SecureRandom.uuid)
  end
end
``` 

You have:
```ruby
class PhotoUploader < CarrierWave::Uploader::Base
  def filename
    secure_filename if original_filename.present?
  end

  protected

  def secure_filename
    var = :"@#{mounted_as}_secure_filename"
    sec_filename = "#{SecureRandom.uuid}.#{file.extension}"
    model.instance_variable_get(var) or model.instance_variable_set(var, sec_filename)
  end
end
```

**Comment by abMatGit** [comment]
Just as an update, the problem for me was memoizing the `secure_token`. Make sure that if you're saving the same instance of an uploader multiple times, the `secure_token` is memoized to prevent it being recalculated.

**Comment by acaron** [comment]
Thanks @abMatGit, I will try that!

**Comment by acaron** [comment]
No, it doesn't work! `original_filename` returns something even if it is not the original name (it returns the last `#{secure_token}.#{file.extension}"` set and it is suppose to be nil).

**Comment by 1v** [comment]
I have same behavior in pure rspec tests, but in capybara tests it working as expected.

**Comment by aleks** [comment]
Any updates on this? We experience the same issue. The secure_token gets shuffled and the reference to the original file is gone once the record is updated.

**Comment by tglocicero** [comment]
Bump

**Comment by mshibuya** [comment]
https://github.com/carrierwaveuploader/carrierwave/commit/f1eff6e212fb0c374c9235968bfc4e7580bf1e2a should have solved this.
