### ISSUE TITLE
Make mount_uploaders work with one_to_many relationships

### ISSUE THREAD

**Issue by thedrow** [carrierwaveuploader/carrierwave#1899]
I have a list of photos that a user has and I'd like to model them as a one to many relationship between the users and the photos.

The user model looks like:
```ruby
class User < ActiveRecord::Base
  mount_uploaders :photos, UserPhotoUploader

  has_many :photos, class_name: "Photo", :foreign_key => "parent_user_id"
end
```

The Photo model looks like this:
```ruby
class Photo < ActiveRecord::Base
  attr_accessible :file_name, :content_type, :file_size, :update_at
end
```
When I assign a file to photos I get:
```ruby
f=File.open('/Users/omer.katz/Pictures/me.jpg')
u.photos=f
NoMethodError: undefined method `photos_will_change!' for #<User:0x007fb666efb838>
from /Users/omer.katz/.rvm/gems/ruby-2.2.0@myapp/gems/activemodel-4.1.13/lib/active_model/attribute_methods.rb:435:in `method_missing'
```
So something is obviously wrong with what I'm doing or that carrierwave doesn't support this kind of usage.

**Comment by mshibuya** [comment]
That can't be done, please read documentation carefully on how to use `mount_uploaders`.
