### ISSUE TITLE
Ruby Toolbox entry for this gem has the old github repo associated with it.

### ISSUE THREAD

**Issue by Yanchek99** [carrierwaveuploader/carrierwave#1901]
Might be nice to get this resolved because when comparing against paperclip it looks as if carrierwave is not active.

Please see https://www.ruby-toolbox.com/projects/carrierwave, I have requested a modification that needs approval https://www.ruby-toolbox.com/projects/carrierwave/modifications.

**Comment by mshibuya** [comment]
Updated by them.
