### ISSUE TITLE
Keep the original filename as it is 

### ISSUE THREAD

**Issue by huzefa-btc** [carrierwaveuploader/carrierwave#1907]
I am using Carrierwave gem and when i download the file, if that file name contains space then it's converted into underscores. So how to remove that underscore from the filename while downloading it ? 
This should not effect a scenario when the user himself has kept an underscore in their filename for some reason.In that case it should not remove it.

**Comment by mshibuya** [comment]
This [sanitization behavior](https://github.com/carrierwaveuploader/carrierwave/blob/85d2111ebf5af5a8a97a925d1c9481957262de7d/lib/carrierwave/sanitized_file.rb#L319) can be configured like:

```ruby
CarrierWave::SanitizedFile.sanitize_regexp = /[^[:word:]\.\-\+\s]/
```

**Comment by alexsmartens** [comment]
In my understanding that's a global change, correct? Is it possible to keep the spaces only for some method calls, say with `CarrierWave::Uploader::Base`?

**Comment by alexsmartens** [comment]
just some thoughts, it seems unintuitive that the `original_filename` is mutated. Probably there're some cases where this is necessary, however it would be nice if there was a way to see the original immutable file name

**Comment by alexsmartens** [comment]
@mshibuya, could you please help to clear things out?
