### ISSUE TITLE
Sessions are not accessible in carrier wave uploader

### ISSUE THREAD

**Issue by vamsipavanmahesh** [carrierwaveuploader/carrierwave#1913]
I want to customize the folder of the upload directory, I waned to give it's name as the users email id. But both current_user and sessions are not accessible in carrierwave uploader. Is there any work around for this

http://stackoverflow.com/questions/36418669/sessions-are-not-accessible-in-carrier-wave-uploader/36418905#36418905

**Comment by mshibuya** [comment]
Already answered in the thread above.
