### ISSUE TITLE
How can I get "convert" the image to my exact given width and height?

### ISSUE THREAD

**Issue by Rubioli** [carrierwaveuploader/carrierwave#1916]
I am using `CarrierWave::RMagick` and has giving my **thumb**, width: 193 and height: 112.
Here is my code:

  ```
version :thumb do
    process :resize_and_pad => [193, 112, background = "#EFF5F7", gravity = ::Magick::CenterGravity]
  end
```

Everything works fine except that often the image gets some blank spaces with background: **#EFF5F7** and I am not happy with that.

How can I make the image to be exact **193x112** with **NO** blank spaces and if **RMagick** needs to cut some parts of the image to get it right, it's okei as long as it's center gravity.

I have also tried these, with same result:
```
process :resize_to_fit => [194, 225]
process :resize_to_limit => [194, 160]
```
Thanks in advanced!

**Comment by mshibuya** [comment]
`:resize_to_fill` will be what you're looking for.
