### ISSUE TITLE
dependencies.rb:274:in `require': No such file to load -- carrierwave/processing/mime_types (LoadError)

### ISSUE THREAD

**Issue by baash05** [carrierwaveuploader/carrierwave#1918]
I get this error when I include the "master" gem

from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/Documents/work/airtasker/app/uploaders/message_attachment_uploader.rb:1:in `<top (required)>'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:526:in `load_missing_constant'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/me/Documents/work/airtasker/app/models/message_asset.rb:17:in `<class:MessageAsset>'
	from /home/me/Documents/work/airtasker/app/models/message_asset.rb:2:in `<top (required)>'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /home/me/.gem/ruby/gems/railties-4.2.6/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/me/.gem/ruby/gems/railties-4.2.6/lib/rails/engine.rb:471:in `each'
	from /home/me/.gem/ruby/gems/railties-4.2.6/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/me/.gem/ruby/gems/railties-4.2.6/lib/rails/engine.rb:469:in `each'
	from /home/me/.gem/ruby/gems/railties-4.2.6/lib/rails/engine.rb:469:in `eager_load!'
	from /home/me/Documents/work/airtasker/spec/rails_helper.rb:7:in `<top (required)>'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/me/Documents/work/airtasker/spec/controllers/api/v2/tasks/related_documents_spec.rb:1:in `<top (required)>'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/me/.gem/ruby/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/me/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/me/.gem/ruby/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by umberto** [comment]
The file has been removed in the master branch: 947eee5bf58051bedec8b63a44aa5d3c53988e16
