### ISSUE TITLE
Support for remote URLs without protocol?

### ISSUE THREAD

**Issue by justinperkins** [carrierwaveuploader/carrierwave#1919]
When specifying a remote URL on an uploader, I'm running into a situation where the protocol portion is left off (for protocol agnostic URLs), and this is throwing an UploadError exception (Unsupported source URL). Would be great if the library could handle the protocol agnostic format, or at the very least, provide a means to prefix a protocol before the string goes into the uploader.

I'm trying to avoid patching my code all over the place when we use remote URLs for creating images.

**Comment by mshibuya** [comment]
I'm not sure of usefulness of this, just prepending protocol on url assignment appears to be enough.
