### ISSUE TITLE
Multiple File Upload using same UUID url for each image

### ISSUE THREAD

**Issue by txssseal** [carrierwaveuploader/carrierwave#1920]
When uploading multiple files I am unable to generate multiple UUIDs for an image.

The UUID's generated do not match the UUID's on aws.  They are completely different.  Below is the code snippet.

``` ruby
class BaseUploader < CarrierWave::Uploader::Base
  storage :aws

  def filename
    @name = "#{SecureRandom.uuid}.#{file.extension}" if original_filename.present?
  end

  def store_dir
    "uploads/#{Rails.env}/#{model.class.to_s.underscore.pluralize}/#{mounted_as}/#{model.id}"
  end

end
```

**Comment by mshibuya** [comment]
See the instruction in Wiki.
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Create-random-and-unique-filenames-for-all-versioned-files#unique-filenames
