### ISSUE TITLE
AuthorizationQueryParametersError error when trying to download from S3

### ISSUE THREAD

**Issue by LimeBlast** [carrierwaveuploader/carrierwave#1923]
I'm using carrierwave to store files in a non-public S3 bucket. The files all upload without issue, but I'm having a problem as soon as I try downloading them via the `.url` link generated by the gem. Here's the error message:

```xml
<Error>
   <Code>AuthorizationQueryParametersError</Code>
   <Message>Error parsing the X-Amz-Credential parameter; a non-empty Access Key (AKID) must be provided in the credential.</Message>
   <RequestId>20416CB751FA681D</RequestId>
   <HostId>9CaqogdryFyrsayr7pn61tZ1C5wgm04Li6m04OlrHKzC04QTOuPnHoEaGwZMKA6ukw1OuXhsBP8=</HostId>
</Error>
```

And an example URL:

    https://s3.amazonaws.com//uploads/batch/zip/1/batch.zip?X-Amz-Expires=600&X-Amz-Date=20160418T152339Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=/20160418//s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=bedca36b929f30c22456e8de97fd28209e39d0c430697c507a8770b82d0f359d

I've tried a whole bunch of different configuration options, and even tried different versions of the `fog` and `carrierwave` gems, but without any joy (at this point in time I'm using carrierwave 0.11 and fog 1.38).

Here's some of my config, if it helps any:

```ruby
  CarrierWave.configure do |config|
    config.fog_credentials = {
        provider:              'AWS',
        aws_access_key_id:     ENV.fetch('S3_KEY'),
        aws_secret_access_key: ENV.fetch('S3_SECRET'),
        region:                ENV.fetch('S3_REGION')
    }
    config.fog_directory   = ENV.fetch('S3_BUCKET_NAME')
    config.fog_public      = false
    config.storage         = :fog
    config.cache_dir       = "#{Rails.root}/tmp/carrierwave"
  end
```

Thank you

**Comment by mshibuya** [comment]
Looks like you're missing region parameter:
https://github.com/fog/fog-aws/blob/562673d3b212a1567b133eae2aed1f449bab3db0/lib/fog/aws/signaturev4.rb#L76

**Comment by LimeBlast** [comment]
Hi, thank you for the reply, I've just started working on this project again, so this is good timing.

Can you expand a little on what you mean, please? I've got an `S3_REGION` set in my `.env` file

```
S3_REGION=eu-west-1
```

and as mentioned, the files are all uploading correctly, so I'm not sure where I'm missing the region from.

Thanks.

**Comment by LimeBlast** [comment]
I've toyed with this issue some more, and it only occurs when using `foreman start` (or `heroku local`) to boot the server. When using `rails s`, or `rails c`, or even `bundle exec puma -p 3000 -C ./config/puma.rb` (which is the `web:` line in my `Procfile`) it works as intended.

**Comment by robwilliams** [comment]
@LimeBlast What happens if you start foreman with `PORT=3000 foreman start` (ensuring that web is the first entry in the Procfile)? I wonder if the port being different from 3000 has something to do with it?

**Comment by LimeBlast** [comment]
No difference.

**Comment by LimeBlast** [comment]
It seems the issue was related to foreman being unable to load the envars from my `.env.local` file. What a weird issue.
