### ISSUE TITLE
version_exists? does not seem to be working

### ISSUE THREAD

**Issue by hmistry** [carrierwaveuploader/carrierwave#1927]
I have an image data model and created 4 different versions of it, small, med, large, xlarge. I've verified the files do exist in S3 and the respective url's do work. However when I query the uploader whether a version exists, it always returns `false`. Is this a bug or is this not reporting whether a version exists?

Using carrier wave v0.11, carrier wave-aws 1.0.0, Rails 5.0.0.beta2, ruby 2.3.
Rails console:

```
 img.file.versions.keys
 => [:xlarge_1, :large_1, :medium_1, :small_1]

img.file.url(:small_1)
 => "https://aaa.s3.amazonaws.com/.../small_1_aaa.jpeg" (image existence verified in browser)

img.file.version_exists?(:small_1)
 => false 

```

**Comment by mshibuya** [comment]
`#version_exists?` takes condition into account, I think that's where this behavior came from.
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L171
