### ISSUE TITLE
Retrieve from (local) cache first?

### ISSUE THREAD

**Issue by hrangel** [carrierwaveuploader/carrierwave#1929]
Hi,

I'm using carrierwave (+ carrierwave-ftp) in a Rails API project that uses devise token auth, but I'm getting ftp (too many connections) errors since everytime a rest API call is made, it loads up the current_user and retrieves the image from the FTP (even tough it won't be used in the response).

I've already contacted the project host providers but I was wondering if there is any way to:
- Skip the automatic retrieval from store when current_user is loaded
- ... or Force carrierwave to try loading file/image first from (local) cache

Any suggestions?

Regards,

Henrique

**Comment by mshibuya** [comment]
Not a built-in way to do so. My recommendation is to move away from ftp and use some sort of an object storage like S3.
