### ISSUE TITLE
ActiveRecord::RecordInvalid - Validation failed: Image could not download file: 404 Not Found:

### ISSUE THREAD

**Issue by saroar** [carrierwaveuploader/carrierwave#1935]
i am trying to download image from another site xml i getting this error when there image link not have image

i got this link 
```
>> redirected_url(URI.extract(URI.encode((product.at_xpath('picture').text.strip)))[0])
=> "http://www.mir-sumok.ru/wa-data/public/shop/products/95/21/52195/images/188841/188841.970.jpg"
```

here is my code 
`Product.create!( remote_image_url: redirected_url(URI.extract(URI.encode((product.at_xpath('picture').text.strip)))[0]))`

after i read internet i add this two method in my carrierwave ImageUploder class 

  # Provide a default URL as a default if there hasn't been a file uploaded:
```
  def default_url
    # For Rails 3.1+ asset pipeline compatibility:
     ActionController::Base.helpers.asset_path("fallback/" + [version_name, "default.png"].compact.join('_'))

    #"/images/fallback/" + [version_name, "default.png"].compact.join('_')
  end

  def process_uri(uri)
    return URI.parse(uri)
  end
```

thanks advance

**Comment by mshibuya** [comment]
So, what's the problem here?
