### ISSUE TITLE
content_type_whitelist on 0.11.x

### ISSUE THREAD

**Issue by tneems** [carrierwaveuploader/carrierwave#1938]
I saw that with the release of [0.11.1](https://github.com/carrierwaveuploader/carrierwave/compare/v0.11.0...v0.11.1) there was a backport for ImageTragick suggesting that `content_type_whitelist` be used to mitigate the vulnerability, but unless I'm losing it I don't believe there is support in 0.11.1 for `content_type_whitelist`, it's only on master.

**Comment by locriani** [comment]
That's correct, it was an oversight on my part. There's a PR currently against the 0.11-stable branch that backports the `content_type_whitelist` that you can use in the interim: https://github.com/carrierwaveuploader/carrierwave/pull/1937

**Comment by thiagofm** [comment]
@tneems I've generated a release for 0.11.2, please update :)
