### ISSUE TITLE
Cannot view image in images for Multiple Images Uploading

### ISSUE THREAD

**Issue by RathanakSreang** [carrierwaveuploader/carrierwave#1943]
I just saw carrierwave have just add new feature about  Multiple Images Uploading and I want to try follow the document. But it did display the image after I create record.

Here what I got after add 4 image.

```ruby
[#<ImageUploader:0x007f94df822618 @model=#<Garllery id: 1, images: "[\"Screen_Shot_2016-05-01_at_8.45.11_PM.png\", \"Scre...", name: "", created_at: "2016-05-08 10:16:55", updated_at: "2016-05-08 10:16:55">, @mounted_as=:images, @storage=#<CarrierWave::Storage::File:0x007f94df822348 @uploader=#<ImageUploader:0x007f94df822618 ...>>, @file=#<CarrierWave::SanitizedFile:0x007f94df821a60 @file="/Users/sreangrathanak/MyRubyonRails/test-uploader/public/uploads/garllery/images/1/[\"Screen_Shot_2016-05-01_at_8.45.11_PM.png\", \"Screen_Shot_2016-05-05_at_9.36.46_PM.png\", \"Screen_Shot_2016-05-05_at_9.41.29_PM.png\"]", @original_filename=nil, @content_type=nil>, @versions={}>]
```

**Comment by fheswara** [comment]
Hi, Have u find any workaround on this? I'm having same experiences

**Comment by fheswara** [comment]
- carrierwave (0.11.0 b31f7ce)
Using that version solved my problem.

**Comment by daniel-g** [comment]
I had to use my own serialization in order to get the multifile upload feature working properly. I will write the solution in a blog post this week I think, and post it here.

**Comment by fheswara** [comment]
This is weird, I dont know suddenly the problem occur again. @daniel-g can you share ur solution?

**Comment by daniel-g** [comment]
https://coderwall.com/p/nnjrlq/multifile-uploads-with-carrierwave  let me know if you need any clarification

**Comment by fheswara** [comment]
@daniel-g Thanks for sharing.
Now everything works again. 
One thing that I notice is carrierwave version. In my case, if version is carrierwave (0.11.0 b31f7ce) it works. But, if version 0.11.0 it didnt work.
<img width="248" alt="screen shot 2016-06-28 at 7 41 37 pm" src="https://cloud.githubusercontent.com/assets/2821068/16415751/f9d29dc6-3d68-11e6-918b-40e595e394dc.png">

**Comment by daniel-g** [comment]
It seems you have to be in master in order to use this feature

**Comment by mshibuya** [comment]
@daniel-g is right, please keep up with the master.
