### ISSUE TITLE
Problem with MiniMagick height and width methods

### ISSUE THREAD

**Issue by aried3r** [carrierwaveuploader/carrierwave#1947]
When I try to get the width or height of an image (added here: https://github.com/carrierwaveuploader/carrierwave/pull/1405), I receive the following error:

``` Ruby
> image.height
Errno::ENOENT: No such file or directory @ rb_sysopen - /uploads/profile/image/853/Screen_Shot_2016-05-03_at_20.54.29.png
from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'
```

which is absolutely right. There is no `/uploads` (note the leading `/`). I think it's because of [this line](https://github.com/carrierwaveuploader/carrierwave/blob/ef0d36a7c195621d8d7d4c769a47a9aee6f64d95/lib/carrierwave/processing/mini_magick.rb#L320), because `.url` returns `/uploads/profile/image/853/Screen_Shot_2016-05-03_at_20.54.29.png`, while something like `.path` or `.current_path` returns the full path: `/full/path/to/uploads/profile/image/853/Screen_Shot_2016-05-03_at_20.54.29.png`.

Does `.url` ever return something falsey, so the method would work?

Using:
Rails 4.2.6
carrierwave `master` version.
MiniMagick
Ruby 2.3.0

**Comment by aried3r** [comment]
I'd like to send a PR with a fix, but the way it looks to me is that `.url` never returns something falsey, so I don't know how to properly test for it. Is there a way to check if a file is local, so we can use `.path` instead of `.url`?

**Comment by aried3r** [comment]
For anyone having the same problem, here's how I temporarily fixed it for our project (this solution is specific to how our uploaders work, so YMMV)

```Ruby
# my_uploader.rb
...

private 

def mini_magick_image
  ::MiniMagick::Image.open(path)
end

...
```

**Comment by mshibuya** [comment]
Don't use `url` to access local file, use of `path` is what's supposed to be.

**Comment by aried3r** [comment]
> Don't use url to access local file, use of path is what's supposed to be.

I'm not, carrierwave is :)
See [this line](https://github.com/carrierwaveuploader/carrierwave/blob/bd692b107b6a9969dbdc079b8552efd9ac8add28/lib/carrierwave/processing/mini_magick.rb#L320), which is why I had to overwrite the implementation, because `url` was never falsey and thus always `url` was used, even for local files.

**Comment by mshibuya** [comment]
Oh, I've missed that...😕

**Comment by michaelnwani** [comment]
I've been experiencing the same issue FYI.

Using:
```
Rails 5.0.2
carrierwave-aws v1.1.0
MiniMagick
Ruby 2.4.0p0 (2016-12-24 revision 57164)
```

I modified @aried3r's fix a little:

```ruby
def mini_magick_image
  if Rails.env.production?
      super
  else
      ::MiniMagick::Image.open(path)
  end
end
```

Unrelated, but, when testing this I ran into this issue:
```
MiniMagick::Invalid: `identify /var/folders/_f/mrgt1nn15d91vm0sd3s597r19tl1z8/T/mini_magick20171225-42084-x2n5te.png` failed with error:
identify: unable to load module `/usr/local/Cellar/imagemagick/6.9.6-2/lib/ImageMagick//modules-Q16/coders/png.la': file not found @ error/module.c/OpenModule/1302.
identify: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504.
```

I just had to brew uninstall and install imagemagick, then `brew unlink libpng` and brew link --overwrite libpng
