### ISSUE TITLE
Does multifile feature allow update/destroy of each file?

### ISSUE THREAD

**Issue by daniel-g** [carrierwaveuploader/carrierwave#1948]
I saw in the docs I can upload multi files, but I can't see how I could delete one specific or replce it with another. Is there a way to do that in this version?

**Comment by aried3r** [comment]
In the wiki there's [an article](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Add-more-files-and-remove-single-file-when-using-default-multiple-file-uploads-feature) with a link to a blog post where you can see how a specific image can be deleted. I guess implementing the same for replacing is very similar.
