### ISSUE TITLE
[BUG] Rails 4.2.6 + Polymorphic + Carrierwave 0.10 + conditions

### ISSUE THREAD

**Issue by kvokka** [carrierwaveuploader/carrierwave#1950]
I've made long investigation, which is listed in this topic http://stackoverflow.com/questions/37152854/rails-4-2-6-polymorphic-carrierwave-0-10-conditions and I'll be really very pleased, if you know how solve it out.
Thank you.

**Comment by mshibuya** [comment]
This is not a bug, due to the limitation of ActiveRecord polymorphic association.
