### ISSUE TITLE
Potential issue: carrierwave stores versions, but not the original file, though updates the DB column

### ISSUE THREAD

**Issue by rocketblr** [carrierwaveuploader/carrierwave#1958]
Hi there,

I'm experiencing a really weird issue with carrierwave 0.10.0. When I update the existing record with a new picture, carrierwave successfully stores both versions, but doesn't store the original file. The column in the database is updated with a new filename. Moreover it is consistently reproduced every 2nd time. So I update the record -> it works, update again -> it doesn't. I'm using a carrierwave for a while already, but haven't seen anything like that before.
I did some logging in `store!` method and found out the following:

```
SQL (0.6ms)  UPDATE `activities` SET `image` = 'julia_web-16.jpg', `updated_at` = '2016-05-24 11:20:56' WHERE `activities`.`id` = 10

#<CarrierWave::SanitizedFile:0x007f262ab74970 @file="/public/uploads/tmp/1464088855-22231-4539/Cosy_Eleven.jpg", @original_filename=nil, @content_type="image/jpeg">
"1464088855-22231-4539"


#<CarrierWave::SanitizedFile:0x007f262acb4218 @file="/public/uploads/tmp/1464088855-22231-4539/full_julia_web-16.jpg", @original_filename=nil, @content_type="image/jpeg">
"1464088855-22231-4539"


#<CarrierWave::SanitizedFile:0x007f262acadad0 @file="/public/uploads/tmp/1464088855-22231-4539/thumb_julia_web-16.jpg", @original_filename=nil, @content_type="image/jpeg">
"1464088855-22231-4539"

   (68.4ms)  COMMIT
```

`@file` variable points to a wrong file (a previous one) when method is executed for the first time. Any ideas?

Tried with both rmagick and mini_magick. Behavior is the same.

I understand that I probably provided not enough information, but honestly I have no idea what to check next. Any suggestions are appreciated.

Update: Rails 4.2.5, Ruby 2.2.3, Carrierwave default config.

**Comment by nukturnal** [comment]
Kindly include your associated Uploader Class, this will be every helpful

**Comment by fabiancarlos** [comment]
Yes, i have it to, i remove before update de record now, and works.

@record.remove_avatar = true 
@record.save!

**Comment by mshibuya** [comment]
Stale.
