### ISSUE TITLE
Resize_to_fit not working in production.

### ISSUE THREAD

**Issue by mahendhar9** [carrierwaveuploader/carrierwave#1964]
Sorry, this is not an issue. But any help would be greatly appreciated.

In development, everything is working great.
But in production, resize_to_fit is not working. 
I am using 'RMagick' and made sure both 'Rmagick' and 'ImageMagick' are installed in production.
Also made sure that the public folder has required permissions.

**Comment by vadim-zverugo** [comment]
@mahendhar9: some error stacktrace from your production could be very helpful.

**Comment by mshibuya** [comment]
Please reopen on update.
