### ISSUE TITLE
Fix for Amazon S3 Virtual Hosted Buckets

### ISSUE THREAD

**Issue by bentiffany** [carrierwaveuploader/carrierwave#1971]
I'm serving my images from a subdomain of my site, and would like Carrierwave to save images directly into my S3 bucket without uploading into a subdirectory by the same name as my bucket. I'm following this AWS guide on virtual hosted buckets: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

My carrierwave.rb looks like the following with an intentionally omitted config.fog_directory:

```ruby
CarrierWave.configure do |config|
  config.fog_provider = 'fog/aws'

  config.fog_credentials = {
    provider: 'AWS',
    aws_access_key_id: ENV['S3_ACCESS_KEY_ID'],
    aws_secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
    region: 'us-east-1',
    host: 'images.example.com',
    endpoint: 'https://images.example.com'
  }
  config.fog_public =  true
  config.fog_attributes = { 'Cache-Control' => "max-age=#{365.day.to_i}" }
end
```

My files upload to the S3 bucket correctly, just the way I want them to. However, Carrierwave will return the wrong public url for the resource with an extra forward slash in the URL after the endpoint. I've fixed the URL issue by making fog_directory optional in the public_url method. I'll be submitting a pull request against this issue in a few minutes.

**Comment by mshibuya** [comment]
Adding `asset_host` should be enough:
```
  config.asset_host = "https://images.example.com"
```

**Comment by bentiffany** [comment]
Thank you, @mshibuya. When I created this issue/PR, I was forced to use master because of another bug in the stable version and config.asset_host wasn't working for me. Thanks!
