### ISSUE TITLE
DEPRECATION WARNING: `serialized_attributes`

### ISSUE THREAD

**Issue by swelther** [carrierwaveuploader/carrierwave#1973]
With Rails 4.2.6 I see lots of these deprecation warnings during our test runs:

`DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from read_identifiers at ~/.rvm/gems/ruby-2.3.1/bundler/gems/carrierwave-b31f7ce006ba/lib/carrierwave/mounter.rb:28)`

Any plans and/or ideas how to make Carrierwave Rails 5 ready?

**Comment by connorshea** [comment]
Rails 5 is out now, any news?

**Comment by connorshea** [comment]
Based on the error in the OP, this is on b31f7ce006ba, which is the current master commit :(

**Comment by swelther** [comment]
Yeah. I hope to get some time in the near future to try to get rid of the deprecation warnings. Not sure how, but with some time... :)

**Comment by mshibuya** [comment]
CarrierWave do not use `serialized_attributes` at all, please check your app or dependencies.
