### ISSUE TITLE
"uninitialized constant CarrierWave" inside a rails mounted engine

### ISSUE THREAD

**Issue by neilhanekom** [carrierwaveuploader/carrierwave#1974]
Hi guys,

I can't seem to use carrier wave inside a mounted engine as I get a "uninitialised constant" error.

What to do??

![screen shot 2016-06-20 at 1 14 02 pm](https://cloud.githubusercontent.com/assets/5267784/16192322/e6aee3d4-36e8-11e6-92bc-df9f9abdc70e.png)

**Comment by Shwetakale** [comment]
@neilhanekom Which ```carrierwave``` version are you using?

I have used ```carrierwave-mongoid``` in one of my projects and it worked fine.

**Comment by mshibuya** [comment]
Please reopen on update.
