### ISSUE TITLE
Can't add more attachments for multiple files

### ISSUE THREAD

**Issue by tam-vo** [carrierwaveuploader/carrierwave#1975]
Hi,

I can't add more attachments for multiple files (`mount_uploaders`). Here is my configuration

```
migrations
    add_column :users, :doc_ids, :string, array: true, default: []

user_documents.rb
...
    mount_uploaders :doc_ids, UserDocumentUploader

user = User.find 123
user.doc_ids += [Pathname.new("black-logo.png").open]
user.save

user = User.find 123
user.doc_ids += [Pathname.new("white-logo.png").open]
user.save
```

But it saved doc_ids field as:
`
doc_ids: [nil, "2309_doc_ids-98b63686-84f8-41a7-a22c-51fe2389ecfa.png"]
`

Please help. Thank you

**Comment by daniel-g** [comment]
If you have many files, your string file type might be the problem. What happens if you try to add 2 files? Does it do the same?
```ruby
user.doc_ids += [Pathname.new("black-logo.png").open, Pathname.new("black-logo-2.png").open]
user.save and user.reload
user.doc_ids # => ?
```

**Comment by tam-vo** [comment]
@daniel-g, it worked fine for that situation but will store wrongly incase I reload model `user`.

**Comment by daniel-g** [comment]
I found that's an issue in CarrierWave, you will have to use a type cast:
```
class ArrayType < ActiveRecord::Type::Text
  def type_cast(value)
    Array.wrap(YAML::load(value || YAML.dump([])))
  end
end

class Note < ActiveRecord::Base
  attribute :files, ArrayType.new
  mount_uploaders :files, GeneralUploader
end
```
for example. I explain this here: https://coderwall.com/p/nnjrlq/multifile-uploads-with-carrierwave

**Comment by daniel-g** [comment]
CarrierWave dumps the array into a JSON, but that doesn't play well everywhere :/

**Comment by tam-vo** [comment]
Thanks @daniel-g, sadly, `ActiveRecord::Type::Text` is only available in activerecord > 4.2 while I'm using 4.1.7

I'm finding a solution for this

**Comment by daniel-g** [comment]
@tam-vo you can also use ActiveRecord::Type::String . I used Text for convenience :), is that available in your version? otherwise, I'd say there should be an equivalent.

**Comment by daniel-g** [comment]
I started a research around that, and it seems there is not an option as you said, but maybe you can dig in the code of Postgres adapter for your version: https://github.com/rails/rails/blob/v4.1.7.1/activerecord/lib/active_record/connection_adapters/postgresql/array_parser.rb

It seems it is not doing a good parsing after all. Maybe CarrierWave isn't doing it well either, so you might follow my post in the `read_uploader` and `write_uploader` part. You can use them for reading from your database (and parse it right), and writing back (in the format you need it.)

**Comment by tam-vo** [comment]
It's not actually a bug from carrierwave, it caused from my customize filename for multiple files. Sorry for my stupidness and many thanks for your enthusiasm :)
