### ISSUE TITLE
Invalid locale in CarrierWave::MiniMagick#manipulate!

### ISSUE THREAD

**Issue by paweljw** [carrierwaveuploader/carrierwave#1977]
If a MiniMagick::Error or a MiniMagick::Invalid exception is raised within `manipulate!`, the rescue block will try to find a default error message with

``` ruby
I18n.translate(:"errors.messages.mini_magick_processing_error", e: e, locale: :en)
```

If the :en locale is not included in an application's locales, which is my case, an I18n::InvalidLocale exception will be raised within the rescue block, effectively blocking the developer from gaining insight into what actual exception has occured.

I'm currently using this as a workaround:

``` ruby
rescue ::MiniMagick::Error, ::MiniMagick::Invalid => e
  default = if I18n.available_locales.include?(:en)
              I18n.translate(:"errors.messages.mini_magick_processing_error", e: e, locale: :en)
            else
              ''
            end
  message = I18n.translate(:"errors.messages.mini_magick_processing_error", e: e, default: default)
  raise CarrierWave::ProcessingError, message
end
```

But it's rather specific to my use case and far from perfect for general usage. However, the current implementation is also not perfect in the edge case of apps that do not have a :en locale.

**Comment by mshibuya** [comment]
Dup of #1729, and fixed by #2083.
