### ISSUE TITLE
Heroku and ENOENT

### ISSUE THREAD

**Issue by juancaldera** [carrierwaveuploader/carrierwave#1978]
I saw another issue related to this, but I'm not sure the cause is the same. In this instance, everything works, until the size of the image gets too large. Then suddenly, carrierwave starts spitting out ENOENT errors. 

I noticed the tmp files created have a "-0", "-1", and "-2" suffixes. i don't know if this is carrierwave attempting to download the original multiple times, or heroku doing some weird things.

anyway, carrierwave is looking for a file `/tmp/mini_magick20160624-351-1jzbnx8.jpg`
but the files that exist are 

`"mini_magick20160624-351-1jzbnx8-2.jpg", ".", "..", "mini_magick20160624-351-1jzbnx8-0.jpg", "mini_magick20160624-351-1jzbnx8-1.jpg"`

any pointers on helping me narrow down my list of suspects would be great. Not sure if this is a carrierwave or a heroku problem

<img width="1433" alt="screen shot 2016-06-24 at 11 39 07 am" src="https://cloud.githubusercontent.com/assets/2301519/16347371/35da80a6-3a01-11e6-8477-ff79ad95cf19.png">

**Comment by janko-m** [comment]
This means that you gave a file in a multi-layered/multi-paged format (e.g. PSD, PDF) to MiniMagick, and ask it to convert it to a single-layered image (e.g. JPEG, PNG). This makes ImageMagick produce multiple files with the layer indices in the filename, but MiniMagick doesn't handle these automatically, it returns representation of an image with a filename *without* these layer indices, which doesn't exist.

**Comment by juancaldera** [comment]
thanks for the response. sadly, the original image is a JPEG as well. this is not my area of familiarity but i believe jpegs can only come as rasterized images.

**Comment by janko-m** [comment]
Hmm, that's strange. Can you try downloading and converting that JPEG image directly using ImageMagick: `convert input.jpg output.jpg`, and confirm that it's not producing multiple images?

**Comment by juancaldera** [comment]
hmm, interesting. 
<img width="227" alt="screen shot 2016-06-25 at 8 53 19 pm" src="https://cloud.githubusercontent.com/assets/2301519/16360421/e4117e52-3b16-11e6-805d-11be9c8f5ab5.png">

what is this a symptom of?

**Comment by juancaldera** [comment]
here's the file info `Adobe Photoshop Image, 3992 x 2242, RGB, 3x 8-bit channels` sorry if i'm a bit dunce. images are not my thing.

**Comment by janko-m** [comment]
Ok, so we see here that you have an `Adobe Photoshop Image`, which is a PSD (not a JPEG), so in this case we have the input format which has multiple layers, while the output format supports only one layer, so ImageMagick handles that by creating multiple files of the output format.

**Comment by juancaldera** [comment]
that make sense. thanks so much. i guess the user who uploaded this image manually just set the extension to jpg.
