### ISSUE TITLE
remote_XXX_url not reading correct content-type when extension is not provided

### ISSUE THREAD

**Issue by coneybeare** [carrierwaveuploader/carrierwave#1981]
When setting the remote_image_url to `https://pbs.twimg.com/media/ClfjzYQUYAEYGpx.jpg:large` -- a valid twitter image url -- I would expect that the headers returned: 

``` ruby
[16] pry(main)> HTTParty.get('https://pbs.twimg.com/media/ClfjzYQUYAEYGpx.jpg:large').headers['content-type']
=> "image/jpeg"
```

would dictate the image type for validation. Instead, I am getting an error with the message:

> You are not allowed to upload files

Shouldn't carrierwave be validating against the headers['content-type'] value of `image/jpeg`? It appears the library isn't even registering the url based on the missing extension in the error message.

**Comment by coneybeare** [comment]
I found a temporary work around, but not a solution. The error above comes from my checking content type using 

````
def content_type_whitelist
  /image\//
end
````

I still want this, but until this issue is addressed by carrierwave, I have to now use extension validation instead (undesired).

````
def extension_whitelist
  [:jpg, :jpeg, :gif, :png, :jpg_large]
end
````

The relevant `jpg_large` extension is what `carrierwave` is assuming the twitter `jpg:large` extension is instead of jpg. Hopefully they fix this soon.

**Comment by mshibuya** [comment]
No longer happens in the master.
