### ISSUE TITLE
be_format helper not work

### ISSUE THREAD

**Issue by piotr-galas** [carrierwaveuploader/carrierwave#1983]
I followed documentation related to rspec, and tried to test extension of file.

I used `be_format` and everything work propertly on master branch (gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'),  
When I switch to version 0.11.2 be_format does not exist.

**Comment by jefvlamings** [comment]
I can confirm this. The Readme is misleading because the `be_format` is documented while it's only available in the master branch and not in the latest stable release (0.11.2).
