### ISSUE TITLE
How to setup private files with CloudFront?

### ISSUE THREAD

**Issue by betjaminrichards** [carrierwaveuploader/carrierwave#1986]
Currently I have an S3 Bucket with an access policy that only allows access from a CloudFront Origin Access Identity:

```
{
    "Version": "2012-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": "Grant a CloudFront Origin Identity access to support private content",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXXXXXXXXX"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}
```

This should prevent any access to the S3 asset which is not through the CloudFront distribution. However when I input the S3 URL into my web browser I can still access the file.

I have `config.fog_public = true` so Carrierwave is putting a public access setting on the uploaded object.

I tried changing the setting to `config.fog_public = false` but that then started returning signed URL's that ignored my asset_host setting (so provided the signed S3 URL rather than the unsigned CloudFront URL).

Can you advise what is the correct way to set this up with Carrierwave?

**Comment by patricknpinto** [comment]
Hi @betjaminrichards. Have you managed to resolve this? I have the same problem. Thanks.

**Comment by 8vius** [comment]
+1

**Comment by h-nago** [comment]
I have the same problem.

I override url method to avoid this problem.
```ruby
  def url
    "#{asset_host}#{path}"
  end
```

However, it is better to reflect asset_host.

**Comment by mshibuya** [comment]
Use carrierwave-aws for such an advanced feature. Setting `asset_host` and `aws_signer` will achieve what you want. 
https://github.com/carrierwaveuploader/carrierwave-aws#usage
