### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by thiagofm** [carrierwaveuploader/carrierwave#1987]
Hello everyone,

Recently I've got very busy and issues just keep piling up.

It would be nice to have a new maintainer, this new maintainer should preferably have contributed with something in carrierwave or has some good experience using it under its belt. But if you are nevertheless very interested in the project and willing to spend some time to gain knowledge and help people, don't be afraid to get in touch with me.

Preferably contact me by e-mail(it's the one on my Github profile)

Cheers and thanks a lot.

**Comment by mshibuya** [comment]
@thiagofm I've sent you an e-mail about a week ago, how is it going? :)

**Comment by ozgg** [comment]
@mshibuya please give us hope that you'll continue to actively develop carrierwave and make it stable in Rails5.

**Comment by mshibuya** [comment]
I'll take care of it shortly(probably next weekend), don't worry 😃

**Comment by connorshea** [comment]
Thank you for all your work @thiagofm ❤️ 

And thank you @mshibuya for taking on maintaining the project, it's greatly appreciated!
