### ISSUE TITLE
Rails 5 to_json double nests attribute name

### ISSUE THREAD

**Issue by tomprats** [carrierwaveuploader/carrierwave#1988]
I recently updated to Rails 5 and with it, the latest version of the Carrierwave gem. I have a pretty generic model and uploader.

    class MyModel < ApplicationRecord
      mount_uploader :logo, LogoUploader
    end

In the past the `to_json` method would return:

    MyModel.first.to_json
    => "{\"logo\":{\"url\":\"/mymodel/logo.jpg\"}}"

But now it returns:

    MyModel.first.to_json
    => "{\"logo\":{\"logo\":{\"url\":\"/mymodel/logo.jpg\"}}}"

The database still has the value `logo.jpg` (which is correct)

I looked through the open issues but couldn't find anything related to it. I'm also looking into the code now too to see if anything changed recently. But I think the previous way was better and was hoping to get it back.

**Comment by tomprats** [comment]
Testing it against master, it no longer has the problem, whereas 0.11.2 does have the problem

**Comment by mshibuya** [comment]
0.11 is not Rails 5 ready, please use the master.

**Comment by ozgg** [comment]
...But keep in mind that cache does not seem to work with Rails 5 and master, so one cannot use `from_version` in uploaders.

**Comment by tomprats** [comment]
Thanks for the feedback! I'll continue using master
