### ISSUE TITLE
[question] Directly set URL on model

### ISSUE THREAD

**Issue by boydkr** [carrierwaveuploader/carrierwave#1993]
Is there a way to directly set the image URL on a model using CarrierWave, bypassing the image upload?

There are some cases in an app where I want to by default have a link to an external image.  Using the `default_url` won't work because I don't want this to happen in all cases where there is no uploaded image.  Behavior similar to default_url is what I'm trying to achieve, though

**Comment by boydkr** [comment]
It's a bummer if there's no way to do this, because my alternative is adding a flag and hacking up my serializer.

**Comment by kgilmur** [comment]
What workaround did you use for this problem? I would like to do the same thing.

**Comment by mshibuya** [comment]
Storing external link is not supported, alternative will be download and store it using the URL.
