### ISSUE TITLE
Image column always NULL when manually creating instance of model

### ISSUE THREAD

**Issue by djflorio** [carrierwaveuploader/carrierwave#2001]
Carrierwave 0.11.2
Rails 5.0.0
Ruby 2.3.1

When I try to manually create an instance of a model, such as:

`Painting.create(name: "Starry Night", image: "starrynight.jpg")`

the resulting SQL query looks like:

`INSERT INTO 'paintings' ('name', 'image', 'created_at', 'updated_at') VALUES ('Starry Night', NULL, '2016-08-12 18:35:50', '2016-08-12 18:35:50')`

Is there any way to manually set the image string without it defaulting to NULL (so I can use it in my seeds.rb file)? Or does it HAVE to be done through the file_field helper?

**Comment by ozgg** [comment]
It is [described](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file) in how to's:

`Painting.image = Pathname.new("/path/to/file/logo_1.jpg").open`

**Comment by djflorio** [comment]
Perfect, thanks.
