### ISSUE TITLE
How to get url by using SQL ? 

### ISSUE THREAD

**Issue by fifiteen82726** [carrierwaveuploader/carrierwave#2002]
I need to get `url` by using SQL, I know it's easy to get by using ActiveRecord. But I got a complex sql, it include join and many condition. 

For example, I got two modal called `Goods` and `BookContent`, and the `BookContent` has the column `cover` which is using by `carrierwave`

The SQL is like 

```ruby 
g = Goods.joins('INNER JOIN book_contents ON book_contents.id=goods.reference_id').
                 where('Condition').
                 select('...., book_contents.cover').
                 as_json
```

But when I access the `g.first.cover`, it will only return the file name like `xxxx.png`. How do I directly access the cover `url`?

**Comment by ozgg** [comment]
I don't think that you can do it without an instance of `uploader`, because paths are computed in `#store_dir`.

**Comment by fifiteen82726** [comment]
@ozgg  `Goods.includes(:book_content)` will help?

**Comment by mshibuya** [comment]
That's not possible, you have to follow association to BookContent.

**Comment by fifiteen82726** [comment]
I finally change to use Bookcontent.join(xxx) to get url.
