### ISSUE TITLE
Rspec content_type

### ISSUE THREAD

**Issue by webchi** [carrierwaveuploader/carrierwave#2003]
I am trying to upload image to test helper wich return link or img tag base on attachment content_type
helper:
```
def link_or_image(object)
    if (object.file.content_type.split('/')[0] == 'image')
      image_tag object.file.url
    else
      link_to object.file_identifier, object.file.url
    end
  end
```
rspec:
```
it 'return image on image' do
      task = create(:task, user: user,
                    file: Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec', 'factories', 'files', 'minions.png')))

      expect(helper.link_or_image(task)).to  have_xpath('//img')
    end
```
But on png image uploaded I have content type in console: "text/plain"

How this could be possible?

**Comment by mshibuya** [comment]
You could pass content_type argument to Rack::Test::UploadedFile.
http://www.rubydoc.info/github/brynary/rack-test/Rack%2FTest%2FUploadedFile%3Ainitialize
