### ISSUE TITLE
ArgumentError: wrong number of arguments (1 for 2) when accessing images Rails 5

### ISSUE THREAD

**Issue by JesalR** [carrierwaveuploader/carrierwave#2008]
I get a wrong number of arguments error when accessing images attached to a CarrierWave upload on Rails 5. Using version 0.11.2

> ArgumentError: wrong number of arguments (1 for 2)
> from /Users/jesalrajdev/.rvm/gems/ruby-2.2.5@rails5/gems/arel-7.1.1/lib/arel/visitors/reduce.rb:12:in `visit'

Seems like an issue with reduce in Arel, but only seeing it on images attached via CarrierWave

Wasn't an issue in 4.2 (CarrierWave 0.10.0)

Any help would be great. 
Thanks

**Comment by mshibuya** [comment]
Full stack trace, please.

**Comment by JesalR** [comment]
That's all that shows up.

In the browser window it only references the line of code where I try to access the image, but in console it at least lets me know it's something to do with reduce in arel.

**Comment by mshibuya** [comment]
Didn't you ever see the lengthy stack trace like this?
https://github.com/carrierwaveuploader/carrierwave/issues/1143#issuecomment-20581994
Check `logs/development.log` in your app.

**Comment by JesalR** [comment]
I did, but it was just a trace of the templates rendered that led to the access of the image. 

> ActionView::Template::Error (wrong number of arguments (1 for 2)):
>     33:       .navbar-user-menu
>     34:         #user-menu-toggle
>     35:           a href="#"
>     36:             - if current_user.picture.present?
>     37:               .user-picture style='background-image: url(#{current_user.picture})'
>     38:             .user-name
>     39:               = truncate(current_user.full_name, length: 16)
>   
> app/models/user.rb:94:in `picture'
> app/views/user/dashboard/_navbar.slim:36:in `_app_views_user_dashboard__navbar_slim__2905922341976714058_70171288091800'
> app/views/layouts/homepage.html.slim:10:in `_app_views_layouts_homepage_html_slim__621187930153581589_70171376029520'
> app/controllers/welcome_controller.rb:7:in `show'

But it's an error that occurs regardless of where I access that image. I think I may have messed something up in all honesty, when I removed the call to the avatar, there was a simillar error in my serializer.

**Comment by mshibuya** [comment]
That's not enough, I need __full__ version of whole stack trace to tell you what's going on.

**Comment by JesalR** [comment]
That is the entirety of what is in my log and what was printed to my terminal too. Again, it wasn't descriptive, and nothing I could do could get any deeper than associating it with Arel::Visitors::Reduce

**Comment by mshibuya** [comment]
0.11.2 is not Rails 5 ready anyway, try with the master branch:
```ruby
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```
If the problem persists, try hitting someghint like `User.find(xxx).picture.present?` or so in Rails console, so the error can produce whole stack trace.

**Comment by onebree** [comment]
@mshibuya is CarrierWave Rails 5 ready as of the 1.0 beta?

**Comment by mshibuya** [comment]
@onebree Sure, please give it a try 😃

**Comment by rdaniels** [comment]
Same problem here but with simple operations like Post.where(id: [1,2,3]) Rails 5 too, same Arel version, same reduce.rb line

Fixed by removing gem 'postgres_ext', apparently it doesn't yet have support for rails 5

**Comment by mshibuya** [comment]
@rdaniels Thanks for follow-up, closing this.
