### ISSUE TITLE
Support aws instance profile / role based access

### ISSUE THREAD

**Issue by lgarvey** [carrierwaveuploader/carrierwave#2011]
The Carrierwave config requires aws_access_key_id and aws_secret_access_key keys. If supplied but left blank, AWS returns a 400 saying that the authorisation header is malformed.

Fog supports AWS role based auth, so it should be trivial for carrierwave to do the same?

**Comment by mshibuya** [comment]
Probably related to https://github.com/fog/fog-aws/issues/441, basically just `use_iam_profile: true` will be fine.
