### ISSUE TITLE
GIF Upload Memory Leak breaking entire site (App Crashed Error on Heroku) 

### ISSUE THREAD

**Issue by callancarr** [carrierwaveuploader/carrierwave#2016]
This is a really serious issue i've run into and it seems to relate to gif uploads.

I have to process every image to make it square for my app. The standard resize doesn't work for GIFs, it distorts them, so I had to use a work around I found online. Below is my full uploader code

````
class PictureUploader < CarrierWave::Uploader::Base

  # Include RMagick or MiniMagick support:
  # include CarrierWave::RMagick
  include CarrierWave::MiniMagick
  include ::CarrierWave::Backgrounder::Delay

  # Auto-orient
  process :auto_orient

  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Prevent sideways on mobile
  def auto_orient
    manipulate! do |img|
      img = img.auto_orient
    end
  end

  def resize_with_animate(width,height)
    manipulate! do |img|
    if img[:format].downcase == 'gif'
      #coalesce animated gifs before resize.
      img.coalesce
    end
    img.resize "#{width}x#{height}>"
    img = yield(img) if block_given?
    img
    end
  end


  # Create different versions of your uploaded files:
  version :thumb do
    process :resize_with_animate => [640,640]
    process :resize_to_fill => [640, 640]
  end

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_white_list
     %w(jpg jpeg gif png)
  end

  # Override the filename of the uploaded files:
  # Avoid using model.id or version_name here, see uploader/store.rb for details.
  # def filename
  #   "something.jpg" if original_filename
  # end
end
`
```

So essentially fairly standard, I have tried using carrierwave_backgrounder to make sure that the app is processing things normally. What seems to happen is that during processing the GIF a memory leak occurs. I then hit a "Memory Limit Reached" exception and my whole app dies, so really serious since we serve about 5k people and simply uploading a GIF breaks the site.

The obvious solution is to prevent GIF uploads, but it's very important to my clients they are kept. What should I do and what is causing this? Is this an internal issue with carrierwave.

**Comment by janko-m** [comment]
Since the processing is done by ImageMagick (through the MiniMagick gem), the memory leak is most likely caused by ImageMagick, not CarrierWave.

Did you say that uploading *one* GIF can break the site, or just when enough GIFs are uploaded to overflow the memory? What exception is raised when memory is overflown? Can you reproduce the memory leak in an isolated script using MiniMagick/ImageMagick? You can see which ImageMagick commands are executed by MiniMagick by [turning on logging](https://github.com/minimagick/minimagick#logging).

**Comment by callancarr** [comment]
@janko-m Well it would seem one large GIF can killl the entire site. I am only using 1x worker and 1x Dyno, but a single GIF upload shouldn't break it. Shall I take my Query to MiniMagick? Thanks for the help.

The Exception Raised is the Heroku "Memory Limit Exceeded" I can also see in my console testing in development that when processing the CPU goes way up to max and often my IDE (c9.io) will terminate the process.

**Comment by callancarr** [comment]
@janko-m  For now I have disabled GIF uploads as a precaution, still issues though

**Comment by mshibuya** [comment]
Looks like an ImageMagick issue, not CarrierWave.

**Comment by a-barbieri** [comment]
So basically there is no solution? 

> I think that imagemagick cannot handle animated gifs. I encountered this problem several years ago and came to this conclusion. Virtually every animated gif became glitchy after resize.
[link](https://github.com/carrierwaveuploader/carrierwave/issues/2015#issuecomment-244801510)

> For now I have disabled GIF uploads as a precaution, still issues though
[link](https://github.com/carrierwaveuploader/carrierwave/issues/2016#issuecomment-245526822)

I'll try RMagick to see if it happens again, not sure makes any difference.
