### ISSUE TITLE
remove_file: removes file even if parameter is '0'

### ISSUE THREAD

**Issue by davidwessman** [carrierwaveuploader/carrierwave#2017]
Rails: 4.2.7.1
Carrierwave 0.10.0, running from Github.

When I have a `User` with an `avatar` and I call:
- `user.update(remove_avatar: false)` **will not remove the avatar**
- `user.update(remove_avatar: true)` **will remove the avatar**
- `user.update(remove_avatar: '0')` **will remove the avatar**
- `user.update(remove_avatar: '1')` **will remove the avatar**

So when I use a `check_box` to allow users to remove their avatars, my views look like:

```
if user.avatar.present?
  form.check_box :remove_avatar
end
```

But if this box is unchecked I receive `params: { user: { remove_avatar: '0'} }` which will remove the avatar.

Is this how Carrierwave is implemented?, and in that case - what can I do differently?

**Comment by mshibuya** [comment]
Sounds unlikely - this behavior is implemented here:
https://github.com/carrierwaveuploader/carrierwave/blob/v1.0.0.beta/lib/carrierwave/mounter.rb#L112
and tested here:
https://github.com/carrierwaveuploader/carrierwave/blob/v1.0.0.beta/spec/mount_single_spec.rb#L415

Can you make the spec fail?

**Comment by davidwessman** [comment]
I cannot get the spec to fail, but it works in my console:
```
u = User.first
u.avatar.present? => true
u.remove_avatar = '0' => '0'
u.remove_avatar? => false
```
But if I save this:
```
u = User.first
u.avatar.present? => true
u.remove_avatar = '0' => '0'
u.save => true
u.avatar.present? => false
```

**Comment by jonian** [comment]
For anyone having this issue, use a check-box without a hidden input:

```ruby
form.check_box :remove_avatar, {}, true, false
```

**Comment by mshibuya** [comment]
My guess is that something in your code is causing this behavior, I can point it out if you could paste your uploader and model.
