### ISSUE TITLE
Migrate single upload to multiple upload in same model

### ISSUE THREAD

**Issue by misazr** [carrierwaveuploader/carrierwave#2018]
I need to extend my model which is using carrierwave for storing single file to multiple files.
I have field in model eg. **avatar** now I need to move this avatar to new field in same model field **avatars** which is json or string array.

I tried like this:

```
a=Model.first
a.avatars[0]=a.avatar
a.save!
```

but this doesn't copy and save field to new field.

Can somebody explain me how?

**Comment by mshibuya** [comment]
```ruby
a = Model.first
a.avatars = [a.avatar]
a.save!
```
will do the job.
