### ISSUE TITLE
Add Rails 5.0 gemfile

### ISSUE THREAD

**Issue by connorshea** [carrierwaveuploader/carrierwave#2021]
https://github.com/carrierwaveuploader/carrierwave/tree/master/gemfiles

Currently there's no 5.0 gemfile, there's only a rails master gemfile which tests with a version that's very different from 5.0 stable.

Could we have a 50-stable gemfile?

**Comment by mshibuya** [comment]
Rails 5.0 is actually tested by root Gemfile:
https://github.com/carrierwaveuploader/carrierwave/blob/master/.travis.yml#L19

I don't think adding `gemfiles/rails-5-0-stable.gemfile`(and removing root `Gemfile` from travis matrix) is bad idea, but please make sure that all matrix jobs pass to merge #2026 in.

**Comment by connorshea** [comment]
Will do :+1:

I wonder if the problem is with using the Rails repo directly and it'd pass if we used 5.0.0.1?

**Comment by mshibuya** [comment]
activemodel-serializers-xml is needed for the spec to pass, like we do in the root Gemfile:
https://github.com/carrierwaveuploader/carrierwave/blob/master/Gemfile#L3
