### ISSUE TITLE
Problem with file cache on form validation using S3

### ISSUE THREAD

**Issue by lemingos** [carrierwaveuploader/carrierwave#2022]
Hi, 

I am using Carrierwave + Fog to store files on S3. 
It works when form is saved successfuly without any errors, file is save to S3. 
It doesn't work when object is not valid and file is saved to temporary location. 
In that case file is saved to application server public/uploads/tmp directory - but the app is looking for that file on S3. 

Please advise. 

Here is my config:

```
 CarrierWave.configure do |config|
    config.fog_credentials = {
      :provider                   => 'AWS',
      :aws_access_key_id          => ENV['FOG_AWS_ACCESS_KEY_ID'],
      :aws_secret_access_key      => ENV['FOG_AWS_ACCESS_KEY_SECRET'],
      :region                     => ENV['ELB_REGION'],
      :path_style                 => true
    }
    config.fog_directory        = ENV['FOG_DIRECTORY']
    config.asset_host           = ENV['ASSET_HOST_UPLOAD']
    config.storage              = :fog
  end
```

**Comment by mshibuya** [comment]
`cache_storage` feature works perfectly for that purpose. See #1312 for detail.
