### ISSUE TITLE
Removing single image when using multiple file uploads feature, doesn't work when only one image left

### ISSUE THREAD

**Issue by bobbybobby** [carrierwaveuploader/carrierwave#2024]
According to the wiki https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Add-more-files-and-remove-single-file-when-using-default-multiple-file-uploads-feature it's possible to remove only one image of a column where `mount_uploaders` is used with the following manipulation : 

```
remain_images = @gallery.images # copy the array
deleted_image = remain_images.delete_at(index) # delete the target image
deleted_image.try(:remove!) # delete image from S3
@gallery.images = remain_images # re-assign back
```

However I found that in case there is only one image left in the array it doesn't work. I can workaround that by checking the length of the array and calling `@gallery.remove_images!` in that case, but that would be great for code consistency if it always worked.

**Comment by anduong** [comment]
I have another issue with this code (commented here https://github.com/carrierwaveuploader/carrierwave/issues/1704#issuecomment-259106600)

**Comment by bobintornado** [comment]
@bobbybobby Hi bobby I am aware of the issue but haven't dived into solving it. As I don't really have a clue why this happens yet. 😕

**Comment by anduong** [comment]
@bobbybobby @bobintornado I have this issue too and others have confirmed it. There is a workaround for it. See https://github.com/carrierwaveuploader/carrierwave/issues/1990

**Comment by bobintornado** [comment]
@anduong thanks I see! 😃

**Comment by mshibuya** [comment]
Merging into #1990.
