### ISSUE TITLE
Dynamically define S3 region and bucket in uploader

### ISSUE THREAD

**Issue by tboyko** [carrierwaveuploader/carrierwave#2028]
We are using carrierwave in a web application. Each user account stores data in different S3 buckets/regions. I'd like to configure CarrierWave to use the correct bucket and region as seamlessly as possible and this seems to be in the uploader definition. 

This seems like half of the solution to the problem: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Define-different-storage-configuration-for-each-Uploader.

The one catch is how to access the user information, which is stored in an activerecord model, from within the uploader. Suggestions?

**Comment by mshibuya** [comment]
Uploaders have access to the model instance they're mounted on via `model` method.
https://github.com/carrierwaveuploader/carrierwave/blob/c45699c318ca895f89fa3304204e48b5f1c411f1/lib/carrierwave/uploader/mountable.rb#L5
