### ISSUE TITLE
Avatar URL not working with Carrierwave 1.0.0

### ISSUE THREAD

**Issue by connorshea** [carrierwaveuploader/carrierwave#2029]
After testing carrierwave 1.0.0.beta with [GitLab](https://gitlab.com), the entire test suite passes except for one test (our app is pretty huge, so this is commendable!).

I suspected that #1481 might be the culprit, so I bisected the commits down to 04003e4435cf95ea4920276f2c32e7499a4a9a90 (success) and d42bc52dc91d074c5b658daf90880daa4ed257d7 (failure), which means that #1481 is most definitely the problem here.

The specific failing spec is this (actual source file [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/3b206ccb8393d8f2c5ad227874d9a60beb054782/spec/models/project_spec.rb#L698-714)):

``` ruby
describe '#avatar_url' do
  subject { project.avatar_url }

  let(:project) { create(:project) }

  context 'When avatar file is uploaded' do
    before do
      project.update_columns(avatar: 'uploads/avatar.png')
      allow(project.avatar).to receive(:present?) { true }
    end

    let(:avatar_path) do
      "/uploads/project/avatar/#{project.id}/uploads/avatar.png"
    end

    it { should eq "http://localhost#{avatar_path}" }
  end
end
```

`avatar_url` is defined in [our `project.rb` model](https://gitlab.com/gitlab-org/gitlab-ce/blob/3b206ccb8393d8f2c5ad227874d9a60beb054782/app/models/project.rb#L767-773) as follows (I removed one else statement since that code path isn't being exercised here and is unrelated to Carrierwave):

``` ruby
def avatar_url
  if self[:avatar].present?
    [gitlab_config.url, avatar.url].join
  end
end
```

Before (behavior in 0.10.0 and 04003e4435cf95ea4920276f2c32e7499a4a9a90): `/uploads/project/avatar/1/uploads/avatar.png`

After (behavior in 1.0.0.beta and d42bc52dc91d074c5b658daf90880daa4ed257d7): An empty string

(The above URL seems to be produced by `"uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"` in our [avatar_uploader.rb](https://gitlab.com/gitlab-org/gitlab-ce/blob/3b206ccb8393d8f2c5ad227874d9a60beb054782/app/uploaders/avatar_uploader.rb) if that matters)

Here's the specific build where the test fails on 1.0.0.beta: https://gitlab.com/gitlab-org/gitlab-ce/builds/4505244

Hopefully this helps, I'd like to get this resolved if we can. Please ask if there's anything I've left unclear or if I can do anything to help. Thanks!

**Comment by connorshea** [comment]
Looks like #1855 may be related.

**Comment by mshibuya** [comment]
I couldn't get the point for a long time but I finally found out, please don't do #update_columns since it will make the attribute value and `uploaders` out of sync.
Slightly related issue is discussed in #2253.
