### ISSUE TITLE
Unable to redirect_to model.attachment.url in Rails controller

### ISSUE THREAD

**Issue by onebree** [carrierwaveuploader/carrierwave#2031]
- `rails (5.0.0.1)`
- `carrierwave (1.0.0.beta)`
- `fog-aws (0.11.0)`

## Expected behavior

When the user clicks "Download", a GET for `/documents/some-slug` is created, which will redirect them to `@document.attachment.url`, either displaying it or prompting for download. (Depending on file type.)

## Actual behavior

Upon clicking "Download" the same GET is created. Rails console says the user has been redirected to `@document.attachment.url`. However, the user's browser is "stuck" on `/documents/some-slug`, and instead showing the file contents in the window. Checking dev tools, the content type is HTML.

If you visit `/documents/some-slug` directly, or refresh the page from the above example, the redirect will happen as expected (like before).

## Relevant code

```ruby
class AttachmentUploader < CarrierWave::Uploader::Base
  # NOTE - storage set to :file by default
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end

class Document < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
end

class DocumentsController < ApplicationController
  def show
    @document = Document.find_by(slug: params[:slug])
    redirect_to @document.attachment.url 
  end
end
```

```erb
<%= link_to 'Download', document_url(slug: @document.slug), class: 'btn btn-default' %>
```

## Logs from actual behavior

```
Started GET "/documents/receipt/info" for 127.0.0.1 at 2016-09-28 14:48:10 -0400
Processing by DocumentsController#info as HTML
  Parameters: {"slug"=>"receipt"}
  Document Load (0.6ms)  SELECT  "documents".* FROM "documents" WHERE "documents"."slug" = $1 LIMIT $2  [["slug", "receipt"], ["LIMIT", 1]]
  Rendering documents/info.erb within layouts/application
  Rendered documents/info.erb within layouts/application (6.7ms)
Completed 200 OK in 86ms (Views: 82.6ms | ActiveRecord: 0.9ms)


Started GET "/documents/receipt" for 127.0.0.1 at 2016-09-28 14:48:13 -0400
Processing by DocumentsController#show as HTML
  Parameters: {"slug"=>"receipt"}
  Document Load (0.2ms)  SELECT  "documents".* FROM "documents" WHERE "documents"."slug" = $1 LIMIT $2  [["slug", "receipt"], ["LIMIT", 1]]
Redirected to http://localhost:3000/uploads/document/attachment/6/receipt.pdf
Completed 302 Found in 2ms (ActiveRecord: 0.2ms)
```

**Comment by connorshea** [comment]
Possibly related to #2029?

**Comment by onebree** [comment]
Closing this issue because I figured out the cause today.

The issue is not with Carrierwave, but instead from using Turbolinks. By following the instructions below, the app worked as expected again.

http://stackoverflow.com/a/38649595
