### ISSUE TITLE
Support for pre-signed upload URLs

### ISSUE THREAD

**Issue by bsutherland** [carrierwaveuploader/carrierwave#2034]
Hi,

We'd like to use the pre-signed upload URL feature from S3. This is supported by fog with the `put_object_url` method, but I can't see any reference to this in CarrierWave.

At the moment I'm rolling my own, by creating an Uploader instance, and using its fog connection and configuration. Any plans to support this in CarrierWave? Or is it already supported and I just don't know how to use it?

Thanks!

**Comment by mhluska** [comment]
@bsutherland how did you end up rolling this yourself?

**Comment by bsutherland** [comment]
Sorry Maros, I don't have access to that code anymore. In the end, I think I switched to just using fog without Carrierwave for that project.

**Comment by mhluska** [comment]
Ok makes sense. I'm basically just using Fog now too but unsure how to get S3 to call back to my server when the upload is done. Did you get S3 to do the callback? I could just make the client do the callback but security-wise I'd prefer S3 does it.

**Comment by abraham** [comment]
You can already get pre-signed URLs by setting `fog_public` to `false`. Then `model.file.url` will be pre-signed.

```
  # config/initializers/carrierwave.rb
  CarrierWave.configure do |config|
    config.fog_provider = 'fog/aws'
    config.fog_credentials = { ... }
    config.storage = :fog
    config.fog_directory = 'bucket'
    config.fog_public = false
    config.asset_host = 'https://s3-external-1.amazonaws.com'
  end
```

**Comment by mhluska** [comment]
@abraham would those work with PUT requests from the client?

**Comment by mshibuya** [comment]
https://github.com/dwilkie/carrierwave_direct will be what you're looking for.
