### ISSUE TITLE
Load balanced servers

### ISSUE THREAD

**Issue by kernow** [carrierwaveuploader/carrierwave#2035]
I have a rails app deployed across multiple ec2 instances with an elb (load balancer) in front of them. File uploads are stored in S3 after manipulation.

Form time to time I'm getting an error such as

    Errno::ENOENT·No such file or directory @ rb_sysopen - /tmp/mini_magick20160930-4405-1g299ui.jpg

Whenever I test the file upload myself it is working and this error is not seen very often. It is my understanding that when a file is uploaded the processing of the file (unless backgrounding the task) is performed as part of the browsers request cycle and so the file will be uploaded to one of the servers in the load balanced pool, manipulated and then stored in S3.

I'm wondering if maybe there could be a situation where a file is uploaded on one server and then another server tries to manipulate the file but the file is not present in other server tmp folder. I want to rule this situation out before trying to figure out if the issue is being caused by something else.

Thanks

**Comment by janko-m** [comment]
This is most likely caused when a file is cached by CarrierWave and the user receives a validation error. In that case the form is submitted again with the CarrierWave's cached id, but now the form might be submitted to a different server, which isn't the one that cached the file.

**Comment by kernow** [comment]
@janko-m thank you, that makes sense, I'll create some shared storage for the carrierwave tmp directory

**Comment by mshibuya** [comment]
My recommendation is `cache_storage` feature, see #1312 for detail.
