### ISSUE TITLE
Issues with two file fields in the same form

### ISSUE THREAD

**Issue by Drillan767** [carrierwaveuploader/carrierwave#2037]
I created a portfolio inside which I added a nested form to be able to upload several pictures. However, when I added the possibility to upload a single file inside the portfolio's form, it failed: it's as if the form element was ignored.

Moreover, I tried to create an article with 2 single file fields inside, the second one always gets ignored.
How can I do to get all my file fields to work ?
Thanks in advance

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
