### ISSUE TITLE
config.asset_host is not working in production on Rails 5

### ISSUE THREAD

**Issue by RathanakSreang** [carrierwaveuploader/carrierwave#2038]
I've been using Rails 5.0.0.1.
And I try to config CarrierWave:

```ruby
CarrierWave.configure do |config|
  config.asset_host = "http://www.example.com"
end
```
And it working fine in development.(http://www.example.com/upload/../....jpg)
However, when I run in production it shows nothing.(upload/../....jpg)
Do anyone know how to fix this?
Thanks

**Comment by mshibuya** [comment]
Something must be wrong with your configuration, opening Rails console in production will help track down the issue.
