### ISSUE TITLE
Uploading data:image/png;base64 instead of select image or from url

### ISSUE THREAD

**Issue by Rubioli** [carrierwaveuploader/carrierwave#2047]
In my application Im trying to upload a `data:image/png;base64` image instead of selecting a file or url. 

I tried to use **upload from url** and inserted the `data:image/png;base64` inside `<input type="text" name="user[image_url]" id="image_url">` but when submitted, In my table, my `image column` is `null`.

Is it possible to insert a `data:image/png;base64` file and upload it to my server?

_I am using:_
**gem 'rails', '4.2.4'**
**gem 'carrierwave', '>= 1.0.0.beta', '< 2.0'**

**Comment by Deckluhm** [comment]
The [`carrierwave-base64`](https://github.com/lebedev-yury/carrierwave-base64) gem is what you need.
