### ISSUE TITLE
Hard to determine whether a potential file already exists!

### ISSUE THREAD

**Issue by mltsy** [carrierwaveuploader/carrierwave#2053]
It seems unnecessarily difficult to determine whether a given file already exists where a new Carrierwave file would be saved (in order to prevent overwriting it, and having duplicate models pointing at the same file).  Using File storage, it can be done by adding a method like this to your uploader:

``` ruby
    class XxxUploader < CarrierWave::Uploader::Base
      def exists?
        File.exists? Pathname(root).join(store_path)
      end
    end
```

And using Fog storage, it can be done like this:

``` ruby
    class XxxUploader < CarrierWave::Uploader::Base
      def exists?
        fog_file = CarrierWave::Storage::Fog::File.new(self,
                     CarrierWave::Storage::Fog.new(self), store_path)
        fog_file.exists?
      end
    end
```

It seems like it should be pretty easy to add this as an instance method to `CarrierWave::Uploader::Store`, for instance... or is there another easy way already to determine whether a given file already exists before saving it?

**Comment by mshibuya** [comment]
I don't recommend to do so, since filesystems and object storages often do not have strong consistency so overwriting still happens with this.

**Comment by mltsy** [comment]
It seems to be that it could be useful even if it's not fool-proof for this use-case.  I don't even remember why I wanted this now, but I'm assuming it was something to do with a cloud/data migration.
