### ISSUE TITLE
Letter url is null after save

### ISSUE THREAD

**Issue by PAMulligan** [carrierwaveuploader/carrierwave#2064]
I'm using CarrierWave to try to upload a letter file to my api. Following the instructions on the Github, my model looks like this:

    class SubOrder < ActiveRecord::Base
        ...
        mount_uploader :letter, LetterUploader
    end

My controller looks like this:

    class Api::V2::SubOrdersController < ApplicationController
        ...
        def create
            sub_order = SubOrder.new(sub_order_params)
            user = User.find(sub_order[:userid])
            ...
            if sub_order.save
                render json: sub_order, status: 201, location: [:api, :v2, sub_order]
            else
                render json: { errors: sub_order.errors }, status: 422
            end
        end

        private
            def sub_order_params
                params.require(:sub_order).permit(:letter, :userid)
            end
    end

My uploader file uses the default settings for now. I used the console to test if this works, and with the following commands, it does:

    s = SubOrder.new
    => #<SubOrder sub_order_id: nil, userid: nil, letter: nil>
    letter = File.read('lib/test.txt')
    => [LETTER_CONTENTS]
    s.letter = "data:text/plain;#{letter{"
    => "data:text/plain;[LETTER_CONTENTS]"
    s.userid = "[VALID_USER_ID]"
    => "[VALID_USER_ID]"
    s.save!
    BEGIN TRANSACTION
    [SQL STUFF]
    COMMIT TRANSACTION
    => true

However, when I look at the new record, letter is listed as nil. I'm sure I'm just missing a crucial detail, but cursory Googling hasn't turned up anything. Any thoughts?

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
