### ISSUE TITLE
SourceClear raising a vulnerability for Carrierwave

### ISSUE THREAD

**Issue by abarriga** [carrierwaveuploader/carrierwave#2065]
Vulnerabilities - Premium Data
NO-CVE                                      Medium Risk     Information disclosure through an exception message     carrierwave 0.11.2

**Comment by mshibuya** [comment]
Give us more details, please.

**Comment by abarriga** [comment]
https://www.sourceclear.com/registry/security/information-disclosure-through-exception-message/ruby/sid-2734

Seems fixed in 1.0.0 version

**Comment by mshibuya** [comment]
Good to hear that, thanks.
