### ISSUE TITLE
Files remove in nested forms for 0.11

### ISSUE THREAD

**Issue by Ammet** [carrierwaveuploader/carrierwave#2066]
You have a commit in `master`
https://github.com/carrierwaveuploader/carrierwave/commit/76e00a08e0eff059b13182ac478c0c4cc0d8fac9

Can you please add it to `0.11-stable` branch? My app is stick to this version, but I'm really need this fix.

Thanks!

**Comment by mshibuya** [comment]
Please open PR is you need it to be backported.
