### ISSUE TITLE
uninitialized constant CarrierWave::Storage::Fog with Google Cloud Storage

### ISSUE THREAD

**Issue by dessery85** [carrierwaveuploader/carrierwave#2068]
I am trying to use the sitemap_generator gem but I host with Heroku so I am trying to follow their documentation [here](https://github.com/kjvarga/sitemap_generator/wiki/Generate-Sitemaps-on-read-only-filesystems-like-Heroku) to use Carrierwave to upload the sitemaps to Google Cloud Storage. I am already using Carrierwave with Google Cloud to upload my images with all works fine so I was hoping it would be straightforward however the files are not being uploaded. The documentation says you need to add:

`config.storage = :fog`

To your carrierwave config file however whenever I add it, I get the following error:

`gems/carrierwave-49fdad1ec6ca/lib/carrierwave/uploader/configuration.rb:75:in `eval': uninitialized constant CarrierWave::Storage::Fog (NameError)`

My Carrierwave config looks like this:

```
CarrierWave.configure do |config|
     config.cache_dir = "#{Rails.root}/tmp/"
     config.storage = :fog
     config.fog_credentials = {
         :provider => 'Google'
     }
     config.fog_directory = 'bucket-name'
     config.asset_host = 'https://domain.storage.googleapis.com'
end
```
(fog_directory and asset_host are replaced with dummy values)

And in my gem file I have:

```
gem 'fog'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
```

I have seen a lot of people using AWS with the same error but their solution is to change to use fog gem instead of fog-aws (which I am already doing) and require fog/aws. I have tested this like so:

`gem 'fog', require: 'fog/google'`

But still have the same issue. Can you make any recommendations on how to resolve this?

Many thanks

**Comment by MrOutis** [comment]
@dessery85, look at this solution https://github.com/carrierwaveuploader/carrierwave/issues/2023#issuecomment-252407542

**Comment by anakinakova** [comment]
https://github.com/carrierwaveuploader/carrierwave#using-google-storage-for-developers

**Comment by dessery85** [comment]
Sorry for the slow reply on this one. Thank you both for responses. I followed the steps mentioned by @MrOutis and that worked a treat ;)

Many thanks
