### ISSUE TITLE
Use fog/google json API for uploads

### ISSUE THREAD

**Issue by JanStevens** [carrierwaveuploader/carrierwave#2069]
The json API is faster and who knows how long google will support the old XML S3 style api?
Fog-google currently has support for the new JSON API so lets use that!

I think the only change needed it to change the credential options in `fog_credentials`, maybe carrierwave should just pass them along in the future without assuming the keys? Then it's really independent of the underlying fog implementation.

**Comment by juanpastas** [comment]
do you know how to set this up?

**Comment by mshibuya** [comment]
It is supported, the documentation was updated by #2502.
