### ISSUE TITLE
NameError: uninitialized constant SomeModel::FooUploader

### ISSUE THREAD

**Issue by mbigras** [carrierwaveuploader/carrierwave#2072]
Hello there!

I'm working through [The Rails Tutorial](https://www.railstutorial.org/book) in section [13.4.1](https://www.railstutorial.org/book/user_microposts#sec-basic_image_upload) he uses CarrierWave to handle image uploads.

I'm pretty sure he is expecting the gem to just work because in the `config/application.rb` file there is the following lines:

    # Require the gems listed in Gemfile, including any gems
    # you've limited to :test, :development, or :production.
    Bundler.require(*Rails.groups)

error:

    SomeModelTest#test_some_model_knows_about_carrierwave:
    NameError: uninitialized constant SomeModel::PictureUploader
        app/models/some_model.rb:7:in `another_method'
        test/models/some_model_test.rb:13:in `block in <class:SomeModelTest>'

Honestly not sure what to make of this. If you add the `require 'carrierwave'` even one time inside `config/application.rb` then everything will work even after you comment it out.

I put together another test app https://github.com/mbigras/yet_another_rails_app_testing_carrier_wave

Something weird seems to be going on. It doesn't make sense that my test fails, I add a line and the test passes, then I comment it out and the test still passes.

@mhartl thanks for your awesome work! thought you might be interested to see this.

**Comment by mbigras** [comment]
@mhartl thank you for your awesome work! Would be interested to know if you can verify this.

**Comment by mbigras** [comment]
Honestly not sure what to make of this. If you add the `require 'carrierwave'` even one time inside `config/application.rb` then everything will work even after you comment it out.

I put together another test app https://github.com/mbigras/yet_another_rails_app_testing_carrier_wave

Something weird seems to be going on. It doesn't make sense that my test fails, I add a line and the test passes, then I comment it out and the test still passes.

**Comment by mhartl** [comment]
Thanks for the note. Please compare with the [reference implementation](https://bitbucket.org/railstutorial/sample_app_4th_ed) and let me know if you find any discrepancies. The [Rails Tutorial help page](http://railstutorial.org/help) might also be of assistance.

**Comment by janko-m** [comment]
@mbigras Could it be that you added the new `app/uploaders/` directory without restarting Spring afterwards?

**Comment by mshibuya** [comment]
Seems to be solved.
