### ISSUE TITLE
Automated validation with valhammer getting wrong value for file column

### ISSUE THREAD

**Issue by walterdavis** [carrierwaveuploader/carrierwave#2075]
Using <https://github.com/ausaccessfed/valhammer> to validate a model containing a CW file column, it appears that the content of the file (or some other very large representation of the attachment) is being presented to the ActiveRecord Validations in place of the string contents of the db column that represents the attachment. As a result, I am getting "too long" errors on a 10-character filename in a 255-character limit string value field. 

I raised this [in an issue to valhammer](https://github.com/ausaccessfed/valhammer/issues/19), but they refer me to you, indicating that all they are doing is auto-constructing a generic `validates :column, length: { maximum: 255 }, if: :column` under the hood. 

Is CW not compatible with this sort of validation? If I disable this column from automatic validation in VH, what can I use to replace it in a manually-constructed validation?

Thanks,

Walter

**Comment by mshibuya** [comment]
CarrierWave uses the `:length` validator for validating the attachment length.
https://github.com/carrierwaveuploader/carrierwave/commit/8fc8181e7ab7b65a54c85c1cbe2613c83d2bcc6c

So it's incompatible with what Valhammer expects. My recommendation is to disable Valhammer validation for CarrierWave columns.
https://github.com/ausaccessfed/valhammer#disabling-validators
