### ISSUE TITLE
Errno::EEXIST / File exists @ dir_s_mkdir  on symlinked directories. 

### ISSUE THREAD

**Issue by buggle** [carrierwaveuploader/carrierwave#2076]
Trying to write carrierwave attachments into a symlinked directory fails with: 
`File exists @ dir_s_mkdir ` on the symlinked directory. 

Obviously this is due to [sanitized_file.rb#mkdir!](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L315)
with for `File.exist?` yielding false and then `mkdir_p` failing on the existing parent symlinked directory. 

I experienced this with all the latest versions (ruby 2.3.1 / rails 5.0.0.1 / carrierwave 0.11.2). According to [Stackoverflow](http://stackoverflow.com/questions/26462016/carrierwave-upload-hits-errnoeexist-file-exists-error) this has been a long time around. 

[EDIT: my initial assumption was false that `File.exist?` yields false misleadingly on symlinks]

**Comment by buggle** [comment]
It seems this had to do with some defective file permissions on OS X. Sorry too have bothered.

**Comment by sankalpsingha** [comment]
I am getting the same issue for a the 'public/uploads' directory that is symlinked with my mina deploy. Can you tell me how you resolved your issue?

**Comment by 4268146** [comment]
how to fix?

**Comment by tasawar-hussain** [comment]
> how to fix?

remove the symlinked directory from version control and add it to gitignore

**Comment by 4268146** [comment]
> > how to fix?
> 
> remove the symlinked directory from version control and add it to gitignore

ok
