### ISSUE TITLE
Debug information can not be disabled

### ISSUE THREAD

**Issue by BadAllOff** [carrierwaveuploader/carrierwave#2077]
`  <%= @photo_album.photos.each do |photo| %>
      <%= image_tag photo.thumb.url, class: 'img-responsive img-thumbnail', alt: 'Alt text' %>
  <% end %>`

this code is in view, and this debug info can't be disabled. I can't figure it out where it came from. I use gem from master branch. Maybe there is forgotten ".inspect" there. 10x 

![screenshot from 2016-12-10 08 46 16](https://cloud.githubusercontent.com/assets/13168837/21071414/e3234770-beb8-11e6-914d-373238fe58e8.png)

**Comment by BadAllOff** [comment]
It happens every time I call `.each` method on collection.

**Comment by mshibuya** [comment]
Use `<%` instead of `<%=`.
