### ISSUE TITLE
Image Hosting with Amazon S3 problem

### ISSUE THREAD

**Issue by RichieD83** [carrierwaveuploader/carrierwave#2079]
I keep getting this error message:

/home/ubuntu/workspace/yelp2/config/initializers/carrierwave.rb:2:in `block in <top (required)>': undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)

I've followed all the instructions but it still doesn't work

Please help

**Comment by mshibuya** [comment]
Use 1.0.0.rc or master branch for `fog_provider=` support.

**Comment by RichieD83** [comment]
Sorry, I'm really new to all this. By "1.0.0.rc" are you talking about the name of the gem I should put in my gem file? I don't understand what this means. And what should I do with "fog_provider="

Thanks very much for your help

**Comment by mshibuya** [comment]
In your Gemfile,
```
gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'
```
