### ISSUE TITLE
Deprecation warning from rails regarding use of after_commit

### ISSUE THREAD

**Issue by skatkov** [carrierwaveuploader/carrierwave#2082]
carrierwave version: carrierwave (0.11.2)
railse version: Rails 4.2.7.1

I receive this deprecation warning then i start my project:
```

(called from <class:Survey> at /Users/sk/client/survey_admin/app/models/survey.rb:14)
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

```
all those warning points to this line of code:

`mount_uploader :document, DocumentUploader`

**Comment by skatkov** [comment]
Seems like these need changes:
https://github.com/carrierwaveuploader/carrierwave/blob/c45699c318ca895f89fa3304204e48b5f1c411f1/lib/carrierwave/orm/activerecord.rb#L57-L61

more details here rails/rails#14488 and rails/rails#16537

**Comment by Kacpert** [comment]
Hi @skatkov  This particular warning inform us that behaviour of "`after_commit / after_rollback`" will be changed. 

Right now, when error occurs when Ruby execute `after_commit / after_rollback` ruby will logged that error. In newer version ruby will also stop current execution. 

If this message is annoying you.
Add it to initializers
`ActiveRecord::Base.raise_in_transactional_callbacks = true`
Or to config:
`config.active_record.raise_in_transactional_callbacks = true`

**Comment by arthurnn** [comment]
I guess this could be closed.. seems like a rails config thing, and not a carrierwave issue
