### ISSUE TITLE
not able to upload to aws when using documentation " Making uploads work across form redisplays" rather works locally

### ISSUE THREAD

**Issue by rabisathuaxcid** [carrierwaveuploader/carrierwave#2084]
I am trying to use the documentation for " Making uploads work across form redisplays" .I have a logo to be uploaded and shown in the next page for preview. This works perfectly when using the path inside the application but not with aws. When I use aws it creates a logo url as https://s3.amazonaws.com/devtestbucket/tmp/1482273992-12777-3371/bmi_chart.jpg
but the files does not get uploaded to the /tmp/1482273992-12777-3371/ folder.
I have pasted the logo uploader created

`class LogoUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  include CarrierWave::MimeTypes
  include Sprockets::Rails::Helper
  
  storage Myapp.setting(:carrierwave, :storage)
  
  def remove!
    
  end
  def cache_dir
    '/tmp/onboard'
  end
  def storage_dir
    "Images"
  end

  def store_dir
    "images"
  end
  
 
  def extension_white_list
    %w(jpg jpeg gif png)
  end

  def content_type_whitelist
    /image\//
  end

 
end
`

**Comment by klebervirgilio** [comment]
I have a similar issue, apparently the uploader isn't caching the file.

**Comment by mshibuya** [comment]
Add `cache_storage :fog` or use master branch, which has been changed to use the same storage for cache_storage and storage(see 629afecbaeccd2300e4660b78ee36bd95dd845c5).
