### ISSUE TITLE
Any plan to support Japanese URL?

### ISSUE THREAD

**Issue by toshimaru** [carrierwaveuploader/carrierwave#2086]
When I try to download URL which includes Japanses (e.g. http://はじめよう.みんな/assets/img/pc/top/about_img_girl.gif ), I get the following error:

```
CarrierWave::DownloadError (could not download file: Failed to open TCP connection to %E3%81%AF%E3%81%98%E3%82%81%E3%82%88%E3%81%86.%E3%81%BF%E3%82%93%E3%81%AA:80 (getaddrinfo: nodename nor servname provided, or not known)):
```

Any plan to support Japanese URL? 

Using [addressable](https://github.com/sporkmonger/addressable) instead of `URI` fixes this issue. I fixed this issue on my forked repo, so I'm happy to send PR.

Thanks.

**Comment by Rob117** [comment]
Can I get an update on this? This would be a crazy useful feature for a lot of people.
