### ISSUE TITLE
Carrierwave 1.0 dependency resolving too strictly with Bundler?

### ISSUE THREAD

**Issue by deep-spaced** [carrierwaveuploader/carrierwave#2090]
Good morning!

Today I tried to upgrade one of my Rails 4.2.7.1 apps from 0.11.2 to 1.0.0. After updating the Gemfile and running `bundle update carrierwave`, I received the following error: 

```shell
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    carrierwave (~> 1) was resolved to 1.0.0, which depends on
      activemodel (>= 4.0.0) was resolved to 4.0.13, which depends on
        activesupport (= 4.0.13)

    carrierwave (~> 1) was resolved to 1.0.0, which depends on
      activesupport (>= 4.0.0)

    liquid-rails was resolved to 0.1.3, which depends on
      rails (>= 3.2) was resolved to 4.2.7.1, which depends on
        activesupport (= 4.2.7.1)
```

I only have activesupport 4.2.7.1 installed, not 4.0.13. Is Bundler trying to resolve the carrierwave dependency on activesupport to _only_ the 4.0.x releases? I see the Travis tests that clearly run Rails 4.2, so I'm a little confused here. Any thoughts? Thanks!

**Comment by airjoshb** [comment]
I am also having the same issue

**Comment by lavrovdv** [comment]
Execute `bundle install` fix issue for me

**Comment by deep-spaced** [comment]
Removing `carrierwave_backgrounder` and deleting all my local gems (yay rbenv!) made `bundle install` work correctly. Thanks, all!

**Comment by joshirashmics** [comment]
Why is this issue closed.. What if we just want to upgrade carrier-wave and not all the other gems.
