### ISSUE TITLE
gem dependency JSON - does not work with ruby 2.4.0

### ISSUE THREAD

**Issue by fffdan** [carrierwaveuploader/carrierwave#2095]
See rails issue [Rails 27450](https://github.com/rails/rails/issues/27450) for more info - it seems that the JSON gem does not work with Ruby 2.4.0. For the time being the Rails team are simply removing the dependency - carrierwave has a similar dependency so looks like the same problem.

**Comment by fffdan** [comment]
...there's a [comment](https://github.com/flori/json/issues/308) on the JSON gem gitub page that JSON is included in Ruby >1.9 and that the dependency can be removed altogether from other gems.

**Comment by connorshea** [comment]
JSON isn't a direct dependency of carrierwave, I assume the problem is that carrierwave depends on activesupport, so until activesupport drops json as a dependency in 4.2.8 it won't work.

**Comment by fffdan** [comment]
Thanks for looking at it, appreciated.

**Comment by nachokb** [comment]
I think the problem is `fog` which removes its `json` dependency in 2.0, but that's been in `pre` for 2 years already…

**Comment by mshibuya** [comment]
Not an issue with CarrierWave anyway.
