### ISSUE TITLE
convert to 0 byte file and error raised when uploaded multi page pdf

### ISSUE THREAD

**Issue by znz** [carrierwaveuploader/carrierwave#2096]
http://www.rubydoc.info/github/minimagick/minimagick/MiniMagick/Image#format-instance_method
Default of `MiniMagick::Image#convert`'s page is `0`, but [carrierwave-1.0.0's default is nil](https://github.com/carrierwaveuploader/carrierwave/blob/9ef68325dd5ea465b4d340af9a9def10934cd677/lib/carrierwave/processing/mini_magick.rb#L105).

This causes 0 byte converted file.

```
% irb -r irb/completion --simple-prompt
>> require 'mini_magick'
=> true
>> image = MiniMagick::Image.open('spec/fixtures/multi_page.pdf'); nil
=> nil
>> image.format('jpg', nil); nil
=> nil
>> image.write('out.jpg')
=> nil
>> File.size('out.jpg')
=> 0
```

When uploaded using rails, error message is `` `identify /path/to/tmp/1483600482-61224-0001-7223/thumb/file.jpg` failed with error:
identify: Empty input file `/path/to/tmp/1483600482-61224-0001-7223/thumb/file.jpg' @ error/jpeg.c/JPEGErrorHandler/322.``.

**Comment by znz** [comment]
I'm using carrierwave with following `process`.
This can upload multi page pdf with carrierwave < 1.0.0, but carrierwave 1.0.0 causes error in `convert`.

```ruby
class AttachmentUploader < CarrierWave::Uploader::Base
    include CarrierWave::MiniMagick
  include Sprockets::Rails::Helper
  storage :file

  process :rotate, if: :image?

  def rotate
    manipulate! do |image|
      image.auto_orient
      image
    end
  end

  version :thumb do
    process resize_to_fit: [200, 200]
    process convert: 'jpg', if: :pdf?

    def full_filename(for_file = model.source.file)
      super.sub(/\.pdf\z/i, '.jpg')
    end
  end

  def pdf?(new_file)
    /\.pdf\z/i =~ new_file.filename
  end
  protected :pdf?

  def extension_whitelist
    %w(jpg jpeg gif png pdf)
  end

  def content_type_whitelist
    [
      /\Aimage\//,
      'application/pdf',
      'text/plain', # some pdf is detected as text/plain
    ]
  end
end
```

**Comment by jdongelmans** [comment]
+1, also having the same issue

**Comment by mrsellars** [comment]
Had the same issue, you have to add an additional default page parameter in the process convert call:

`process convert: [:png, 0]`

The problem is an API change which was introduced in: https://github.com/carrierwaveuploader/carrierwave/commit/a32dd2a827ea019bd9c60b7fc8b9e3c7ca2b09dc
