### ISSUE TITLE
Eager loading fog in development

### ISSUE THREAD

**Issue by paulodeon** [carrierwaveuploader/carrierwave#2100]
Should we be eager loading Fog in development?

The reason for https://github.com/carrierwaveuploader/carrierwave/issues/1198 was to improve the first fog hit at the expense of initial load time, great for production, not really great for development.

Additionally if for whatever reason the cloud storage is down or inaccessible your app doesn't boot, again not great for development.

I would suggest only eager loading in production or adding an eager_load config option

**Comment by mshibuya** [comment]
Merging into #2395.
