### ISSUE TITLE
Caching a file locally unexpectedly runs process callbacks

### ISSUE THREAD

**Issue by multiplegeorges** [carrierwaveuploader/carrierwave#2101]
Hi,

I am storing my files on S3 using Fog through CarrierWave. Using CarrierWave 0.11.

```ruby
  class XmlAsset < Asset
    mount_uploader :file, XmlUploader

    def local_file
      uploader = file
      uploader.cache_stored_file! # This runs the process callbacks
      uploader.send(:cache_id=, CarrierWave.generate_cache_id)
      cache_name = uploader.cache_name
      uploader.retrieve_from_cache!(cache_name)
      uploader.file
    end
  end
```

**Issue 1)** I have to force the cache_id assignment. If I do not, then @cache_id is always nil. 

**Issue 2)** Nothing in this code snippet indicates to me that processing will happen in the background. This is a potentially very expensive side-effect of caching a file. This to me seems like a bug.

I simply want to get the local/on-server SanitizedFile instance without any processing. I am using a gem that take a string path to a local file, I can't pass it a FileIO-like object, unfortunately. I also want to avoid doing my own Tempfile creation and handling.

Thoughts? and thanks for any help on doing this in a better way.

**Comment by schwarzh** [comment]
multiplegeorges - Did you ever figure out a solution for this?  I'm running into the exact same issue, and I thinking I may use a different method of pulling a file to local that doesn't involve Carrierwave's cache_stored_file method.

Thanks,
Brad

**Comment by multiplegeorges** [comment]
@schwarzh I can't remember exactly, but I'm pretty sure we created a custom class to wrap up Tempfile and did the downloading and handling ourselves.

These days I've pretty much switched to using Shrine for file attachment handling. It's very good at what it does and leaves a lot of room for customizing behaviour.

**Comment by schwarzh** [comment]
Ok, thanks for the response!
