### ISSUE TITLE
Image translation missing: en.errors.messages.mini_magick_processing_error

### ISSUE THREAD

**Issue by gichuru** [carrierwaveuploader/carrierwave#2102]
I am getting this error while on one branch but while using a different computer /branch, it's working perfectly well....

The error disappears when I hash out #process :resize_to_fit => [200, 300], but of course that does not resize my images, any help?

**Comment by gichuru** [comment]
This was a real pain for a couple of days. I managed to solve it by reinstalling the carrierwave gem again

    Go to your gemfile, delete gem 'carrierwave'
    Run bundle install
    Go back to gem file and add gem 'carrierwave'
    Run bundle install
    Run rails s
    Add a new image.

Best of luck!

**Comment by VoTaiTri** [comment]
@gichuru 
i tried to do it, in my local everything's ok, but when i deploy to server (use puma) i get this error
my Gemfile like : 
```ruby
gem "carrierwave"
gem "mini_magick"
gem "fog"
```
and uploader : 
```ruby
class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :fog
  process resize_to_fit: [128, 128]

  ...
end
```

**Comment by mshibuya** [comment]
Make sure to install ImageMagick in your production server, too.

**Comment by BillionaireZ** [comment]
@gichuru Unfortunately that didn't quite work for me.
I even uninstalled the gem and reinstalled it, keeps giving the same error.

Am on the latest version of rails.

**Comment by andrei-blaj** [comment]
I ran a brew install of imagemagick and that did the trick.

> _brew install imagemagick_
