### ISSUE TITLE
Update content type of existing files

### ISSUE THREAD

**Issue by mitfik** [carrierwaveuploader/carrierwave#2104]
Hi all,

Just updated lately my version of carrierwave from 0.10.0 to 1.0.0 to support mime-types out of box.
The problem which I am facing right now is that with old gem we didn't set mime-types manually so most of the files have wrong content type. Is there a easy way to update content type for existing files? 

All files are stored on s3 so one of the solution will be to use cmd line interface and just update all meta data but in my opinion will be much easier to do it through carrierwave. 

Thanks a lot for any feedback.

**Comment by mshibuya** [comment]
I guess there's no hustle-free way to do this, sadly.
