### ISSUE TITLE
multiple mounts: ApplicationRecord instance "to_json" result is weird.

### ISSUE THREAD

**Issue by ejvalmores** [carrierwaveuploader/carrierwave#2106]
I am trying to make an API only Rails app (Rails 5.0.1).  In my Service model I have something like: 
```
class Service < ApplicationRecord
   mount_uploaders :photos, ServicePhotoUploader
end
```

I noticed this issue while I was making the test script for my ServicesController.  However, I managed to replicate it in the test environment console.

```
> service = Service.new()
> service.photos = [ Rack::Test::UploadedFile.new(File.join(Rails.root, 'spec', 'fixtures', 'images', 'altia.jpg')) ]
> service.save!
> service.to_json
=> "{\"id\":3053,\"photos\":[{\"url\":\"/uploads/service/photos/3053/altia.jpg\"}]}"
```

The result looks ok.  But when I do `service.reload` the result looks weird.
```
> service.reload
> service.to_json
=> "{\"id\":3053, \"photos\":[{\"url\":\"/uploads/service/photos/3053/%5B%22altia.jpg%22%5D\"}]}"
```

Decoded, the 'url' value loooks like:
```
> URI.decode "/uploads/service/photos/3053/%5B%22altia.jpg%22%5D"
=> "/uploads/service/photos/3053/[\"altia.jpg\"]"
```

This is causing an issue when I to `JSON.parse( respond.body )` in my test script.  

Is this the expected result? or am I doing something wrong? 

Thanks!

**Comment by mshibuya** [comment]
Not reproducible here, how does your uploader and test code look like?

**Comment by ejvalmores** [comment]
Hi, 

I can't replicate this in the latest version anymore.  

Thanks!
