### ISSUE TITLE
Update AWS documentation in Readme.md file

### ISSUE THREAD

**Issue by meganedesigns** [carrierwaveuploader/carrierwave#2109]
When following the documentation code for implementing carrierwave with AWS, the following error is received:
_Could not find generator 'uploader'. Maybe you meant 'helper', 'jbuilder' or 'model'_

This issue has been documented by others [here](https://github.com/carrierwaveuploader/carrierwave/issues/2023) and [here](https://github.com/fog/fog/issues/3429).

Recommend updating the configuration block example code under the [Using Amazon S3](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3) section of the Readme.md file by adding `config.storage = :fog` after the `config.fog_credentials` hash.

I'm willing to make the change.

**Comment by mshibuya** [comment]
ca201ee2ceebe2d916be3bc1396fe381cc93afd7 resolved this.
