### ISSUE TITLE
Customize your version file names - broken in v 1.0.0

### ISSUE THREAD

**Issue by oslyak** [carrierwaveuploader/carrierwave#2114]
Next code works fine in 0.11.2
And doesn't work in 1.0.0

    class ImageUploader < CarrierWave::Uploader::Base
      include CarrierWave::RMagick
      include CarrierWave::Processing::RMagick
    
      storage :file
    
      def extension_white_list
        %w(jpg jpeg gif png)
      end
    
      process :strip   # Strip comments and other meta-data
      process resize_to_limit: [1280, 1024]
      process :store_dimensions
    
      def cache_dir
        '/tmp/CarrierWave'
      end
    
      def watermark
        watermark_original = Magick::Image.read("#{Rails.root.to_s}/app/assets/images/watermark.png").first
        watermark_resized = watermark_original.resize_to_fit(model.width)
        manipulate! do |img|
          img.composite(watermark_resized, Magick::SouthWestGravity, 15, 15, Magick::OverCompositeOp)
        end
      end
    
    private
    
      def store_dimensions
        if file && model
          img = ::Magick::Image::read(file.file).first  #RMagick
          model.width  = img.columns
          model.height = img.rows
          model.pixels = model.width * model.height
          if model.class.column_names.include?("position") and model.class.name.start_with?('Images::')
            model.position = Time.now.to_i
          end
        end
      end
    
    end
    
And next class with versions

    class ProductImageUploader < ImageUploader
    
      def store_dir
        "images/products/#{model.id}"
      end
    
      version :full_size do
        process :watermark
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','')
        end
      end
    
      version :adwords do
        process resize_to_fit: [300, 300]
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','adwords_')
        end
      end
    
      version :preview, from_version: :full_size do
        process resize_to_fit: [350, 350]
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','preview_')
        end
      end
    
      version :thumbnail do
        process resize_to_fit: [240, 240]
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','thumbnail_')
        end
      end
    
      version :mini do
        process resize_to_fit: [90, 90]
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','mini_')
        end
      end
    
      version :micro do
        process resize_to_fit: [75, 75]
        def full_filename(for_file = model.logo.file)
          for_file.gsub('without_water_mark_','micro_')
        end
      end
    
      def filename
        product = Product.unscoped.where(id: model.product_id).first
        "without_water_mark_#{product.permalink_ua}.#{file.extension}"
      end    
   
    end

All file names proceed correct, but files  absent.

For example let permalink="argox"

Only one file exists and it should be original file, but it proceeded with resolution of version :micro
/images/products/2670/without_water_mark_argox.jpg

**Comment by mshibuya** [comment]
Still having the issue? Could you provide minimal reproducible code?

**Comment by mshibuya** [comment]
Please reopen on update.
