### ISSUE TITLE
Rails 5.1 deprecation warning

### ISSUE THREAD

**Issue by IamNaN** [carrierwaveuploader/carrierwave#2115]
I'm upgrading from Rails 4.2 to 5.1, haven't tried this in 5.0. My tests are flooded with rails deprecation warnings in carrierwave.

```DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from store_previous_changes_for_image at /Users/dave/.rvm/gems/ruby-2.3.3@rails5edge/gems/carrierwave-1.0.0/lib/carrierwave/mount.rb:189)```

Mount is pretty meta, so I'm having a hard time grokking it but if you want I can try some more.

**Comment by mysmallidea** [comment]
Pulling from master, the deprecation warnings go away.
