### ISSUE TITLE
No such file or directory @ rb_sysopen when uploaded file has the same name as full_filename

### ISSUE THREAD

**Issue by dan** [carrierwaveuploader/carrierwave#2120]
If a user uploads a file that has the same name as a destination file name defined by `full_filename`, for example:

```
  version :small do
    def full_filename (for_file = model.avatar.file)
      "avatar_small.jpg"
    end
  end
```

The original file `avatar_small.jpg` will no longer be there (being removed after store) and we will see the no such file error.

**Comment by dan** [comment]
One year later, any thoughts?

**Comment by mshibuya** [comment]
I think you're configuring CarrierWave to save user-uploaded file in the same location as the store_dir. Pasting full source code of your uploader will help track down the issue.
