### ISSUE TITLE
File still attempts to upload again while using _cache

### ISSUE THREAD

**Issue by filipegorges** [carrierwaveuploader/carrierwave#2122]
Hello, 

I'd like to cache user's uploads so that they don't have to upload their files again in case of validation errors on the other fields of the form, but following the documentation and other issues on StackOverflow, I haven't been successful at it.

Is there an issue with my configuration?

This is my form:
````
 # retention_environments/_form.html.erb
 <%= f.file_field :document %>
 <%= f.hidden_field :document_cache, value: @retention_environment.document_cache %>
````

This is my model:
````
# retention_environment.rb
class RetentionEnvironment < ApplicationRecord
  attr_accessor :document_cache
  mount_uploader :document, DocumentUploader
 
  (...)
end
````
This is my controller:
````
 # retention_environments_controller.rb
 def retention_environment_params
    params.require(:retention_environment).permit(:project_id, :document,
     :remove_document, :document_cache, ...)
 end
````

Thanks!

**Edit:**
This is a StackOverflow question, demonstrating the same issue, from 2013:
[CarrierWave not saving upload after form redisplay](http://stackoverflow.com/questions/9783904/carrierwave-not-saving-upload-after-form-redisplay)

I'm running Rails 5.0 and Carrierwave 1.0.0

**Comment by Quintasan** [comment]
Running into exact same problem. My field is named `campaign_image`. no matter what I do `campaign_image_cache` is empty. From what can I see in `lib/carrierwave/mount.rb` there's no need to add `attr_accessor :#{column}_cache` since it's defined when mounting the uploader.
