### ISSUE TITLE
Add v1.0.0 release notes

### ISSUE THREAD

**Issue by atz** [carrierwaveuploader/carrierwave#2123]
Last release notes are from 2014, so it would be good to communicate what the major differences are now that `1.0.0` has dropped:
https://github.com/carrierwaveuploader/carrierwave/releases

Ideally including any migration path that might need to be followed.

**Comment by Deckluhm** [comment]
You might want to check the [CHANGELOG.md](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md).

**Comment by brunoocasali** [comment]
@atz are u talking about creating a new "Latest release" too? I think is a good thing 👍

**Comment by mshibuya** [comment]
It's better to have it but if I do so 1.0.0 will appear at the top of latest releases, because the release feature doesn't support setting the release date.
https://github.com/community/community/discussions/5447
It'll confuse users, so I don't do it for now. Please refer to the CHANGELOG.md.
