### ISSUE TITLE
Rails 5.1.0.beta1 deprecation

### ISSUE THREAD

**Issue by CvX** [carrierwaveuploader/carrierwave#2129]
Rails 5.1 deprecates ActiveRecord's `changes` and other related methods (e.g. `attribute_changed?`). See: https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81 and https://github.com/rails/rails/commit/ef993d36bc952046f312a3695617eaa6d5fe352e

Here's one of the warnings:
```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.
```

Offending lines in Carrierwave gem are:
https://github.com/carrierwaveuploader/carrierwave/blob/62667955c7ba3d2789944b0598f5b3c79ae1b3ea/lib/carrierwave/mount.rb#L189
and
https://github.com/carrierwaveuploader/carrierwave/blob/62667955c7ba3d2789944b0598f5b3c79ae1b3ea/lib/carrierwave/mount.rb#L343

What's the strategy for handling such deprecations? `if respond_to?(:saved_changes) … else …`?

**Comment by Deckluhm** [comment]
Duplicate of https://github.com/carrierwaveuploader/carrierwave/issues/2115.

**Comment by CvX** [comment]
By bad, somehow missed it when browsing issues list earlier!
