### ISSUE TITLE
Conditional versions checking everytime uploader called?

### ISSUE THREAD

**Issue by adysson** [carrierwaveuploader/carrierwave#2132]
Hi,
after update of Carrierwave from 0.6.2 to 1.0.0, our app started to be painfully slow.
We use conditional versions in an uploader i.e. `Object#logo`. By method `is_big_enough?`, it checks source image resolution (using mini_magick gem) before versions `:medium` and `:large` are created - to prevent increasing of image resolution i.e. from 200x200px to 400x400px.
There are other versions without conditionals: `:small` and `:semi_small`
In Carrierwave v. 0.6.2, if I call `object.logo.small.url`, conditional method `is_big_enough?` is not called.
In Carrierwave v. 1.0.0, conditional method `is_big_enough?` seems to be called everytime.

In a big page with 100+ calls to various instances of the uploader, loading of page starts to be painfully slow, because `is_big_enough?` uses mini_magick which touches HDD/SDD.

Is this desired behavior because of some reason or it happens by mistake?
Thank you

**Comment by francisneedham** [comment]
same problem here

**Comment by marcek** [comment]
Have the same problem currently using version 2.2.2

**Comment by jasonfine** [comment]
Bumping, this needs input from the authors.

**Comment by mshibuya** [comment]
The change itself came from #1351, but makes some sense.
So what I recommend is to [get dimensions of the file and store it in some model columns on processing](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Get-image-dimensions), so the dimensions can be checked with little overhead later.
