### ISSUE TITLE
Callback remove are no longer triggered after deleting the original file.

### ISSUE THREAD

**Issue by mcoiffier** [carrierwaveuploader/carrierwave#2135]
Hi,
I'm using CarrierWave 1.0.0  with ckeditor 4.2.2, and my Rails version is 5.0
When I delete the original file, the deletion does occurs, but this prevents the callback `after: remove` from triggering. 
In my uploader "TRIGGER BEFORE_REMOVE_TEST" is never displayed.

This has as consequences that the callbacks `after: remove,: remove_versions!` of the `CarrierWave :: Uploader :: Versions` is never triggered and therefore the version files are not deleted.

Did I miss something ?

My uploader:
```
class CkeditorPictureUploaderDevelopment < CarrierWave::Uploader::Base
  include Ckeditor::Backend::CarrierWave
  include CarrierWave::MiniMagick
  include CarrierWave::MiniMagick::AddOn

  after :store, :remove_original_file
  after :remove, :test_before_remove

  storage :file

  def store_dir
    "uploads/ckeditor/pictures"
  end

  process :extract_dimensions

  def filename
    "#{Time.zone.now.to_i}.#{file.extension}" if original_filename.present?
  end

  version :thumb do
    process resize_to_fill: [118, 100]
  end

  version :progressive do
    process resize_to_limit: [800, 800]
    process interlace: :Plane
  end

  version :content do
    process resize_to_fill: [320, 260]
  end

  def extension_white_list
    Ckeditor.image_file_types
  end

  def remove_original_file(file)
    if self.version_name.nil?
        self.file.delete if self.file.exists?
    end
  end

  def test_before_remove
    puts "TRIGGER BEFORE_REMOVE_TEST"
  end

end
```

**Comment by pjforde1978** [comment]
@mcoiffier did you ever figure this out? I seem to be having the same issue.

When I issue an object.remove_image! it returns an empty array. The model is marked as dirty but the CarrierWave mounted object is still intact. In fact, it runs an update and the supposedly deleted value gets re-saved.

A mystery, to be sure.

**Comment by tonycchung** [comment]
@pjforde1978 you ever figure it out? I'm working on an opposite problem - being able to successfully upload a picture.

I did notice your code did not update `extension_whitelist` 

`https://github.com/carrierwaveuploader/carrierwave/pull/1819`

**Comment by pjforde1978** [comment]
@tonycchung it's been a while but I did figure out the best strategy for me. The takeaway is that the library has some non-obvious logic and non-obvious naming; if there's an easier way to delete an attachment than:

```
model.remove_image!
model.save
```

... I couldn't figure it out. You have to mark it as deleted (with the bang) and then save the model. This is the only way I could remove it from S3 and leave the attribute as nil after a save operation.

Note that in the above example, the attachment is mounted as 'image'.

I'm not at all familiar with the functionality of extension_whitelist, unfortunately. This was not a factor in my project.

**Comment by tonycchung** [comment]
thanks for the response! there was an API change with carrierwave 1.0.0 where `extension_white_list` was renamed to `extension_whitelist` which may have been applicable to OP.

I'm having more of an issue with a ckeditor integration atm which I think is specific to ckeditor 4.x.x and carrierwave 1.x.x it seems.

cheers

**Comment by pjforde1978** [comment]
It might make sense to lock to an earlier version of the gem. It hasn’t
fundamentally changed in years.

**Comment by tonycchung** [comment]
yes. we were on 0.11.0 but we're trying to upgrade to Rails 5.1 and it seems officially supported in this gem's 1.1.0 version

perhaps this isn't the actual case, I may try it out to see what I end up with.

Thanks
