### ISSUE TITLE
`uploader.cache!` loads entire contents of file into memory

### ISSUE THREAD

**Issue by vergenzt** [carrierwaveuploader/carrierwave#2136]
I've been encountering this in production with 1-2 GB uploads and it's causing background processors to crash. :( (They `cache!` the file first from AWS in order to do local processing.)

The load happens at [this line](https://github.com/carrierwaveuploader/carrierwave/blob/v1.0.0/lib/carrierwave/uploader/cache.rb#L81):

```rb
def sanitized_file
  _content = file.read

  # ...

end
```

I've been trying to look around and see if I can figure out how to fix it, but I've gotten a bit lost in the codebase and am not sure where this needs to be fixed.

Why does the whole file get read into the sanitized file? What's the _purpose_ of the sanitized file here in the first place?

**Comment by vergenzt** [comment]
Related to:
 - #2016 
 - #1780
 - #1529
 - #1523
 - #795
 - #467
 - #413

**Comment by thauburger** [comment]
+1

**Comment by oponce1611** [comment]
+1

**Comment by a-barbieri** [comment]
+1

**Comment by thucnguyen** [comment]
+1
