### ISSUE TITLE
Original filename not persisted across form reload

### ISSUE THREAD

**Issue by yellow-cpu** [carrierwaveuploader/carrierwave#2137]
The following code works when before cache is called and stores the original filename on the model:
```
def save_original_filename(file)
  model.original_filename ||= file.original_filename if file.respond_to?(:original_filename)
end
```
However after a form reload (which may occur due to a user input error for example) the original filename is no longer stored on the model and it isn't stored on the new file cache objects either.

Therefore if you want to save the original filename after caching the files it is necessary to extract the name from the file cache's details.

Would it not be beneficial to store the original filename within the cached files as well so that after a cache it can be easily accessed?

**Comment by mshibuya** [comment]
Don't look for `#original_filename` in SanitizedFile. Use [it in Uploader](https://github.com/carrierwaveuploader/carrierwave/blob/2e8bfc042ded9b51a8129ed41baf9283fd67aef6/lib/carrierwave/uploader/cache.rb#L199) instead.

```
model.original_filename ||= original_filename if original_filename
```
