### ISSUE TITLE
specs with expectations on FileUtils.rm_rf fail

### ISSUE THREAD

**Issue by snex** [carrierwaveuploader/carrierwave#2138]
We are using carrierwave to handle file uploads, however after recently upgrading to 1.0.0, unrelated specs that used FileUtils.rm_rf are suddenly failing.

Here is the spec, related to a custom library that generates sitemaps:

```ruby
it 'empties out current sitemaps' do
  expect(FileUtils).to receive(:rm_rf).with(Dir.glob("#{Rails.root}/public/uploads/sitemaps/*"))
  described_class.generate_sitemaps
end
```

rspec fails with:

```
  1) Sitemap.generate_sitemaps empties out current sitemaps
     Failure/Error: File.open(@tempfile) { |f| uploader.store!(f) }

       FileUtils received :rm_rf with unexpected arguments
         expected: ([...expected files...])
              got: ("/rails/path/tmp/1489163249-29926-0001-5711/")
```

I am able to get the spec to pass by adding "allow(FileUtils).to receive(:rm_rf)" at the top, but this seems to be a code smell since my spec must now be aware that carrierwave is doing some kind of magic in the background that calls FileUtils.rm_rf.

**Comment by mshibuya** [comment]
That's a smell in your test code, please do not blame us.
