### ISSUE TITLE
Can't set remote_#{column}_url in a rails job

### ISSUE THREAD

**Issue by dyc3** [carrierwaveuploader/carrierwave#2145]
~~**Edit:** Seems like you can't access the mounted uploader at all in a rails job.~~

This is the model I'm trying to work with:

https://gist.github.com/dyc3/fb6e0bb96dc5da2edd917699bb6c7d5e

This is the job I'm using. (Irrelevant parts omitted.)

https://gist.github.com/dyc3/98c48176d6f15a34c65914aeddb4f4e9

**Edit:** I'm running the job like this: `rails runner -e development 'SyncWithRssJob.perform_now'`

**Comment by dyc3** [comment]
If I comment out the `mount_uploader` in my model, and then run the job, I can set the `thumbnail` (the column I am using) as a string. This is not an ideal solution, but it works.

**Comment by mshibuya** [comment]
Do not mix up `mount_uploaders` with `mount_uploader`.
