### ISSUE TITLE
Carrierwave won't generate URL for conditional versions

### ISSUE THREAD

**Issue by bjedrocha** [carrierwaveuploader/carrierwave#2148]
I'm using carrierwave's [conditional versioning](https://github.com/carrierwaveuploader/carrierwave#conditional-versions) to perform version processing in a background job. Here is my uploader class

```
class LogoUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  attr_writer :process_delayed

  def process_delayed?(_img = nil)
    !!@process_delayed
  end

  # directory files are stored when running in development
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :optimized, if: :process_delayed? do
    process resize_to_limit: [nil, 200]
  end
end
```

In the background job, I simply set `model.logo.process_delayed = true` prior to running `model.logo.recreate_versions! :optimized`. This works in that it creates my optimized version but then if I try `model.logo.optimized.url` it simply returns `nil`. Interestingly enough, if I just remove the condition from the `version` block, the version url then works. Thus it appears that conditions on versions get re-evaluated when generating the URL but for the life of me I can't find what in the code determines this. Any help would be appreciated.

**Comment by MGPalmer** [comment]
I'm having the same issue :(

**Comment by MGPalmer** [comment]
If I change this line:
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L290
to use "versions" instead of "active_versions", I get the URLs back as it was before.

I'm reluctant to use it for me, though, because this behaviour is explicitly specced...

**Comment by dnswus** [comment]
I'm also having this issue on `1.0` and `1.1`. Have to switch back to `0.11` to make it work.

**Comment by piotrze** [comment]
+1

**Comment by ahmedrayhan** [comment]
is anyone still facing this issue?

**Comment by MGPalmer** [comment]
Sorry, I don't remember if we fixed this back then...

**Comment by victmask** [comment]
it seems to be done intentionally with https://github.com/carrierwaveuploader/carrierwave/pull/1351

**Comment by mshibuya** [comment]
This is how versions are supposed to work.

To achieve what you want, you'll need to persist the processing status into the model. The pseudo-code will look like:

```ruby
class LogoUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  def processed?(_img = nil)
    model.logo_processed
  end

  # directory files are stored when running in development
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :optimized, if: :processed? do
    process resize_to_limit: [nil, 200]
  end
end

# in controller
model.logo = params[:file]
model.save

# in the background job
model.logo_processed = true
model.save
model.logo.recreate_versions!
```

Or you can simply use the existing solutions, like [carriervave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder).
