### ISSUE TITLE
Carrierwave fails on case insensitive filesystems.

### ISSUE THREAD

**Issue by pluff** [carrierwaveuploader/carrierwave#2155]
[Carrierwave compares file via Ruby](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L200) while moving optimized file. At the same time OS filesystem can be  case insensitive which leads to FileUitls exception.
```
ArgumentError - same file: /tmp/1491470909-25848-0001-0775/optimized/64x44_copy.JPG and /tmp/1491470909-25848-0001-0775/optimized/64x44_copy.jpg
```

Steps to reproduce: try to upload `abc.JPG` file on case insensitive file system (e.g. MacOS default fs)

**Comment by mshibuya** [comment]
Nothing strange in it, it's up to your app.
