### ISSUE TITLE
cache_dir not being accessed.

### ISSUE THREAD

**Issue by dvodvo** [carrierwaveuploader/carrierwave#2156]
I have the same application on 2 VPSes, Ubuntu 14.04 and 16.04.  The former runs fine, while the code deploys to both.  However, the newer instance will handle some uploads, but not those being created for an uploader for handling signatures as file_attachments with error

No such file or directory @ rb_sysopen - tmp/58iniziofirma.png

That mode specifies:

  def generate_firma
    unless self.signature.nil?
      instructions = self.signature.map { |h| "line #{h['mx'].to_i},#{h['my'].to_i} #{h['lx'].to_i},#{h['ly'].to_i}" } * ' '
      path_signature_image="tmp/"+self.intervento_id.to_s+self.sequence+"firma.png"
      puts path_signature_image
      system "convert -size 1010x395 xc:transparent -stroke blue -draw '#{instructions}' #{path_signature_image}"
      self.firma = File.open(path_signature_image)
    end
  end

Line "self.firma[...]" is pointed to as the guilty party.

All tmp directories at the root level, user level and at the release level have identical permissions.

drwxrwxrwt  (root level)
drwxrwxr-x  (user level)
drwxrwxr-x  (current release level)

cache_dir is NOT defined in the uploader.  I believe this to be inconsequential as on the Ubuntu 14.04 instance, the files are in the 'tmp' directory.

The relevant uploader file has

class FirmaUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :aws
  def store_dir
    "tasks/#{model.class.to_s.underscore}"
  end
  version :base do
    process :resize_to_limit => [240, 60]
  end
  def extension_white_list
    %w(jpg jpeg gif png)
  end
end

I fail to see where this inconsistency is stemming from.

**Comment by mshibuya** [comment]
Closing since seemingly too environment-dependent. Please reopen if you still have this issue.
