### ISSUE TITLE
Reprocessed image not upload to s3

### ISSUE THREAD

**Issue by nichthinkof30** [carrierwaveuploader/carrierwave#2161]
I'm using
ruby 2.3.1
fog 1.22.0
carrierwave 1.10.0

It is a strange issue because previously don't have any issue until I upgraded the app into 2.3.1.

```
image.cache_stored_file!
image.retrieve_from_cache!(image.cache_name)
image.edited_version.editing_image  // this is the place where I process my image
image.recreate_versions! :edited_version
self.save!
```

Debug:

```
image.cache_stored_file!
image.retrieve_from_cache!(image.cache_name)
puts image.file.inspect
// this return my local tmp for original version
image.recreate_versions! :edited_version
puts image.edited_version.file.inspect
// this return my aws fog object, is it suppose to be this way?
self.save!
```
When I do image.recreate_versions! , then it will automatically remove my processed image which it is in the tmp directory. When I proceed to save!, I guess it is not saving the correct file? 

```
image.cache_stored_file!
image.retrieve_from_cache!(image.cache_name)
puts image.file.inspect
// this return my local tmp for original version
puts image.edited_version.file.inspect
// this return my local tmp for edited_version version
self.save!
// I assume now I save, it should upload the tmp file to aw3? but it did not upload
```

Is anyone encounters this issue? I got the same piece of code in another app, but it works properly in the other app, I change to the same gem version also and even tried to downgrade to a different ruby version (2.2.2)

**Comment by mshibuya** [comment]
Do not expect a cached file to locally accessible. See https://github.com/carrierwaveuploader/carrierwave/issues/2262#issuecomment-759912837.
