### ISSUE TITLE
NoMethodError: undefined method `map' for #<ActionDispatch::Http::UploadedFile

### ISSUE THREAD

**Issue by NSLog0** [carrierwaveuploader/carrierwave#2164]
Hi, I'm try to create multiple data at once and attached image each of data so look at my postman parameter 

<img width="1123" alt="screen shot 2560-04-26 at 2 30 07 am" src="https://cloud.githubusercontent.com/assets/1640817/25404244/56cf6376-2a29-11e7-9851-8f698ee3f74d.png">

as you see I try in one array of data to prof is work but I got error "NoMethodError: undefined method `map' for #<ActionDispatch::Http::UploadedFile"

Here is my controller code 

```ruby
def create
    create_param = {}
    params[:form].each { |f|
      r = Reward.new
      r.name = params[:form][f][:name]
      r.discription = params[:form][f][:discription]
      r.reward_type = params[:form][f][:reward_type]
      r.is_getbyself = params[:form][f][:is_getbyself]
      r.rule = params[:form][f][:rule]
      r.image_url = params[:form][f][:image_url]
      r.save
    }
  end
```

Model code 

```ruby
class Reward < ApplicationRecord
  mount_uploaders :image_url, ImageUploader
end
```
so what wrong and any suggestion ?

Ps. So I already use "rails generate uploader Image"

**Comment by colosam** [comment]
@avatarr I have been struggling with the same error today - looks like your problem could be line 

```ruby
mount_uploaders :image_url, ImageUploader
```

it should be

```ruby
mount_uploader :image_url, ImageUploader
```

eg. lose the plural on "mount_uploaders"

**Comment by Jojoooo1** [comment]
If you remove the S from mount_uploderS, multiple file upload is not set anymore, or I am guessing wrong ?

**Comment by rhk10** [comment]
If you use mount_uploaders, you need 'multiple: true' on file_field.

`<%= form.file_field :image_url, multiple: true %>`

Also, image_url in strong parameters must be an array.

`params.require(:reward).permit(:foo, :bar, {image_url: []})`

For more detail, refer to README file.
https://github.com/carrierwaveuploader/carrierwave#multiple-file-uploads

**Comment by harishpathakamuri** [comment]
This issue only because of mount_uploaders :image_url, ImageUploader
it should be:
mount_uploaders: image_url, ImageUploader
