### ISSUE TITLE
Add more images bug on update

### ISSUE THREAD

**Issue by kuzevanoff** [carrierwaveuploader/carrierwave#2165]
def update

    add_more_images(params[:car][:images])

    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def add_more_images(new_images)
    images = @car.images
    images += new_images
    @car.images = images
  end

Work's fine if i use @car.save but not update.

**Comment by mshibuya** [comment]
It's obvious, because images will be overwritten by `car_params[:image]` on `@car.update(car_params)`.
