### ISSUE TITLE
Multiple uploaders mounted to one model, full_filename receives wrong filename

### ISSUE THREAD

**Issue by yanaizmene** [carrierwaveuploader/carrierwave#2172]
I'm using carrierwave 0.11.2 with carrierwave-mongoid 0.10.0 and rails 5.0.2

I have 2 different uploaders mounted to one model.

In my uploaders I have such version:

```ruby
version "retina_version" do
  def full_filename(for_file)
    super.tap do |file_name|
      file_name.gsub!('.', '@2x.').gsub!('retina_', '')
    end
  end
end
```
So this pseudo code is fine:
```ruby
MyModel.create!(img1: Pathname.new(file).open, img2: Pathname.new(file2).open)
```
But if I use this scenario:
```ruby
m = MyModel.create!(img1: Pathname.new(file).open)
m.update(img2: Pathname.new(file2).open)
```

Upon updating, method full_filename does not receives correct filename of file that being uploaded. Actually it does not receives it at all. 

Instead it receives something like this: "retina_verion__old_" (when everything is correct it receives something like this "retina_verion_filename.jpg")

Maybe this is carrierwave-mongoid bug, but I have no possibility to check it with RDBS.

**Comment by mshibuya** [comment]
> Instead it receives something like this: "retina_verion__old_" (when everything is correct it receives something like this "retina_verion_filename.jpg")

I don't understand this part, could you be more concrete?

**Comment by mshibuya** [comment]
Stale, please let me know on update.
