### ISSUE TITLE
translation missing: en.errors.messages.extension_whitelist_error

### ISSUE THREAD

**Issue by jdzak** [carrierwaveuploader/carrierwave#2173]
I'm using `carrierwave (1.1.0)` and `rails (5.0.2)` and i'm getting `translation missing: en.errors.messages.extension_whitelist_error` when I try an upload a file that isn't in the whitelist. I looked at the i18n load path and don't see carrierwave in the load path. Any ideas?

My uploader has:
```
class UserProfilePhotoUploader < CarrierWave::Uploader::Base
  def extension_whitelist
    %w[jpg jpeg gif png]
  end
end
```

**Comment by jdzak** [comment]
So I just stumbled upon [this discussion](https://github.com/carrierwaveuploader/carrierwave/issues/1823) about carrierwave-i18n and a corresponding [PR](https://github.com/carrierwaveuploader/carrierwave/pull/1848).

Seems to me the intent was to keep `carrierwave/locale/en.yml` in the `carrierwave` repo and pull all the other localizations into `carrierwave-i18n` repo. It seems the PR did that, but it also [removed part of the initializer that includes carrierwave in i18n load path](https://github.com/carrierwaveuploader/carrierwave/pull/1848/files#diff-b9b95ffaa8fe82aef6a5d922757578dbL50) making the `carrierwave/locale/en.yml` file unloadable.

Should the code to add the carrierwave localizations directory to the i18n load path be re-added?

**Comment by leoi11** [comment]
Running into the exact same error. Looks right to me that we need to add it back..

**Comment by leoi11** [comment]
Don't have time to send a PR yet, but currently I'm deploying a VERY HACKY workaround using Bundler (>1.3) (please refrain to use):
In config/initializers/carrierwave.rb:
```
carrierwave_gem = Bundler.rubygems.find_name('carrierwave').first
I18n.load_path.prepend(File.join(carrierwave_gem.full_gem_path, 'lib', 'carrierwave', 'locale', "en.yml")) if carrierwave_gem.present?
```

**Comment by johnfoley3** [comment]
For anyone else running into this issue, the better answer is to add
```
gem 'carrierwave-i18n'
```
to your gem file
