### ISSUE TITLE
Doesn't work with 'awesome_nested_set' gem

### ISSUE THREAD

**Issue by StarWar** [carrierwaveuploader/carrierwave#2174]
In my Rails 4.2 app, the file uploads stopped working for the model which has following
`acts_as_nested_set counter_cache: :children_count, touch: true`
Removing this line, the uploads starts working again.
I'm uploading adding content via RailsAdmin using **Carrierwave** and **fog-google** gems.

The file is being created in 'tmp/uploads' directory with all the versions but not being uploaded to google storage.

**Comment by StarWar** [comment]
Moving `acts_as_nested_set counter_cache: :children_count, touch: true` after setting uploader in model solved this issue.

**Comment by anlek** [comment]
The issue is still should stay open, as a developer wouldn't know that `acts_as_nested_set` is the cause of the problem and waste their time solving it like you and I did. I recommend it stays as an open issue.

**Comment by anlek** [comment]
Also, the issue is present in Rails **5.0** as well.

**Comment by StarWar** [comment]
@anlek I've reopened the issue.

**Comment by plusor** [comment]
just remove `depth` column

**Comment by anlek** [comment]
@plusor what if you are using `depth` in `acts_as_nested_set`?

**Comment by plusor** [comment]
my mistake, actually is awesome _nested_set

**Comment by anlek** [comment]
@plusor, I was referring to `awesome_nested_set` as well. I still need to use both of these and need the depth column. Do you have any idea how to work around this issue?

**Comment by anlek** [comment]
Never mind, found the answer at in the awesome_nested_at issues: https://github.com/collectiveidea/awesome_nested_set/issues/375

**Comment by ccastillop** [comment]
Same problem where but with Rails 6.0.0.rc1 and `ActiveStorage`, saving at Disk. 

Using a brand new app, with just one model `Post` and adding `gem 'awesome_nested_set', github: 'collectiveidea/awesome_nested_set', branch: 'master'` version 3.1.4

As said at collectiveidea/awesome_nested_set#375 removing `depth` from the model is the answer

```
class Post < ApplicationRecord
  validates :title, presence: true
  acts_as_nested_set
  has_one_attached :avatar
end
```

**Comment by p8** [comment]
The problem here is that if the depth_columns is present AweNestedSet does a reload:
https://github.com/collectiveidea/awesome_nested_set/blob/94075850a669761c1c9bc14d621bd0877512b6f7/lib/awesome_nested_set/model.rb#L203
And Carrierwave resets the mounters in reload.
https://github.com/carrierwaveuploader/carrierwave/blob/d12a289d9cdd68d26d3900cf7f1e4e879678d16b/lib/carrierwave/orm/activerecord.rb#L94

**Comment by p8** [comment]
This has been fixed in: https://github.com/collectiveidea/awesome_nested_set/pull/413
