### ISSUE TITLE
Append Pictures

### ISSUE THREAD

**Issue by elbarto132** [carrierwaveuploader/carrierwave#2176]
I tried to append pictures instead of overwriting them when a User uploads them in Activeadmin.
The regular multiple File upload is working fine. Then i overwrite the update method to append new pictures instead of overwriting them, wich looks like this:

```
  permit_params :name, pictures: []

  controller do
    def update
      if params['product']['pictures']
        p = Product.find(params['id']).pictures + params['product']['pictures']
        params['product']['pictures'] = p
      end
      update!
    end
  end
```

According to this page it should work as i did it: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Add-more-files-and-remove-single-file-when-using-default-multiple-file-uploads-feature

But now i'm getting "Unpermitted parameter: pictures". I thought this happened because i modified the params hash, but when i do something like
`p = params['product']['pictures']*3`
it is working and sets the picture 3 times as expected

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
