### ISSUE TITLE
extension_whitelist is not case-insensitive for regular expressions

### ISSUE THREAD

**Issue by jayantsharma** [carrierwaveuploader/carrierwave#2177]
I'm aware that a past PR made extension whitelists case-insensitive. However, when the whitelist includes a Regexp, the whitelisting is not case-insensitive for the set of extensions the Regexp aims at. For example, `[ /jpe?g/, 'png' ]` does not accept the extension `'JPG'`, but will accept the extension `'PNG'`.

**Comment by mshibuya** [comment]
Closed by #2201.
