### ISSUE TITLE
Rails 5.1.1 deprecation warning

### ISSUE THREAD

**Issue by oni7uka** [carrierwaveuploader/carrierwave#2181]
I‘m using carrierwave master branch, My tests are flooded with rails deprecation warnings in carrierwave.

`DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from remote_cover_url= at /usr/local/bundle/bundler/gems/carrierwave-07dc4d7bd780/lib/carrierwave/orm/activerecord.rb:18)`

[https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L18](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/orm/activerecord.rb#L18)

**Comment by matthewrudy** [comment]
I get this all the time.
Just ignoring for now

**Comment by seanfcarroll** [comment]
Duplicate of https://github.com/carrierwaveuploader/carrierwave/issues/2115

**Comment by matthewrudy** [comment]
@seanfcarroll not sure it is.

This seems to come out of the activerecords.rb and is definitely not fixed on master.

**Comment by matthewrudy** [comment]
I mean, it's the same warning, but out of a different bit of the library

**Comment by pedroadame** [comment]
`bundle update carrierwave` solved it for me.

**Comment by CD1212** [comment]
Even after a `bundle update` when on master, I'm still getting a deprecation warning from `lib/carrierwave/orm/activerecord.rb:67`

**Comment by pedroadame** [comment]
I'm not on master, @CD1212, last release on rubygems, if it helps.

**Comment by matthewrudy** [comment]
FYI: I found that my problem was that we did the carrierwave upload inside an `after_save` callback.

That's why it hit the deprecation warning.

**Comment by CD1212** [comment]
My situation is exactly the same, I'm using Carrierwave in `after_save`. Did you find any solution @matthewrudy or are you just ignoring the warnings?

**Comment by matthewrudy** [comment]
@CD1212 I moved the code into a Delayed Job.

Which was a better idea anyway.
