### ISSUE TITLE
Can't display uploaded images / Mongoid + Carrierwave

### ISSUE THREAD

**Issue by dikey94** [carrierwaveuploader/carrierwave#2182]
Hello everybody,
I'm trying to integrate Mongoid and Carrierwave. Everything looks good except that I can't display my uploaded images.

Model:

```
class Advertisement
  include Mongoid::Document
  field :title, type: String
  field :anchor, type: String
  field :starting_date, type: Date
  field :expiration_date, type: Date
  mount_uploader :ad_image, AdImageUploader
end
```

template:
```
<% unless @advertisement.ad_image.file.nil? %>
      <%= image_tag @advertisement.ad_image.path %>
    <% end %>
```

As the result I get:

`<img src="/Users/myname/Sites/forrum/public/uploads/advertisement/ad_image/5921b805e41d5516de795a75/googlelogo_color_284x96dp.png" alt="Googlelogo color 284x96dp" />`

The file I uploaded and visible on the disc but browser can not load it.

Thanks for any help.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
