### ISSUE TITLE
content_type_whitelist problem in test env

### ISSUE THREAD

**Issue by inyerade** [carrierwaveuploader/carrierwave#2188]
Hi 
I have content_type_whitelist

    def content_type_whitelist
        /image\//
    end

In develop env work great,  only images can upload, but in test env have a problem.

I have a test to upload a file but the `content_type` do not get well with the same file as in development env.  

    <Rack::Test::UploadedFile:0x007f4978ae2950 @content_type=nil, @original_filename="i2.png", @tempfile=#<Tempfile:/tmp/i2.png20170531-25026-bw4wx>>

And if I comment the `def content_type_whitelist` function the file upload with no problem in test env.

I set the image with `fixture_file_upload("files/i2.png")`

I am doing something wrong?

**Comment by mshibuya** [comment]
`fixture_file_upload` does not infer MIME type automatically. You have to pass it like `fixture_file_upload("files/i2.png", "image/png")`.
