### ISSUE TITLE
Permission denied @ dir_s_mkdir - /PATH

### ISSUE THREAD

**Issue by 209cameronism** [carrierwaveuploader/carrierwave#2189]
When following the wiki for how to secure file uploads,  I keep getting denied. The error I get is : Permission denied @ dir_s_mkdir - /PATH

I am following this guide [https://github.com/carrierwaveuploader/carrierwave/wiki/How-To%3A-Secure-Upload]

Any ideas what I can do?

**Comment by mshibuya** [comment]
The given path `/PATH/RAILSAPPLICATION/...` in the article is just a placeholder, use real path(depending on your production env) instead.
