### ISSUE TITLE
 CarrierWave can't save image propertly in Linux on Windows VirtualBox (Vagrant)

### ISSUE THREAD

**Issue by N0xFF** [carrierwaveuploader/carrierwave#2190]
When files stored on VBGuest mounted storage, the next code got corrupted `file_out` image
```ruby
file_in = '/home/vagrant/test1.jpg'
file_out = '/home/vagrant/test2.jpg'
img = MiniMagick::Image.open(file_in)
img.resize "100x100>"
img.rotate "-90"
img.flip
img.write file_in
FileUtils.cp file_in, file_out, verbose: true
```
Bug in `img.write file_in` that overwrites opened file. If I write in other file all works fine. But CarrierWave uses this code in `manipulate!` method of MiniMagick module:

```ruby
def manipulate!
  ...
  image = ::MiniMagick::Image.open(current_path)

  begin
    ...
    image.write(current_path)
    ...
end
```

Tested in Ubuntu 16.04 LTS and Debian 8.8.
Ruby 2.4.1 and 2.3.3

VirtualBox 5.1.18
Vagrant 1.9.3
Windows 10

**Comment by svensson-david** [comment]
@N0xFF Did you ever fix this issue? I seem to be experiencing something similar.

**Comment by N0xFF** [comment]
@svensson-david Its not only CarrierWave problem. Now I use Unison to sync VirtualBox shared folder with internal folder. And use bash alias to get short command like `project-sync`.

**Comment by mshibuya** [comment]
That's their bug, not ours.
