### ISSUE TITLE
Unable to configure storage path with CarrierWave using `config.root`

### ISSUE THREAD

**Issue by c80609a** [carrierwaveuploader/carrierwave#2192]
I want to configure environment to use different storage paths with Carrierwave using `config.root`.

I've got an app which contains several uploaders.
The app includes several gems that contain uploaders too.
Each uploader defines the `store_dir`, for example:

```ruby
class LogoUploader < CarrierWave::Uploader::Base
  # [...]
  
  def store_dir
    "uploads/logo"
  end
  
  # [...]
end  
```

To solve the problem I added `config/initializers/carrierwave.rb`:

```ruby
CarrierWave.configure do |config|
  if Rails.env.development?
    config.root = File.join(Rails.root, 'public', 'dev')
  elsif Rails.env.test?
    config.root = File.join(Rails.root, 'public', 'test')
  end
end
```

Restart the server in development environment and uploaded one test `file.jpg`:
it **correctly** has been saved by path `public/dev/uploads/logo/file.jpg`. 

*But* when I called `image_tag(foobar.logo.url)` I got `public/uploads/logo/file.jpg` - my `config.root` was **ignored here**.

Where was I wrong?

**Comment by scottbarrow** [comment]
root must respond to `call` and currently you are setting `config.root` to a string. Wrap this in a proc or object that responds to `call`

**Comment by scottbarrow** [comment]
```  if Rails.env.test?
    config.storage = :file
    config.enable_processing = false
    config.root = -> { "#{Rails.root}/spec/support/uploads" }
  end
```
works for me™

**Comment by brunohkbx** [comment]
It still doesn't work :(

```
CarrierWave.configure do |config|
  config.asset_host = ENV['HOST']

  if Rails.env.test?
    config.storage = :file
    config.enable_processing = false
    config.root = -> { "#{Rails.root}/spec/support/uploads" }
  end
end
```

product_image.image.url
=> "http://localhost:3000/uploads/product_image/14/product_image.png"

**Comment by scottbarrow** [comment]
are you overriding it elsewhere? does you running in a test env? pry in and check the root value before and after the proc

**Comment by brunohkbx** [comment]
```
CarrierWave.configure do |config|
  config.asset_host = ENV['HOST']

  binding.pry
  if Rails.env.test?
    config.storage = :file
    config.enable_processing = false
    config.root = -> { "#{Rails.root}/spec/support/uploads" }
  end

  binding.pry
end
```

[1] pry(main)> config.root.call
=> "/home/bruno/Desktop/Projects/carrierwave-example/public"

[1] pry(main)> config.root.call
=> "/home/bruno/Desktop/Projects/carrierwave-example/spec/support/uploads"

It looks like the problem is in the image.url method

**Comment by pjg** [comment]
I was able to get around the issue with `config.root` being ignored by also setting `base_path`, like this (both for test & development):

```
    config.storage = :file
    config.root = lambda { "#{Rails.root}/public/uploads/#{Rails.env}" }
    config.base_path = "/uploads/#{Rails.env}"
```

**Comment by mshibuya** [comment]
`config.root` is only effective the local path. What's in the URL path needs to be taken care separately, like the above one.
