### ISSUE TITLE
Carrierwave 1.1.0 deletes images when setting the property to the same value on an ActiveRecord model.

### ISSUE THREAD

**Issue by RocketPuppy** [carrierwaveuploader/carrierwave#2196]
This is a little tough to pin down a minimal example for, so I'm going to do my best here:

```ruby
class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  version :thumb do
    process resize_to_fill: [256, 256]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  def store_dir
    "avatars"
  end

  def filename
    File.extname(super) if super
  end
end

class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  validates :avatar file_size: { less_than 2.megabytes }
end
```

Ok, so normal operation all seems to work fine. Uploading a file will set the `avatar` property to the path, and uploading a different file will change the path. However, if I do something like `user.update(avatar: u[:avatar])`, the image is deleted and the `avatar` property stays the same. This could easily happen if, for example, a form was prefilled with the existing values and those values were all passed into a call like `user.update(form_params)`.

It seems to me like this is normally desirable behavior to remove old images when new ones are uploaded. However in this case there isn't a new image to upload and the value doesn't change.

Note that I did not see this behavior on version 0.10.0, only on 1.1.0.

**Comment by llpereiras** [comment]
I tried to do this with version 1.1.0 and 1.0.0, and this doesn't work.

e = Equipe.find(1)
e.update(e.attributes)
e.imagem.url
nil

This bug are confirmed in this 2 versions.

Only on 0.10.0 it's work's properly.

**Comment by ivane-gkomarteli** [comment]
Any update on this issue?

**Comment by mshibuya** [comment]
#2401 has changed this behavior.
