### ISSUE TITLE
Cannot get image url in model after_update callback when using remote storage

### ISSUE THREAD

**Issue by TangMonk** [carrierwaveuploader/carrierwave#2200]
When user upload image, carrierwave will store in on local server, and then send to remote storage.

But The problem is I cannot get uploaded remote storage url in model callback

I can only got temp file located at `"/uploads/tmp"`, like `"/uploads/tmp/1498102200-8082-0001-7298/3a75f93d60cec4605883fc2952f97cf1.jpg"`, instead of `http://assets.aws-storage.com/uploads/asdasdadas.jpg`

**Comment by mshibuya** [comment]
Why do you need that in `after_save`?

**Comment by mshibuya** [comment]
Stale.
