### ISSUE TITLE
Wrong type and format validation on uploader field in ActiveRecord model

### ISSUE THREAD

**Issue by ViXP** [carrierwaveuploader/carrierwave#2203]
I have `User` model, with `login, email, avatar` fields. If I'm trying to save user with `{login: 1, email: 1, avatar: 1}` wrong integer data, both login and email fields will throw `ActiveRecord::RecordInvalid` errors with `wrong format` message, but `avatar` field, where `Carrierwave` uploader is actually mounted, throws `TypeError: no implicit conversion of nil into String`, also when I'm trying to create model with `{avatar: 'some_wrong_string'}`, it won't show any error at all. Is there's any way to check the correct data type and the correct string format of such fields?

**Comment by dfockler** [comment]
@ViXP Did you ever figure out a solution to this problem? I'm running into the same issue and wondering how to solve it.
