### ISSUE TITLE
Trying to capture image dimensions outside of the uploader seems to be impossible

### ISSUE THREAD

**Issue by nebtrx** [carrierwaveuploader/carrierwave#2204]
Hi, I'm making this question here because I been reading around for a while without finding any answer. So, according to [this](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Get-image-dimensions), if you wanna grab the image dimensions you have to do it inside the context of the uploader. But, what if I wanna do it inside the model? Is it possible?
I was trying to do it inside the model with the following code without success:
```
img = ::MiniMagick::Image::read(image.path)
```
I end up having the following error every time:
```
MiniMagick::Invalid:
       `identify /var/folders/kc/v7gzh2p568nd2x9qfqr9qq3400010f/T/mini_magick20170713-32583-ub2whs` failed with error:
       identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
```
FYI everything else is properly set up. I have the uploader, the extensions whitelist, I'm mounting the uploader on the model. Everything is working flawlessly If I grab the dimensions inside the context of the uploader.

I've read about it and apparently it's a library installation issue but it only happens if try to access the image file from inside the model after it gets uploaded. If I hooked that code inside the uploader using the `before` hook it works like a charm. 

My knowledge about image processing is limited, but I guess the carrier wave does something with the uploaded that prevents `MiniMagick`from the reading the file properly. That's crazy, I know, but it's the only thought I can come with right now. Can you explain to me a little bit?.

My motivations to do this is decoupling the field validation from the uploader. I'm currently storing the dimensions int the last one so I can access it later inside the validation logic and I want to get rid of that coupling. Yes, I could actually store the dimensions on the database but I don't really need to do it. The requirement is just to validate the dimensions while uploading

**Comment by mshibuya** [comment]
> capture image dimensions outside of the uploader

Don't do that. Doing it properly requires enough understanding on the lifecycle of the uploaded file.
Instead use [this](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Get-image-dimensions) with some tweak, like storing dimensions into a `attr_accessor` field, not a column.
