### ISSUE TITLE
Database record field does not retain old files.

### ISSUE THREAD

**Issue by nomanurrehman** [carrierwaveuploader/carrierwave#2205]
I am not sure if I have missed it in the documentation but when a new file(s) is uploaded, the database JSON column the uploader is mounted on does not retain the old files.

For example, the old column value is `["Sample_Delivery_Order.pdf", "Sample_Export_Trucking_Instruction.pdf", "Sample_Import_Trucking_Instruction.pdf", "Sample_Invoice__with_fields.pdf"]` but when a new PDF `example.pdf` is uploaded on the edit page, the column value becomes `["example.pdf"]`.

Now, there is a very strong case to have an entity where the files need to be added and removed from it flexibly so shouldn't there be a pull request for this?

**Comment by mshibuya** [comment]
Closed by #2401.
