### ISSUE TITLE
Same file issue on different uploaders

### ISSUE THREAD

**Issue by codemotion** [carrierwaveuploader/carrierwave#2208]
In working project I've 3 uploaders (AvatarUploader, PostUploader, BlogUploader) inherited by basic ImageUploader.

I'm trying to upload the same file for a couple of times.

When I'm uploading this file two or more times to one kind of uploader – it's ok.

But if I switch to another uploader and try to upload exact same file – it fails with error:
`ArgumentError: same file: /Sites/current/tmp/1500842722-78234-0147-9888/morning-street.JPG and /Sites/current/tmp/1500842722-78234-0147-9888/morning-street.jpg
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:200:in `move!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:186:in `move_to'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/processing/mini_magick.rb:298:in `manipulate!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/processing/mini_magick.rb:108:in `convert'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/processing.rb:75:in `each'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/processing.rb:75:in `block in process!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/processing.rb:74:in `process!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/callbacks.rb:14:in `each'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/cache.rb:137:in `cache!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/uploader/download.rb:75:in `download!'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/mounter.rb:81:in `block in remote_urls='
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/mounter.rb:79:in `map'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/mounter.rb:79:in `remote_urls='
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/mount.rb:166:in `remote_avatar_url='
/Users/dima/.rvm/gems/ruby-2.4.1/gems/carrierwave-1.1.0/lib/carrierwave/orm/activerecord.rb:19:in `remote_avatar_url='
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:46:in `public_send'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:39:in `each'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activemodel-5.1.2/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/core.rb:337:in `initialize'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/inheritance.rb:66:in `new'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/inheritance.rb:66:in `new'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/persistence.rb:33:in `create'
/Sites/current/db/seeds.rb:43:in `block in <top (required)>'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:39:in `each'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:39:in `each'
/Sites/current/db/seeds.rb:40:in `<top (required)>'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/engine.rb:549:in `load_seed'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:270:in `load_seed'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:184:in `block (2 levels) in <top (required)>'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/Sites/current/bin/rails:9:in `require'
/Sites/current/bin/rails:9:in `<top (required)>'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/dima/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Sites/current/bin/spring:15:in `require'
/Sites/current/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'`

I'm get stucked with this. Please, help me with this bug.

**Comment by mshibuya** [comment]
This is because you're using case-insensitive filesystem, not an issue with CarrierWave.
