### ISSUE TITLE
rails5 activesupports encoding error

### ISSUE THREAD

**Issue by kbsc332** [carrierwaveuploader/carrierwave#2211]
im using rails 5 and activesupports 5.0.4
when i try to upload photos with using actionrecord
"Encoding::UndefinedConversionError" error comes out and it doesn't store to directory.
detail error is "\x89" from ASCII-8BIT to UTF-8

someone said install activesupport-json_encoder does work for me, but activesupport-json_encoder support only under rails 4.

is there any things that i can do for rails 5??

(when i click upload and submit, photos stored at tmp folder but encoding error comes out on localhost page)

**Comment by vidurangaw** [comment]
@kbsc332 did you find a workaround?

**Comment by light-flight** [comment]
https://github.com/carrierwaveuploader/carrierwave/issues/2260#issuecomment-370188513
maybe you've met my mistake?

**Comment by kbsc332** [comment]
@vidurangaw  i couldn't solve it. i ended the project and made it in new way.

@light-flight i tried before but it was same. and whenever i fixed an error then the new error comes out just right after so i quited. :(
