### ISSUE TITLE
Add more files and remove single file when using default multiple file uploads feature

### ISSUE THREAD

**Issue by foliwe** [carrierwaveuploader/carrierwave#2212]
I have this error 
### No route matches {:action=>"create", :controller=>"pictures", :product_id=>nil} missing required keys: [:product_id]

when i try to create a new object following  [this tutorial](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Add-more-files-and-remove-single-file-when-using-default-multiple-file-uploads-feature)

**Comment by mshibuya** [comment]
Closed by #2401.
