### ISSUE TITLE
A way to figure out why certain images won't save

### ISSUE THREAD

**Issue by rgallison** [carrierwaveuploader/carrierwave#2215]
I installed the gem, and the base64 one, on a Rails 5 project.  Got everything working.  Images saving left and right.  Until this one image that just won't save. There's no error, nothing to indicate why.  Images decodes fine.  It's tiny.  I even reduced it to 4kb just to check, and it still won't save.  I wish I had some indication why this is happening.  I should mention that this image came from  a mobile camera and sent to the server as a base64 encoded string via an api call

**Comment by jguthrie100** [comment]
Can you paste a url to the image / base64 encoded string?

**Comment by mshibuya** [comment]
Stale.
