### ISSUE TITLE
cache_only breaks validation on updates

### ISSUE THREAD

**Issue by CodingAnarchy** [carrierwaveuploader/carrierwave#2216]
I have a class like this:

```ruby
class Child < ActiveRecord::Base
    mount_uploader :image, ImageUploader
   
    validate :image, presence: true
end
```

In the specs, I have some various tests that validate cases where this model will be updated, but if I set `config.cache_only = true` in my configuration of CarrierWave in the test environment, this validation fails when the update occurs.

I would like to use this feature, so as not to have to copy all the files to a `:file` storage, but I can't until this problem is resolved.  Thanks.

**Comment by mshibuya** [comment]
#2658 should have solved this.
