### ISSUE TITLE
Intermittent "broken pipe" errors

### ISSUE THREAD

**Issue by paulvwarner** [carrierwaveuploader/carrierwave#2218]
I'm using Carrierwave 1.1.0 to upload files to Rackspace from a Ruby on Rails server.  I've been seeing "Broken Pipe" errors happening intermittently at the point the code tries these file uploads.  I see it a few times a week, but it isn't something I've been able to reproduce locally, because it happens relatively rarely.  

The only information I've seen about this type of error online is that it often happens because people aren't pointing to the correct region when trying to upload files, but the region in my config (IAD) matches what the Rackspace site tells me the region is for the folder where I'm uploading.

My Carrierwave config (minus username, API key, fog_directory) looks like this:

```
CarrierWave.configure do |config|
  config.fog_provider = "fog/rackspace/storage" 
  config.fog_credentials = {
      provider: 'Rackspace',
      rackspace_username: 'XXXX',
      rackspace_api_key: 'XXXX',
      rackspace_region: :iad
  }
  config.fog_directory = 'XXXX'
end
```

The error messages I get look like this:
!ruby/exception:Excon::Error::Socket
message: Broken pipe (Errno::EPIPE)
socket_error: !ruby/exception:Errno::EPIPE
  message: Broken pipe

I turned on Excon debug logging, and it looks like Excon tries the request 4 times and then shows the broken pipe message when this happens.

I've tried a few different versions of Carrierwave and Fog and haven't found a configuration that solves this.  Right now I'm using Carrierwave 1.1.0 and set my Gemfile to use Fog 1.41.0.  Has anyone else run into this?

**Comment by paulvwarner** [comment]
I'm going to close this and open it under the Excon repo instead.

**Comment by manvedu** [comment]
I have the same issue. And if I use only fog I can connect without problems but with carrierwave always the same.
