### ISSUE TITLE
Fails to manipulate WEBP image on Heroku

### ISSUE THREAD

**Issue by IvanDreamer** [carrierwaveuploader/carrierwave#2219]
Hello everyone! 

I faced one problem with image manipulation in Carrierwave either with MiniMagick or RMagick when it's related to .webp and Heroku.

On local machine webp images can be manipulated but when I do the same on Heroku I've gotten following error: 
`Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `mogrify -auto-orient /tmp/mini_magick20170828-4-jq00cs.webp` failed with error: mogrify.im6: no decode delegate for this image format `/tmp/mini_magick20170828-4-jq00cs.webp' @ error/constitute.c/ReadImage/544. `

I've found buildpack with dwebp but I don't know how to integrate it to inner "convert" process. 

Does someone knows how to fix it?

**Comment by mshibuya** [comment]
Image processing is delegated to ImageMagick, so CarrierWave can't handle what can't be handled by ImageMagick.
