### ISSUE TITLE
Carrierwave leaves empty folders when I delete an attachment

### ISSUE THREAD

**Issue by danielvlopes** [carrierwaveuploader/carrierwave#222]
I'm not sure if this behavior is expected or not but everytime a user deletes his attachments Carrierwave leaves an empty folder instead of delete it.

Is that a known issue? (I couldnt found here).

**Comment by vijayprasad6** [comment]
Guys do not worry just use a simple line after object destroy as marked here and it will delete the directory.
**Here is code of destroy action: ** 
def destroy
    @remember_id = @image.id
    @image.destroy
   **_ FileUtils.remove_dir("#{Rails.root}/public/uploads/image/file/#{@remember_id}")_**
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

**Comment by mahfuz10** [comment]
1. Create a helper
2. Include helper in your uploader
3. Add `after :remove, :remove_empty_container_directory` -  in your uploader

``` ruby
# app/uploaders/upload_helper.rb

module UploadHelper
  def remove_empty_container_directory
    path = "#{Rails.root}/public/#{store_dir}"
    Dir.rmdir(path)
  rescue
    true
  end
end
```

``` ruby
# app/uploaders/gig_image_uploader.rb

class GigImageUploader < CarrierWave::Uploader::Base
  include UploadHelper
  after :remove, :remove_empty_container_directory
  # and your other code here
end
```

Note: `Dir.rmdir` delete only empty directory, so it is safe.

Issue with this solution:
when delete file, `remove_empty_container_directory` is running twice. but the code works.

Thanks to @arefaslani
