### ISSUE TITLE
When implementing multiple image uploads using JSON / serialized text, is it possible to store nested attributes such as alt and title for each image

### ISSUE THREAD

**Issue by acrolink** [carrierwaveuploader/carrierwave#2222]
If not possible currently, maybe you could consider implementing this feature.

**Comment by mklb** [comment]
would love to see this as well

**Comment by acrolink** [comment]
@mklb 

What I have done in the meanwhile is to add a JSON field to the model named `attrs`. Attributes (title, alt, etc..) are saved to it as nested properties belonging to parent keys (filenames). Like this:

```
{
  "sun_picture.png": {
    "alt": "sun",
    "title": "The Sun"
  },
  "moon_picture.png": {
    "alt": "moon",
    "title": "The Moon"
  }
}
```

**Comment by mshibuya** [comment]
That's not possible, using nested has_many is what I recommend.
