### ISSUE TITLE
Carrierwave deletes existing files without clearing table field on row update

### ISSUE THREAD

**Issue by akashsuresh** [carrierwaveuploader/carrierwave#2227]
I have a a post table where each row has two attachment fields. When I perform an update on any one attachment, the image of the other attachment gets deleted from S3, however the table field still remains the same.

I have checked the S3 cloudtrail logs and it confirms this.

**Comment by mshibuya** [comment]
Looks like path conflict between two uploaders, if you could paste your uploader code I can tell what's wrong.
