### ISSUE TITLE
How to build versioned urls through transformations

### ISSUE THREAD

**Issue by codemang** [carrierwaveuploader/carrierwave#2229]
I have an AR model `Ad` that mounts an image.

```
pry(main)> Ad.last.image_url
=> "http://res.cloudinary.com/company/image/upload/version_num/image_name.jpg"
```

You can see that the version `version_num` is present.

However, when applying cloudinary transformation, the version disappears. 

```
class AdImageUploader < CarrierWave::Uploader::Base
  def extension_white_list
    %w(png jpg jpeg)
  end

  version :jpg do
    cloudinary_transformation quality: 80, format: :jpg
  end
end
```
And then

```
pry(main)> Ad.last.image_url(:jpg)
=> "http://res.cloudinary.com/company/image/upload/q_80/image_name.jpg"
```

I want

```
pry(main)> Ad.last.image_url(:jpg)
=> "http://res.cloudinary.com/company/image/upload/q_80/version_num/image_name.jpg"
```

The issue is that once I change the image, cloudinary's CDN still contains a cached copy of the original image. Without the version number present in the url, the original image will be shown. I've poured through the docs and the code itself but I can't figure out how to do it. Is this supported?

**Comment by mshibuya** [comment]
You should ask in https://github.com/cloudinary/cloudinary_gem.
