### ISSUE TITLE
Get public url for an item uploaded using authenticated read

### ISSUE THREAD

**Issue by manojmj92** [carrierwaveuploader/carrierwave#2232]
I am uploading photos using `AvatarUploader` which has configured `self.aws_acl = 'authenticated-read'`

As a result, all the urls generated have expiry tokens.
However, for a specific case, I need to get the public url (this should not expire) for a model.
However calling `model.image.url` always gives links that will expire. 

Is there a way to get a public url even though the `aws_acl` is set as `authenticated_read`. Can we override this on a per method basis or something?

**Comment by mshibuya** [comment]
`aws_acl` is the feature of https://github.com/sorentwo/carrierwave-aws.
