### ISSUE TITLE
Rails image upload requires calling reload before rendering json

### ISSUE THREAD

**Issue by chewedon** [carrierwaveuploader/carrierwave#2235]
I'm not sure if this is a Rails problem or a Carrierwave problem or if it even is a problem at all.

Anyhow, some background information about the problem is on my Stackoverflow question (and answer):

https://stackoverflow.com/questions/46271081/carrierwave-cloudinary-image-upload-works-but-null-values-returned-right-after-u

Basically, the problem is when creating a new user or updating one, the JSON that gets returned does not include Carrierwave image data, they come back as null values.

I want to point out, the actual images are uploaded to Cloudinary CDN but the JSON response values themselves are null.

The solution I found is I have to call 

```
user.reload
```

Immediately after `user.save` or `user.update(user_params)`.

E.g:

```
def create
  user = User.new(user_params)

  if user.save
    # -------------------------------------------------
    # NEED TO RELOAD FOR CARRIERWAVE
    # -------------------------------------------------
    user.reload

    render json: user, status: :created
  else
    render json: user.errors, status: :unprocessable_entity
  end
end
```

After calling `user.reload`, then my rendered JSON values come with the proper URL information for the image instead of null values.

Is this a bug with Carrierwave or is this how Carrierwave is expected to behave?

It seems like an extra step, which may or may not affect system performance, it just feels a bit odd. 

I was hoping it would automatically fill in the proper JSON value on the `save` operation rather than me having to call a manual `reload`.

**Comment by joelmoss** [comment]
I'm seeing this issue too. Does seem like a bug to me, as I can't see how or why this would be intended.

**Comment by Jellyfishboy** [comment]
I am also seeing this issue, any solutions?

**Comment by bramski** [comment]
So many months old. And I've now seen this on two separate projects. Can someone comment or fix this issue please? @trevorturk @jnicklas ? You guys seem to have been the most prolific contributors.

**Comment by Jellyfishboy** [comment]
Hey @bramski, agreed. Still using the `reload` method to resolve the issue but it feels kind of messy, any kind of fix in sight?

**Comment by trevorturk** [comment]
Sorry I haven't been a maintainer for a long time now, and I'm not sure who has been. Maybe check the latest commits and reach out to whoever has been active and see if you can help out? I'm sure lots of people would appreciate this gem being kept in good shape!

**Comment by bramski** [comment]
How about @amatsuda or @mshibuya ? You guys seem to be the most recent contributors.

**Comment by mshibuya** [comment]
Merging this into #2253.

**Comment by mshibuya** [comment]
If anyone can provide reproduction steps please report back to #2253.
https://github.com/carrierwaveuploader/carrierwave/issues/2253#issuecomment-783195819

**Comment by ykamin-booth** [comment]
I'm also getting this issue. I have an Event model which has an event_photo column

```
class Event < ApplicationRecord
  ...
  mount_uploader :event_photo, EventPhotoUploader
end
```

The EventPhotoUploader class:
```
class EventPhotoUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

end
```

A user uploads an image in a form:

```
<%= form_with(model: @event, local: true) do |f| %>
  ...
  <%= f.file_field :event_photo, id: "event_photo_uploader" %>
  ...
<%end%>
```

Then, in the event controller:

```
def update
    @event.assign_attributes(event_params)
    #at this point, the image is correctly mounted and added to the event
    respond_to do |format|
      if @event.save
        #at this point, @event.changed shows that event_photo has been changed and I need to call
        #@event.reload before saving the event again. If I don't, the image is cleared. 
        ...
      else
        ...
      end
    end
  end
```

I can put this in #2253 as well but based on my experience troubleshooting it makes more sense for this issue.

**Comment by mshibuya** [comment]
@ykamin-booth Are you able to reproduce that by using a fresh app generated by `rails new` ?
If you could do it, sharing me that app as a public repo will be really helpful for tracking down the issue.
