### ISSUE TITLE
Please make `CarrierWave::Uploader::Download::RemoteFile#download!` compatible with multi-byte characters.

### ISSUE THREAD

**Issue by seak0503** [carrierwaveuploader/carrierwave#2239]
I uploaded it using `CarrierWave::Uploader::Download::RemoteFile#download!`

The file name of the original file contained Japanese.

However, when I looked at the uploaded file, the Japanese part was `__`.

```
f = File.new
f.remote_file_url = "https://foo.bar/sample日本語.xls"
f.save!

f.file.file.identifier
=> "sample______.xls"
```

When not using `download!`.....

```
f = File.new
f.file = file object
f.save!

f.file.file.identifier
=> "sample日本語.xls"
```

When using `CarrierWave::Uploader::Download::RemoteFile#download!`, it seems that the file name encoding is ASCII.

Therefore, I converted the file name into UTF - 8 in `SanitizedFile#sanitize`.

**lib/carrierwave/sanitized_file.rb**

```
...

def sanitize(name)
  name.force_encoding("utf-8")  <-- I added this

  name = name.tr("\\", "/") # work-around for IE
  name = File.basename(name)
  name = name.gsub(sanitize_regexp,"_")
  name = "_#{name}" if name =~ /\A\.+\z/
  name = "unnamed" if name.size == 0

  return name.mb_chars.to_s
end

...
```

This will correctly register the Japanese file name.

```
f = File.new
f.remote_file_url = "https://foo.bar/sample日本語.xls"
f.save!

f.file.file.identifier
=> "sample日本語.xls"
```

Please correct `lib/carrierwave/sanitized_file.rb`

**Comment by mshibuya** [comment]
57a4a3b65f475ec21b51bba36da13eab9f864a67 addresses this issue.
