### ISSUE TITLE
how set struct store_dir with year/month of upload file

### ISSUE THREAD

**Issue by nelisr** [carrierwaveuploader/carrierwave#2244]
Hi there!

I have an application with carrierwave and I would like to structure the store_dir with year / month file upload.

now I have this code

`uploads / # {Time.current.year} / # {Time.current.month}`

but when changing the month the url of the file is also changed

**Comment by nelisr** [comment]
the solution to the problem is this

`# find file in struct of directory
      getFile = Dir.glob(Rails.root.join("public/system/uploads/**/**/#{model.read_attribute(mounted_as)}"))

      # find month that file created
      urlMonth = File.mtime(getFile[0]).month

      # find year that file created
      urlYear = File.mtime(getFile[0]).year
      "system/uploads/#{urlYear}/#{urlMonth}"`

he going to mounter in "uploads/2017/11/file_name.png"

**Comment by Grafikart** [comment]
@nelisr If your attachments are linked to a model, a good solution would be to use the created_at field

```ruby


  def store_dir
    if model.created_at.nil?
      created_at = Time.now
    else
      created_at = model.created_at
    end
    "uploads/#{created_at.strftime('%Y/%m')}"
  end
```

**Comment by nelisr** [comment]
thanks!

good solution also!

but my business rule not permit dependency of model to upload file, that is, i can upload of file whitout need of model.

**Comment by marcosanfilippo** [comment]
Hello. How can I use this to change my store_dir dynamically?

I have it in a photo model, but I want to distinct between "admin" and "user", so:
`"uploads/#{admin_path}/..."` and `"uploads/#{user_path}/..."`

where `admin_path` (or `user_path`) is something like (`admin_model.class`) or (`user_model.class`)
There's a way to use params in the store_dir?

Thanks

**Comment by nelisr** [comment]
Hi @marcosanfilippo !

you code are more or less correct! 

do you replace to just this "#{admin_path}" to "#{model}"}"

**Comment by marcosanfilippo** [comment]
Thanks @nelisr !
So, what do you suggest? I would like to have a local variable like `model_path`, to be passed to the store dir...

Might I override the:

      def initialize(model=nil, mounted_as=nil)
        @model = model
        @mounted_as = mounted_as
      end


with another params??

Or simply, could I modify the `store_dir` method?

This because I don't want to pollute my uploader with future gem modifications.

Thanks

**Comment by mshibuya** [comment]
Solution offered.
