### ISSUE TITLE
Remove from multiple files

### ISSUE THREAD

**Issue by seliverstov-maxim** [carrierwaveuploader/carrierwave#2257]
I have faced with same problem. Original https://github.com/carrierwaveuploader/carrierwave/issues/401

**Summary:**
When using with multiple images.
```
@product = Product.find(10)
@product.photos[0].remove!
@product.save!
```
only remove original image and its thumbnails in my case
but photos[0] is still there.

```
@product.photos[0]
=> #<PhotoUploader:...>

@product.photos[0].file
=> #<CarrierWave::SanitizedFile:...>
```

**Comment by aashish** [comment]
I also faced the same problem. The versioned images are not getting deleted either on local or on s3 bucket.

**Comment by seliverstov-maxim** [comment]
up

**Comment by mshibuya** [comment]
f94b0615c1b0c1000c31cd64b373dae85f0f4893 should have solved this.
