### ISSUE TITLE
couldn't download remote file 

### ISSUE THREAD

**Issue by dieuit07** [carrierwaveuploader/carrierwave#2258]
It happened when I try to set remote_image_url = '...' . It loads forever for some images.  

I test several times with those. when I uploaded from computer, It run fine. But when I set remote_image_url = that_url, It overlap and never return, I had to kill rails console process to break bug.

the storage I use is amazon s3

**Comment by mshibuya** [comment]
Question is unclear, please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request.
