### ISSUE TITLE
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8) error for rails 5.1

### ISSUE THREAD

**Issue by amrutjadhav** [carrierwaveuploader/carrierwave#2260]
I am having this error while uploading image. I tried to add activesupport-json_encoder gem in Gemfile as mentioned in #1404, but activesupport-json_encoder does not work with rails 5.1. Any suggestions?

**Comment by light-flight** [comment]
My mistake was using `json` instead of `string`:
```rb
class AddImagesToGallery < ActiveRecord::Migration
  def change
    add_column :galleries, :images, :string, array: true, default: [] # add images column as array
  end
end
```
It caused this error

**Comment by mshibuya** [comment]
Full stack trace please.

**Comment by mshibuya** [comment]
Stale, please let me know on update.
