### ISSUE TITLE
cached temp image is in the wrong location

### ISSUE THREAD

**Issue by atstockland** [carrierwaveuploader/carrierwave#2262]
I only experience this issue when converting a multi page pdf into a png or jpg version.  Converting an image or single page PDF processes just fine...

     carrierwave.rb
          config.cache_dir = "#{ Rails.root }/tmp/uploads"

when the large version is processed it errors with:

     Validation failed: Asset Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `identify /Users/secret/Sites/secret/tmp/1514247368-67574-0037-6191/large/agency_card2.png` 
     failed with error: identify: improper image header `/Users/secret/Sites/secret/tmp/1514247368-67574-0037-6191/large/agency_card2.png' @ error/png.c/ReadPNGImage/4227.

Notice the path in the error is not the same format as the path set in config.  The path is missing "/uploads", and incorrectly includes "/large"...none of the tmp directories in my app include subdirectories of the version name.

This temp image does in fact live at: 
     ++ '/uploads' 
     -- '/large'

     `/Users/secret/Sites/secret/tmp/uploads/1514247368-67574-0037-6191/agency_card2.png'

This, I believe, is actually a MiniMagick error.  The error message "improper image header" seems a bit misleading...as it seems to indicate the image was not found.  And, if you notice in the error the path does not include "/uploads", and incorrectly includes "/large".

If I change the config back to (and, restarted server):

     carrierwave.rb
          config.cache_dir = "#{ Rails.root }/tmp"

the path in the error message is the same format

     `/Users/secret/Sites/secret/tmp/1514248360-79772-0001-3254/large/agency_card2.png'

accept no '1514248360-79772-0001-3254' directory is ever created and therefor no image.

Is it a carrierwave issue that config.cache_dir = "#{ Rails.root }/tmp/uploads" does not match the path in the first error message above?  If MiniMagick is generating this error, where is it deriving the path  (from carrierwave)?

# - - - - - - - - - - - -

In an effort to make this more readable...here are the two paths again.  The first is incorrect (as seen in the error message), the second is correct (and, I can see the image is actually there).

     /Users/secret/Sites/secret/tmp/1514247368-67574-0037-6191/large/agency_card2.png
     /Users/secret/Sites/secret/tmp/uploads/1514247368-67574-0037-6191/agency_card2.png
     config.cache_dir = "#{ Rails.root }/tmp/uploads"

**Comment by tonycchung** [comment]
@atstockland did you ever resolve this? i'm running into a similar issue but the path is wrong only in a test/spec

**Comment by atstockland** [comment]
I don't know if I ever did.  Sorry I'm not able to help.  I converted over to ActiveStorage some time ago.  I HIGHLY recommend you drop Carrierwave and head over to ActiveStorage.  No offense to CarrierWave...but, none of the original uploaders compete with what is now baked in to Rails.

**Comment by tonycchung** [comment]
no problem, thanks for the rec.

unfortunately not on Rails 5.2 yet - doing upgrades just to get to 5.1 at the moment.

Cheers~

**Comment by no-itsbackpack** [comment]
To anyone who comes across this bug this [commit](https://github.com/carrierwaveuploader/carrierwave/commit/629afecbaeccd2300e4660b78ee36bd95dd845c5) defaults `cache_storage: nil` causing the temp files to either get deleted or show up in the wrong location. Setting `config.cache_storage: file` fixed it for me ❤️
