### ISSUE TITLE
Limited conditional processing

### ISSUE THREAD

**Issue by dvodvo** [carrierwaveuploader/carrierwave#2264]
Note this has been asked [on stackoverflow](https://stackoverflow.com/questions/48087628/carrierwave-limited-conditional-processing).  While there is an [interesting refactoring approach across models](http://andreapavoni.com/blog/2012/3/using-one-carrierwave-image-uploader-with-different-sizes-on-several-models/#.Wk0zzVUo-Cg), the problem of refactoring WITHIN a model is vexing.

I have attempted to create various scenarios where conditional processing follows different methods according to a model attribute.  But everytime the number of cases gets past two, the conditions break down.  The following case is a head scratcher
With protected methods
`
def is_header? image
  !model.image_h? && !model.image_v?
end

def is_v? image
  model.image_v?
end

def is_h? image
  model.image_h?
end
`
the first method fires up and creates the defined versions below, but the latter two, no. 

`
version :small_v, if: :is_v? do
  process :resize_to_limit => [180, 300]
end

version :small_h, if: :is_h? do
  process :resize_to_limit => [320, 102]
end

version :medium, if: :is_header? do
  process :resize_to_limit => [640, 120]
end

version :small, if: :is_header? do
  process :resize_to_limit => [416, 78]
end
`

Now how can that be as the first method references the model attributes of BOTH the other two?  Params are being submitted `"photo"=>{image_v: "f", image_h: "f"...`
Mind you, if only the `is_h`method is kept, it does NOT fire up properly... which makes the fact that the `is_header` method runs curious (I assume by default).

**Comment by mshibuya** [comment]
I'm not quite sure of what's happening here, but if you think `"f"` is evaluated to false in Ruby, that's not.
