### ISSUE TITLE
Multiple file upload mobile Safari IOS < 10

### ISSUE THREAD

**Issue by sandergroen** [carrierwaveuploader/carrierwave#2265]
This issue was mentioned before in #1617. When the file field is set to multiple and multiple images are attached to this file field. The file name for all images is image.jpg when this files get saved to the server the last file is saved and all other files in the database record is referenced to this last file.

To reproduce this issue you need an IOS device or simulator and then upload multiple images whit this devise.

**Comment by mshibuya** [comment]
Dup of #1855.
