### ISSUE TITLE
Recreating versions, cached file is always nil

### ISSUE THREAD

**Issue by jonathanrbowman** [carrierwaveuploader/carrierwave#2266]
I tried creating a rake task out of the code provided here for carrierwave/fog image reprocessing:
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Recreate-and-reprocess-your-files-stored-on-fog

However, while it worked last year, I am trying it now and it's returning `nil` when trying to retrieve anything from cache. Specifically, `cache_name` is `nil`.

So, if I do `ProjectPhoto.last.image.cache_stored_file!`, followed by `ProjectPhoto.last.image.cache_name`, it returns `nil`. Shouldn't it return something there?

I have seen people post similar issues, but haven't found a resolution yet. Is this something that is still a bug, or am I just not understanding it?

Thanks.

**Comment by milkfarm** [comment]
I'm encountering this as well (Carrierwave version 2.1.0). Some uploaders successfully cache, other don't. When calling `cache_stored_file!` on those that don't, `nil` is quickly returned. All files exist in S3. Any insight?
