### ISSUE TITLE
How does one save previews original file after re-upload, without resized versions

### ISSUE THREAD

**Issue by PragmaticEd** [carrierwaveuploader/carrierwave#2273]
I know about:

```ruby
CarrierWave.configure do |config|
  config.remove_previously_stored_files_after_update = false
end
```

But the problem with this is, that it saves the versions too, which might not be good every time.

Let me give an example.

I have an uploader, that saves the original file + 4 versions:
* 1_default.jpg
* 1_thumb_default.jpg
* 1_small_default.jpg
* 1_medium_default.jpg
* 1_large_default.jpg

And i re-upload image, now i have 10 files:
* 1_default.jpg
* 1_thumb_default.jpg
* 1_small_default.jpg
* 1_medium_default.jpg
* 1_large_default.jpg
* 2_default.jpg
* 2_thumb_default.jpg
* 2_small_default.jpg
* 2_medium_default.jpg
* 2_large_default.jpg

Is there a way to tell CarrierWave to only store the original version, like so:
* 1_default.jpg
* 2_default.jpg
* 2_thumb_default.jpg
* 2_small_default.jpg
* 2_medium_default.jpg
* 2_large_default.jpg

Cos i want to keep history, for admin model version management, so its possible to see what user uploaded what, but i don't want to waste server space on versions, that wont appear, since ony original version will be shown in admin.

How does one do this, without any `rm -rf 1_*` hacks, or similar?

**Comment by mshibuya** [comment]
There's no ready-made way, but you can perform such a cleanup by hooking into the `after :store` callback.
