### ISSUE TITLE
Empty array when I m trying to view an image

### ISSUE THREAD

**Issue by pmalliak** [carrierwaveuploader/carrierwave#2275]
I use carrierwave gem to upload images to my rails 5 app. Everything works fine for storing. I can see the image saved in public folder and the image name saved in my database in photo field.

When I m trying to view the image with the following code <%= image_tag @news.photo.url %> I get the following error undefined methodurl' for []:Array`.

When I trying to print the content of photo field with <%= @news.photo %> I get an empty array []

The database is MySQL.

Any idea where is the problem?

**Comment by mshibuya** [comment]
Are you mounting an uploader using `mount_uploaders`?
If so, use `mount_uploader` instead.
