### ISSUE TITLE
Strange behavior for override filename

### ISSUE THREAD

**Issue by zlx** [carrierwaveuploader/carrierwave#2276]
Hi guys.

Hope the issue does not trouble you.

I want to rename uploaded filename by override filename. like below:

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  store :file
  ...
  def filename
     if original_filename
       "logo.jpg"
     else
       "default.jpg"
     end
   end
end
```

Besides, there is a model named product with two columns: logo and name, and logo is mounted to ImageUploader. 

It work fine when create product. But nightmare begin, when I update the name attribute for existing product record, the logo image will missing, each time. In database, the logo column change from "logo.jpg" to "default.jpg".

After I make below change:

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  store :file
  ...
  def filename
     if original_filename
       "logo.jpg"
     # else
     #  "default.jpg"
     end
   end
end
```

It works.

So my question is: ***Why the logo value still updated without any logo changes?***

[Here](https://github.com/zlx/Bugs) can help you make the bug reproduction quickly.

Hope the description is clear.

**Comment by cdesch** [comment]
Yeah, I'm having this issue as well. Any luck?

**Comment by mshibuya** [comment]
https://github.com/carrierwaveuploader/carrierwave/commit/f1eff6e212fb0c374c9235968bfc4e7580bf1e2a should have fixed this.
