### ISSUE TITLE
How to save a modified (post-processed) version of the uploaded file, while discarding the original?

### ISSUE THREAD

**Issue by cynicalsubject** [carrierwaveuploader/carrierwave#2278]
I have an application where I upload videos, and due to the fluctuating sources they can come from I have the need to convert them to an uniform format I can use everywhere.

I know it is possible to make several versions of the original file, but I'd like to discard the original, essentially keeping only one version of it (the modified one). The files can be kinda large (300mb or so), which is why I'd like to discard the original and save HD space.

I intend to use streamio-ffmpeg to do the transcoding, as I've used it successfully for images. I also intend to use background processing due to the time the transcoding can take, but that's an entirely different topic.

I'm using rails 5.1.4, carrierwave 1.2.2, and File as storage method.

**Comment by mshibuya** [comment]
Processing original file directly, without using versions will be enough.
