### ISSUE TITLE
Upload generated PDF

### ISSUE THREAD

**Issue by JulienItard** [carrierwaveuploader/carrierwave#2279]
Hello,

I want to use Carrierwave to upload generated PDF to Amazon S3.

In my model, i have: 
```
class Invoice 
    mount_uploader :pdf, InvoiceUploader

    def pdf=
        super(Invoice::PdfGeneration.new(self).generate)
    end
end
```

`Invoice::PdfGeneration.new(self).generate` Generate a PDF from current object.

Nothing happen, `pdf` is nil and i have no error. Any idea ? 

Thanks !

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
