### ISSUE TITLE
Carrierwave + Sequel. Isn't the gem carrierwave-sequel abandoned?

### ISSUE THREAD

**Issue by GildedHonour** [carrierwaveuploader/carrierwave#2281]
Do I understand correctly that for Sequel, not ActiveRecord, I should use the gem `carrierwave-sequel` instead of this one?

If so, the last update of `carrierwave-sequel` was in 2015, hasn't  been abandoned?

**Comment by mshibuya** [comment]
There's no active maintainer, please let me know if anyone is interested in maintaining it.
