### ISSUE TITLE
Dynamically get the model name to create versions

### ISSUE THREAD

**Issue by DaniG2k** [carrierwaveuploader/carrierwave#2282]
I posted this question [on SO](https://stackoverflow.com/questions/48850510/rails-5-dynamically-get-the-model-name-to-create-versions-with-carrierwave) but thought I'd put it here too in case someone knows how to do this.
I'm trying to dynamically create a version of a Carrierwave image if the polymorphic association is of a certain model, and skip it otherwise.

For instance:

**user.rb**

```
class User < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy
end
```

**listing.rb**

```
class Listing < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy
end
```

**picture.rb**

```
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :imageable, polymorphic: true
  validates :image, presence: true
  validates_integrity_of :image
end
```

I'm trying to do the following in the uploader:

```
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  # Only do this if model type is Listing
  version :card do
    process resize_to_fit: [800, 800]
    process resize_to_fill: [640, 430]
  end

  # Only do this if model type is User
  version :profile do
    process resize_to_fit: [600, 600]
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end
end
```

I've tried with `version :profile, if: :is_user?` do and then creating a method like:

```
def is_user?(picture)
  model.imageable_type.downcase == 'user'
end
```

but `model.imageable_type` is nil when a Picture is still not committed.

I am overwriting Devise's update method to add images to users:

```
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    super do
      pics = params[:user][:pictures]
      if pics.present?
        pics.each { |pic| resource.pictures << Picture.new(image: pic) }
      end
    end
  end
end
```

and for listings I am creating images like this:

```
class ListingsController < ApplicationController
  def create
    @listing = Listing.new(JSON.parse(params[:listing]))
    @listing.owner = current_user
    @listing.pictures = params[:file].values.map {|file| Picture.new(image: file)}

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_path(@listing), notice: 'Listing was created successfully!' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end
end
```

Is there a way to dynamically get the model name to create versions so that I don't have to create new uploaders for each model (which seems to defeat the purpose of having a polymorphic Picture model in my opinion).

Thanks in advance!

**Comment by tannakartikey** [comment]
Try using `model.imageable.class` instead of `model.imageable_type` in `is_user?` method.

**Comment by DaniG2k** [comment]
The problem is that the object class is only defined once saved, so in `is_user?` I still don't get any class info:

```
model.imageable
=> nil
model.imageable.class
=> NilClass
```

**Comment by mshibuya** [comment]
My intuition is adding `inverse_of` might help getting around this.
```ruby
class User < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy, inverse_of: :imageable
end
```
This is usage issue of ActiveRecord and not specific to CarrierWave, though.
