### ISSUE TITLE
Mounted uploader column is populated on create, even when no file is present, when using filename override

### ISSUE THREAD

**Issue by lpradovera** [carrierwaveuploader/carrierwave#2284]
The following is a console snippet from our application (newlines added for readability):

```2.3.3 :001 > cc = Customer.create(customer_number: 'f123456')
   (0.3ms)  BEGIN
  SQL (1.9ms)  INSERT INTO "customers" ("customer_number", "created_at", "updated_at", 
"recording_file") VALUES ($1, $2, $3, $4) RETURNING "id"  [["customer_number", "f123456"], 
["created_at", "2018-02-26 20:01:37.848502"], ["updated_at", "2018-02-26 20:01:37.848502"], 
["recording_file", "f123456.mp3"]]
   (0.6ms)  COMMIT
 ```

Code is a very simple uploader, with

```
def filename
    "#{model.customer_number}.mp3"
end
```

As you can see, the recording_file column, corresponding to a mounted uploader, is being set on create even if there is no attachment. When using Fog and S3, it results in `recording_file_url` erroneously returning a path.

We are on Rails 5.1, Carrierwave 1.2.1.

**Comment by raulccabreu** [comment]
I have this problem too, try this with your override.
`def filename
    return @filename if file.nil?
    "#{model.customer_number}.mp3"
end`

**Comment by raulccabreu** [comment]
I have this problem too, try this with your override.
`def filename
    return @filename if file.nil?
    "#{model.customer_number}.mp3"
end`

**Comment by raulccabreu** [comment]
I have this problem too, try this with your override.
`def filename
    return @filename if file.nil?
    "#{model.customer_number}.mp3"
end`
