### ISSUE TITLE
Added Instance Methods for Polymorphic relationship

### ISSUE THREAD

**Issue by tannakartikey** [carrierwaveuploader/carrierwave#2293]
I am using Carrierwave uploader in a polymorphic association as below:
```
class Image < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :imageable, polymorphic: true, optional: true
end
```

Are there any [instance methods added](https://github.com/carrierwaveuploader/carrierwave/blob/87c37b706c560de6d01816f9ebaa15ce1c51ed58/lib/carrierwave/mount.rb#L220) generated for polymorphic relationships?

**Comment by DaniG2k** [comment]
Seems not. This is probably why I can't get [my issue](https://github.com/carrierwaveuploader/carrierwave/issues/2282) resolved ether.

**Comment by mshibuya** [comment]
See https://github.com/carrierwaveuploader/carrierwave/issues/2282#issuecomment-488241548.
