### ISSUE TITLE
ArgumentError: string contains null byte on file upload with fog-google

### ISSUE THREAD

**Issue by Shashindran** [carrierwaveuploader/carrierwave#2294]
Hello,

I'm using carrierwave v1.2.2 and fog-google v1.3.2. I authenticate to bucket using new JSON API.

When uploading image, i'm getting
ArgumentError: string contains null byte

**Comment by cis-ankitk** [comment]
Hey,
any update on this issue
I am facing the same issue. I recently upgrade to carrierwave v 1.2.2 and fog-google v 0.6.0 and then this issue strike

**Comment by mshibuya** [comment]
https://github.com/fog/fog-google/pull/311 seems to solve this.
