### ISSUE TITLE
undefined method `all_versions_processors' for #<Array:0x007fac47e834d8>

### ISSUE THREAD

**Issue by jcgalbano** [carrierwaveuploader/carrierwave#2295]
I followed the carrierwave documentation step-by-step using pg but still I get an error like this when I try to upload images on the form. I've googled it, but to no avail.

` @project = Project.new(proj_params) `
`  @project.user_id = @current_user.id if logged_in? `
`    if @project.save `
`     flash[:success] = "Project Succesfully Added" `
`     redirect_to new_project_path `
`   else `

The error appears to be on @project.save and when I debug it on the console returns the specific error on the title.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
