### ISSUE TITLE
Encoding::UndefinedConversionError "\xFF" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by ZASMan** [carrierwaveuploader/carrierwave#2302]
When I tried to create a new comment with an image attached, I received this error.

<img width="1037" alt="screen shot 2018-04-12 at 11 39 38 am" src="https://user-images.githubusercontent.com/13513340/38688120-4e8b58b4-3e46-11e8-9add-2b9366ac6005.png">

I got this with the following migration (I wanted to set it up for multiple image uploads):

```
  def change
    add_column :comments, :images, :json
  end
```

I found [this answer](https://stackoverflow.com/questions/24164205/carrierwave-upload-encodingundefinedconversionerror-xff-from-ascii-8bit-to) on stackoverflow where someone suggested:

> Removed support for the encode_json hook used for encoding custom objects into JSON. This feature has been extracted into the activesupport-json_encoder gem. (Related Pull Request / More Details)
> 
> Because activesupport doesn't encoding invalid code anymore. Add activesupport-json_encoder gem to Gemfile fix this issue.
> 
> 

However, this gem `activesupport-json_encoder` does not seem to be compatible with rails 5.

I did this because for postgres the documentation suggested using :json whilst using :string for an sqlite type database. Anyways, I'm moving forward with using a string and it seems to be working for now, but it might be worth updating the documentation if this isn't a valid solution anymore to use :json.

**Comment by mshibuya** [comment]
Dup of #2260.
