### ISSUE TITLE
Not working validation on heroku

### ISSUE THREAD

**Issue by harubuta** [carrierwaveuploader/carrierwave#2312]
Hi everyone.

I faced one problem that Active Record Validations for uploading image is not working on heroku  when it was updated carrierwave 1.2.2 latest version.

Do you know solution?
Could you please explain why this happens?

**Comment by MikeRogers0** [comment]
Do you have any code samples you can share?

**Comment by harubuta** [comment]
Thank you for your reply!
Yes, I share as follows.

```
class User < ActiveRecord::Base
  validates :image, presence: true

 mount_uploader :image, UserImageUploader
```

it's working for carrierwave (0.10.0) on heroku but it isn't working for carrierwave (1.2.2) on heroku.

When I try to check on development environment, It's working.

I don't know why it like image validations isn't working only on heroku.

**Comment by MikeRogers0** [comment]
Do you have the UserImageUploader / Carrierwave config also? I'm going to try to create a similar standalone app to recreate the problem you're reporting :)

**Comment by harubuta** [comment]
Yes.

UserImageUploader
```
class UserImageUploader < CarrierWave::Uploader::Base

  include Cloudinary::CarrierWave

  process :convert => 'jpg'

  version :large do
    process :resize_to_fit => [960]
    cloudinary_transformation :quality => 50, :flags=>:lossy
  end
  
  def extension_white_list
    %w(jpg jpeg png)
  end

end

```
but I don't have Carrierwave config because I upload images for the cloudinary.
I have thought it's unnecessary.

Could you give me your advice If I need Carrierwave config.
Thank you

**Comment by MikeRogers0** [comment]
Oh Cloudinary - cool 👍 

I setup an app ( https://github.com/MikeRogers0/CloudinaryHerokuDemo/tree/bug/carrierwave-not-responding-to-presence / https://damp-sea-51954.herokuapp.com/users/1 ) based upon what you've provided so far & I was unable to recreate your issue.

Do you know if you used a direct upload approach for Cloudinary ( like https://github.com/MikeRogers0/CloudinaryHerokuDemo/blob/bug/carrierwave-not-responding-to-presence/app/views/users/_form.html.erb#L35 ) or are you uploading to Heroku, then again to Cloudinary?

**Comment by harubuta** [comment]
Oh really...?but Thank you so much!!
and I don't use the direct upload approach.
I used like this.

```
<%= f.file_field :avatar %></div>
```

By the way, Would you try validation as follows?
I use it together to refer to (https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Validate-image-file-size)

```
class User < ApplicationRecord
  validates :avatar, presence: true
  validates :avatar, file_size: { less_than: 2.gigabytes }

  mount_uploader :avatar, User::AvatarUploader
end
```

or

```
class User::AvatarUploader < ApplicationUploader
  process convert: 'jpg'
  process resize_to_fill: [200, 200, "Center"]

  def size_range
    1..5.megabytes
  end

  version :user_small do
    process resize_to_fit: [60]
    cloudinary_transformation quality: "auto", flags: :lossy, fetch_format: :auto
  end
end
```
I appreciate your cooperation.
Thank you very much.

**Comment by MikeRogers0** [comment]
https://github.com/MikeRogers0/CloudinaryHerokuDemo/tree/bug/carrierwave-not-responding-to-presence - I updated my demo app to use the Pass-through uploads approach you've mentioned above & I'm still unable to recreate a validation error for the presence validator :/ However, I'm only uploading an image that is 100kb.

However, based on what you've provided I have two suggestions for you which might solve your initial problem:

1. Use Direct uploads: [Direct uploads are Herokus preferred approach](https://devcenter.heroku.com/articles/s3#direct-upload) and will save you a lot of other headaches (such as request timeouts) and it works really nicely with Carrierwave. I have an [example app](https://github.com/MikeRogers0/CloudinaryHerokuDemo/blob/master/app/views/users/_form.html.erb#L35) with some [sample JavaScript](https://github.com/MikeRogers0/CloudinaryHerokuDemo/blob/master/app/assets/javascripts/components/cloudinary.js) which should get you 90% of the way there :)
2. Ditch the file size validator: Cloudinary has a [limit of 40mb](https://support.cloudinary.com/hc/en-us/articles/202520592-Do-you-have-a-file-size-limit-), it will reject anything bigger. As it resizes on the fly, I'd just let you're users upload as much as they like & only serve a resized version of the image.
