### ISSUE TITLE
resize_to_fill and resize_to_fit create blurry thumbnails

### ISSUE THREAD

**Issue by JakeBooher** [carrierwaveuploader/carrierwave#2317]
original (2364x3152)
![y2clrxo](https://user-images.githubusercontent.com/179180/40730958-99d84c9e-63f5-11e8-807a-220eeb7c1abc.jpg)

thumb: (400x300)
![thumb_y2clrxo](https://user-images.githubusercontent.com/179180/40730968-9e5038b8-63f5-11e8-80d7-aa248fe073aa.jpg)

thumb_2x: (800x600)
![thumb_2x_y2clrxo](https://user-images.githubusercontent.com/179180/40731008-bb68f700-63f5-11e8-852c-467019096c2b.jpg)

Uploader:

```
class ProductThumbnailUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :fog
  def store_dir
    "#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  version :thumb do
    process resize_to_fill: [400, 300]
  end

  version :thumb_2x do
    process resize_to_fill: [800, 600]
  end

  # version :thumb_3x do
  #   process resize_to_fill: [1200, 900]
  # end
end
```

**Comment by mshibuya** [comment]
If you believe this to be a problem, consult with ImageMagick team(I see nothing wrong, though).

**Comment by mikecreuzer** [comment]
Looks quite blurry to me

**Comment by mikecreuzer** [comment]
Look at the street light @mshibuya

**Comment by JakeBooher** [comment]
Here is another example where it is much more obvious:

![2018-06-13_10-49-50](https://user-images.githubusercontent.com/179180/41363213-fffcff7a-6ef8-11e8-8472-4261e62b1f42.png)

![thumb_2018-06-13_10-49-50](https://user-images.githubusercontent.com/179180/41363216-026dabba-6ef9-11e8-86d4-99b6514eaabc.png)

We're not doing anything crazy, only using the resize_to_fit and resize_to_fill methods that exist within CarrierWave, if there is an issue coming from ImageMagick it's due to your integration with ImageMagick, as we're not directly using anything from ImageMagick...
