### ISSUE TITLE
Can't use Minimagick outside an uploader

### ISSUE THREAD

**Issue by a-ta-ta** [carrierwaveuploader/carrierwave#2318]
I'm using Carrierwave with minimagick and thankfully it does everything fine.

Nevertheless, today I faced the fact that it somehow  modifies minimagick methods so I can't use Minimagick outside uploaders.

```
class Image < ApplicationRecord
 	require 'carrierwave'
	require 'carrierwave/orm/activerecord'
        require 'minimagick'

	mount_uploader :imageup, ImageupUploader

  def crop(width, height, x, y)
		image = MiniMagick::Image.open(self.imageup.file.file)
		image.crop "#{width}x#{height}+#{x}+#{y}"
  end
end
```

So when I call the crop method it crashes with:
```
MiniMagick::Error (`mogrify -imageup /tmp/mini_magick20180602-10185-1ujzsmw.jpg` failed with error:
mogrify: unrecognized option `-imageup' @ error/mogrify.c/MogrifyImageCommand/5096.
):
```

I tried using:
```
MiniMagick::Tool::Mogrify.new do |mogrify|
  mogrify.crop("#{width}x#{height}+#{x}+#{y}")
  mogrify << "image.jpg"
end
```

But still command is becoming modified with -imageup...

**Comment by mshibuya** [comment]
How does full stack trace look like?

**Comment by a-ta-ta** [comment]
```
MiniMagick::Error (`mogrify -imageup /tmp/mini_magick20180604-3878-udq9zj.jpg` failed with error:
mogrify: unrecognized option `-imageup' @ error/mogrify.c/MogrifyImageCommand/5096.
):
  
app/controllers/images_controller.rb:117:in `block in set_resized_ava'
app/controllers/images_controller.rb:116:in `set_resized_ava'

```

That's all what appears...

**Comment by mshibuya** [comment]
Can you paste what have around `app/controllers/images_controller.rb:117` ?

**Comment by a-ta-ta** [comment]
Of course! Here it goes:
```
  def set_resized_ava
    image = Image.find(params[:id]).crop( params[:avatar_x].to_f, 
                                          params[:avatar_y].to_f, 
                                          params[:avatar_width].to_f, 
                                          params[:avatar_height].to_f)
    respond_to do |format|
      if current_user.update!(ava: image.imageup)
        format.html { redirect_to current_user, notice: 'Avatar set!!' }
      else
        format.html { redirect_to current_user, notice: "Error took place" }
      end
    end
  end
```

**Comment by a-ta-ta** [comment]
@mshibuya , thank you very much for helping! 

Could it happen that MiniMagick inherits not from its base class Image but from my Image class when I do `image = MiniMagick::Image.open(self.imageup.file.file)` or that's nonsense?

**Comment by mshibuya** [comment]
That's not the point, you just can't pass `image` as `current_user.update!(ava: image.imageup)`, because `image` is a `MiniMagick::Image` instance returned from `Image#crop`. Don't mix it up with an `Image` model instance.
You'd better make sure what you do is intentional step by step, not try to accomplish everything at once.

**Comment by a-ta-ta** [comment]
Right! Thank you very much once more!
