### ISSUE TITLE
Losing content-type when copying file from cache to permanent store

### ISSUE THREAD

**Issue by ollieh-m** [carrierwaveuploader/carrierwave#2319]
We use rackspace for our cloud storage, and recently switched the cache store to be in rackspace as well (because we have multiple servers and cannot guarantee the cached file will be on the same server that receives a request to resubmit a form).

The problem is that now the content type goes missing when a pdf or docx file is saved.

I've fixed it by overriding the copy_to method as below:
```
  def copy_to(new_path)
    # add content-type to headers so the content-type is correctly set when copying from the cache to the permanent store
    headers = self.send(:acl_header).merge({'Content-Type'=>content_type})
    # now carry out the original copy_to method with the customised headers
    connection.copy_object(@uploader.fog_directory, file.key, @uploader.fog_directory, new_path, headers)
    CarrierWave::Storage::Fog::File.new(@uploader, @base, new_path)
  end
```

Should the content-type be set explicitly in the headers like this?

Any ideas as to why rackspace isn't copying the content-type properly anyway?

Many thanks!

**Comment by mshibuya** [comment]
Looks like fog-rackspace issue, though I'm unclear about why it has been closed.
https://github.com/fog/fog-rackspace/issues/9
