### ISSUE TITLE
how to set filename without actually uploading file

### ISSUE THREAD

**Issue by ryancheung** [carrierwaveuploader/carrierwave#2325]
Since I use qiniu file storage, before create db record, the file was already uploaded with the qiniu js client, then there's no need to actually upload file in rails server. All I need to do is set the image db field.

**Comment by saiqulhaq** [comment]
I think it should be done with your regular rails code, not carrierwave
so qiniu js should send filename with full path

if it exist, then from your model, create new record with `File.open(filepath)`
and be careful with security

**Comment by ryancheung** [comment]
Yeap, I'm closing this issue.
