### ISSUE TITLE
Get a  different file in version after uploading

### ISSUE THREAD

**Issue by evinsou** [carrierwaveuploader/carrierwave#2327]
Hello. I have worked on uploading hls playlist to s3.
I am wondering, it is possible to change a source file before uploading, or set another url after upload?
 
As I see desired behavior, I upload a file, in some version it is processed, I get a master hls playlist and upload the file (playlist) for using it later.

Maybe, I have missed something and there is another solution for the problem, or no one needs to upload hls playlist to s3.

**Comment by BryanH** [comment]
Ask support questions on [StackOverflow](https://stackoverflow.com/questions/tagged/carrierwave)
