### ISSUE TITLE
`store_dir` change breaks file saving

### ISSUE THREAD

**Issue by cireficc** [carrierwaveuploader/carrierwave#2328]
This is a minimal example to demonstrate the fact that changing the `store_dir` for an uploader, then subsequently updating a record with a mountable file causes `Errno::ENOENT: No such file or directory` (or a Fog error). I have some models:

```ruby
class Tenant < ApplicationRecord
    has_many :files

    after_update :update_files

    def update_files
        files.each do |file|
            file.path.recreate_versions!
            file.save
        end
    end
end
```

```ruby
class File
    belongs_to :tenant
    mount_uploader :path, FileUploader
end
```

and the uploader:

```ruby
class FileUploader < CarrierWave::Uploader::Base

    storage :file

    def store_dir
        tenant = model.tenant.decorate
        "#{tenant.full_name}"
    end

    def filename
        name = model.tenant.decorate.full_name
        date = DateTime.now.strftime('%Y-%d-%m')
        "#{name} #{date}.#{file.extension}"
    end
end
```

Pretty simple stuff. I can upload files just fine, and they are named appropriately.

I am trying to re-organize the files if `Tenant` data is changed, i.e. their first or last name, via an `after_update` callback. However, this breaks the `store_dir` method and thus the path to the file.

For example, if I have a file stored in the folder `/John Doe/` and the tenant's name is changed to *Updated Doe*, I would like all the associated files to move to `/Updated Doe/`, and have the *John Doe* directory/files disappear (i.e. a standard file _move_ operation).

However, I get the following error (local `:file` storage):

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /path/to/my-app/public/Updated Doe/John Doe 2018-18-07.pdf
```

It seems that the `store_dir` should update *after* the file has been loaded, so that it loads the file correctly before the update.

If I make the `store_dir` static, of course everything works fine. But for my use case, I need to have a folder for each `Tenant` using their full name. If an employee made a mistake entering the tenant name, or if some tenant data changed, I want to be able to reflect those changes in the *folder structure*, and not just in the file name. It seems CarrierWave assumes that the `store_dir` won't ever change.

**Is this a bug, or am I simply doing things wrong?** Ideally, simply updating model attributes in this case should automatically change the `store_dir` and `filename` attributes, as well as move the local file according (or send a PATCH request through Fog). At least that's what the expected behavior is... but it seems the `store_fir` is updated before the file is loaded, meaning that if it *changed*, the file path will be broken. I don't think that should be happening.

Is there a way to work around this or is this a bug that can be fixed?

**Comment by mshibuya** [comment]
This is obvious, you must take care of stored files yourself if you want to change `store_dir`.

**Comment by cireficc** [comment]
> This is obvious, you must take care of stored files yourself if you want to change `store_dir`.

Why can't the library move the files when the `store_dir` changes? I had to write a ton of code to deal with this issue, when **it seems the library already knows the _previous_ `store_dir` when it deals with the file, and it knows the _new_ `store_dir`. Why can't the library properly move the file when the `store_dir` changes?** I'm not aware of any technical limitation to do this. Here's the kind of code I wrote to fix the issue, which just boils down to taking the old path, copying the file to the new path, and deleting the file at the old path (a standard way to move files):

```ruby
# Manually moves/renames the tenant's file directory using its old data to find the file, and new data for the new
# path to move to. We have to do this because CarrierWave updates the path without moving the actual file. This method
# will move the ComplianceFile (CF.path) associated with the tenant, as well as supplemental uploads (CF.supplemental_files).
def self.move_compliance_files(tenant, unit_id_was, hoh_first_name_was, hoh_last_name_was)
    tenant.compliance_files.each do |file|
        old_file_path = old_file_path(file, tenant, unit_id_was, hoh_first_name_was, hoh_last_name_was)
        new_file_path = new_file_path(file)
        move_file(file, old_file_path, new_file_path)
    end
end
	
def self.copy_file(file, old_file_path, new_file_path)
    new_filename = file.path.filename
    
    bucket = google_cloud_storage_bucket
    cloud_file = bucket.file(old_file_path.to_s)
		
    if cloud_file
        cloud_file_copy = cloud_file.copy(bucket.name, new_file_path.to_s)
        # Make sure to set the ACL to public so that the application links work properly
        cloud_file_copy.acl.public!
    else
        'Google Cloud Storage: file not found, skipping move'
    end
		
    # Make sure that the database has the new file by forcing an update
    file.update_column(:path, new_filename)
end

def self.delete_file(file_path)
    bucket = google_cloud_storage_bucket
    cloud_file = bucket.file(file_path.to_s)
    if cloud_file
        cloud_file.delete
    else
        puts 'Google Cloud Storage: file not found, skipping deletion'
    end
end
	
private
	
def self.old_file_path(file, tenant, unit_id_was, hoh_first_name_was, hoh_last_name_was)
    # If the building, unit, tenant software id, tenant first name or tenant last name had changed, we have to use that
    # when building the old path
    previous_tenant_full_name = "#{hoh_first_name_was} #{hoh_last_name_was}"
    previous_unit = Unit.find(unit_id_was)
    old_storage_directory = Pathname.new(ComplianceFileUploader.storage_directory(previous_unit, tenant.id, previous_tenant_full_name))
    old_filename = ComplianceFileUploader.full_filename(previous_tenant_full_name, file, file.created_at, file.path.file)

    old_storage_directory.join(old_filename)
end
	
def self.new_file_path(file)
    Pathname.new(file.path.store_dir).join(file.path.filename)
end
	
# Move a file by copying from the old path to the new path, then deleting the file at the old path
def self.move_file(file, old_file_path, new_file_path)
    copy_file(file, old_file_path, new_file_path)
    delete_file(old_file_path)
end
```

The above code works - if `store_dir` changes, it'll move the files. However, this is all code that could be in the library, because CarrierWave already knows about the old and new storage directories. I don't think it should be the end-user's responsibility to prevent their file links from breaking - CarrierWave should be handling this in my opinion.

**Comment by mshibuya** [comment]
It's an open source project, you can open a pull request if you believe such a feature useful.
Please be sure to include test code to keep it maintainable!
