### ISSUE TITLE
Potential security vulnerability in the default error messages configured in en.yml

### ISSUE THREAD

**Issue by tomichal** [carrierwaveuploader/carrierwave#2335]
Hi there,
This likely is not a big deal, but thought I'd post it out there just in case and it can be closed if it's a non-issue. 

Here it is:
The default error message configured in the en.yml file, e.g.: `en.errors.messages.mini_magick_processing_error`, exposes the original error coming from MiniMagick, which in turns contains file system paths (i.e. "/tmp/343lqf/..."). 

The error can be triggered by uploading a bad image file (e.g. a text file saved as a "jpeg").

Perhaps this is of no value to a potential attacker and it can be easily fixed anyway by customizing the error message in your project, but maybe the default message should not include this info just in case the message is not customized in your project and in case the error contains some sensitive info?

**Comment by mshibuya** [comment]
Merging this into #2499.
