### ISSUE TITLE
Broken when content_type is gif but extension isn't

### ISSUE THREAD

**Issue by ff2248** [carrierwaveuploader/carrierwave#2341]
Hi,

I got an error when user input a unusual url, the content type is `image/gif` but extension is `jpg`.

Is it a bug? or it should be check before setting to remote url?

Thanks!

```ruby
image_url = 'https://lh3.googleusercontent.com/-uiEq1knng2s/AAAAAAAAAAI/AAAAAAAAAB4/uGZctJ6lcbM/photo.jpg'
user.remote_avatar_url = image_url

# It will be raise: 
# Errno::ENOENT: No such file or directory @ rb_sysopen - /var/folders/jc/sw7m_53j3ln_mb084z_3ywnh0000gn/T/mini_magick20181011-99489-145wzoe.jpg
```

### System configuration
**carrierwave version**: 1.2.3

**mini_magick version**: 4.9.2

**ruby version**: 2.3.3

**rails version**: 4.2.10

**Comment by mshibuya** [comment]
Merging this into #2111.
