### ISSUE TITLE
undefined method `map' for #<ActionDispatch::Http::UploadedFile:0x007fe977eec7e0> Did you mean? tap

### ISSUE THREAD

**Issue by Theopaps** [carrierwaveuploader/carrierwave#2347]
Hello,

I'm using a nested form to create the item, upload multiple files through the nested form field and then create each file(attachment) in a column.

Unfortunately I can't get it to work because I' getting this error: 
`undefined method map' for #<ActionDispatch::Http::UploadedFile:0x007fe977eec7e0> Did you mean? tap`

This is the setup I have:

    class Item < ApplicationRecord
      has_many :attachments, dependent: :destroy
      accepts_nested_attributes_for :attachments, allow_destroy: true

    class Attachment < ApplicationRecord
      belongs_to :item
      mount_uploaders :media_files, AttachmentUploader
      validates_presence_of :media_files

    <%= form_for(@item, url: items_create_path, :html => { :id => "fileupload", :multipart => true }) do |form| %>
     <%= form.text_field :title, id: :item_title, autofocus: true, :class=>"form-control" %>
    <%= form.text_area :description, id: :item_description, :class=>"form-control" %>
      <%= form.hidden_field :category_id, value: 1 %>
      <%= form.fields_for :attachments do |f| %>

     <%= f.file_field :media_files, multiple: true %>
      <%= f.hidden_field :item_id, value: @item %>
      <% end %>

     <%= form.submit "Submit", :class=>"btn btn-default" %></div>

This is the create method for the item and where I'm trying to loop through each file from the nested form field and create an attachment. And also that is the line where the error happens.

    def create
       @item = Item.new(item_params)

    respond_to do |format|
      if @item.save

        params["item"]["attachments_attributes"]["0"]["media_files"].each do |a|
          @attachment = @item.attachments.create!(:media_files => a, item_id: @item.id, account_id: nil)
        end

        format.html { redirect_to items_show_path(id: @item.id), notice: 'Success' }
        format.json { render :'shows/show', status: :created, location: @item }
        new_page_email_followers
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
      end
     end

The schema for both models:

    create_table "items", force: :cascade do |t|
      t.string "title"
      t.string "description"
      t.integer "category_id"
      t.integer "account_id"
      t.datetime "created_at", null: false
      t.datetime "updated_at", null: false
    end

    create_table "attachments", force: :cascade do |t|
      t.integer "item_id"
      t.integer "account_id"
      t.string "media_files"
      t.string "content_type"
      t.boolean "success"
      t.datetime "created_at", null: false
      t.datetime "updated_at", null: false
    end

And this is the route:
 
     post "items/create"=> "items#create", :as => :items_create

Any ideas on how to make this work?

**Comment by mshibuya** [comment]
Sounds obvious, because `:media_files` is supposed to be an array of ActionDispatch::Http::UploadedFile.

```ruby
      @attachment = @item.attachments.create!(:media_files => a, item_id: @item.id, account_id: nil)
```
