### ISSUE TITLE
Is carrierwave thread-safe?

### ISSUE THREAD

**Issue by linyaoli** [carrierwaveuploader/carrierwave#2348]
I'm using Sidekiq and Carrierwave to upload images to S3. The background job does the following things:

1. Downloads image from a remote url;
2. Resizes it using minimagick;
3. Uploads the resized images to S3.

Here's the code snippet:
```ruby
  def store_for_mobile(file)
     self.class.process optimize: [1080, 810]
     %w(android ios).each do |device|
        @directory = File.join('banners/mobile', device)
        store!(file)
     end
  end

  def store_for_web(file)
     self.class.process optimize: [750, 562]
     @directory = 'stores/750x562/'
     store!(file)
  end

  def store_header(file)
    self.class.process resize_to_limit: [640, 640]
    @directory = 'headers/images/consumer_app_brand_logos/'
    store!(file)
  end

  def store_header_mailer(file)
    self.class.process resize_to_limit: [360, 120]
    @directory = 'headers/images/360x120/'
    store!(file)
  end
```
The above methods are executed in different jobs respectively, which means sometimes they are running concurrently.

Soon I noticed that some images resized by store_header_mailer were uploaded to the directory which should be owned by store_for_mobile, store_for_web and store_header. (e.g. 'headers/images/consumer_app_brand_logos/' got 120x120 images)

This issue didn't exist while I was using Resque.

I looked into carrierwave's source code, and noticed that

~~https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/processing.rb#L54~~

~~it is using class variables `self.processors` and class methods `self.process` while invoking image_magick command lines.~~

https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/processing.rb#L9

the class_attributes are modified and shared by different instances.

Is this part of code thread-safe? or it is designed on purpose? Thanks in advance.

**Comment by BryanH** [comment]
Ask support questions on [StackOverflow](https://stackoverflow.com/questions/tagged/carrierwave)

**Comment by mshibuya** [comment]
Calling `self.class.process` from a uploader instance will cause thread-safety issue, as you mentioned.
Use condition instead, in this way class's processors are not modified on processing.
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/processing.rb#L33-L34
