### ISSUE TITLE
bypass wrong file type

### ISSUE THREAD

**Issue by illia108** [carrierwaveuploader/carrierwave#2351]
Hi.
I use carrierwave with rails.

If a user uploads file with a wrong type I want to set a default fallback image.

I don't want to show any notification. So if instead of jpg jpeg gif png it's a txt I just want to set default.jpg.

I have these two snippets in my uploader. But I believe I need something else here.

```
def default_url(*args)
  "/images/default.jpg"
end

def extension_whitelist
  %w(jpg jpeg gif png)
end
```

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
