### ISSUE TITLE
Uploads do not work across form redisplays

### ISSUE THREAD

**Issue by ianaverno** [carrierwaveuploader/carrierwave#2353]
Carrierwave does not cache files:

in _form.haml:
```
= f.input :attachment, label: false
= f.input :attachment_cache, as: :hidden
```
in controller the `:attachment_cache` is permitted;
in the model I have `attr_accessor :attachment_cache`

After a validation fails, I can verify, that the object has a file, but it's not cached, so the form tells me, there is an upload, however, after resubmit, the file isn't saved

Rails v. 4.2.7.1
Carrierwave v. 1.2.3

Current doc is misleading, many other reports on the same issue have no solution, because there is no info on conditions required for this to work. It's either broken, or only works in primitive scenarios with local file storage. For me this didn't work for nested objects, and it doesn't work for `:fog`

**Comment by richardrails** [comment]
For me too. Do you have some workaround?

**Comment by ianaverno** [comment]
None, unfortunately. This feature is still iceboxed for us.

**Comment by mshibuya** [comment]
This does work if you set `cache_storage :fog`, and in CarrierWave 2.0.0 default `cache_storage` will be the same as `storage`.

**Comment by rogerhu** [comment]
This change breaks AWS S3 storage - I think the cache_storage should be :file, not the default storage.

```
  config.fog_credentials = {
      provider: 'AWS',
      region: 'us-west-2'
    }
config.storage = :fog
config.cache_storage = :file
```

**Comment by sshaw** [comment]
Yeah if you upgrade and the bucket has a policy that restricts the resource's (bucket's) path things will likely fail since uploads will now go to `/uploads/tmp` 🙀
