### ISSUE TITLE
How can I get CarrierWave to stop putting mystery filenames in my mount column?

### ISSUE THREAD

**Issue by myfitment** [carrierwaveuploader/carrierwave#2371]
All I want is for CarrierWave to preserve the way that I named the file after I assign the file to the record.

I have an AR model called Publication. It contains a column called "payload".

My program writes the file and calls it:

    xyz123.xml

now:

    publication.payload = File.open("xyz123.xml")
    publication.save!

When I look in the record, inside the payload column I see the word upload.

If I do:

    publication.upload.path

I see:

    upload/upload

What exactly is that?

I desperately need my filename to be there, because I am looking the record up by filename later and performing some actions.

This is my uploader:

    # encoding: utf-8
    class PayloadUploader < CarrierWave::Uploader::Base

      def extension_white_list
        %w(csv xml txt xlsx)
      end

      def fog_attributes
        {'Content-Disposition' => "attachment"}
      end

      def delete_local_copy(dummy)
        local_filename = Rails.root.join(store_dir,File.basename(filename))
        FileUtils.rm(local_filename) if File.exists?(local_filename)
      end

    end

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
