### ISSUE TITLE
Strange routing behavior when submitting forms with File upload/File field in Production

### ISSUE THREAD

**Issue by Rubioli** [carrierwaveuploader/carrierwave#2372]
In my application I'm using `carrierwave` for image upload.

My `CampaignsController` is a usual `create action`

    def create
      @campaign = Campaign.new(campaign_params)
    
      respond_to do |format|
        if @campaign.save
          format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
          format.json { render :show, status: :created, location: @campaign }
        else
          format.html { render :new }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end

Everything works fine in `development`, but in `production` after submit/save things go wrong.

By that I mean:
In `development` when form is submitted, after save it goes to `localhost:3000/campaigns/38` and my form is: `action="campaigns/38"`

*BUT*

In **production** when form is submitted, after save, instead of going to `example.com/campaigns/38`, it goes to `example.com/campaigns/campaigns/38` and my form changes to: `action="campaigns/campaigns/38"`. 

As you can see that extra `campaigns` is in the URL and I'm not sure why.

This is my `routes.rb`:

    Rails.application.routes.draw do
      resources :campaigns do
        get 'changes', to: 'campaigns#deactivate_activate'
        put 'changes', to: 'campaigns#deactivate_activate'
      end
    
      # match '*any' => 'application#options', :via => [:options]
    end

This is my `ImageUploader`:

    class ImageUploader < CarrierWave::Uploader::Base
      include CarrierWave::MiniMagick
    
      storage :file
    
      def store_dir
          "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
      end
    
      version :large do
        resize_to_limit(600, 600)
      end

My `Campaign` Model:

    class Campaign < ApplicationRecord
      mount_uploader :image, ImageUploader

This is my application version:

    ruby "2.3.1"
    gem 'rails', '~> 5.1.6'
    carrierwave (1.3.1)

I've been testing with different things to see what exactly is the issue. I tested with `simple_form_for`, `form_for` and even removed parts of the `form`.

Everything works as long as `= f.file_field :image` is not there. when I remove `= f.file_field :image` from my `form` everything works fine in all ENVs, but when I add it back, its than `Production` has this strange behavior.

Any help is appreciated and thanks in advance!

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
