### ISSUE TITLE
Overridden methods

### ISSUE THREAD

**Issue by mainameiz** [carrierwaveuploader/carrierwave#2379]
Hello!

First of all, many thanks for all maintainers of this gem. It became a default gem for handling file uploads for many of us.

----

I just noticed that carrierwave overrides some useful methods on ActiveRecord models

E.g. `reload` 

https://github.com/carrierwaveuploader/carrierwave/blob/f15f4ba71dd2c78e8df494bf65938bbaf13960f9/lib/carrierwave/orm/activerecord.rb#L87-L90

And `initialize_dup`

https://github.com/carrierwaveuploader/carrierwave/blob/f15f4ba71dd2c78e8df494bf65938bbaf13960f9/lib/carrierwave/orm/activerecord.rb#L93-L96

So, if I also want to override these methods (and I do it :roll_eyes:) I will break some features of carrierwave. WDYT is it possible to rework this part of code? I will try to make a PR if you are OK with it.

**Comment by mshibuya** [comment]
Thanks for the idea, it would make sense to move them in anonymous module and prepend it in the model.
