### ISSUE TITLE
Zeitwerk, Rails 6 autoloader, and carrierwave uploaders models

### ISSUE THREAD

**Issue by remomueller** [carrierwaveuploader/carrierwave#2380]
Hi, I'm trying to get carrierwave v1.3.1 working with rails 6.0.0.beta2 (and onwards) with zeitwerk enabled, and I typically get the following errors when running tests for models that access an uploader:

```console
rails test
...
ActiveRecord::Fixture::FixtureError: table "users" has no columns named "somerelationship".
...
```

The error is coming from the fact that the model is unable to get loaded past the "mount_uploader" step, and it then doesn't know about the belongs_to relationship.

My models have something like this:

```ruby
class User
  mount_uploader :picture, PictureUploader
  ...

  belongs_to :somerelationship
end
```

There is also a corresponding `app/uploaders/picture_uploader.rb`.

I've been able to fix this by adding the following to my `config/initializers/carrierwave.rb` file:

```ruby
# Preload uploaders folder
autoloader = Rails.autoloaders.main
uploaders = Dir.glob(Rails.root.join("app", "uploaders", "*.rb"))
uploaders.each do |uploader|
  autoloader.preload uploader
end
```

Is this a good way to load the `app/uploaders` folder, or is there a better way (or even a way where carrierwave does this for you in Rails 6?)

Alternatively, I've also noticed changing the "zeitwerk" autoloader back to "classic" fixes this without the initializer as well.

In `application.rb`
```
module MyApplication
  class Application < Rails::Application
    config.load_defaults 6.0
    config.autoloader = :classic # :zeitwerk by default in 6.0
    ...
  end
end
```

Thanks!

**Comment by fxn** [comment]
If you have a file called `app/uploaders/picture_uploader.rb`, autoloading should work without a problem.

Do you see any relevant error? Can you enable traces without preloading and share them?

In `master` engines are managed by the `main` autoloader and there are some optimizations, but in principle this particular use case should work in beta 2.

**Comment by remomueller** [comment]
Hi @fxn, I do have the `app/uploaders/picture_uploader.rb` file as that location. I'll see if I can replicate this in a smaller application to make sure nothing else is interfering, and I'll enable the traces as well, thanks!

**Comment by remomueller** [comment]
Hi @fxn, just tried to replicate on a fresh 6.0.0.beta3 app with carrierwave and zeitwerk enabled, and I couldn't reproduce the issue. It may be spring related, but for the time being this issue can be closed.

**Comment by fxn** [comment]
Fantastic!

**Comment by remomueller** [comment]
Just an FYI, I figured out what caused the issue. I had the following setup which zeitwerk wasn't expecting:

`models/item.rb`
```
mount_uploader :file, ItemPDFUploader
```

`uploaders/item_pdf_uploader.rb`
```
class ItemPDFUploader
end
```

Turns out, the casing for `PDF` needs to be changed to `Pdf` to work correctly with zeitwerk. It had correctly autoloaded the uploaders folder, but had expected the naming to be camelized.

```
Error:
ItemsControllerTest#test_should_get_show:
NameError: uninitialized constant #<Class:0x00007f9d1fb34228>::ItemPDFUploader
Did you mean?  ItemPdfUploader
```

Fortunately it's a quick fix, and made me learn a bit more about how the constants (in zeitwerk) are loaded. Closing this issue.

**Comment by fxn** [comment]
Awesome.

Classic mode looks for a file given a constant name (`underscore`), while Zeitwerk mode infers a constant name from a file name (`camelize`), to set an autoload for it.

In a case like yours, you can either rename the constant, or also define an acronym in `config/initializers/inflections.rb`:

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'PDF'
end
```

With that, you'll get it the way you had it:

```
$ bin/rails runner 'puts "item_pdf_uploader".camelize'
Running via Spring preloader in process 1798
ItemPDFUploader
```

Thanks for testing the new mode, I learn from these experiences and that may be reflected in documentation or the upgrade guide. ❤️

**Comment by remomueller** [comment]
Thank you for the detailed information! The `Rails.autoloaders.logger = method(:puts)` did help to see that the files were loaded as expected and was helpful in understanding how it references files that it "loads". Also, thanks for the work you've put into zeitwerk! I think I have a few more modules to restructure slightly in my larger code bases in order to work correctly with zeitwerk, but the [README.md](https://github.com/fxn/zeitwerk/blob/master/README.md#file-structure) has been pretty detailed in how those changes need to be made.
