### ISSUE TITLE
Upload record exists but file physically missed from S3

### ISSUE THREAD

**Issue by sveredyuk** [carrierwaveuploader/carrierwave#2385]
Files magically missed from S3. We still have the record in DB about upload with file_url, but S3 file missing. S3 logs display 4 records: 1 PUT for update and 3 DELETE's for this attachment, but still - record in db is present do not deleted. How it could possible that something delete record from S3 and not change record in DB?

**Comment by mshibuya** [comment]
What version of carrierwave are you on?

**Comment by mshibuya** [comment]
Please reopen on update.
