### ISSUE TITLE
Carrierwave and Multitenancy

### ISSUE THREAD

**Issue by paulmdi** [carrierwaveuploader/carrierwave#2389]
Our app is utilising multitenancy with AWS . And file uploading does have issues with pointing to the right S3 bucket. By the way, we are using `CarrierWaveDirect::Uploader`

I cant find any reference where to set the current tenant to the uploader.

Is multi-tenancy supported?

**Comment by mshibuya** [comment]
There's a way to change storage configuration dynamically.
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Define-different-storage-configuration-for-each-Uploader.

**Comment by paulmdi** [comment]
in our case we just overwrite the `fog_directory` and provided the right subdirectory, such that during the tenant switch, the files goes to the right directory.


thanks
