### ISSUE TITLE
mount_uploaders fails to upload images to cloudinary and save in DB

### ISSUE THREAD

**Issue by Pifoupif** [carrierwaveuploader/carrierwave#2396]
Hello,

Via an html form I'm trying to upload multiple images to Cloudinary and save those images in a single postgre array column. Both of these actions are failing and I'm not sure why and how I can fix it.

PhotoUploader:
```
class PhotoUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave
end

```

Model:
```
class Profile < ApplicationRecord
  mount_uploaders :photos_library, PhotoUploader
end
```

DB:
```
create_table "profiles", force: :cascade do |t|
  ...
  t.text "photos_library", array: true
  ...
end
```

Controller:
```
 def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path
    else
      render 'new'
    end
  end

def profile_params
  params.require(:profile).permit({ photos_library: [] })
end
```

Form:
```
<%= simple_form_for(@profile, html: { multipart: true }) do |f| %>
  <%= f.file_field :photos_library, multiple: true, as: :file, input_html: { multiple: true }, label:"Librairie de photo" %>
  <%= f.input :photos_library_cache, as: :hidden %>
  ...
<% end %>
```

It seems like both images are properly inserted into:

![image](https://user-images.githubusercontent.com/23505154/57364795-26acee80-7184-11e9-8c75-a086e70bde03.png)

But then updated as an empty array (or hash?!):

![image](https://user-images.githubusercontent.com/23505154/57364867-447a5380-7184-11e9-9563-1c4c6e42b3a0.png)

The corresponding profile is created but none of the images are available and the corresponding DB column is an empty [] (note that I'm doing exactly the same thing with a mount_uploader for a single image on another column and it works perfectly).

I have also tried with a `serialize :photos_library` in my model but I get the following error:
![image](https://user-images.githubusercontent.com/23505154/57365363-324ce500-7185-11e9-9248-64d84c648d98.png)

Can anyone help?
Thanks

**Comment by mshibuya** [comment]
Multiple upload feature is meant to be used with a json column, not an array.

**Comment by Pifoupif** [comment]
So why does the documentation says array or json?
![image](https://user-images.githubusercontent.com/23505154/57383275-c8493580-71ae-11e9-87ea-a880050398cb.png)

I've also seen a fair amount of posts online using it with an array column.

I think I need to use an array column because I'm planning to also use this feature with active admin which doesn't seem to support JSON column. 

See this post for example:
https://github.com/carrierwaveuploader/carrierwave/issues/1653

Can you please let me know why my setup above doesn't work + let me know what the best approach is to do this active admin?

**Comment by Pifoupif** [comment]
I just tried (again) with a JSON postgres type column and still get the exact same behaviour. The newly created record doesn't have anything in the corresponding column.

Can you please re open this issue?
