### ISSUE TITLE
Image Upload with CSV record import

### ISSUE THREAD

**Issue by Rubioli** [carrierwaveuploader/carrierwave#2402]
I'm importing posts with CSV, but I have issue with uploading images when I import record with CSV.

Basically, in my application, I insert records by importing a CSV file. Everything on that part works well. I tried to upload images with *remote_image_url*, but with no luck.

I would appreciate if anyone can come tips on how I can upload files when importing records with CSV.

Thanks in advance!

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/carrierwave) for the support request, thanks.
