### ISSUE TITLE
Invalid file extension on remote url with no extension

### ISSUE THREAD

**Issue by yllihv27** [carrierwaveuploader/carrierwave#2408]
I am trying to upload image from a remote url like this with no luck

https://api.tbotechnology.in/imageresource.aspx?img=FbrGPTrju5e5v0qrAGTD8pPBsj8/wYA5fyPRj8rAX+R5MnG/qe2Xb8ueHLbdyMeDVVxboAU+ZCXgWhBgn65dhqCeVbV9c4elBy/wk3I3G2RgiVB6XTRYPQ==

**Comment by mshibuya** [comment]
Dup of #1768.
