### ISSUE TITLE
store_avatar! has not been defined

### ISSUE THREAD

**Issue by lewislinlin** [carrierwaveuploader/carrierwave#2414]
1.3.1 Upgrade to 2.0.0  method store_#{column} not defined
```ruby

class MediaMaterial < ApplicationRecord
  attr_accessor :skip_uploader
  mount_uploader :file, ImgUploader

  skip_callback :save, :after, :store_file!, if: -> { skip_uploader } # carrierwave 1.3.1 ok, 2.0.0 false
  skip_callback :save, :before, :write_file_identifier, if: -> { skip_uploader }
end

```

- ruby 2.5.3
- Rails 5.2.3

**Comment by pione30** [comment]
I'm facing exactly the same issue on 2.0.2 

- ruby 2.6.3
- Rails 5.2.3

**Comment by redscode** [comment]
Just ran into this same issue.

As of this commit:
https://github.com/carrierwaveuploader/carrierwave/commit/665f2254a2c70385b67942b13a4710dc6826c42d

The callback was moved from save to commit.
Changing to `skip_callback :commit` will fix your issue.
