### ISSUE TITLE
Removing uploaded files fails in 2.0.0

### ISSUE THREAD

**Issue by pbougie** [carrierwaveuploader/carrierwave#2416]
CarrierWave 2.0.0 fails to delete the assets when using a form checkbox to remove a file. The file is properly removed in the database but is not deleted from S3 (in my case). However, if I update an image, it properly deletes the previous version from S3 and replaces it as expected. Everything worked as expected in CarrierWave 1.3.1. I should also mention that I'm using CarrierWave for Mongoid if that makes a difference. Anybody else experiencing this problem?

**Comment by mshibuya** [comment]
If you could provide reproduction steps I can take a look.

**Comment by espen** [comment]
I'm also facing this issue. However in my case it works on S3 but in local development using file storage the file is not deleted (the db value is set as nil).
