### ISSUE TITLE
default_url not working on heroku with cloudinary

### ISSUE THREAD

**Issue by mayankkumarji** [carrierwaveuploader/carrierwave#2418]
HI There,

When I am using default_url in the up-loader to use one default image when there will be no image, so it works fine at local. but didn't work when deploy it on heroku server. 
I am using cloudinary to store images, so should I also create any folder there to store default.png or I am missing something here. 

here is the code of uploader.
///////////////////////
  def default_url(*args)
    # "/images/fallback/" + [version_name, "default.png"].compact.join('_')
    ActionController::Base.helpers.asset_path("/assets/fallback/" + ["default.png"].compact.join('_'))
  end
///////////////////////

Added default.png to "/assets/images/fallback" folder into app. 

@thomasfedb @bensie

**Comment by mshibuya** [comment]
Make sure that the file is included in the asset pre-compilation target.
