### ISSUE TITLE
TMP file url instead of AWS storage url, after migration from 1.3.1 to 2.0.1

### ISSUE THREAD

**Issue by AleksandrLeontev** [carrierwaveuploader/carrierwave#2421]
I save `Message` model with nested `Attachment` model via `accepts_nested_attributes_for` and everything works on 1.3.1
When I migrate to 2.0.1 in general everything work, except one moment:
First time server return tmp path instead of absolute file path to AWS.
When I try to check attachment url via rails console or reload the page it works, but right after first upload `uploader` start return tmp file with 2.0.1 version

**Comment by mshibuya** [comment]
Can I take a look at your uploader code?

**Comment by AleksandrLeontev** [comment]
`# frozen_string_literal: true

class AttachmentUploader < BaseUploader

  version :show, if: :image? do
    process resize_to_fit: [720, 720], if: :check_dimensions
    process :store_dimensions
  end

  version :image_show, if: :image? do
    process resize_to_fit: [200, 200], if: :check_dimensions
  end

  version :pdf_thumb, if: :pdf? do
    process :thumbnail_pdf
    process resize_to_fit: [200, 200]
    process convert: :jpg
    process :set_content_type

    def full_filename(for_file = model.source.file)
      super.chomp(File.extname(super)) + '.jpg'
    end

  end

  def set_content_type(*_args)
    file.instance_variable_set(:@content_type, 'image/jpeg')
  end

  protected

  def extension_white_list
    %w[pdf jpeg jpg png tiff]
  end

  def pdf?(new_file)
    model.new_record? ? new_file.content_type.include?('pdf') : model.content_type.include?('pdf')
  end

  def image?(new_file)
    model.new_record? ? new_file.content_type.start_with?('image') : model.content_type.start_with?('image')
  end

  def check_dimensions(_new_file)
    width, height = ::MiniMagick::Image.open(file.file)[:dimensions]
    (width > 720) || (height > 720)
  end

  def store_dimensions
    model.image_width, model.image_height = ::MiniMagick::Image.open(file.file)[:dimensions] if file && model
  end

  def thumbnail_pdf
    manipulate! do |img|
      img.format 'png' do |convert|
        convert.density '100'
        convert.quality '100'
        convert.transparent 'white'
        convert.flatten
        convert.alpha 'off'
      end
      img = yield(img) if block_given?
      img
    end
  end

end
`

**Comment by AleksandrLeontev** [comment]
![image](https://user-images.githubusercontent.com/1915670/65394694-bfda4b80-dd99-11e9-8305-ff397283efb6.png)
![image](https://user-images.githubusercontent.com/1915670/65394702-cf599480-dd99-11e9-9598-a0c87b661067.png)
![image](https://user-images.githubusercontent.com/1915670/65394704-dbdded00-dd99-11e9-9757-d595b099fada.png)

**Comment by mshibuya** [comment]
Sorry for getting back late.

> but right after first upload uploader start return tmp file with 2.0.1 version

How and when do you obtain the attachment url? Could you provide a code snippet?

**Comment by mshibuya** [comment]
I suppose this is because of #2209, which defers the timing of storing attachments to after_commit phase.
Version 3.0 comes with #2546 that restores the timing to after_save. Or if you need to stay on 2.x, you need to hook into after_commit to obtain a stored URL, not cached one.
