### ISSUE TITLE
remote_url for facebook not pulling the image

### ISSUE THREAD

**Issue by drkpkg** [carrierwaveuploader/carrierwave#2423]
I'm working with carrierwave and omniauth, and i'm using remote_[object]_url to pull the provider.info.image data from that. Everything normal with google image profile. But for facebook image is not pulling. I try with Down library and set the avatar = down_file and is not working.

Using down not working
```
require "down"

file_fb = Down.download(provider.info.image)
data = {user: user,
            first_name: provider.info.name,
            avatar: file_fb}
```

Using remote_avatar_url either
```
data = {user: user,
              first_name: provider.info.first_name,
              first_last_name: provider.info.last_name,
              remote_avatar_url: provider.info.image}
```

remote_avatar_url is pulling the image, but not saving according the debug 
![Screenshot_20190914_112436](https://user-images.githubusercontent.com/972555/64910259-49c34e00-d6e2-11e9-900f-2c15e4a5258c.png)

It seems carrierwave is not getting the file format, because I don't have another theory.

**Comment by courtsimas** [comment]
Same goes for vimeo og images. the file format isn't evident and it's just not working properly.

**Comment by mshibuya** [comment]
Dup of #2411 and using 2.0.2 will solve this.

**Comment by courtsimas** [comment]
2.0.2 did not fix this @mshibuya just fyi. Still have the issues on 2.0.2.
