### ISSUE TITLE
Bug with content type detection

### ISSUE THREAD

**Issue by n-rodriguez** [carrierwaveuploader/carrierwave#2424]
Hi there!

I think it should be nil here : https://github.com/carrierwaveuploader/carrierwave/blob/d12a289d9cdd68d26d3900cf7f1e4e879678d16b/lib/carrierwave/sanitized_file.rb#L334
(like in the rescue block) to let `mini_mime_content_type` have a chance to find the right mime type.

**Comment by mshibuya** [comment]
This is intentional, see #1942.

**Comment by n-rodriguez** [comment]
> This is intentional, see #1942.

I understand, but for some reason it breaks CSV files detection.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by inkstak** [comment]
I have the same problem with CSV and plain text files.

**Comment by inkstak** [comment]
Example :

```
> CSV.open('foo.csv', 'w') { |f| f << %w[a b] }
> File.open('foo.csv') { |file| MimeMagic.by_magic(file) }
 => nil
```

The original plot about using MimeMagic was to mitigate a CVE on images files, right ?
Can we return the "invalid/invalid" only in such cases ?

```ruby
type = File.open(path) do |file|
  MimeMagic.by_magic(file)&.type
end

if type.match?('image/') && type != MimeMagic.by_path(path)&.type
  type = 'invalid/invalid' 
end

type
```

**Comment by tiagoovieira** [comment]
Has anyone worked on a workaround on this? 

I used Mini Mime to fetch the content_type as set it manually.

**Comment by inkstak** [comment]
```rubyclass DocumentUploader < CarrierWave::Uploader::Base

def content_type
    type = super

    # FIXME: https://github.com/carrierwaveuploader/carrierwave/pull/2474
    if type == 'invalid/invalid'
      type = ::MiniMime.lookup_by_filename(path).try(:content_type)
      type = 'invalid/invalid' unless type.nil? || type.start_with?('text/')
    end

    # Carrierwave always returns a string, even when content type is missing
    type.to_s
  end
