### ISSUE TITLE
Deprecations warnings

### ISSUE THREAD

**Issue by majksner** [carrierwaveuploader/carrierwave#2425]
When Rails (5.2.3) is started, logs showing deprecations warnings.

[fog][DEPRECATION] Fog::Storage::AWS is deprecated, please use Fog::AWS::Storage.
[fog][WARNING] Unrecognized arguments: aws_access_key_id, aws_secret_access_key, region, host, endpoint, path_style

**Comment by MH4GF** [comment]
me too(Rails 6.0.3.4)

**Comment by mshibuya** [comment]
Upgrading `fog-core` gem will solve this.
