### ISSUE TITLE
Migration from 1.3.1 to 2.0.1 breaks public permissions with Google Cloud Storage

### ISSUE THREAD

**Issue by nerf-qh** [carrierwaveuploader/carrierwave#2426]
After migration from 1.3.1 to 2.0.1 public permissions per object get 
`ruby 2.6.4`
`carrierwave 2.0.1`
`fog-core 2.1.0`
`fog-google 1.9.1`

example
https://github.com/nerf-qh/carrierwave_update

Config
```
creds = {
  provider: 'Google',
  google_project: ENV['GCS_PROJECT'],
  google_json_key_string: ENV['GCS_AUTH']
}

CarrierWave.configure do |config|
  config.fog_credentials = creds
  config.fog_directory  = ENV['GCS_BUCKET']
  config.fog_public     = true
  config.storage = :fog
end
```

The initial file is public, but in the `copy_to` method this option is lost
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L444-L446

The same happens if you just copy files
https://gist.github.com/nerf-qh/2606513f42e3be169e52cac4ca72f5ce

**Comment by yosiat** [comment]
Getting the same issue, when upgrading carrierwave.

We noticed the difference is that:
- old carrierwave gave this ACL:
```
  {
    "entity": "allUsers",
    "role": "READER"
  }
```
- new carrierwave don't give this ACL and this is the only reader role it gives (replaced values):
```
  {
    "entity": "XXXXX",
    "projectTeam": {
      "projectNumber": "XXXXX",
      "team": "viewers"
    },
    "role": "READER"
  },
```

This is a major issue when upgrading carrierwave.

**Comment by yosiat** [comment]
Did investigation of the issue and as written here it happens because of `copy_object` (which I think happens because of - https://github.com/carrierwaveuploader/carrierwave/issues/2136)

I opened an issue to ask fog-google on how to pass auth query parameters so we can pass it from carrierwave - https://github.com/fog/fog-google/issues/505
