### ISSUE TITLE
Carrierwave Fog get file extension

### ISSUE THREAD

**Issue by qaswm** [carrierwaveuploader/carrierwave#2430]
I asked this on StackOverflow but with no answer yet. Wondering if someone here could assist.

https://stackoverflow.com/q/58453801/827770

I am using CarrierWave and Fog. Need to access the extension of the file being uploaded to be able to check if it is an image or a video?

How do I go about this? I need to execute fix_exif_rotation if it is an image being updated and extension is in image_file_list.

class MediaUploader < CarrierWave::Uploader::Base

  include CarrierWave::MiniMagick
  storage :fog

```
  def extension_white_list
    %w(srt xml mid midi kar aac f4a f4b m4a mp3 oga.ogg opus ra wav bmp gif jpeg jpg jxr hdp wdp png svg svgz tif tiff wbmp webp jng 3gp 3gpp f4p f4v m4v mp4 mpeg mpg ogv mov webm flv mng asf asx wmv avi)
  end

  def fix_exif_rotation
    manipulate! do |img|
      img.tap(&:auto_orient)
    end
  end

  image_file_list = %w(bmp gif jpeg jpg png tif tiff)

end
```

**Comment by mshibuya** [comment]
Answered in StackOverflow.
