### ISSUE TITLE
The problem with validation in the presence client_max_body_size

### ISSUE THREAD

**Issue by afuno** [carrierwaveuploader/carrierwave#2431]
I needed to specify the maximum available file size. For this inside `*Uploader` I wrote the following:

```ruby
def size_range
  0..30.megabytes
end
```

Locally (on a laptop) everything works successfully. I have an API request that returns an error text if the file size is exceeded. Locally I don't have nginx.

But on the nginx server there is (wow). And in the configuration file contains this line:

```conf
client_max_body_size 30m;
```

It is this line that spoils everything for me.
If the file that I upload (not locally, the application is already on the server) exceeds 30 Mb, then error 413 comes up:

> POST https://mysite.com/api/uploads 413 (Request Entity Too Large)

I can do the following:

```conf
client_max_body_size 0;
```

This will fix the validation on the server. CarrierWave will be responsible for validation. I don't know how good this decision is?

**Comment by mshibuya** [comment]
I recommend prioritizing Nginx configuration, since it will help prevent DoS situation.
