### ISSUE TITLE
Errno::ENOENT after upgrading to rails 6.0.0

### ISSUE THREAD

**Issue by ayza-hamid** [carrierwaveuploader/carrierwave#2432]
After upgrading to rails 6.0.0 I am getting an error **Errno::ENOENT**, while cropping an image I am getting this error on `manipulate!`

```No such file or directory @ rb_sysopen - uploads/tmp/1572333766-199774527733440-0009-5515/1.jpg```

This is the method.

```
  def reprocess(crop_options)
    manipulate! do |img|
      w = crop_options[:crop_w].to_i
      h = crop_options[:crop_h].to_i
      x = crop_options[:crop_x].to_i
      y = crop_options[:crop_y].to_i
      img.crop "#{w}x#{h}+#{x}+#{y}"
    end
    recreate_versions!
  end
```

Anyone faced a similar or issue or have any idea why am I getting this error?

**Comment by courtsimas** [comment]
bump

**Comment by coding-bunny** [comment]
We run into the same problem when trying to upload files with `seeds.rb` and `Rack::Test::UploadedFile`.

See: https://github.com/sorentwo/carrierwave-aws/issues/156 for additional code details.

**Comment by courtsimas** [comment]
This may not help anyone but I ended up just using carrierwave to upload and imgix to handle processing :)

**Comment by coding-bunny** [comment]
I've gotten around the problem by setting the following in our initializer:

```
  config.cache_storage = :file # https://github.com/carrierwaveuploader/carrierwave/issues/2413
```

maybe it will help
