### ISSUE TITLE
Mimetype detection: docx files are being saved as zips

### ISSUE THREAD

**Issue by anthonypenner** [carrierwaveuploader/carrierwave#2433]
After upgrading to 2.0.0 uploaded files are now being saved with the wrong file extensions. 

Related: https://github.com/minad/mimemagic/issues/80

Edit: 
https://github.com/minad/mimemagic#extra-magic-overlay
Note the extra require needed to support MS office files.

**Comment by mshibuya** [comment]
Fixed by #2447.
