### ISSUE TITLE
Can't set protocol for url requested from google cloud storage

### ISSUE THREAD

**Issue by alexborovkov** [carrierwaveuploader/carrierwave#2443]
I am using google cloud storage for image upload, but all requested urls come with http protocol. Is it possible to set https in config?

**Comment by mshibuya** [comment]
Use fog-google with the JSON API.
https://github.com/carrierwaveuploader/carrierwave#using-google-cloud-storage
The XML API seems somehow locked to HTTP.
https://github.com/fog/fog-google/blob/7d0c4f358daeb64e970fcc32af53cde22ffff485/lib/fog/storage/google_xml/models/file.rb#L121
