### ISSUE TITLE
Assign a version to default_url image in carrierwave

### ISSUE THREAD

**Issue by sidhunavroop** [carrierwaveuploader/carrierwave#2445]
I am trying to add a version to the default_url image. I was trying something like this but it is not working due to which default_url image is smaller than other uploaded images. Any Idea where am I going wrong. The images which are uploaded, the URL for them appears like this 

    `<img src="https://xyz.s3.amazonaws.com/uploads/user/image/19/thumb_image_demo.jpg" class="main">`
    
but for the default_url image, it appears like this 

    `<img src="/fallback/avatar.png" class="main">`

version is not attached to the image name. Maybe that's the issue. This is how I have defined it in the uploader. Please suggest what can I do to make it work.
  

 
    `def default_url
        "/fallback/images/" + [thumb_image, "avatar.png"].compact.join('_')
      end`
    
     `version :thumb_image do
        process resize_to_fill: [365, 421]
      end`

**Comment by mshibuya** [comment]
Follow the instruction in README.
https://github.com/carrierwaveuploader/carrierwave#providing-a-default-url
