### ISSUE TITLE
Uploader#convert does not rename the filename

### ISSUE THREAD

**Issue by Kukunin** [carrierwaveuploader/carrierwave#2454]
Let's assume I have a simple uploader:

```
class MyUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  process convert: 'jpg'
end
```

and a simple test:

```
  it 'converts BMP to JPG' do
    uploader.store!(File.open('spec/fixtures/images/example.bmp'))
    expect(uploader.url).to end_with('example.bmp.jpg')
  end
```

so it fails with `expected "/uploads/post/file/5/example.bmp" to end with "example.bmp.jpg"`

So, the filename is still `example.bmp` but there is actually a jpeg image. I believe it's expected that it should be either `example.jpg` or `example.bmp.jpg` to indicate that format was changed. 

I spent 2 hours to find a workaround for that:

```
  process :correct_extname

  def correct_extname
    return if File.extname(@filename) == File.extname(file.file)

    @filename += '.jpg'
  end
```

**Comment by courtsimas** [comment]
I dont think this bug is present anymore and therefore this workaround probably isn't needed.
