### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by afuno** [carrierwaveuploader/carrierwave#2459]
I periodically (can say randomly) get this error:

```
end of file reached (EOFError)
```

This error refers to this line in the code:

```ruby
file.content_type.start_with?('image')
```

This line is in this method:

```ruby
def image?(file)
  file.content_type.start_with?('image')
end
```

And the method itself is used in this way:

```ruby
version :sm, if: :image? do
  process resize_to_fit: [256, nil]
end
```

This code was taken from [here](https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-do-conditional-processing).

It is logical that this method is used to separate other files and images. I have a `MediaFileUploader`. It is used to upload both images and other files (mp3, mp4, pdf, etc.). And periodically, when I try to get the file, when I want to display the image on the page, I get the error that I showed above.

If I use, for example, `VideoUploader`, then this problem is not with it. There is no problem with it because there is no `if: :image?` inside it.

Tell me, please, how to fix this problem?

**Comment by mshibuya** [comment]
Full stack trace please.

**Comment by mshibuya** [comment]
Stale, please let me know on update.
