### ISSUE TITLE
Change AWS S3 Storage Class

### ISSUE THREAD

**Issue by namila** [carrierwaveuploader/carrierwave#2463]
Is there any way to define the s3 storage class in which the file should be stored (STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING )? By default all files are stored in 'Standard' storage class

**Comment by mshibuya** [comment]
Setting `storage_class` in `fog_attributes` will do the job.

```ruby
class AvatarUploader < CarrierWave::Uploader::Base
  storage :fog
  fog_attributes({storage_class: 'STANDARD_IA'})
  ...
end
