### ISSUE TITLE
rename folder before saving file

### ISSUE THREAD

**Issue by almeidaz** [carrierwaveuploader/carrierwave#2467]
I've made a mistake in the name of the folder where i want to save files.
now people have upload files.

i want to rename the folder the next time they want to save a file.
i think i can do that in the store_dir def

def store_dir
      ...
         File.rename("./old", "./new")
    ...
  "new/"
  end

old and new are some variables

final path should be : https://mywebsite.com/test/new
instead of                : https://mywebsite.com/test/old

Unfortunately this don't works. ( no such file or directory)
Do you have any idea to do that?

How can i use File.rename here

current settings is :
config.ftp_folder = "/www/test"
config.ftp_url = "https://mywebsite.com/test"

**Comment by mshibuya** [comment]
Just rename the folder from your FTP console.
