### ISSUE TITLE
Possible to upload several formats of some image?

### ISSUE THREAD

**Issue by srikanthreddy919** [carrierwaveuploader/carrierwave#2469]
I have an issue while creation multiple versions with .png and .jpg formats for the same upload but i am unable to get .jpg version of image. I am uploading .png image but in the versions i can see only .png version. Anybody pls help on this, many thanks.

my code here

```
version :medium, :if => :image? do
    def store_dir
      "uploads/#{model.id}"
    end
     process resize_to_fit: [ 200, 200 ]
     process convert: :png
  end

version :large, :if => :image? do
    def store_dir
      "uploads/#{model.id}"
    end
    process resize_to_fit: [ 500, 500 ]
    process convert: :jpg
  end
```

**Comment by mshibuya** [comment]
Dup of #2125.
