### ISSUE TITLE
Carrierwave w/ IAMRole

### ISSUE THREAD

**Issue by mavinalim** [carrierwaveuploader/carrierwave#2470]
Hello I'm having issue with CarrierWave is failing to identity the correct credential for AWS S3. I can confirm that aws cred is working with aws-sdk or fog/fog-aws gem.  It seems CarrierWave is not respecting use_iam_profile. Have any face this issue or can help with the configuration? Maybe i'm doing something wrong / missing something. Thanks
```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider: 'AWS', # required
    use_iam_profile: true,
    region: 'us-east-1' # optional, defaults to 'us-east-1' 
  }
  config.fog_directory  = Rails.application.secrets.aws[:AWS_BUCKET] # required
  config.fog_public     = false                                                 # optional, defaults to true
end
```

**Comment by dvjoness** [comment]
@mavinalim I had the same issue. What does an error you have?

**Comment by mshibuya** [comment]
@mavinalim @dvjoness Are you able to provide detail of the error?

**Comment by mshibuya** [comment]
Stale, please let me know on update.
