### ISSUE TITLE
issue with jbuilder and caching

### ISSUE THREAD

**Issue by seboslaw** [carrierwaveuploader/carrierwave#2471]
Hey guys,

I'm having an issue when using carrierwave in combination with jbuilder and caching (Rails default file caching).

I'm using jbuilder.cache! to cache the JSON I want to render out via an API. 

```
json.cache! [@event] do
...
```

When I still ran Rails 5.2.3 everything worked fine, but since I've upgraded to Rails 5.2.4.2 I get the following error in production when restarting the server at the end of a deployment and loading the JSON the first time:

```
An ActionView::Template::Error occurred in events#show_v2:

 uninitialized constant MediaItemUploader::Uploader47081233157840
Did you mean?  MediaItemUploader::Uploader47362494653720
 app/views/events/events/show_v2.json.jbuilder:2:in _app_views_events_events_show_v__json_jbuilder___1680057252446656557_47362491425440
```

I've dug into the issue and it seems that the object I'm caching has an associated uploader (MediaItemUploader) which makes problems when being serialised (and then de-serialized) to a file during caching. Is that the issue here? Is there a way to solve this except wiping the cache on each deployment? 
Is there any reason this worked with 5.2.3?

Cheers,

Sebastian

**Comment by nachiket87** [comment]
@seboslaw did you find a fix for this?
