### ISSUE TITLE
<ActiveRecord::RecordInvalid: Validation failed: File could not download file: 403 Forbidden>

### ISSUE THREAD

**Issue by naveen-kinnal** [carrierwaveuploader/carrierwave#2475]
My model has the line 
`mount_base64_uploader :file, SpeakerFileUploader, file_name: ->(_) { Time.now.to_i }`

And my uploader looks like
class ApplicationUploader < CarrierWave::Uploader::Base
```
  include CarrierWave::MiniMagick
  #include ::CarrierWave::Backgrounder::Delay

  process :strip, if: :not_svg?

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  private

  # Strips out all embedded information from the image
  def strip
    manipulate! do |img|
      img.strip
      img = yield(img) if block_given?
      img
    end
  end

  def not_svg?(_)
    original_filename.exclude?('.svg')
  end
end
```

I am getting a 403 error and I would handle in this way
1. Validate the URL before save
2. Replace with a default URL in case I get this error. 

How can I process here? In which file should I make the changes?

**Comment by mshibuya** [comment]
That'll be what should be handled by your application logic and not related to CarrierWave.
