### ISSUE TITLE
Carrierwave created 2 million empty folders in 7 days: recreate_versions! with arguments leaves empty folders behind forever

### ISSUE THREAD

**Issue by feliperaul** [carrierwaveuploader/carrierwave#2485]
Bug confirmed both on 1.3.1 and on 2.1.0. 

For 2 weeks in a row, we noticed the creation of more than **2 million** empty folders in our Rails app `/tmp` folder.

The folders have a name like `1590758651-267997218347580-0063-0480` and they were all created by Carrierwave. 

This is not just some nuisance, since every time we invoke a simple `ls` to list the folder's content it freezes the terminal for 5+ minutes. 

![image](https://user-images.githubusercontent.com/743879/83265051-59fb5a80-a197-11ea-912a-3edb33607aa4.png)

After around 1 hour of debugging (and lucky intuition), we found out what's causing this.

If we upload files, we can watch in localhost (mac os x finder) these folders being created and deleted a few seconds later, as expected (Carrierwave cleans up after itself). 

If we invoke `.recreate_versions!` on any uploaded file, it also creates these temp folders but Carrierwave also cleans up after itself and deletes them.

**However**, if we invoke `.recreate_versions!(:any, :specific, :versions)` then the bug occurs. The empty folders are not deleted, and they will remain forever in your `/tmp` folder.

By the way, this folder `/tmp` has nothing to do with the `def cache_dir` defined in the model, since we do define it to be a different folder than `/tmp`. This `/tmp` comes from `CarrierWave.tmp_path` and it's the gem's default.

**Comment by feliperaul** [comment]
By the way, the fastest way to delete these folders is by using Ubuntu directly:
`find . -empty -type d -delete`

It still takes 10+ minutes on our server every time, but it's much quicker than using a ruby script for doing so.

**Comment by feliperaul** [comment]
Another tip: if you use the Whenever gem, you can add this duck tape while this still isn't fixed. Using `-mmin +1` below assures that only empty folders that were created after one minute ago are going to be deleted. This has been tested in production.

```
every 5.minutes do
  # Cleans up empty folders 
  #  https://github.com/carrierwaveuploader/carrierwave/issues/2485
  command "cd /path/to/your/rails/root/tmp && find . -empty -type d -mmin +1 -delete"  
end
```

**Comment by mshibuya** [comment]
I could not reproduce this behavior, #recreate_versions! deletes cache directories both with or without arguments.
Could you provide full source code of your uploader?

**Comment by mshibuya** [comment]
Stale.
