### ISSUE TITLE
If you create a different version of the uploaded file, the assignment of params[:file] will fail.

### ISSUE THREAD

**Issue by Sakaki-Ya** [carrierwaveuploader/carrierwave#2486]
Hello.  
I have a question.

```ruby
version :thumb do
    process resize_to_fit: [200, 200]
end
```
If you set the ```version``` in uploader.rb, ```user.avatar = params[:file]``` will fail.
The error message is as follows.
```
#<ArgumentError: wrong number of arguments (given 4, expected 2)>
```
Is there a way to resolve this error?  
What am I misunderstanding?

# Details

I am implementing an action to update the user's avatar.

```ruby
u = User.new
u.avatar = params[:file] # Assign a file like this, or
```

According to the above READEME code, I have set up the avatar update behavior as follows.

```ruby
class UsersController < ApplicationController
  def update
    user = User.find(params[:id])
    user.avatar = params[:file]
    render json: user
  end
  ...
end
```

uploader.rb is as follows.
```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def default_url(*args)
    "/images/fallback/" + [version_name, "default.jpg"].compact.join('_')
  end

  version :thumb do
    process resize_to_fit: [200, 200]
  end
  ...
end
```

# Render JSON

- **Case of not creating a different version.**

```json
{
    "id": 1,
    "name": "foo",
    "avatar": {
        "url": "/uploads/tmp/0000-000-000-000/foo.jpg"
    },
}
```
The URL has changed to the path of the uploaded file.

- **Case to render JSON without assigning params[:filse] to avatar.**

```json
{
    "id": 1,
    "name": "foo",
    "avatar": {
        "url": "/images/fallback/default.jpg",
        "thumb": {
            "url": "/images/fallback/thumb_default.jpg"
        }
    },
}
```

**Comment by danielricecodes** [comment]
I'm pretty concerned no one is replying to these issues. Is this gem abandonware now?

**Comment by mshibuya** [comment]
Please provide the full uploader code. I don't see anything weird to the problem can be in somewhere you've omitted.

**Comment by mshibuya** [comment]
Stale, please let me know on update.
