### ISSUE TITLE
Consider renaming "blacklist/whitelist" methods to something else

### ISSUE THREAD

**Issue by rhymes** [carrierwaveuploader/carrierwave#2491]
Following the example of https://github.com/rails/rails/issues/33677 and https://github.com/thepracticaldev/dev.to/issues/7147 I'm proposing to take into consideration the replacement of words like `whitelist`/`blacklist` from carrierwave's source code.

Possible alternatives: `allow/deny`, `valid/invalid`, `permitted/blocked`

According to a quick search - https://github.com/carrierwaveuploader/carrierwave/search?q=blacklist+OR+whitelist&unscoped_q=blacklist+OR+whitelist - there are a few instances of this.

A possible solution would be to add alternative methods and deprecation notices and then remove them a couple of releases down the line or something like that.

I can work on the initial PR if agreed.

Thank you!

**Comment by mshibuya** [comment]
Fixed by #2442.
