### ISSUE TITLE
NoMethodError (undefined method `reject' for #<String:0x00007fe06337a398>):

### ISSUE THREAD

**Issue by painforever** [carrierwaveuploader/carrierwave#2497]
I'm trying to upload multiple files and I set:
`configure do |config|
      config.remove_previously_stored_files_after_update = false
    end`
in my uploader. 

I want to keep previouly uploaded files, here is my uploader and controller:
`module PatientLabs
  class PatientLabFileUploader < CarrierWave::Uploader::Base
    configure do |config|
      config.remove_previously_stored_files_after_update = false
    end

    storage :fog

    def store_dir
      "uploads/#{model.class.to_s.underscore}/#{Rails.env}/#{mounted_as}/#{model.patient.id}"
    end

  end
end`

`def update
        if params[:file_path].present?
          if params[:file_path].is_a?(Array)
            append_images(params[:file_path])
          else
            @patient_lab.file_path = params[:file_path]
          end
        end
        if @patient_lab.update(lab_params)
          render json: @patient_lab, status: :ok
        else
          render json: @patient_lab.errors.full_messages, status: 500
        end
      end

def append_images(new_images)
        current_images = @patient_lab.file_path
        current_images += new_images
        @patient_lab.file_path = current_images
      end
`

bascially I want to append files to an existing record when I update it. But everytime I upload multiple files or even 1 file it always give me:
NoMethodError (undefined method `reject' for #<String:0x00007fe052f55fe8>):
  
carrierwave (2.1.0) lib/carrierwave/mounter.rb:138:in `remove_previous'
carrierwave (2.1.0) lib/carrierwave/mount.rb:355:in `remove_previously_stored_file_path'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:261:in `block in conditional'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:517:in `each'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:133:in `run_callbacks'
activesupport (5.2.4.3) lib/active_support/callbacks.rb:816:in `_run_commit_callbacks'
activerecord (5.2.4.3) lib/active_record/transactions.rb:347:in `committed!'

**Comment by younthu** [comment]
please check if you have something like below in your model:

~~~
mount_uploaders :photos, PhotoUploader
serialize :photos, JSON # this line matters, carrierwave will use it as json instead of string in multiple files upload.
~~~
