### ISSUE TITLE
ActiveRecord::RecordInvalid (Validation failed: [Uploader] could not download file: 500 Internal Server Error)

### ISSUE THREAD

**Issue by IvanDreamer** [carrierwaveuploader/carrierwave#2505]
Hi, 
I have quite weird error with following link when I try to use remote_[uploader]_url. I cannot even "rescue" from it. 

https://ewscripps.brightspotcdn.com/dims4/default/5882ab6/2147483647/strip/true/crop/4032x2117+0+0/resize/1200x630!/quality/90/?url=http%3A%2F%2Fewscripps-brightspot.s3.amazonaws.com%2Ff9%2F01%2F5e8c04524d06a55b12e2531f6ca3%2Fimage0-3.jpeg

It gives 
`ActiveRecord::RecordInvalid (Validation failed: Photo could not download file: 500 Internal Server Error)`

Does somebody have any idea what could be the reason in such behaviour?

**Comment by hajime-goshima** [comment]
Maybe the same issues https://github.com/carrierwaveuploader/carrierwave/issues/2517
