### ISSUE TITLE
Renaming image files

### ISSUE THREAD

**Issue by webcoderman** [carrierwaveuploader/carrierwave#2515]
Hello.
I have ActiveRecord model with 
**mount_uploaders :pictures, PictureUploader**

How to rename uploaded files according to some rule? 
As example: I uploaded 3 images for one AR model
I want to get filenames like  "#{model.id}_1.jpg", "#{model.id}_2.jpg", "#{model.id}_3.jpg"
If I will use method **def filename**...
How to get the uploaded file number from uploaded array?
Thank you

**Comment by mshibuya** [comment]
`#index` will be what you're looking for.
https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/uploader/mountable.rb#L39-L41
