### ISSUE TITLE
AWS Performance Issue

### ISSUE THREAD

**Issue by felipefava** [carrierwaveuploader/carrierwave#2529]
Hi, I'm generating a json that is a list of products. Each product has an image. The problem I'm facing is that is taking too long. 

I did some debug and the problem is on the image URL  generation for the json response. I'm using fog-aws with private bucket. Is there a way of speeding up this?

```
carrierwave (2.1.0)
fog-aws (3.5.2)
```

Thanks for the help!

**Comment by alessandromacagno** [comment]
Any updates on this? I have the very same problem, but with carrierwave 2.1.1 and carrierwave-aws 1.5.0

I have a Exercise model with some videos and pictures attached, and this is a benchmark of `Exercises.all.to_json` with carrierwave URLs

> #<Benchmark::Tms:0x00007f904b14e438 cstime=0.0, cutime=0.0, label=“”, real=7.911554000000251, stime=0.07655499999999998, total=7.905657999999999, utime=7.829102999999999>


If I remove carrierwave URLs this is the benchmark

> #<Benchmark::Tms:0x00007fe7e4a1f030 cstime=0.0, cutime=0.0, label=“”, real=0.546690000000126, stime=0.030209000000000014, total=0.545716, utime=0.5155069999999999>

**Comment by mshibuya** [comment]
Merging into #2461.
