### ISSUE TITLE
Dynamic Asset Host - Incorrect Documentation?

### ISSUE THREAD

**Issue by williamhakim10** [carrierwaveuploader/carrierwave#2530]
Hey there,

We're using Carrierwave with a dynamic asset host, using different CDNs based on whether the file is an image or otherwise. Our Uploader objects are defined using `fog`, e.g.:

```
class User < ApplicationRecord
  ...
  mount_uploader :picture, AvatarUploader
  ...
 end
 
...

class AvatarUploader < CarrierWave::Uploader::Base
  storage :fog
  ...
end
```

We've found that in our configuration, the dynamic asset host section of the docs (https://github.com/carrierwaveuploader/carrierwave#dynamic-asset-host) isn't correct - it says that the Proc will receive an instance of `CarrierWave::Storage::Fog::File`, but in fact the Proc receives an instance of `AvatarUploader`. This was very confusing to us because every instance of `AvatarUploader` has a `file` method which returns a `CarrierWave::Storage::Fog::File` (but can also hit S3, which can cause performance issues here!).

If we're correct that Carrierwave provides an instance of `CarrierWave::Uploader::Base` when setting the asset host  dynamically in certain circumstance (e.g., when using fog), perhaps it's worth updating the documentation? Seems like a common use case and I'm sure it could help other developers in future!

Cheers,

Will

**Comment by mshibuya** [comment]
I couldn't find any asset_host usage with a uploader instance.
In CarrierWave's codebase there's 2 locations which calls asset_host, and both passes a `CarrierWave::SanitizedFile` or `CarrierWave::Storage::Fog::File` as an argument.
https://github.com/carrierwaveuploader/carrierwave/blob/3d1259f531c5e672de5e5abad7be45ee051b2e34/lib/carrierwave/uploader/url.rb#L28
https://github.com/carrierwaveuploader/carrierwave/blob/f90e14ca91892d677ee6ed42321a21a2fe98f360/lib/carrierwave/storage/fog.rb#L368
Could you provide a stacktrace when asset_host is called with an uploader instance?

**Comment by mshibuya** [comment]
Stale.
