### ISSUE TITLE
2.1.0 -> 2.1.1 upgrade issue

### ISSUE THREAD

**Issue by streetlogics** [carrierwaveuploader/carrierwave#2531]
I just got a dependabot security update alert for 2.1.0 to 2.1.1 - which indicated a minor version upgrade.  However, all of my tests where carrierwave is underneath are now failing saying I haven't stubbed things properly.  Doing some digging, I'm noticing some weirdness / inconsistencies in the output. 

Hypothesis: Something in the update broke the use of `asset_host`.

Example error output:
```
Real HTTP connections are disabled. Unregistered request: GET https://*REDACTED_LOCAL_IPV6_ADDRESS*/uploads/account/avatar/[ID]/img.jpg with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'*OUR_CLOUDFRONT_DISTRO_SUBDOMAIN*.cloudfront.net', 'User-Agent'=>'CarrierWave/2.1.1'}

      You can stub this request with the following snippet:

      stub_request(:get, "https://*REDACTED_LOCAL_IPV6_ADDRESS*/uploads/account/avatar/[ID]/img.jpg").
        with(
          headers: {
          'Accept'=>'*/*',
          'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
          'Host'=>'*OUR_CLOUDFRONT_DISTRO_SUBDOMAIN*.cloudfront.net',
          'User-Agent'=>'CarrierWave/2.1.1'
          }).
        to_return(status: 200, body: "", headers: {})
```

Specifically, the fact that it's telling me I need to stub a request to my IPv6 address, but the `with()` is actually passing the correct `Host` value of our cloudfront distro feels like something is amiss here, and since the only thing that's changed in this branch is upgrading from 2.1.0 to 2.1.1, I'm hoping you all might be able to provide some guidance.  

For reference, this is what my "working" stub looks like:

```
  stub_request(:get, /*OUR_CLOUDFRONT_DISTRO_SUBDOMAIN*.cloudfront.net/).
    to_return(status: 200, body: "ok1", headers: {})
```

**Comment by pnikrat** [comment]
Hi, just wanted to say I'm having a similar problem. In test env previously recorded VCR cassettes are now failing - we use hostname matching to inject proper cassette. Now instead of hostname in request there is just a bare IP address there. Started happening right after 1.3.1 -> 1.3.2 bump so there must be something wrong in that commit: https://github.com/carrierwaveuploader/carrierwave/commit/91714adda998bc9e8decf5b1f5d260d808761304

**Comment by christhesoul** [comment]
@pnikrat I'm currently investigating the exact same thing: all our VCR cassettes don't know how to handle the bare IP address that's being requested after bumping from 2.1.0 to 2.1.1.

**Comment by lloydwatkin** [comment]
You can simply tell carrierwave to skip SSRF protection for tests as follows:

```ruby
  before(:each) do
    allow_any_instance_of(CarrierWave::Downloader::Base).to receive(:skip_ssrf_protection?).
      and_return(true)
  end

**Comment by christhesoul** [comment]
For interest / reference for other readers, when Carrierwave does NOT skip SSRF protection, the URI is requested using the `ssrf_filter` [gem](https://github.com/arkadiyt/ssrf_filter).

It does this: `SsrfFilter.get(uri, headers: headers)` [here](https://github.com/carrierwaveuploader/carrierwave/blob/003e2ceeaa856f2605cf8096b401e76168ffc8ba/lib/carrierwave/downloader/base.rb#L32)

That `get` method uses a _default resolver_ that you can see [here](https://github.com/arkadiyt/ssrf_filter/blob/f7cbd4342691a4e599a9aa302adb8b7288b0f185/lib/ssrf_filter/ssrf_filter.rb#L69-L71) and it does this:

```ruby
::Resolv.getaddresses(hostname).map { |ip| ::IPAddr.new(ip) }
```

which is why the VCR cassettes are getting confused because they're not expecting a request to this filtered URI that's using IP addresses instead of hostnames.

**Comment by mshibuya** [comment]
Yeah this was required to make CarrierWave safer.
It basically does not affect existing production behavior anyway, please your tests accordingly.

**Comment by streetlogics** [comment]
So to summarize:

- a "minor" version upgrade was released to address a security vulnerability, which upon rollout, was discovered to have broken test suites, preventing people from rolling out said update.
- after waiting days to reply, the official response is that we're supposed to stub out the "fix" posted to address the vulnerability, because it "Just Works" in production

Am I missing a section in the changelog or readme that outlines this is "expected behavior", or do I rely on the code provided above as the "official" recommended solution?

**Comment by takamario** [comment]
We encountered some issue after bump to 2.1.1. 

We tried on 2.1.1 with Rails, setting `remote_x_url`.
Model's `remote_x_url` value is okay before saving, but when saving (downloading), sometimes DNS lookup fails and going to access to invalid IPv6 address.

**Comment by izenk** [comment]
Faced this issue too.

The most important question is what to do with qa envs, which are in clouds like AWS, GCP, Azure or just inside docker
Production env has public ips for all public components - it's ok. But again, there were no any info, that gem is suitable for downloading files only from public ips and now it is so.

But qa envs off course do not have public ips at all. All dns names are resolved to private ips - its normal scheme.

I think, gem ssrf_filter which is used to filter requests is not right solution. It just blocks any request to so called private networks without possibility to edit or configure ip black_list

**Comment by dfuentes77** [comment]
We noticed this as well going from 1.3.1 to 1.3.2.  Would have been great if the Changelog included notes about this.

**Comment by Loschcode** [comment]
On my end with 1.3.2, it worked by adding this into RSpec

```
allow_any_instance_of(CarrierWave::Uploader::Download).to receive(:skip_ssrf_protection?).and_return(true)
```

The class was slightly different since the other one was considered undefined with our version of CarrierWave.

**Comment by mateusdeap** [comment]
I know this is closed, but I ran into a similar issue where I was just using dummy urls and it would fail because it tried to resolve `example.site`. Maybe there should be some config that differentiates testing from production?
