### ISSUE TITLE
Transfer carrierwave-aws to carrierwaveuploader organization

### ISSUE THREAD

**Issue by sorentwo** [carrierwaveuploader/carrierwave#2534]
I've maintained carrierwave-aws for many years now, though I haven't actually used it for several years. Despite a low maintenance burden I'd like to transfer ownership over to the carrierwaveuploader team so that you all can give the library the attention and support it deserves.

If this is desirable, please get in touch and we'll organize a transition. Thanks!

**Comment by mshibuya** [comment]
Sounds really great, since carrierwave-aws is feature-rich and looks stable for a long time!

How can we arrange the transition? Just waiting for your GitHub repo transition is enough?
After the transition I will create a new team for carrierwave-aws in carrierwaveuploader org so you can continue the maintenance.

**Comment by sorentwo** [comment]
> How can we arrange the transition? Just waiting for your GitHub repo transition is enough?

According to the [Transferring a Repository](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository) docs I need to be added as a collaborator in order to initiate the transfer. Afterwards I can add new owners to rubygems.

> After the transition I will create a new team for carrierwave-aws in carrierwaveuploader org so you can continue the maintenance.

Part of initiating this is that I'd like to hand off maintenance to the carrierwaveuploader team. Most of the questions that come in are actually related to carrierwave and not the aws side at all, so I think users would be better served. I'll stay on for a while after the transition to make sure things are smooth.

**Comment by mshibuya** [comment]
Now I understand your intention.
I've sent an invitation to the carrierwaveuploader organization, after accepting that you should be able to do the transfer.

**Comment by sorentwo** [comment]
Thanks @mshibuya, transfer complete!

**Comment by mshibuya** [comment]
The repo transfer seems to be complete, waiting for the gem ownership transition.
https://github.com/carrierwaveuploader/carrierwave-aws

**Comment by sorentwo** [comment]
Ownership granted to @mshibuya (`gem owner carrierwave-aws -a mshibuya`). It says it sent an email along:

> mshibuya was added as an unconfirmed owner. Ownership access will be enabled after the user clicks on the confirmation mail sent to their email.

Should be set! 🤞

**Comment by mshibuya** [comment]
OK I could confirm it, thanks! 👍
