### ISSUE TITLE
Need to implement #delete_dir! , but how?

### ISSUE THREAD

**Issue by willc0de4food** [carrierwaveuploader/carrierwave#2535]
Hello! I'm attempting to upgrade carrierwave from v1.2.3 -> 1.3.2. We are using carrierwave with Cloudinary on Heroku. v1.2.3 works great, but just upgrading the gem produces the following error:
```
NotImplementedError - Need to implement #delete_dir! if you want to use Cloudinary::CarrierWave::Storage as a cache storage.:
carrierwave (2.2.0) lib/carrierwave/storage/abstract.rb:35:in `delete_dir!'
carrierwave (2.2.0) lib/carrierwave/uploader/store.rb:69:in `block in store!'
carrierwave (2.2.0) lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
carrierwave (2.2.0) lib/carrierwave/uploader/store.rb:65:in `store!'
carrierwave (2.2.0) lib/carrierwave/mounter.rb:105:in `each'
carrierwave (2.2.0) lib/carrierwave/mounter.rb:105:in `store!'
carrierwave (2.2.0) lib/carrierwave/mount.rb:401:in `store_image!'
```
I've searched through the wiki, docs, Google, SO and cannot find anywhere that illustrates how to implement delete_dir!
Looking at the source code, I can see where it's implemented, but even that doesn't really give a clue as to what I need to implement 😅 so.. what needs to be done to fix this error?

Thanks!

**Comment by mshibuya** [comment]
You can either change your app to use Cloudinary not for a cache storage by doing

```ruby
config.cache_storage = :file
```

in config/initializer/carrierwave.rb, or implement something similar to [this](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L105-L154) into [cloudinary_gem](https://github.com/cloudinary/cloudinary_gem).
