### ISSUE TITLE
Upgrade 2.1 -> 2.2 breaks interaction with webmock by resolving domain names to IP

### ISSUE THREAD

**Issue by greenfork** [carrierwaveuploader/carrierwave#2537]
I use [webmock](https://github.com/bblimke/webmock) to stub requests to external sites.

For example:
```ruby
stub_request(:get, "https://media-exp1.licdn.com/dms/image...")
```
stubs request which is used by carrierwave to retrieve the image.

After upgrade to version 2.2 this no longer works, test fails saying that it caught not stubbed request to
```
https://2.18.34.43/dms/image...
```
which is a resolved IP address for `media-exp1.licdn.com`.

This is a problem because one cannot reliably stub IP address, domain name does not guarantee to always resolve to the same address.

**Comment by mshibuya** [comment]
This is expected, see this for the workaround:
https://github.com/carrierwaveuploader/carrierwave/issues/2531#issuecomment-776623496
