### ISSUE TITLE
remove_#{column}! does not call #remove! on uploaders

### ISSUE THREAD

**Issue by brunosedler** [carrierwaveuploader/carrierwave#2540]
I have an application with a model that uses a mounter like this
`mount_uploader :zip_file, ZipFileUploader`

At some other place I call `model.remove_zip_file!` and expected that this would trigger a call to `delete` on an instance of a `Carrierwave::Storage::Fog::File`

I recently upgraded Carrierwave from 0.11.0 to 2.2.0. Before this upgrade, above mentioned code worked as expected but afterwards it broke. So I dug into the source code and came across [this commit](https://github.com/carrierwaveuploader/carrierwave/commit/7d4713f251399ca6f107e0660616cd7b9494929c).

I've noticed that the call to `super` has been moved to the bottom of the method in `remove_#{column}!`, and this seems to break the code for me. Following `super` we'll eventually get to the method `remove!` in [`lib/carrierwave/mounter.rb`](https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/mounter.rb#L120) which looks like this in version 2.2.0

```
   def remove!
      uploaders.reject(&:blank?).each(&:remove!)
      @uploaders = []
    end
```

However, in `remove_#{column}!` in [`lib/carrierwave/orm/activerecord.rb`](https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/orm/activerecord.rb#L85) there is a call to `write_#{column}_identifier`, which is defined in [`lib/carrierwave/mount.rb`](https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/mount.rb#L173) and looks like this:

```
        def write_#{column}_identifier
          return if frozen?
          mounter = _mounter(:#{column})

          mounter.clear! if mounter.remove?
          write_uploader(mounter.serialization_column, mounter.identifiers.first)
        end
```

mounter.clear! is defined in [`lib/carrierwave/mounter.rb`](https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/mounter.rb#L125) and looks like this 
```
    def clear!
      @uploaders = []
    end
```

To get to my point, it seems to me, that the uploaders are cleared in `write_#{column}_identifier` before they ever get a chance to call `remove!`. 

As above mentioned commit is a couple of years old, I'm not sure if I'm misunderstanding something, because it seems weird to me that a bug like that could survive this long.  

Was there a specific reason why `super` had been moved to the bottom of the method? 
Has some behavior changed since then? (I know, upgrading two major versions like I did is a huge step and behavior changes)

I'd appreciate it, if someone could tell me if my assumptions aren't correct or if this is an actual bug

**Comment by brunosedler** [comment]
Hi, I just wanted to ask if you had a chance to take a look at this yet and give me some feedback.

**Comment by danielricecodes** [comment]
I'm pretty concerned no one is replying to these issues.  Is this gem abandonware now?

**Comment by danielricecodes** [comment]
This is constructive feedback. When a project with Carrierwave's stature has dozens of unanswered issues going back over a year, that's not a good look.
