### ISSUE TITLE
Just wondering what CarrierWave is meaning

### ISSUE THREAD

**Issue by KSH-code** [carrierwaveuploader/carrierwave#2558]
Hi all,
it is just my personal question.
I've known carrier wave meaning is, in network, to modulate.
by the way, I was wondering CarrierWave  gem which has been named why.

how related that?

**Comment by seuros** [comment]
@KSH-code , It a mean to transmit files(data) to your application.

**Comment by KSH-code** [comment]
that makes sense. cool!
thanks for comment.
so close this issue because of solved my question.
