### ISSUE TITLE
URL getting double/improperly encoded when % percent sign is present

### ISSUE THREAD

**Issue by joemsak** [carrierwaveuploader/carrierwave#2561]
Hi there - Rails 6.1 with Carrierwave main github branch (I need the fix mentioned here https://github.com/carrierwaveuploader/carrierwave/issues/2415#issuecomment-783002425)

So we have an uploader with a retina version with code like this:

```ruby
version :retina do
  process resize_to_fill: [1600, 900]
  process :optimize

  def full_filename(for_file)
    super.tap do |file_name|
      file_name.gsub!('.', '@2x.').gsub!('retina_', '')
    end
  end
end
```
And when I call `model.logo.retina.url` I get something like this:

```
https://s3-host.aws-example.com/path/to/file%25402x.jpg?security-params...
```

I can see that `%25` is supposed to be the % sign itself, and it should be forming `%40` for the `@` sign but it's not and therefore AWS bonks out with AccessDenied (which is how they handle 404)

For now my workaround is to use `URI.decode(model.logo.retina.url)` and I'm very lucky I only have this one retina version on one uploader, referenced in one place in my code, but you can imagine this would get out of hand, and I assume there should be (and might be, but I can't find it) a better way to handle this? 

Thanks!

**Comment by joemsak** [comment]
Just wanna add on to say I had this issue come up in another spot in my codebase. It's not really about the retina version obviously, it's about the `%` symbol being present in the URLs

**Comment by joemsak** [comment]
Another update on this. `URI.decode(model.attachment.url)` is not always the right thing to do, either. Sometimes there are `%` that need to be in there as-is, as part of the AWS token. I'm currently not sure what to do about this issue I'm having. Any help or advice is much appreciated

**Comment by joemsak** [comment]
Current workaround to this issue is in my base uploader mixin:

```ruby
module MyBaseUploader
  def url(*)
    super&.gsub('%25', %')
  end
end
```

Since so far what needs to be fixed here is that the % is already involved in encoding some other character, but has itself been encoded, so the URLs which have encoded characters in them are being sort of over-encoded

**Comment by mshibuya** [comment]
Tried with the filename `test@2x.jpg` but couldn't reproduce, just getting `test%402x.jpg`.
What setup are you using and how do you get the url? Can you provide the full uploader code?

**Comment by mshibuya** [comment]
Stale.
