### ISSUE TITLE
Type is set to invalid when a valid type is found

### ISSUE THREAD

**Issue by waferbaby** [carrierwaveuploader/carrierwave#2565]
https://github.com/carrierwaveuploader/carrierwave/blob/1c7bdd2e329a2d24949dc8ac6c177d31e006ac47/lib/carrierwave/sanitized_file.rb#L339

Is this line possibly meant to read like so?
`type = 'invalid/invalid' if type.nil? || !type.start_with?('text/')`

I have a valid type for a file I'm working with on the line before this one, but it's then set to `invalid/invalid` because of the `unless type.nil?` bit.

**Comment by Timboh56** [comment]
I'm having the same issue after creating a tempfile, generating a CSV and writing to it.

**Comment by agnyp** [comment]
I'm also having this issue with pdfs.
