### ISSUE TITLE
Primarly rely on magic to determine mime type

### ISSUE THREAD

**Issue by MarcelEeken** [carrierwaveuploader/carrierwave#2570]
I have been investigating some issue lately about file uploads and mimetype determination and was looking at how CarrierWave implements it, and also how other projects implement it.

I saw in the source code of CarrierWave that it primarly relies on the given `content_type` of the file being attached https://github.com/carrierwaveuploader/carrierwave/blob/d50d80eee95054d4e2567b685c5b82a8128146f7/lib/carrierwave/sanitized_file.rb#L261-L266. 

As most files used by CarrierWave are potentially uploaded this can be an entry point for abuse, as the given `content_type` can be easily spoofed, as also has been mentioned here https://github.com/carrierwaveuploader/carrierwave/pull/1942#issuecomment-218609925.

With the recognition here https://github.com/carrierwaveuploader/carrierwave/issues/2465#issuecomment-782805790 as well that spoofing protection will become more important is it maybe an idea to not rely on the existing content type, and fully rely on the content type given by tools such as `Marcel`?

This is by the way how it is now solved in `ActiveStorage` https://github.com/rails/rails/blob/e848e8861d5c9221b77e039c2f041abced3aa577/activestorage/app/models/active_storage/blob/identifiable.rb#L21-L23

**Comment by aquintino** [comment]
Is there any official patch/solution to this issue? I am thinking of patching sanitized file to ignore the existing content type if file is an instance of ActionDispatch::Http::UploadedFile

**Comment by varentsov** [comment]
any updates on that issue?

**Comment by mshibuya** [comment]
Quite agree, changed in https://github.com/carrierwaveuploader/carrierwave/commit/a2ca59cbe67046ba7818c64849a9a4ffa90306db 👍
