### ISSUE TITLE
How to skip to create cache?

### ISSUE THREAD

**Issue by tashirosota** [carrierwaveuploader/carrierwave#2576]
Our project does not need cache.
And cache incompatibles these code.

```rb
Ruby: 2.6.6
Rails: 6.1.3.1
 # Without cache
ActiveRecord::Base.transaction do
  image_a = Image.create! image: params[:image]
  image_a.image_url # => https://example.com/uploads/images/:hogehoge/image.jpg
  Image.create! remote_image_url: image_a.image_url
  # Succeed 🙆‍♂️
end

 # With cache
ActiveRecord::Base.transaction do
  image_a = Image.create! image: params[:image]
  image_a.image_url # => https://example.com/uploads/images/:hogehoge/image.jpg
  Image.create! remote_image_url: image_a.image_url
  # Failed 🙅‍♂️  not found
  # Because image_url is correctly tmp url like `https://example.com/uploads/tmp/:hogehoge/image.jpg`.
  # But remote_image_url was created from  completed url.
end

```

**Comment by Dylan0203** [comment]
Had the same issue, that I tried to get the `real file path` via using `file.reload.url` inside the transaction

I wrap the process with  `AfterCommitEverywhere` and It goes as I expect without using `reload`

FYI. gem 'after_commit_everywhere'

**Comment by mshibuya** [comment]
Could you be a bit more specific? I don't understand what you're referring to as `with/without cache`...

**Comment by mshibuya** [comment]
Stale.

**Comment by cpgo** [comment]
Hi @mshibuya , sorry to ping you on a stale issue but we are upgrading from 1.x to 2.x and we found a few issues like this one on our code base

It looks like 2.0 moves some cache handling logic to an after_commit hook, and in our case we had some bugs when we upload the file and need to work with the uploaded url inside the a transaction block.
When the transaction finishes, whatever logic we ran using the `model.file.url` will be pointing to the cache url

What I'm doing for now is puting some more logic around the code and moving the model creation outside the transaction. Is there any way around that?

Thanks

**Comment by fragkakis** [comment]
I am having similar issues ☝️

**Comment by Drowze** [comment]
![qq 2023-12-27 08 16 43](https://github.com/carrierwaveuploader/carrierwave/assets/9031589/4875324a-baa9-4752-8a02-a85bffde77d4)

We had a similar issue, apparently related to caching, this week:
We had one user trying to upload an image to our servers, which failed for an unknown reason (error 500 coming from Cloudflare R2). The database record however was persisted just fine.
From inspecting our traces (screenshot attached), we can see:
- initial attempt to upload the image to the cache succeeded (there was one error 5xx, but seems that Carrierwave retried and got around it)
- after uploading the image to the cache, the database record was inserted and committed (but if I were to check `record.attachment.url` at this point, I believe we would get the non-cache url, as there isn't any UPDATE db statement after this)
- after persisting to the database, we attempt a new upload, this time to the "real path" within Cloudflare R2. After 4 failed attempts (5xx errors from Cloudflare), Carrierwave gives up.

(_note: Cloudflare R2 implements Amazon S3 API; we use [carrierwave-aws](https://github.com/carrierwaveuploader/carrierwave-aws/) with it_)

Here's roughly the code that initiated Carrierwave upload:
```ruby
class PictureUploader < BaseUploader
  include CarrierWave::MiniMagick

  version :preview do
    process resize_to_fill: [640, 480]
  end

  def store_dir
    "uploads/foo/bar/#{model.id}"
  end

  def extension_white_list
    IMAGE_EXTENSIONS
  end
end

class Picture
  mount_base64_uploader :picture, PictureUploader
end

class MyModel
  has_many :pictures

  def process_picture(params)
    # I'd expect the following to return false (i.e.: do not create the record) if the upload failed
    # but instead, if the cache upload succeeds and the "real store" upload fails, it leaves the
    # record persisted and its image with a bad reference to the "real store" when we call
    # `picture.url`
    pictures.create(
      picture: params[:src],
      # ... other params
    )
  end
end

MyModel.find(42).process_picture(params)
```
