### ISSUE TITLE
SSRF filter thinks ip address is a hostname

### ISSUE THREAD

**Issue by skiggety** [carrierwaveuploader/carrierwave#2581]
I have :preview as my uploader:
`mount_uploader :preview, PreviewUploader`, where `PreviewUploader` derives from `CarrierWave::Uploader::Base`

I run `resource.remote_preview_url = "http://10.0.0.10:6660//uploads/job/screenshot/85/b2232c09-af25-4cc5-8438-091e90b0e99e.jpg"` (because I already tried and got the same error with 'localhost' in the url), and got this exception:
'CarrierWave::DownloadError Exception: could not download file: Hostname '10.0.0.10' has no public ip addresses'
So it seems carrierwave is doesn't realize that 10.0.0.10 is an ip address.

I've already determined that this was introduced with commit '012702e'.

I can avoid this error with the following bit of code, which I don't think should be necessary:
`class CarrierWave::Downloader::Base
  def skip_ssrf_protection?(uri)
    uri.hostname == 'localhost' || uri.hostname == '10.0.0.10'
  end
end`

I guess it's debatable if this is intended behavior, but at the very least it's weird that it thinks an ip address is a hostname. Also the documented workaround is for downloaders, not uploaders, and wasn't very easy to find.

**Comment by mshibuya** [comment]
It's just a wording issue in ssrf_filter, you can open an issue there.
https://github.com/arkadiyt/ssrf_filter/blob/ebb24a11fc521344f910bc809794df6562413c27/lib/ssrf_filter/ssrf_filter.rb#L126
