### ISSUE TITLE
Upload from local file deletes the local file

### ISSUE THREAD

**Issue by mortik** [carrierwaveuploader/carrierwave#2585]
Hey,

When I follow this wiki entry https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file, the local file gets deleted after the upload was successful.

Is this intentional and if so, how can I prevent this from happening?

I'm using Carrierwave 2.2.2 with Rails 6.1.4.1

Thanks

**Comment by jbosse** [comment]
We constantly upload from local files for seeds and samples and I have never seen it delete a file. It will "upload" the local file to a temp directory on its way then delete the temp file. Is it possible that you are using a file that is in the temp directory?

**Comment by mortik** [comment]
No, the Files are located in the db/seeds folder. I did work before, so I wondered if others have similar issues with the latest Carrierwave Version.
