### ISSUE TITLE
remote_#{column}_request_header is ignored?

### ISSUE THREAD

**Issue by alexsmartens** [carrierwaveuploader/carrierwave#2589]
Hi I'm using CarrierWave to host files on S3 for my project. I'm trying to host selected files with `Content-Disposition: attachment` header. It seems like `remote_#{column}_request_header=` is the way to go for setting up headers for individual files and `fog_attributes` would be a way to do it for all files as I'm gathering from #2006 and #2193.

Here is an example of how I'm trying to set up the request header:
```ruby
class RemoteFile
  mount_uploader :file, CarrierWave::Uploader::Base
end

...
remote_file = RemoteFile.create!(name: my_file_name)
remote_file.remote_file_request_header = {"Content-Disposition" => "attachment" }
remote_file.file = my_file
remote_file.save
```

I can upload a file without a problem. However there is no `Content-Disposition` in the request header when I get the file from S3. So it seems like `remote_file_request_header` setter is ignored. Something does not seem right, could you please help?

**Comment by mshibuya** [comment]
You're getting it wrong, `remote_#{column}_request_header=` is for setting headers on downloading a file using `remote_#{column}_url`. You need to use `fog_attributes` to achieve what you want.
