### ISSUE TITLE
Is it possible to point to an external URL without fetching the file using remote_<file>_url?

### ISSUE THREAD

**Issue by andrewdang17** [carrierwaveuploader/carrierwave#2594]
I have files in the correct storage directory that need to be linked to a model but I want to avoid fetching and reprocessing all the files. I thought updating the filename column that gets generated from the migration would work and it kind of does but then calling `file.present?` returns `false`. I can call `model.file.url` though which gives me what I need but ideally I would be able to check the file presence. 

Looks like the difference between an actual upload is that it uses `CarrierWave::Storage::Fog::File` 
```
#<AvatarUploader:0x000000000d8f7458
 @cache_id=nil,
 @file=#<CarrierWave::Storage::Fog::File:0x000000000d8f7048 ...>,
 @filename=nil,
 @identifier="avatar.jpg",
 @model= 
```
whereas setting the file name uses `CarrierWave::SanitizedFile`
```
#<AvatarUploader:0x00007fb494b59000
 @cache_id=nil,
 @file=
  #<CarrierWave::SanitizedFile:0x00007fb494b58970
   @content=nil,
   @content_type=nil,
   @file="https://s3/path/to/avatar.jpg"
   @original_filename=nil>,
 @filename=nil,
 @identifier="avatar.jpg",
 @model=
```

**Comment by danielricecodes** [comment]
I'm pretty concerned no one is replying to these issues. Is this gem abandonware now?

**Comment by mshibuya** [comment]
`model.avatar.file.exists?` will be what you're looking for.
