### ISSUE TITLE
Fog s3 always storing in cache_dir

### ISSUE THREAD

**Issue by nolyoi** [carrierwaveuploader/carrierwave#2598]
I've recently setup carrierwave with fog on a sinatra app. I ran into an issue where the uploads to my bucker are using the cache_dir location rather than the store_dir.

Is this something that is expected? If so, how do I get it to use the store_dir? Here's my current setup:

what i was running to store:
```
a = AvatarUploader.new
a.store!(params[:avatar])
```
intializer:
```
CarrierWave.configure do |config|
  config.fog_credentials = {
    :provider               => 'AWS',
    :aws_access_key_id      => 'zzz',
    :aws_secret_access_key  => 'xxx',
    :region                 => 'us-east-2',
  }
  config.fog_directory = 'cosmily-storage'
end
```
uploader:
```
class AvatarUploader < CarrierWave::Uploader::Base
  storage :fog

  def store_dir
    'development/users/avatars'
  end

  def cache_dir
    '/tmp/uploads'
  end
end
```

**Comment by mshibuya** [comment]
@nolyoi  You'd better to describe how you could resolve this. It'll help others with similar question in the future.

**Comment by nolyoi** [comment]
> @nolyoi You'd better to describe how you could resolve this. It'll help others with similar question in the future.

I had to set store_dir otherwise it was defaulting to a cache location
