### ISSUE TITLE
Using remote_image_url stores in wrong location.

### ISSUE THREAD

**Issue by nolyoi** [carrierwaveuploader/carrierwave#2599]
So, I'm trying to move some old data and I'm running a migration that basically does this:

```ruby
      url = "https://exs3.us-east-2.amazonaws.com/images-old/products/10/10.jpg"
      image = Models::UserImage.new(user_id: user.id, is_avatar: true)
      image.remote_image_url = url
      image.save
```
It is saving the image, but it's going to the cache_dir and not using the correct `filename`. It does seem to be using my filename method to generate the next level folder though which is odd and then uses it's original filename. ex: `/development/1645607287-429008200631828-0001-3614/cool_photo.jpg`. Anyone have any clues into what might be going on here?

Here is my image uploader:

```ruby
# frozen_string_literal: true

class ImageUploader < CarrierWave::Uploader::Base
  storage :fog

  def filename
    "#{secure_token}.#{file.extension}" if original_filename.present?
  end

  def store_dir
    "#{ENV['RACK_ENV']}"
  end

  def extension_allowlist
    %w(jpg jpeg gif png)
  end

  protected

  def secure_token
    var = :"@#{mounted_as}_secure_token"
    model.instance_variable_get(var) or model.instance_variable_set(var, SecureRandom.uuid)
  end
end
```

**Comment by courtsimas** [comment]
I'm curious as well. I've run into weird things like this without answers.

**Comment by danielricecodes** [comment]
I'm pretty concerned no one is replying to these issues. Is this gem abandonware now?

**Comment by nolyoi** [comment]
> I'm pretty concerned no one is replying to these issues. Is this gem abandonware now?

I ended up getting it working using some conditionals. There was some commits on their main branch a couple months ago, so I don't think it's dead.

**Comment by mshibuya** [comment]
Make sure that `image.save` succeeds. Things like a validation error causes the image only cached to the storage, but not stored in the final location.
