### ISSUE TITLE
Fog: url generation is too slow

### ISSUE THREAD

**Issue by clm-a** [carrierwaveuploader/carrierwave#261]
Hi !
I'm enjoying your awesome work !
I may be wrong but :
Using Rails 3.0.4 + CarrierWave 0.5.2 + fog 0.7.0 (uploading on s3) + sqlite3, file url generation seems very slow out of the box.
When I type Painting.last.file (Painting's file attribute) in Rail's console, that method responds http://bucket.blahblah within a couple of seconds, about 2 sec. That's pretty poor :-/

Rendering views take a while (6 secs for displaying 3 pics)...

Am I missing something ?
Is there a simple way to cache file's url after upload ?

Thanks :)
Clément

**Comment by phillipp** [comment]
Nice work, setting the default to "it costs money" (like, every requests costs freaking money with S3 or google cloud). We've made a couple thousand GET requests FOR ONE PAGE LOAD!!!

**Comment by krtschmr** [comment]
in case somebody knows his storage-url and want's to save all the lookups you can use the following hijack.
```
[45] pry(main)> **Brand.last.image_url**
  Brand Load (0.4ms)  SELECT  `brands`.* FROM `brands` ORDER BY `brands`.`id` DESC LIMIT 1
=> **"https://storage.googleapis.com/our_project-development/brands/test.png"**

[46] pry(main)> Brand.last.image.url
  Brand Load (0.6ms)  SELECT  `brands`.* FROM `brands` ORDER BY `brands`.`id` DESC LIMIT 1
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development?
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development/o/brands%2Ftest.png?
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development?
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development/o/brands%2Flogo_test.png?
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development?
Sending HTTP get https://www.googleapis.com/storage/v1/b/our_project-development/o/brands%2Fthumb_test.png?
=> **"https://storage.googleapis.com/our_project-development/brands/test.png"**

just put the following code in `/app/models/concerns/carrierwave_fix.rb`

```
module CarrierwaveFix
  def self.included(base); base.extend(Mount); end

  module Mount
    def mount_uploader(column, uploader=nil, options={}, &block)
      define_method "#{column}_url" do
        "https://storage.googleapis.com/our-project-#{Rails.env}/#{uploader.new(self).store_dir}/#{read_attribute(column)}"
      end
      uploader.new.versions.each do |version, _v|
        define_method "#{column}_#{version}_url" do          
          "https://storage.googleapis.com/our-project-#{Rails.env}/#{uploader.new(self).store_dir}/#{version}_#{read_attribute(column)}"
        end
      end
      super #super? husocarrierwave!!!
    end
  end
end

and include it 

    class ApplicationRecord
      include CarrierwaveFix
    end

**Comment by krtschmr** [comment]
@geemus we should reopen this issue and somehow work on a better handling

**Comment by geemus** [comment]
@krtschmr possibly, I think for AWS it is pretty well setup, but maybe not for google. I haven't used carrierwave, really ever though, so I'm not totally sure where we are on this. Happy to support efforts as best as I can though.

**Comment by mathportillo** [comment]
I can confirm that `paperclip` + `fog_google` + `google-api-client ~> 0.9.27` queries urls very slowly when `fog_host` is unset.
When it is set it runs much faster.

**Comment by dgmora** [comment]
Hi, this issue is quite old but I could not find documentation about it. I'm using carrierwave with fog-google. Authenticated url generation is quite slow , even when setting `asset_host`. Should `asset_host` also help too with authenticated urls? If it doesn't, is there anything that could help speeding this up?

**Comment by geemus** [comment]
@dgmora - It's been some time since I worked in/around this. I don't see an obvious reason why this wouldn't work as-is with the current version of fog-google. The URL calls all appear to just make local lookup calls, as you can see here: https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/utils.rb. Could you share a bit more about the context in which you are using it and a version of the config you are passing in (with any secrets removed if needed) to see if anything jumps out?

**Comment by dgmora** [comment]
Looking at a flame graph, the time is spent signing, which gets called from the file you linked:

https://github.com/fog/fog-google/blob/v1.19.0/lib/fog/storage/google_json/real.rb#L140

What I'm trying to do is serialize a list of attachments. The model is something like:

```ruby
class Attachment < ApplicationRecord
  mount :file, AttachmentUploader
end

class AttachmentUploader < BaseUploader; end

class BaseUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
```
The way I'm getting the url is `attachment.file.url`

**Comment by dgmora** [comment]
Interesting, I'll give that a try! 

I don't have exact information about that, but it could be something between a few hundred or up to 1000. I understand that this may not be the best idea, but I'm checking if it's possible to speed this up before checking other solutions.

**Comment by geemus** [comment]
@dgmora Sounds good. I hope to release soon also, but we had some CI issues (which I think are unrelated, but we wanted to be sure) that we were trying to work out first. Do let me know if that solves it, otherwise we can maybe dig deeper and see if we are missing something else.

**Comment by dgmora** [comment]
It didn't help much. The actual time spend when calling `sign`. I got more accurate numbers, and it's about 4K urls being generated, taking close to 10sec. Looking at the numbers, I think it isn't unreasonable that it takes 8-10 seconds. Thanks for the quick answers though!
