### ISSUE TITLE
Receiving intermittent "internal error. Please try again." from S3, but CW does not try again.

### ISSUE THREAD

**Issue by jsgarvin** [carrierwaveuploader/carrierwave#2610]
After recently upgrading carrierwave from 1.3.2 to 2.2.2, we've begun experiencing windows of time (30 minutes ish) where uploads to S3 are failing, though creating the local ActiveRecord instance succeeds, and files are being lost.  The latest instance we began receiving "We encountered an internal error. Please try again." errors back from AWS (which we are following up with them on), but we've had other instances where the failure was silent and the files just weren't there on S3 when we later tried to retrieve them (although we did find them in CW's cache).

Does anybody have any idea what could be going on, and possibly get CW to do as the error suggests, and "Please try again."?

**Comment by mshibuya** [comment]
I don't think this retry is what CarrierWave should do. Client libraries (fog-aws or aws-sdk-s3, depending on your setup) knows better whether their requests are safe to be retried or not.
Also this behavior

> creating the local ActiveRecord instance succeeds, and files are being lost

should have been addressed by #2546. With this the transaction will be rolled back on failing to store the file.
So I think this issue can be closed.
