### ISSUE TITLE
Filename get change while uploading

### ISSUE THREAD

**Issue by sanjain-progress** [carrierwaveuploader/carrierwave#2611]
Uploading the file with name `06 (1).jpg`. 
When I try to access the filename via `File.basename(path)`. It given the output like this `06__1_.jpg`

This problem occurs when the filename contains brackets (`()`).

This issue is already faced by other users also. Someone posted this question in [stackoverflow](https://stackoverflow.com/questions/61926072/how-does-carrierwave-change-files-name)

**Comment by mshibuya** [comment]
Answered here.
https://github.com/carrierwaveuploader/carrierwave/issues/1907#issuecomment-500760382
