### ISSUE TITLE
Rails 7 - SanitizedFile.sanitize_regexp setting is not working

### ISSUE THREAD

**Issue by bs90** [carrierwaveuploader/carrierwave#2616]
https://github.com/carrierwaveuploader/carrierwave/blob/master/README.md#filenames-and-unicode-chars
I followed this but Japanese filename still became "________________.pdf" after uploading. Can anyone help me? Thank you.
(It seems that the regex is being default now https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L23 )

**Comment by bs90** [comment]
I monkey patch the sanitize function and solve my problem. But please tell me if there is any another way to do it easier with default setting.

**Comment by mshibuya** [comment]
Could you provide the example of filenames which gets converted to `_` ? What encoding do they have?

> I monkey patch the sanitize function

What change you made was effective?

**Comment by mshibuya** [comment]
Stale.
