### ISSUE TITLE
Copying does not apply S3 acl

### ISSUE THREAD

**Issue by xanderman** [carrierwaveuploader/carrierwave#2627]
This is possibly related to #2240. I'm not sure if they're the same issue or not.

We have the following in our carrierwave initializer:

```
config.fog_attributes = {
  "Content-Disposition" => "attachment;",
  cache_control: "max-age=315576000",
  expires: 1.year.from_now.httpdate,
  'x-amz-acl' => 'bucket-owner-full-control'
}
```

The acl is properly set on uploads, but is lost on copies. We use code like `record.document.file.copy_to(new_path)` to do an S3 copy, where `document` is a column with an uploader mounted. The new S3 object is created with a private acl, when it should have the bucket-owner-full-control acl.

**Comment by mshibuya** [comment]
Fixed by #2503.
