### ISSUE TITLE
NoMethodError: undefined method `closed?' for nil:NilClass

### ISSUE THREAD

**Issue by Mirk32** [carrierwaveuploader/carrierwave#2628]
After updating to version 2.1.1 when trying to upload remote file by URL getting following error:
```
NoMethodError: undefined method `closed?' for nil:NilClass
from /Users/xxx/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/net/http/response.rb:333:in `stream_check'
```

In 2.1.0 version it works well.

**Comment by jules-w2** [comment]
@Mirk32 , https://github.com/carrierwaveuploader/carrierwave/issues/2625

**Comment by sailman** [comment]
Same error:

NoMethodError: undefined method `closed?' for nil:NilClass
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/downloader/remote_file.rb:11:in `initialize'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/downloader/base.rb:41:in `new'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/downloader/base.rb:41:in `download'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/uploader/download.rb:19:in `download!'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:98:in `block (2 levels) in remote_urls='
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:176:in `handle_error'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:96:in `block in remote_urls='
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:95:in `each'
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mounter.rb:95:in `remote_urls='
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/mount.rb:166:in `remote_photo_url='
/home/sailman/apps/divatod.hu/shared/bundle/ruby/2.7.0/gems/carrierwave-2.2.2/lib/carrierwave/orm/activerecord.rb:21:in `remote_photo_url='

**Comment by almaron** [comment]
@jules-w2 Same error popping up after I updated an old pet project. 
Seems to be an issue specifically with remote opening. 

Is that fix from the mentioned issue released on rubygems or can I pull it by some version?

**Comment by harssh** [comment]
Still getting this issue . Is there any targeted version which resolves this ?

` si.file.download!(si.file.url)`
`NoMethodError: undefined method `closed?' for nil:NilClass
from /Users/hshrivastava/.rvm/gems/ruby-2.7.6@sullivan_cotter/gems/net-http-0.3.0/lib/net/http/response.rb:507:in `stream_check'`

version gem 'carrierwave', '2.2.2'

**Comment by mshibuya** [comment]
See #2638.
