### ISSUE TITLE
Cannot insert legacy ACL for an object when uniform bucket-level access is enabled.

### ISSUE THREAD

**Issue by sgrverma24** [carrierwaveuploader/carrierwave#2634]
Hi all,

Uploading file to google cloud bucket was working fine when we had "Fine-grained" access. Later it is changed to "uniform bucket-level access". Now upload operations are failing with the below error.

invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access (Google::Apis::ClientError)

Any solutions/suggestions to tackle this issue.

Using 'carrierwave': '1.3.2'

**Comment by lguida-nasdaq** [comment]
Any news on this? I have been searching how to handle this error as the security team is pushing us to use Uniform bucket-level access. 

Looks like the fog-google gem has an option for it: https://github.com/fog/fog-google/blob/c0b13cee73b0493acf76f4c442aeeba85028d8a4/lib/fog/storage/google_json/models/file.rb#L120
