### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pdfrod** [carrierwaveuploader/carrierwave#2638]
Hi! It has been more than a year since the last release. I'm having to use a Git commit reference in my Gemfile to be able to get the latest improvements.

Are there any plans for a new release?

**Comment by nachiket87** [comment]
Please could we have a release?

**Comment by mshibuya** [comment]
Released `3.0.0.beta`, please try and give feedback!

**Comment by mshibuya** [comment]
Also backported the ssrf_filter workarounds to `2.2.3`.
