### ISSUE TITLE
Carrierwave 3.0.0 no longer creates directories using `fog/local`

### ISSUE THREAD

**Issue by JonRowe** [carrierwaveuploader/carrierwave#2668]
:wave: I'm using provider `fog/local` in my tests with a local root thats not in my repository (it only exists locally and during CI builds), previously on 2.2.3 this directory would be created automatically and uploads would work, upgrading to 3.0.0 changed this behaviour, either accidentally or intentionally, causing this error to manifest:

```
undefined method `path' for nil:NilClass (NoMethodError)
```

When attempting to access the uploaded file. I'm mostly opening this issue for searchibility/visibility as its an easy work around locally (I'm just creating the directory in my support files before the build now).

Could we get a note added to the changelog about this to also help future travellers?

(This error happened for me on Rails 6.1, Ruby 3.2)

**Comment by mshibuya** [comment]
Thank you for reporting. This is unexpected, could you provide the full stack trace?

**Comment by mshibuya** [comment]
Stale, please let me know on update.
