### ISSUE TITLE
Version 3.0.0 deduplicates file names even when not needed

### ISSUE THREAD

**Issue by Fs00** [carrierwaveuploader/carrierwave#2670]
In our application we have an uploader set up like the following:
```ruby
class AttachmentUploader < CarrierWave::Uploader::Base
  storage :file

  def store_dir
    "#{Rails.configuration.fs_root}/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end
```
which stores file attachments in a separate sub-folder for each record (notice `#{model.id}` at the end of the path).
When we duplicate a record that has an attachment with `dup`, we've noticed that the duplicated record attachment gets the suffix added to the filename, even though it's stored in a different folder compared to the original one and therefore there's no need to add the suffix.

If we force the uploader not to deduplicate filenames by overriding the following function (which admittedly looks a bit hacky and we'd rather not do that):
```ruby
def deduplicated_filename
  filename
end
```
the issue disappears.

**Comment by Paul-Yves** [comment]
We got a very similar issue, when we reupload a file with an identical name, the saved file has duplicate name (eg `example(2).png`), but what is worse is that the uploader is still looking for the original filename without duplication, and it does no longer exist on our s3 so the picture is not available anymore

**Comment by mshibuya** [comment]
Thank you for reporting. This should be fixed by b732acd63209897e6375a3706330df2c38e3f327, so please try.

**Comment by GabrielKoehler** [comment]
Hi, in my uploader i've got the same issue.

My Carrierwave version is (3.0.7) and i using `storage :fog`, but the file still generates with suffix.

```ruby
class BaseUploader < CarrierWave::Uploader::Base
  if Rails.env.in? %w[production blue staging]
    storage :fog
  else
    storage :file
  end
  
  def store_dir
    if Rails.env.production? || Rails.env.blue?
      "uploads/#{model.class.to_s.underscore}/#{model.id}"
    else
      "uploads-#{Rails.env}/#{model.class.to_s.underscore}/#{model.id}"
    end
  end
end
``` 
```ruby
class CertificateUploader < BaseUploader
  def filename
    'certificate.pdf'
  end
end
``` 
The first time i try generate a new certificate, work's like a charm, but, if i retry to generate a new certificate file `"certificate.pdf"`, my new certificate receives the sufix, like `"certificate(2).pdf"`.

**Comment by mshibuya** [comment]
@GabrielKoehler Yours should be unrelated to this, and is expected. See https://github.com/carrierwaveuploader/carrierwave/issues/2712#issuecomment-1837438412 for reasoning.
