### ISSUE TITLE
Duplicate File Upload Issue with CarrierWave 3.0.2 

### ISSUE THREAD

**Issue by apjames93** [carrierwaveuploader/carrierwave#2682]
A potential bug that we have encountered while using CarrierWave version 3.0.2 and 'carrierwave-aws' gem (version ~> 1.6). Unsure whether this is a bug or if there's a configuration setting or workaround we may have missed.

Issue:
When attempting to upload a file with the same name as an existing file, the expected behavior should be to overwrite the existing file with the new one. However, we have observed an unexpected behavior. Instead of overwriting the existing file, CarrierWave appears to be generating a new filename with a numeric suffix. For instance, if we attempt to upload a file named "favicon.ico" when a file with the same name already exists, we expect the existing file to be replaced. However, the result is "favicon" => "favicon(2).ico" instead of the intended "favicon" => "favicon.ico".

Steps to Reproduce:
1. Use CarrierWave version 3.0.2 with the 'carrierwave-aws' gem (version ~> 1.6).
2. Attempt to upload a file with the same name as an existing file.

Expected Result:
The existing file should be replaced by the new file with the same name.

Actual Result:
A new filename is generated with a numeric suffix, and the original file remains unchanged.

**Comment by mshibuya** [comment]
It's totally an intentional feature starting from CarrierWave 3.0. See https://github.com/carrierwaveuploader/carrierwave/issues/1855 and https://github.com/carrierwaveuploader/carrierwave/pull/2679#issuecomment-1664865815 for reasoning.
