### ISSUE TITLE
Getting error NoMethodError: undefined method `cached?' when I try to upload

### ISSUE THREAD

**Issue by SaimonL** [carrierwaveuploader/carrierwave#2683]
Hi. I am trying trying to upload a file from my local computer and I am getting the following error:
```
NoMethodError: undefined method `cached?' for #<File:tmp/1ccbbf0c-1ebb-4f75-8cde-401e137fb62a/debian-linux_json.zip>
```

I tried both:
```ruby
message.attachments << File.open("tmp/export.zip")
# and
message.attachments << Pathname.new("tmp/export.zip").open
```
and as soon as I save I get that error. The `message.attachments` is an empty array initially

The message model:
```ruby
class Message < ApplicationRecord
  mount_uploaders :attachments, MessageUploader
end
```

The MessageUploader
```ruby
class MessageUploader < CarrierWave::Uploader::Base
  storage :fog

  def store_dir
    "uploads/messages/users/#{model.user.id}/#{model.id}"
  end

  def extension_allowlist
    %w(jpg jpeg gif png json pdf png gif txt doc docx csv xls ppt odt md zip 7z)
  end
end
```

Message model migration has this `t.json :attachments`

The weird part is in the web forum the file field works and it attaches the file just fine from the controller the file gets uploaded to S3 bucket. The problem occurs when I try to do this manually from rails console.

Followed the instructions here with no luck: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file

**Comment by rajyan** [comment]
At least what I can say is that
```ruby
message.attachments = [File.open("tmp/export.zip")]
```

or

```ruby
files = []
files << File.open("tmp/export.zip")
message.attachments = files
```

should work.

**Comment by SaimonL** [comment]
I don't know why but `message.attachments = [File.open("tmp/export.zip")]` worked.
Thank you @rajyan

**Comment by rajyan** [comment]
I think the reason is

https://github.com/carrierwaveuploader/carrierwave/blob/26b6bbda9b412795840f59fe82b38c0c6ba07167/lib/carrierwave/mount.rb#L286-L292

`message.attachments <<` invokes `<<` on uploaders (which is an array), while `message.attachments=` invokes `cache`.
I don’t understand enough the library code, but it might worth making them consistent.
