### ISSUE TITLE
ActiveRecord model 'dup' modifies the original object.

### ISSUE THREAD

**Issue by bblimke** [carrierwaveuploader/carrierwave#2687]
There is an issue with AR model `dup` since version 3.0.0rc

````
my_ar_model[:image]
=> "image_689f742ca69d9d7b9b6aaed556f1f1e31ccc9a3a.JPG"
my_ar_model.dup
my_ar_model[:image]
=> nil
````

btw. is there a way to disable the current dup behaviour. I want to duplicate model but skip the duplication and upload of the file.

**Comment by mshibuya** [comment]
Thank you for reporting, now fixed in the master.

**Comment by bblimke** [comment]
Thank you @mshibuya !
