### ISSUE TITLE
Carrierwave Mongoid inactive

### ISSUE THREAD

**Issue by plribeiro3000** [carrierwaveuploader/carrierwave#2692]
I'm trying to updagrade the version of `carrierwave` in one of my projects but i'm not able to since this project is using mongo and the support for mongo is outdated.

I've opened carrierwaveuploader/carrierwave-mongoid#212 in the project issues but got no answer at all. Maybe there is no active maintainer for it?

**Comment by mshibuya** [comment]
It's a separate project, let's discuss thre.
