### ISSUE TITLE
ActiveRecord model keeps dirty after update

### ISSUE THREAD

**Issue by ssugiyama** [carrierwaveuploader/carrierwave#2702]
```ruby
class FooUploader < CarrierWave::Uploader::Base
  def filename
    'a.png'
  end
end
```

```ruby
class Foo < ApplicationRecord
  mount_uploader :image, FooUploader
end
```

```ruby
foo = Foo.create!(...)
foo.update!(image: File.open(...))
puts foo.changed? # expecting 'false' but we get 'true'
```

this problem occurs since 3.0.0.rc to 3.0.3
  only if filename method is defined in uploader
  and saved outside transactions (if saved inside transactions, we get 'false')

Are there any workarounds or required settings?

**Comment by rajyan** [comment]
Is this issue related to your problem?
https://github.com/carrierwaveuploader/carrierwave/issues/2682

**Comment by sdrioux** [comment]
Yes, its likely a side effect - but this is still technically a bug that we are running into as well.

**Comment by ssugiyama** [comment]
> Is this issue related to your problem?

Maybe, not. We try changing filename in every save, but the problem is reproduced.

```ruby
class FooUploader < CarrierWave::Uploader::Base
  def filename
    (Time.zone.now.to_f * 1000).to_s + '.png'
  end
end
```

Here is additional information.

```ruby
foo = Foo.create!(...)
foo.update!(image: File.open('newfile.png'))
puts foo.changes
=> {"image"=>["1694578531581.793.png", "newfile.png"]}
```

**Comment by rajyan** [comment]
Thank you for the detailed information!
I think https://github.com/carrierwaveuploader/carrierwave/pull/2707 fixes this bug.
