### ISSUE TITLE
Models with files attached are slow to save vs without files attached

### ISSUE THREAD

**Issue by Amnesthesia** [carrierwaveuploader/carrierwave#2730]
Saving a record that has anything attached with Carrierwave takes significantly more time to save than saving records of the same model that don't have anything attached yet

I'm not sure why this is, e.g if Carrierwave is automatically downloading the file and then saving it again

**Comment by mshibuya** [comment]
Most possible cause is #2461.
If that's not the case, providing the uploader code will be helpful to track down the cause.

**Comment by Amnesthesia** [comment]
@mshibuya With or without head requests, should this really be necessary when saving fields on a record that don't touch the carrierwave field? Why should it need to do any requests at all when the file has not been touched?

**Comment by mshibuya** [comment]
Stale.
