### ISSUE TITLE
skip_ssrf_protection configuration doesn't work other than master branch

### ISSUE THREAD

**Issue by takmar** [carrierwaveuploader/carrierwave#2745]
In the README, it states: "you can disable SSRF protection at your own risk using the skip_ssrf_protection configuration."
However, the skip_ssrf_protection configuration only works in the master branch because the [PR](https://github.com/carrierwaveuploader/carrierwave/pull/2696) that implemented the skip_ssrf_protection option has not been backported.

As a result, if I add config.skip_ssrf_protection = true in an initializer, it causes the following error:
```
NoMethodError:
  undefined method `skip_ssrf_protection=' for CarrierWave::Uploader::Base:Class
```

**Comment by mshibuya** [comment]
It's included in the release 3.1.0.beta.
