### ISSUE TITLE
NoMethodError (undefined method `copy_object' for "close":String) using fog

### ISSUE THREAD

**Issue by sectasy0** [carrierwaveuploader/carrierwave#2746]
Hi there, I've been experiencing an strange error when uploading images to DigitalOcean Spaces (S3). Initially, I thought it might be related to the Fog library, but unfortunately, the Fog maintainer wasn't able to assist me. More context in fog repo issue. Thank you

more context: https://github.com/fog/fog-aws/issues/702

**Comment by sectasy0** [comment]
@mshibuya Could you assist?

**Comment by mshibuya** [comment]
Made a comment there: https://github.com/fog/fog-aws/issues/702#issuecomment-2350878945
