### ISSUE TITLE
Version file name customisation does not seem to work since v3.0.6

### ISSUE THREAD

**Issue by highhi** [carrierwaveuploader/carrierwave#2747]
Rails 7.1.3.4
Ruby 3.3.4

Changing the file name of an image will result in the image not being output.
Seems to have stopped working since 3.0.6. It worked in 3.0.5.

```
# Images of this version are not output.

version :thumb do
  def full_filename(for_file)
    "image.jpg"
  end
end
```

I could not find the cause of the problem for me as I checked the code and it seemed to [pass the test](https://github.com/carrierwaveuploader/carrierwave/blob/master/spec/uploader/versions_spec.rb#L958-L961). I would appreciate it if you could confirm this.

**Comment by highhi** [comment]
Sorry. This seems to have been a mistake on my part. I can confirm that it is working correctly. This Issue is closed.

**Comment by marcalc** [comment]
@highhi would you mind mentioning what was the mistake? I've overriden the full_filename of the version and the version is not output same as your initial question. Thanks!
