### ISSUE TITLE
SomeUploader.new.identifier returns nil

### ISSUE THREAD

**Issue by znz** [carrierwaveuploader/carrierwave#2754]
After upgrade to carrierwave 3.0.7 from 2.2.6, `SomeUploader.new.identifier` always returns `nil`.

When `AttachmentUploader.new.filename` returns an unique identifier,
`SomeUploader.new.store_path` returns `store_dir/filename` with carrierwave 2.2.6,
but `SomeUploader.new.store_path` returns `store_dir/` with carrierwave 3.0.7.

Is this intentional?

I think this is changed at <https://github.com/carrierwaveuploader/carrierwave/commit/f1eff6e212fb0c374c9235968bfc4e7580bf1e2a>.

There is "when #filename is set to always return a value" in spec, if `a value` means the `dummy` filename not `nil`, it seems not intentional.

**Comment by mshibuya** [comment]
It is intentional.

Sorry if the spec description wasn't clear, but what it means is "even if #filename always returns a value, resulting #identifier returns nil". So the spec and the implementation matches.
