### ISSUE TITLE
Incompatible with URI >=1.0.0

### ISSUE THREAD

**Issue by swelther** [carrierwaveuploader/carrierwave#2759]
Today the standard gem URI was released as 1.0.0, introducing a new default parser `RFC3986_Parser`: https://github.com/ruby/uri/pull/107/files

This results in errors like

```
NameError: uninitialized constant URI::REGEXP
Did you mean?  Regexp
…/ruby/3.1.0/gems/uri-1.0.0/lib/uri/common.rb:53:in `const_missing'
…/ruby/3.1.0/gems/carrierwave-3.0.7/lib/carrierwave/utilities/uri.rb:7:in `<module:Uri>'
```

I think I could prevent this error by setting the default parser back to the old one with `URI.parser = URI::RFC2396_PARSER`. But not sure how carrierwave should behave.

**Comment by jules-w2** [comment]
i confirm, @ollym 's PR fix this issue.
I hope it can be merged quickly

**Comment by taketo1113** [comment]
I encountered the same error with uri gem v1.0.0.

Updating to uri gem v1.0.1 resolved the `uninitialized constant URI::REGEXP` error.
It seems that in uri gem v1.0.1, `URI::REGEXP` fallback to `URI::RFC2396_REGEXP`.

https://github.com/ruby/uri/issues/125#issuecomment-2463863189
