### ISSUE TITLE
minimagick removed run_command

### ISSUE THREAD

**Issue by bhh** [carrierwaveuploader/carrierwave#2761]
as of the changelog for minimagick

they even mentioned carrierwave in the commit message

removed obsolete `Image#run_command` in v5.0
> It's currently used in CarrierWave, which was the only reason I kept it.
CarrierWave shouldn't be using it anymore, and ImageProcessing locking
MiniMagick to 4.x should ensure we don't break CarrierWave.

with minimagick >= 5 i get following error
`unrecognized option -run-command' @ error/mogrify.c/MogrifyImageCommand/`

i think i can fix that next week. maybe it's an important information to use `minimagick < 5` until then

**Comment by janko** [comment]
I allowed MiniMagick 5.x in latest release of ImageProcessing, forgetting that it would break CarrierWave. My apologies 🙈
