### ISSUE TITLE
CarrierWave::InvalidParameter: invalid cache id

### ISSUE THREAD

**Issue by sorentwo** [carrierwaveuploader/carrierwave#313]
I'm receiving this error inconsistently when attempting to assign a mounted file in a controller. Specs for the model the upload is mounted on and the uploader both pass, it only happens in the controller and it happens in any environment. The issue only happens when processing additional versions, regarldess of the image processor or what is being called inside the version block. Here is the point of failure:

``` ruby
# carrierwave/uploader/versions.rb
def cache_versions!(new_file)
  # We might have processed the new_file argument after the callbacks were
  # initialized, so get the actual file based off of the current state of
  # our file
  processed_parent = SanitizedFile.new :tempfile => self.file,
    :filename => new_file.original_filename

  versions.each do |name, v|
    v.send(:cache_id=, cache_id)
    v.cache!(processed_parent)
  end
end
```

At this point cache_id is nil when saved through the controller. However, when processed in the model spec or the uploader spec the cache_id prints out normally.

I've tried making the action do something as basic as:

``` ruby
def create
  @record = Record.new
  @record.picture = File.open(File.join(Rails.root, 'spec/fixtures/image.jpg'))
end
```

And even that results in the same failure as soon as picture= is called. The file path is verified, and that is the exact same file/path that works in other specs.

Here is the relevant part of the uploader:

``` ruby
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{model.id}/#{mounted_as}"
  end

  def default_url
    '/images/' + [mounted_as, version_name, 'default.png'].compact.join('_')
  end

  process :convert => 'jpg'

  version(:modal) do
    # process :resize_to_fit => [450, 600]
    # process :downsample => 80
  end

  version(:thumb) do
    # process :resize_to_fill => [128, 128]
    # process :downsample => 80
  end

  def extension_white_list
    %w(jpg jpeg png)
  end

  def filename
    'picture.jpg' if original_filename
  end
```

Any ideas?

**Comment by jedschneider** [comment]
for me it occurred when I accidentally passed a bad time stamp, in case that stumps anyone else.

**Comment by Startouf** [comment]
I am also getting this error with FactoryGirl when trying to make a user with avatar
```
factory :user do 
  avatar do
      Rack::Test::UploadedFile.new(
        Rails.root.join('spec', 'fixtures', 'files', 'avatar.png'),
        'image/png'
      )
    end
end
FactoryGirl.build(:user) # => 
```

After debugging some code it would seem during the caching callbacks, I have a `cache_id` that is nil inside `cache_id=`

I managed to fix the bug by changing the following in [`cache_versions!`](https://github.com/carrierwaveuploader/carrierwave/blob/0.11-stable/lib/carrierwave/uploader/versions.rb#L260)

```
next if v.cached?
```

to 
```
next if v.cached? || !cache_id
```

I'm still using carrierwave 0.11.2 as I'm using Mongoid and carrierwave-Mongoid hasn't yet been adapted to 1.x (cf https://github.com/carrierwaveuploader/carrierwave-mongoid/issues/172)

For some reason, in another factory I was adding a company logo using a similar `mount_uploader` and `Rack::Test::UploadedFile` and it worked fine.

Any tips ?
