### ISSUE TITLE
Auto deleting attached files on row deletion?

### ISSUE THREAD

**Issue by ghost** [carrierwaveuploader/carrierwave#336]
For example, if I do

```
Recording.where("start_date < '2011-05-25'").delete_all()
```

I'm left with tens of thousands of attachment files that nothing uses. How would I get those to be automatically deleted when the above is ran?

**Comment by chabgood** [comment]
I am on rails 4.2.3 and I am not seeing the photos being deleted.

**Comment by tom-lord** [comment]
Here's a permanent link for any future reader who, like me, were confused by the above link that now points to a different line of code:

https://github.com/carrierwaveuploader/carrierwave/blob/ba782cc6328f5a1de1d846950a25601f88509eff/lib/carrierwave/orm/activerecord.rb#L57

As of the current version (`1.1.0`), calling `my_record.destroy` will trigger the `remove_{column}!`callback (e.g. `remove_file!`), which deletes the file itself. Calling `my_record.delete`,on the other hand, skips callbacks - so the file still exists.


Note that your server may not have **permission** to delete file, however! For example, if your files are on S3 and the IAM role for the server does not have delete permissions.
