### ISSUE TITLE
User.avatar=  should not immidiately start processing the file

### ISSUE THREAD

**Issue by GBH** [carrierwaveuploader/carrierwave#361]
I started integrating CarrierWave today and I tripped over this. Let's say I have something like this:

```
class Foo < ActiveRecord::Base
  has_many :bars
end

class Bar < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :foo
end

class FileUploader < CarrierWave::Uploader::Base
  # some stuff
  version :thumb do
    process :do_magic
  end

  def do_magic
    resize_to_fill(model.foo.width, model.foo.height)
  end
end
```

Pretty simple thumb generation with dynamic dimensions based on Foo object. You'd think that something like this would work:

```
@foo.bars.create!(:file => File.open(whatever))
```

Nopes. It will blow because at that time `model` has no idea what `foo` is. It's a nil at that point. This is because `file=` immediately triggers thumb generation for the cache before any other assignment had a chance to happen.

You can rewrite it like this:

```
bar = @foo.bars.new
bar.file = File.open(whatever)
```

Now it's actually aware of Foo. But this is pretty terrible.

So the point is, in my opinion, that all activity should be triggered only on `before_save` (or `before_validation`), never on assignment.

I kinda patched up `orm/active_record.rb` to do just that and I'm willing to submit a patch. Let me know if it makes sense. Thanks.

**Comment by opsidao** [comment]
We're using 0.10.0 and have hit this problem, is this still happening on 0.11.2?

**Comment by ErvalhouS** [comment]
Using 0.11.2@0a1c6f4a706c5f910d78fa1eaec809691a9c9c34 this problem is still present.

**Comment by h0jeZvgoxFepBQ2C** [comment]
@trevorturk It's a big vulnerability imo, since you can DOS your server with big files - if the processing starts before the validation already?
