### ISSUE TITLE
to convert an image user is required to change file format extension

### ISSUE THREAD

**Issue by gregwebs** [carrierwaveuploader/carrierwave#368]
I would expect carrierwave to do this for me. When I didn't the image was not converted, and the file extension was not changed.

I am using rails_admin, with the dragonfly_file partial for a file field. This gives me back an ActionDispatch::Http::UploadedFile, which I have to change the original_filename attribute to match the new extension. If I don't, it silently does not convert. I would expect some kind of error message to be logged.

**Comment by vanboom** [comment]
:+1:   Please reopen.  Let's develop a built-in solution for this vs. work arounds.  process :convert=>:jpg should produce a file with .jpg extension, not .png.

**Comment by DonGiulio** [comment]
The workaround very quickly gets into a mess if you are saving versions of you files in different formats (for example PNG previews for PDF files), where you need to reimplement, for each version: 

```
    def full_filename(for_file)
      super(for_file).chomp(File.extname(super(for_file))) + '.png'
    end
```

And if you are using also callbacks the file passed to each callback will have the old name. 

Please reopen this.

**Comment by schnittchen** [comment]
I couldn't figure out how to

1) have a version `process convert: 'png'` including fixing the extname
2) have other versions depend on (1).

**Comment by elsurudo** [comment]
Is there still no decent workaround for this? I am on the latest gem version of carrierwave, and still experiencing the issue

**Comment by mhluska** [comment]
Still ongoing it seems.
