### ISSUE TITLE
Carrierwave is not compatible with Globalize3

### ISSUE THREAD

**Issue by Gu1111** [carrierwaveuploader/carrierwave#418]
When trying to use CarrierWave on a Globalize3 Column (ActiveRecords) the app crashes with an error:

undefined method `attribute_will_change! 

The combination of Carrierwave and Globalize3 can be very useful if the admin wants to upload different images for different locales.

**Comment by jamesalbuquerque** [comment]
Have the same issue.

```
class Cover < ActiveRecord::Base

	translates :cover, :author, :description

	mount_uploader :cover, CoverUploader
	attr_accessor :cover, :cover_cache

```

```
<%= f.fields_for :cover do |builder| %>
	<div class="cover clearfix">
		<div class="overlay">
			<%= image_tag @post.cover && @post.cover.cover unless @post.cover && @post.cover.cover.blank? %>
			<%= builder.file_field :cover, id: 'uploadify' %>
```

```
def new
    @post = current_user.posts.build
    @post.build_cover
end

def create
    @post = current_user.posts.build(post_params)
end
```

Went saving, everything looks ok:
`"cover_attributes"=>{"cover"=>#<ActionDispatch::Http::UploadedFile:0x007f8b53b15a90 @tempfile=#<Tempfile:/var/folders/ht/80rd8_d53_vgrqzbwnr8lk2w0000gn/T/RackMultipart20170507-28076-1j9p1ma.jpg>, @original_filename="20PRE-master768.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"post[cover_attributes][cover]\"; filename=\"20PRE-master768.jpg\"\r\nContent-Type: image/jpeg\r\n">`

If I try to the command `Cover.last` it always has `cover: nil`
