### ISSUE TITLE
Version Content Types

### ISSUE THREAD

**Issue by codezomb** [carrierwaveuploader/carrierwave#480]
I've got an uploader that accepts a PDF, and converts multiple versions to JPG. This works, and everything is (mostly) great. I'm uploading to S3, and I noticed today that Safari isn't displaying the image version placed inside an &lt;img&gt; tag. I looked around, and found that S3 has the content type of the image versions set to "application/pdf" which is causing issues with rendering in certain browsers. 

```
version :thumb do
  process :resize_to_fill => [300,240]
  process :convert => :jpg

  def full_filename (for_file = model.source.file)
    super.chomp(File.extname(super)) + '.jpg'
  end
end
```

As you can see, I'm overwriting the full_filename method inside the version call in order to get the filename to change, as mentioned in issue #378, however this doesn't fix the content type issue. 

Am I overlooking something in the docs, maybe the wiki? I tried searching, however I came up short on resolutions.

**Comment by gavinballard** [comment]
I also ran in to this issue. @dblock's patch wasn't working for me when calling `process :set_content_type => 'image/jpeg'` from within a `version` block (unknown method error), but got things working with a `set_content_type` method similar to @codezomb's solutions above.

**Comment by TrevorHinesley** [comment]
This still seems to be an issue on the stable releases.

**Comment by Xiangshen-Meng** [comment]
Make sure you have included MimeTypes module in uploader.
And then call process to set content_type. This works for me.

``` ruby
include CarrierWave::MimeTypes

process :set_content_type => 'image/jpeg'
```
