### ISSUE TITLE
Fog storage valid subdomain check incorrect for s3

### ISSUE THREAD

**Issue by zacclark** [carrierwaveuploader/carrierwave#531]
https://github.com/jnicklas/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L256

The current regex allows dots in the fog_directory when using the subdomain style urls to AWS. However, the AWS wildcard ssl certificate won't work if the bucket name has a dot. While dots are valid in subdomains, breaking ssl seems to nullify the point of allowing them here.

**Comment by mada41** [comment]
hi guys.
how about handle integration with S3 + Cloudflare ?
https://support.cloudflare.com/hc/en-us/articles/200168926-How-do-I-use-CloudFlare-with-Amazon-s-S3-Service-
