### ISSUE TITLE
Rails 3.2 image versions

### ISSUE THREAD

**Issue by johnbeynon** [carrierwaveuploader/carrierwave#583]
I've just bumped an app to 3.2.rc2 but it seems like when an app is using image versions then it fails with undefined method errors.

eg

photo.image.thumb.url fails

reverting it back to rails 3.1 it works fine. Inspecting the same object reveals that none of the carrierwave methods/properties are being added to the Rails 3.2 version.

**Comment by fatuhoku** [comment]
So what's the solution to my getting `NoMethodError: undefined method `remove_previously_stored_files_after_update' for nil:NilClass` in unit tests?
