### ISSUE TITLE
#filename is always nil.

### ISSUE THREAD

**Issue by postmodern** [carrierwaveuploader/carrierwave#614]
Using carrierwave (0.5.8), carrierwave-datamapper (0.2.0) and DataMapper (1.1.0) on Ruby 1.8.7-p357, and am noticing that `resource.uploader.filename` always returns `nil`. However, I can get the original filename by accessing the underlying identifier column, `resource.attribute_get(:uploader)`.

**Comment by veera** [comment]
@taavo :+1: nice options to get filename

**Comment by TomaszKot11** [comment]
The same here ;>
