### ISSUE TITLE
Fog uploads fail when using Rackspace cloud with Servicenet -- "Excon::Errors::SocketError: Connection reset by peer - SSL_connect"

### ISSUE THREAD

**Issue by charlietran** [carrierwaveuploader/carrierwave#619]
In case anyone else encounters this error, further discussed here by @scottwb: http://sleeplesscoding.blogspot.com/2011/08/rackspace-cloud-files-ssl-failures-over.html

and fixed with a monkeypatch here: https://gist.github.com/1161210

Working for both him and me in production right now.

**Comment by tacnoman** [comment]
I made downgrade to version 1.36 and worked for me.
