### ISSUE TITLE
README suggestion - re: Fog/AWS

### ISSUE THREAD

**Issue by jvenator** [carrierwaveuploader/carrierwave#653]
**UPDATED**
I'm building an app using Rails 3.2 - https://github.com/jvenator/wallet (it will remain public for about another week)

I created a directory to match the README instructions at lib/carrierwave/storage/  and placed the fog.rb file there.

After re-starting my local server I got the following routing error:
`uninitialized constant CarrierWave::Storage::Fog`

Moving the fog.rb file into the config/initializers/  directory and re-starting the server fixed things. I went back and forth several times to confirm the behavior. Am not sure if this is something unique to my app or not. the  [Engine Yard doc](http://docs.engineyard.com/use-carrierwave-and-optionally-fog-to-upload-and-store-files.html#update3) also says to place the file in the initializers directory.

ORIGINAL ISSUE:
I implemented Fog/AWS per your README instructions and got a nil class error when reloading the index view for the related resource class (I have a class called Document that Carrierwave is attaching files to). After googling around I found this [Engine Yard doc](http://docs.engineyard.com/use-carrierwave-and-optionally-fog-to-upload-and-store-files.html#update3) that suggested putting the fog.rb file directly into the config/initializers directory. At the same time I re-started my local dev server. Everything immediately started working, which I attributed to the change in location for the fog.rb file. However, after moving it back to the original location everything still worked.

So... it seems you just need to re-start your server. This may be painfully obvious to even a modestly competent dev, but as a beginner it got me. Perhaps a footnote reminding people to do this would be a helpful addition. (I've never revised or suggested changes to a README before, so feel free to direct me to instruction on how to do this in a more appropriate easy-for-you manner).

Also, thank you so much for the work you've done on this gem. I'm in NYC and every available worthwhile dev class sells out immediately (especially for Ruby/RoR). Easy to use and effective tools like CarrierWave mean a lot to those of us that are new to programming!

**Comment by tommiller1** [comment]
Don't do config.storage :fog inside the initializer, it should be in the uploader.
