### ISSUE TITLE
Doesn't remove "current file" if you upload a new one to S3.

### ISSUE THREAD

**Issue by mrrooijen** [carrierwaveuploader/carrierwave#75]
So my user already has an avatar set. When I want to change it, I simply just re-upload a new avatar over the current one. This one gets added, but when I look in the filesystem, I still see the old avatar and it's versions.

I'm using: Rails 3 from master, CarrierWave from master, Amazon S3

When I use the user.remove_avatar! method, it successfully removes the images from S3. So I think there might be a callback that's failing to check to see if there is already a current avatar available and delete that one first before overwriting it with a new one. Your thoughts?

**Comment by mrdougwright** [comment]
This worked for me, if anyone still has this issue
Simply add `remove_avatar` to your attr_accessible list for your model.
