### ISSUE TITLE
How can I retrieve image width and height

### ISSUE THREAD

**Issue by HungYuHei** [carrierwaveuploader/carrierwave#757]
I need the ability to handle the different process according to image's dimensions.

Like this:

```
  version :normal do
    process :scale_image
  end

  def scale_image
    width = *THE_WAY_TO_GET_WIDTH*
    height = *THE_WAY_TO_GET_HEIGHT*

    if width && height && width > height
      process :resize_to_fit => [224, 320, '#000']
    else
      process :resize_to_fill => [224, 320, '#000']
    end
  end
```

So, my question is, how can I implement THE_WAY_TO_GET_WIDTH and THE_WAY_TO_GET_HEIGHT ?

**Comment by whitebeatle** [comment]
adding to what @cristiansorinel mentioned

<pre>
def image
   // this will provide height and width to any version of the image, like thumb, medium sizes
   // just do model.medium.image_width ...
   @image ||= MiniMagick::Image.open( file.file )
end
</pre>
