### ISSUE TITLE
generating uploader in rails 3 standalone engine fails

### ISSUE THREAD

**Issue by rjayroach** [carrierwaveuploader/carrierwave#789]
rails 3.2.6; carrierwave 0.6.2

Generated uploader class does not work from inside a Rails 3 standalone engine. What I did:
1. Configured carrierwave gem 0.6.2 in a rails engine Gemfile; bundle install
2. ran rails g uploader leadFileUploader

The generated file was created in dir app/uploaders
The generated source had a Class definition

Instantiating this class had all kinds of weird errors until I did the following:
1. mkdir app/uploaders/engine_name
2. moved the generated file from app/uploaders/ to app/uploaders/engine_name
3. modified the generated source to place the class inside the engine module namespace: Module engine_name

**Comment by coderawal** [comment]
I too hit the same issue,  I'm new to rails, so I would be grateful if you please provide a elegant solution or  help me guide the better way. Thanks.
