### ISSUE TITLE
TypeError, can't dump anonymous class

### ISSUE THREAD

**Issue by jess** [carrierwaveuploader/carrierwave#793]
Think I found a bug.  

Scenario:  Only happens when using versions & using a session to store an object that has an uploader attached.

I'm using sessions for a cart. Something like this:

```
# app/models/cart
class Cart
  attr_reader :items

  def initialize
    @items = []
  end

  def add(product)
    @items << product
  end
end

# controller
product = Product.find(params[:id]) 
@cart = session[:cart] ||= Cart.new
@cart.add(product)
```

Now in my view:

```
@cart.items.each do |item|
  item.name
  image_tag item.image.thumb.url #causes the error...image.url will cause error too
```

Here's a short screencast showing the issue:  http://screencast.com/t/GiP4tZwWY8S

Here's a test app you can run and get the result:  https://github.com/jess/test_app 
**Note there's only a "wave" branch**

Here's the trace: https://gist.github.com/3169779

I also ran into a similar issue with FriendlyID (maybe the cross reference will help??) https://github.com/norman/friendly_id/issues/314

Please let me know if I can provide additional information...

**Comment by abonec** [comment]
@bensie, this is don't work after load in new environment. Atomatic generated names for uploaders is missing with error like this:

    undefined class/module ImageUploader::Uploader50028680 (ArgumentError)

**Comment by salanki** [comment]
Exactly. They need a deterministic name. Reopen this issue or create a new one?

**Comment by mrsweaters** [comment]
I'm also experiencing this issue trying to cache Active Model Serializers via Dalli. I'd say just reopen this issue.
