### ISSUE TITLE
Undefined method when running recreate_versions! (fog)

### ISSUE THREAD

**Issue by mattiassvedhem** [carrierwaveuploader/carrierwave#828]
Using FOG, together with S3. When I loop through all or image objects and run recreate_versions! On rare occasions I get this error message. I've isolated the object but it doesn't seem to be anything special about it. Running 0.6.2 & Fog 1.5.0.

```
NoMethodError: undefined method `body' for nil:NilClass
    from /data/kyparn/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.6.2/lib/carrierwave/storage/fog.rb:217:in `read'
    from /data/kyparn/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.6.2/lib/carrierwave/uploader/cache.rb:73:in `cache_stored_file!'
    from /data/kyparn/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.6.2/lib/carrierwave/uploader/versions.rb:174:in `recreate_versions!'
```

I've found an issue that might or might not be related, #571 

Any thoughts?
Thanks

**Comment by saviokmua** [comment]
[http://i.imgur.com/XH2tRZQ.png](url)

**Comment by djchadderton** [comment]
I've just come across this issue when writing a rake task to grab images from my old site, which used Paperclip and the file system, through the URI and reprocess them through a new server using Carrierwave and DigitalOcean Spaces through Fog.

From running a few hundred images through the script on my local machine, I've found that the only files that have this issue are the ones that have the file extension in upper case. So "CIRCUS250_LOGO_Acrobats.jpg" works perfectly well but "01.JPG" has the "undefined method 'body'" issue. Similarly, "my_name_2.jpg" works but "treasure_-69.JPG" doesn't. This appears to be the only difference between the images that work and those that throw this error.

I don't know what this means or how to fix it, but I thought it might help.
