### ISSUE TITLE
"complete" callback?

### ISSUE THREAD

**Issue by codezomb** [carrierwaveuploader/carrierwave#880]
I'm not sure if I've just missed it, or what. However, would be nice to have a callback that can be run after all versions are processed, and carrierwave has finished cleaning up. I've used after :store, but it runs after every version, and it makes sense to be able to run some code after all versions have finished processing. after_save in the model isn't reliable, especially since 90% of the use cases are run via background jobs.

**Comment by amilano** [comment]
This would be really useful, unless I'm missing a way to identify which version just launched the current after :store callback.

I need something similar for when recreate_version! is called, I've been looking around if there's a way to know when the recreation finished processing and uploading back to AWS every single recreated version of a file.

**Comment by mattgilbertnet** [comment]
+1 Would be very helpful to know an asset is actually available.
