### ISSUE TITLE
@file is nil when using cache_stored_file! w/ fog & s3

### ISSUE THREAD

**Issue by dignoe** [carrierwaveuploader/carrierwave#895]
When I call `my_uploader.cache_stored_file!` I get the following error & trace. The file exists on the remote service (s3). I am using v0.7.0.

```
NoMethodError: undefined method `content_length' for nil:NilClass
    from /data/Nudgems/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.7.0/lib/carrierwave/storage/fog.rb:236:in `size'
    from /data/Nudgems/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.7.0/lib/carrierwave/sanitized_file.rb:95:in `size'
    from /data/Nudgems/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.7.0/lib/carrierwave/sanitized_file.rb:135:in `empty?'
    from /data/Nudgems/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.7.0/lib/carrierwave/uploader/cache.rb:116:in `cache!'
    from /data/Nudgems/shared/bundled_gems/ruby/1.9.1/gems/carrierwave-0.7.0/lib/carrierwave/uploader/cache.rb:83:in `cache_stored_file!'
    from (irb):10
```

When I call `my_uploader.file` I get a `CarrierWave::Storage::Fog::File` object back, and `my_uploader.file.size` responds with the correct size of the file.

**Comment by joeyjoejoejr** [comment]
Yep, Still an issue.

**Comment by osetinsky** [comment]
Problem for me too! Just noticed it today for some reason. https://stackoverflow.com/questions/28755528/sudden-carrierwave-fog-upload-error

**Comment by osetinsky** [comment]
Is this the fix?

https://github.com/carrierwaveuploader/carrierwave/commit/bbef19cc90c504d5cdfe8e34303a20f99fe4c453

**Comment by istana** [comment]
I had this issue when I had blank `filename` in uploader:

````
  def filename
    "lol.jpg" if original_filename
  end
````

**Comment by mattymess** [comment]
I'm on `0.10.0` and [this method from the wiki](https://github.com/jnicklas/carrierwave/wiki/How-to%3A-Recreate-and-reprocess-your-files-stored-on-fog) doesn't work for me. Throws one of the two errors below...

```
ERROR: Site: 125 -> undefined method `read' for nil:NilClass
ERROR: Site: 126 -> undefined method `body' for nil:NilClass
```

**Comment by thomasfedb** [comment]
@mattymess Please open a new issue, this issue relates to version 0.7.0.
