### ISSUE TITLE
Asset_host breaks the form redisplays on production

### ISSUE THREAD

**Issue by xdmx** [carrierwaveuploader/carrierwave#899]
Hi, I'm using Carrierwave on an application hosted on Heroku. I've set the root and cache_dir in order to make form redisplay working. Here's my config:

``` ruby
  directory = Rails.env.production? ? "static.domain.com" : "static-staging.domain.com"

  CarrierWave.configure do |config|
    config.fog_credentials = {
        :provider => 'AWS',
        :aws_access_key_id => ENV['AWS_ACCESS_KEY'],
        :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
    }
    config.fog_directory = directory
    config.fog_public = true
    config.fog_attributes = {'Cache-Control' => 'max-age=31536000'}
    if Rails.env.development?
      config.asset_host = nil
    else
      config.asset_host = "https://#{directory}"
      config.root = Rails.root.join('tmp')
      config.cache_dir = 'carrierwave'
    end
  end
```

The problem is that when there is an error, carrierwave tries to load: https://static.domain.com/carrierwave/20121114-1347-11-4314/x100_carl.jpg , instead of https://domain.com/carrierwave/20121114-1347-11-4314/x100_carl.jpg , and this way it doesn't find the image (static.domain.com is a CNAME to S3)
The uploading itself (avatar_cache) will work correctly, as it'll load the cached file from the tmp directory, it's just the img in the form to show the cached image that doesn't work, which is added using a simple_form custom input (it calls avatar.thumb.url):

``` ruby
class ImagePreviewInput < SimpleForm::Inputs::FileInput
  def input
    version = input_html_options.delete(:preview_version)
    out = "<p>#{template.image_tag(object.send(attribute_name).send(version).send('url'))}</p>"
    out << @builder.file_field(attribute_name, input_html_options)
    out << @builder.hidden_field(attribute_name.to_s + "_cache", input_html_options)
    out.html_safe
  end
end
```

**Comment by allaire** [comment]
@bensie I know this is hold, but would it be a good default behaviour to not return the asset_host if the file is cached? (see my exemple here: https://github.com/carrierwaveuploader/carrierwave/issues/1735)
