### ISSUE TITLE
Documentation: What is the difference between resize_to_limit and resize_to_fit methods from rmagick?

### ISSUE THREAD

**Issue by alexbrand** [carrierwaveuploader/carrierwave#938]
Do they do the same thing?

```
- (Object) resize_to_fit(width, height)
From the RMagick documentation: "Resize the image to fit within the specified dimensions while retaining the original aspect ratio.
```
## 

```
- (Object) resize_to_limit(width, height)
Resize the image to fit within the specified dimensions while retaining the original aspect ratio.
```

**Comment by yozzz** [comment]
It will also scale down if they are bigger than the given size, useful when you can expect big images

**Comment by a-ta-ta** [comment]
Difference is hard to detect, but in terms of code:
resize_to_fit means:
`resize "#{width}x#{height}"`

And resize_to_limit means:
`resize "#{width}x#{height}>"`

So you can see ">" in the end. Human translation is already given above by @yozzz and @mikbe .
