### ISSUE TITLE
redisplay not working for versions on "conditional processing"

### ISSUE THREAD

**Issue by github0013** [carrierwaveuploader/carrierwave#980]
hi.

I came across this issue under the env below

- osx 10.7.5
- carrierwave be207942abb1909ecd4d086ec84a0401d515747b
- rails 3.2.12

here's how it happened.

1. form has validations on some fields
2. upload images and have validation errors (creates image cache and can display uploaded image)
3. then fill inputs to remove errors and save
4. image thumb version is missing from its "uploads" directory

I googled around and found it seemed it was already fixed.  
https://github.com/jnicklas/carrierwave/issues/670
https://github.com/jnicklas/carrierwave/issues/720

But I was still having the same issue, and did deep experiments on it and found this problem still happens when version has conditional processing.
ex. [How to: Do conditional processing](https://github.com/jnicklas/carrierwave/wiki/How-to%3A-Do-conditional-processing)

I built an app with rspec tests.   I appreciate if someone can trace the root of this problem.
https://github.com/github0013/carrierwave_redisplay_on_condition

**Comment by plribeiro3000** [comment]
Hmmm. This is pretty old but as it has a replication process defined and an app for it i can say it is also *gold*.

I will try to run it against the latest master.

**Comment by plribeiro3000** [comment]
The related project does not work anymore. A single update of the dependencies to be able to run the specs and everything was broken.

@github0013 @ka8725  I will close this issue since it is pretty old but let me know in the comments if you are still facing this issue.

Thanks!
